creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/AddressDataSection__c.object-meta.xml
<CustomObject>
    <description>Objeto Utilizado apenas para o Squad AtWork</description>
    <label>Seção Dados de Endereço</label>
    <nameField>
        <displayFormat>DE-{00000}</displayFormat>
        <label>Seção Dados de Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Endereço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Endereço</relationshipLabel>
    <relationshipName>AddressDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/ContactDetailsSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Contato</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Seção Dados de Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Contato</relationshipLabel>
    <relationshipName>ContactDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OperationSection__c/OperationSection__c.object-meta.xml
<CustomObject>
    <label>Seção Operação</label>
    <nameField>
        <label>Seção Operação Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Operação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/WarrantyDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Garantia</label>
    <nameField>
        <label>Seção Dados de Garantia Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Garantia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/classes/ProposalIntegrationServiceTest.cls
@isTest
public class ProposalIntegrationServiceTest {

    @TestSetup
    static void makeData(){
        String accPessoaFisica = [SELECT ID FROM RECORDTYPE WHERE DeveloperName = 'Pessoa_Fisica' AND SobjectType = 'Account']?.Id;
        Account accCustomer = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opp = OpportunitySetup.createOpportunity(accCustomer.Id, 'AutoFin');
        opp.Description = 'teste';
        insert opp;

        PersonalDataSection__c personalSection  = new PersonalDataSection__c();
        personalSection.Opportunity__c = opp.Id;
        insert personalSection;

        AddressDataSection__c addressSection   = new AddressDataSection__c();
        addressSection.Opportunity__c = opp.Id;
        insert addressSection;
        
        ContactDetailsSection__c contactSection   = new ContactDetailsSection__c();
        contactSection.Opportunity__c = opp.Id;
        insert contactSection;

        WarrantyDataSection__c warrantySection  = new WarrantyDataSection__c();
        warrantySection.Opportunity__c = opp.Id;
        insert warrantySection;

        IncomeDataSection__c incomeSection    = new IncomeDataSection__c();
        incomeSection.Opportunity__c = opp.Id;
        insert incomeSection;

        OperationSection__c operationSection = new OperationSection__c();
        operationSection.Opportunity__c = opp.Id;
        insert operationSection;
    }

    @isTest
    static void finishAnalysisTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Test.startTest();
        ProposalIntegrationController.finishAnalysis(opp.Id, 'pendency');
        Test.stopTest();
    }
}