creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Pontuação das filas</description>
    <inlineHelpText>Escolha um valor entre 0 e 999</inlineHelpText>
    <label>Pontuação</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomSetup__c/fields/DateFilter__c.field-meta.xml
<CustomField>
    <fullName>DateFilter__c</fullName>
    <label>Data de Filtro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data de Criação</fullName>
                <default>true</default>
                <label>Data de Criação</label>
            </value>
            <value>
                <fullName>Data de Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <label>AtWork</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/PriorityPoints__c.field-meta.xml
<CustomField>
    <fullName>PriorityPoints__c</fullName>
    <label>Priorização</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <businessProcess>%40Work - Creditas</businessProcess>
    <label>@Work</label>
</RecordType>

creditas-sf/force-app/main/default/classes/BatchEvaluateOpportunityTest.cls
@isTest
private with sharing class BatchEvaluateOpportunityTest {
    
    @TestSetup
    static void makeData(){

        Account acc = AccountSetup.createAccount('Batch', 'Pessoa_Fisica');
        insert acc;

        Id recordTypeId = Util.getRecordTypeIdbyName('CustomSetup__c', 'AtWork');

        CustomSetup__c cSetup = new CustomSetup__c(
        RecordTypeId = recordTypeId,
        Name = 'Test',
        DateFilter__c = 'CreatedDate'
        );

        insert cSetup;

        Id queueRecordTypeId = Util.getRecordTypeIdbyName('CustomQueue__c', 'AtWork');

        insert new List<CustomQueue__c>{
            new CustomQueue__c(Name = 'DISCHARGING', QueueName__c = 'DISCHARGING', CustomSetup__c = cSetup.Id, Points__c = 10, recordTypeId = queueRecordTypeId),
            new CustomQueue__c(Name = 'REFINANCING', QueueName__c = 'REFINANCING', CustomSetup__c = cSetup.Id, Points__c = 20, recordTypeId = queueRecordTypeId),
            new CustomQueue__c(Name = 'STORE', QueueName__c = 'STORE', CustomSetup__c = cSetup.Id, Points__c = 30, recordTypeId = queueRecordTypeId),
            new CustomQueue__c(Name = 'PAYROLL_LOAN', QueueName__c = 'PAYROLL_LOAN', CustomSetup__c = cSetup.Id, Points__c = 40, recordTypeId = queueRecordTypeId),
            new CustomQueue__c(Name = 'SALARY_ADVANCE', QueueName__c = 'SALARY_ADVANCE', CustomSetup__c = cSetup.Id, Points__c = 50, recordTypeId = queueRecordTypeId),
            new CustomQueue__c(Name = 'PENDENCY_RETURN', QueueName__c = 'PENDENCY_RETURN', CustomSetup__c = cSetup.Id, Points__c = 100, recordTypeId = queueRecordTypeId)
        };
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppLoan = OpportunitySetup.createOpportunity(acc.Id, 'AtWork');
        oppLoan.QueueName__c = 'PAYROLL_LOAN';
        oppList.add(oppLoan);
        Opportunity oppRefinancing = OpportunitySetup.createOpportunity(acc.Id, 'AtWork');
        oppRefinancing.QueueName__c = 'REFINANCING';
        oppList.add(oppRefinancing);
        Opportunity oppStore = OpportunitySetup.createOpportunity(acc.Id, 'AtWork');
        oppStore.QueueName__c = 'STORE';
        oppList.add(oppStore);
        Opportunity oppSalary = OpportunitySetup.createOpportunity(acc.Id, 'AtWork');
        oppSalary.QueueName__c = 'SALARY_ADVANCE';
        oppList.add(oppSalary);
        insert oppList;
        
    }

    @isTest
    private static void testBatchApexOneQueue(){
        CustomQueue__c queue = [SELECT Points__c FROM CustomQueue__c WHERE Name = 'PAYROLL_LOAN'];
        queue.Points__c = 75;
        Test.startTest();
        update queue;
        Test.stopTest();
        Opportunity opp = [SELECT PriorityPoints__c FROM Opportunity WHERE QueueName__c = 'PAYROLL_LOAN' LIMIT 1];
        System.assertEquals(75, opp.PriorityPoints__c, 'Wrong points!');
    }

    @isTest
    private static void testBatchApexMultipleQueues(){
        List<CustomQueue__c> queues = [SELECT Points__c FROM CustomQueue__c];
        for(CustomQueue__c cQueue : queues){
            cQueue.Points__c = 77;
        }
        Test.startTest();
        update queues;
        Test.stopTest();
        List<Opportunity> oppList = [SELECT PriorityPoints__c FROM Opportunity];
        for(Opportunity opp : oppList){
            System.assertEquals(77, opp.PriorityPoints__c, 'Wrong points!');
        }
    }
}