creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Pontuação das filas</description>
    <inlineHelpText>Escolha um valor entre 0 e 999</inlineHelpText>
    <label>Pontuação</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto para a fila de @work</description>
    <inlineHelpText>O valor escolhido determinará qual a pontuação referente a esse produto.</inlineHelpText>
    <label>Tipo de Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomSetup__c/fields/DateFilter__c.field-meta.xml
<CustomField>
    <fullName>DateFilter__c</fullName>
    <label>Data de Filtro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data de Criação</fullName>
                <default>true</default>
                <label>Data de Criação</label>
            </value>
            <value>
                <fullName>Data de Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <label>AtWork</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/PendencyReturn__c.field-meta.xml
<CustomField>
    <fullName>PendencyReturn__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Campo para marcar se a oportunidade é um retorno de pendência</description>
    <label>Retorno de Pendência</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/PriorityPoints__c.field-meta.xml
<CustomField>
    <fullName>PriorityPoints__c</fullName>
    <label>Priorização</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <businessProcess>%40Work - Creditas</businessProcess>
    <label>@Work</label>
</RecordType>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/EvaluationMethodsTest.cls
/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Classe de testes da classe EvaluationMethods
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       18/01/2021      Created     Classe de testes da classe EvaluationMethods
 **********************************************************************************************************************/
@isTest
private class EvaluationMethodsTest {
  static Id accountId;

  static List<Opportunity> makeOpportunityList(Integer numOpps, Id accountId, String productType) {
    List<Opportunity> lstOpp = new List<Opportunity>();

    for (Integer i = 1; i <= numOpps; i++) {
      Opportunity opp = OpportunitySetup.createOpportunity(accountId, 'AtWork');
      opp.Name = 'Opportunity Test ' + i;
      opp.ProductType__c = productType;
      lstOpp.add(opp);
    }

    return lstOpp;
  }

  static CustomSetup__c makeCustomSetup(String name, String dateFilter) {
    CustomSetup__c cSetup = new CustomSetup__c();
    cSetup.Name = name;
    cSetup.DateFilter__c = dateFilter;
    return cSetup;
  }

  static CustomQueue__c makeCustomQueue(Id cSetupId, String name, String productType, Double points) {
    CustomQueue__c cQueue = new CustomQueue__c();
    cQueue.Name = name;
    cQueue.ProductType__c = productType;
    cQueue.CustomSetup__c = cSetupId;
    cQueue.Points__c = points;

    return cQueue;
  }

  @TestSetup
  static void runSetup() {
    CustomSetup__c cSetup = makeCustomSetup('Parametrização de Filas e Usuários', 'Data de Solicitação');

    insert cSetup;

    List<CustomQueue__c> lstCustomQueue = new List<CustomQueue__c>();
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Quitação', 'DISCHARGE', 10));
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Refinanciamento', 'REFINANCING', 20));
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Store', 'STORE', 30));
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Payroll', 'PAYROLL_LOAN', 40));
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Antecipação', 'SALARY_ADVANCE', 50));
    lstCustomQueue.add(makeCustomQueue(cSetup.Id, 'Retorno de Pendência', 'PENDENCY_RETURN', 100));

    insert lstCustomQueue;

    Account acc = AccountSetup.createAccount('Account Test', 'Pessoa_Fisica');

    insert acc;

    accountId = acc.Id;
  }

  @isTest
  static void runInsertAtWorkOpportunity() {
    List<Opportunity> lstOpp = makeOpportunityList(1, accountId, 'PAYROLL_LOAN');
    lstOpp.addAll(makeOpportunityList(1, accountId, ''));

    Test.startTest();

    insert lstOpp;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c FROM Opportunity WHERE Id IN :lstOpp]) {
      if (opp.ProductType__c == 'PAYROLL_LOAN') {
        System.assertEquals(40, opp.PriorityPoints__c, 'Opportunity priority points should be 40');
      } else {
        System.assertEquals(0, opp.PriorityPoints__c, 'Opportunity priority points should be 0');
      }
    }
  }

  @isTest
  static void runBulkInsertAtWorkOpportunity() {
    Map<String, Double> mapQueuePoints = new Map<String, Double>();
    for (CustomQueue__c cQueue : [SELECT Id, ProductType__c, Points__c FROM CustomQueue__c]) {
      mapQueuePoints.put(cQueue.ProductType__c, cQueue.Points__c);
    }

    List<Opportunity> lstOpp = makeOpportunityList(40, accountId, 'DISCHARGE');
    lstOpp.addAll(makeOpportunityList(40, accountId, 'REFINANCING'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'STORE'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'PAYROLL_LOAN'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'SALARY_ADVANCE'));

    Test.startTest();

    insert lstOpp;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c FROM Opportunity WHERE Id IN :lstOpp]) {
      System.assertEquals(
        mapQueuePoints.get(opp.ProductType__c),
        opp.PriorityPoints__c,
        'Opportunity priority points should be ' + mapQueuePoints.get(opp.ProductType__c)
      );
    }
  }

  @isTest
  static void runUpdateOneCustomQueue() {
    List<Opportunity> lstOpp = makeOpportunityList(1, accountId, 'DISCHARGE');
    lstOpp.addAll(makeOpportunityList(1, accountId, 'REFINANCING'));
    lstOpp.addAll(makeOpportunityList(1, accountId, 'STORE'));
    lstOpp.addAll(makeOpportunityList(1, accountId, ''));

    insert lstOpp;

    CustomQueue__c cQueue = [SELECT Id, ProductType__c FROM CustomQueue__c WHERE ProductType__c = 'DISCHARGE' LIMIT 1];
    cQueue.Points__c = 22;

    Test.startTest();

    update cQueue;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c FROM Opportunity WHERE Id IN :lstOpp]) {
      if (opp.ProductType__c == 'DISCHARGE') {
        System.assertEquals(22, opp.PriorityPoints__c, 'Opportunity priority points should be 22');
      } else if (opp.ProductType__c == 'REFINANCING' || opp.ProductType__c == 'STORE') {
        System.assertNotEquals(22, opp.PriorityPoints__c, 'Opportunity priority points should not be 22');
      } else {
        System.assertEquals(0, opp.PriorityPoints__c, 'Opportunity priority points should be 0');
      }
    }
  }

  @isTest
  static void runUpdateMultipleCustomQueue() {
    List<Opportunity> lstOpp = makeOpportunityList(40, accountId, 'DISCHARGE');
    lstOpp.addAll(makeOpportunityList(40, accountId, 'REFINANCING'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'STORE'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'PAYROLL_LOAN'));
    lstOpp.addAll(makeOpportunityList(40, accountId, ''));

    insert lstOpp;

    List<CustomQueue__c> lstCustomQueue = [
      SELECT Id, ProductType__c
      FROM CustomQueue__c
      WHERE ProductType__c IN ('DISCHARGE', 'REFINANCING', 'STORE', 'PAYROLL_LOAN')
    ];

    for (CustomQueue__c cQueue : lstCustomQueue) {
      if (cQueue.ProductType__c == 'DISCHARGE') {
        cQueue.Points__c = 11;
      } else if (cQueue.ProductType__c == 'REFINANCING') {
        cQueue.Points__c = 21;
      } else if (cQueue.ProductType__c == 'STORE') {
        cQueue.Points__c = 31;
      } else if (cQueue.ProductType__c == 'PAYROLL_LOAN') {
        cQueue.Points__c = 41;
      }
    }

    Test.startTest();

    update lstCustomQueue;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c FROM Opportunity WHERE Id IN :lstOpp]) {
      if (opp.ProductType__c == 'DISCHARGE') {
        System.assertEquals(
          11,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'DISCHARGE\' should have 11 Priority Points'
        );
      } else if (opp.ProductType__c == 'REFINANCING') {
        System.assertEquals(
          21,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'REFINANCING\' should have 21 Priority Points'
        );
      } else if (opp.ProductType__c == 'STORE') {
        System.assertEquals(
          31,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'STORE\' should have 31 Priority Points'
        );
      } else if (opp.ProductType__c == 'PAYROLL_LOAN') {
        System.assertEquals(
          41,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'PAYROLL_LOAN\' should have 41 Priority Points'
        );
      } else {
        System.assertEquals(
          0,
          opp.PriorityPoints__c,
          'Opportunities with no Product Type should have 0 Priority Points'
        );
      }
    }
  }

  @isTest
  private static void testPendencyReturnOpps(){
    List<Opportunity> lstOpp = makeOpportunityList(40, accountId, 'DISCHARGE');
    lstOpp.addAll(makeOpportunityList(40, accountId, 'REFINANCING'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'STORE'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'PAYROLL_LOAN'));
    lstOpp.addAll(makeOpportunityList(40, accountId, 'SALARY_ADVANCE'));
    for(Opportunity iOpp : lstOpp){
      iOpp.PendencyReturn__c = true;
    }

    insert lstOpp;

    List<CustomQueue__c> lstCustomQueue = [
      SELECT Id, ProductType__c
      FROM CustomQueue__c
      WHERE ProductType__c IN ('DISCHARGE', 'REFINANCING', 'STORE', 'PAYROLL_LOAN')
    ];

    for (CustomQueue__c cQueue : lstCustomQueue) {
      if (cQueue.ProductType__c == 'DISCHARGE') {
        cQueue.Points__c = 11;
      } else if (cQueue.ProductType__c == 'REFINANCING') {
        cQueue.Points__c = 21;
      } else if (cQueue.ProductType__c == 'STORE') {
        cQueue.Points__c = 31;
      } else if (cQueue.ProductType__c == 'PAYROLL_LOAN') {
        cQueue.Points__c = 41;
      }
    }

    Test.startTest();

    update lstCustomQueue;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c FROM Opportunity WHERE Id IN :lstOpp]) {
      if (opp.ProductType__c == 'DISCHARGE') {
        System.assertEquals(
          111,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'DISCHARGE\' should have 111 Priority Points'
        );
      } else if (opp.ProductType__c == 'REFINANCING') {
        System.assertEquals(
          121,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'REFINANCING\' should have 121 Priority Points'
        );
      } else if (opp.ProductType__c == 'STORE') {
        System.assertEquals(
          131,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'STORE\' should have 131 Priority Points'
        );
      } else if (opp.ProductType__c == 'PAYROLL_LOAN') {
        System.assertEquals(
          141,
          opp.PriorityPoints__c,
          'Opportunities with Product Type \'PAYROLL_LOAN\' should have 41 Priority Points'
        );
      } else {
        System.assertEquals(
          150,
          opp.PriorityPoints__c,
          'Opportunities with no Product Type SALARY_ADVANCE should have 150 Priority Points'
        );
      }
    }
  }

  @isTest
  static void testUpdatePendencyCustomQueue() {
    List<Opportunity> lstOpp = makeOpportunityList(1, accountId, 'DISCHARGE');
    lstOpp[0].PendencyReturn__c = true;
    lstOpp.addAll(makeOpportunityList(1, accountId, 'REFINANCING'));
    lstOpp.addAll(makeOpportunityList(1, accountId, 'STORE'));
    lstOpp.addAll(makeOpportunityList(1, accountId, ''));

    insert lstOpp;

    CustomQueue__c cQueue = [SELECT Id, ProductType__c FROM CustomQueue__c WHERE ProductType__c = 'PENDENCY_RETURN' LIMIT 1];
    cQueue.Points__c = 150;

    Test.startTest();

    update cQueue;

    Test.stopTest();

    for (Opportunity opp : [SELECT ProductType__c, PriorityPoints__c, PendencyReturn__c FROM Opportunity WHERE Id IN :lstOpp]) {
      if (opp.PendencyReturn__c) {
        System.assertEquals(160, opp.PriorityPoints__c, 'Opportunity priority points should be 160');
      } else if (opp.ProductType__c == 'REFINANCING' || opp.ProductType__c == 'STORE') {
        System.assertNotEquals(22, opp.PriorityPoints__c, 'Opportunity priority points should not be 22');
      } else {
        System.assertEquals(0, opp.PriorityPoints__c, 'Opportunity priority points should be 0');
      }
    }
  }
}