creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalPersonId__c.field-meta.xml
<CustomField>
    <fullName>ExternalPersonId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OpportunityRoles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Titular_da_Conta__c.field-meta.xml
<CustomField>
    <fullName>Titular_da_Conta__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titular da Conta</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityRoleTriggerHandler.cls
/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Handler padrão para a trigger do Objeto Opportunity Roles (OpportunityRole__c).
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Nathalia Rosa           20/10/2021      Created     Implementação de handler voltado para uso da Trigger do objeto Opportunity Roles (OpportunityRole__c)
**********************************************************************************************************************************/
public without sharing class OpportunityRoleTriggerHandler extends TriggerHandler 
{
    private List<OpportunityRole__c> lstNewOpportunityRole;
    private List<OpportunityRole__c> lstOldOpportunityRole;
    private List<OpportunityRole__c> lstNewAccountRecordType;
    private List<OpportunityRole__c> lstOldAccountRecordType;
    private Map<Id, OpportunityRole__c> mapNewOpportunityRole;
    private Map<Id, OpportunityRole__c> mapOldOpportunityRole;
    
    
    public OpportunityRoleTriggerHandler() 
    {
        this.lstNewOpportunityRole = (List<OpportunityRole__c>) Trigger.new;
        this.lstOldOpportunityRole = (List<OpportunityRole__c>) Trigger.old;
        this.lstNewAccountRecordType = (List<OpportunityRole__c>) Trigger.new;
        this.lstOldAccountRecordType = (List<OpportunityRole__c>) Trigger.old;
        this.mapNewOpportunityRole = (Map<Id, OpportunityRole__c>) Trigger.newMap;
        this.mapOldOpportunityRole = (Map<Id, OpportunityRole__c>) Trigger.oldMap;
        
        
    }
    
    public override void beforeInsert()
    {
        this.checkOpportunityRole();
    }
    
    public override void afterInsert() 
    {
    }
    
    public override void beforeUpdate()
    {

    }
    
    public override void afterUpdate() 
    {      
		this.checkOpportunityRole();        
    }
    
    /**********************************************************************************************************************************
* ================================================================================================================================
* @description Caso o PRINCIPAL da Oportunidade seja pessoa física, somente será permitido que um dos participantes seja 
* configurado como o titular da conta bancária.
* ================================================================================================================================
* History
* -------
* VERSION     AUTHOR                  DATE            DETAIL      Description
* 1.0         Nathalia Rosa           20/10/21
**********************************************************************************************************************************/
    public void checkOpportunityRole()
    {  
        Boolean oppTitular = false;
        Set<Id> opportunityIds = new Set<Id>();
        
        for(OpportunityRole__c opportunityRoleNew :lstNewOpportunityRole){
            
            if(opportunityRoleNew.Titular_da_Conta__c){
                oppTitular = true;
            }
            opportunityIds.add(opportunityRoleNew.Opportunity__c);
        }
        
        if(oppTitular){
            Map<Id, List<OpportunityRole__c>> opportunityIdToOpportunityRolesMap = new Map<Id, List<OpportunityRole__c>>();
            
            List<OpportunityRole__c> listOpportunityRole = [ SELECT Id, ExternalPersonId__r.RecordType.DeveloperName, Opportunity__c FROM OpportunityRole__c 
                                                            WHERE Opportunity__c IN :opportunityIds AND Titular_da_Conta__c = true AND ExternalPersonId__r.RecordType.DeveloperName = 'Pessoa_Fisica'];
            
            for(OpportunityRole__c opportunityRoleNew :listOpportunityRole){
                if(!opportunityIdToOpportunityRolesMap.containsKey(opportunityRoleNew.Opportunity__c)){
                    opportunityIdToOpportunityRolesMap.put(opportunityRoleNew.Opportunity__c, new List<OpportunityRole__c>());
                }
                opportunityIdToOpportunityRolesMap.get(opportunityRoleNew.Opportunity__c).add(opportunityRoleNew);
                
            }
            for(OpportunityRole__c opportunityRoleNew :lstNewOpportunityRole){
                List<OpportunityRole__c> oppRolesList = opportunityIdToOpportunityRolesMap.get(opportunityRoleNew.Opportunity__c);
                if (oppRolesList == null){
                    continue;
                }
                if (opportunityRoleNew.Titular_da_Conta__c && ( oppRolesList.size() > 1 || (oppRolesList.size() == 1 && Trigger.isInsert))){
                    opportunityRoleNew.addError('JÁ EXISTE UM TITULAR DA CONTA BANCARIA, NÃO PODE ATUALIZAR, CASO NECESSARIO, DESABILITE O TITULAR ATUAL');
                }
            }
        }
    }   
}