creditas-sf/force-app/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PERSONAL</fullName>
            </value>
            <value>
                <fullName>COMERCIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/auxLeadName__c.field-meta.xml
<CustomField>
    <fullName>auxLeadName__c</fullName>
    <description>Campo auxiliar que é preenchido com os dados do Nome Completo do Lead.

Necessário para utilização nas Integrações que utilizam o Nome Completo do Lead.</description>
    <formula>FirstName &amp; &quot; &quot; &amp; LastName</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>auxLeadName</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do Contato</description>
    <label>CPF do contato</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de Documento do Lead</description>
    <label>Tipo de documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/mainDocumentCode__c.field-meta.xml
<CustomField>
    <fullName>mainDocumentCode__c</fullName>
    <description>Documento Principal da Empresa (CNPJ)</description>
    <label>Documento principal da empresa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <businessProcess>Auto</businessProcess>
    <description>Tipo de Registro do Lead: Auto</description>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/LeadCommunicationContact__c.object-meta.xml
<CustomObject>
    <description>Contatos do Lead (Telefone, WhatsApp, Email, etc.)</description>
    <label>Contato do Lead</label>
    <nameField>
        <displayFormat>LC-{00000000}</displayFormat>
        <label>Número de Contato do Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contatos do Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canal de Comunicação (Email, Phone, WhatsApp).</description>
    <inlineHelpText>Canal de Comunicação (Email, Phone, WhatsApp).</inlineHelpText>
    <label>Canal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Descrição do Canal de Comunicação (Email, Número de Telefone, Número de WhatsApp).</description>
    <inlineHelpText>Descrição do Canal de Comunicação (Email, Número de Telefone, Número de WhatsApp).</inlineHelpText>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Contato do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que leva até o Lead ao qual pertence o Contato.</description>
    <inlineHelpText>Campo que leva até o Lead ao qual pertence o Contato.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Contatos do Lead</relationshipLabel>
    <relationshipName>LeadCommunicationContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do Canal de Comunicação do Lead (Personal, Comercial).</description>
    <inlineHelpText>Tipo do Canal de Comunicação do Lead (Personal, Comercial).</inlineHelpText>
    <label>Tipo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/LeadAndLeadContactsIntegration.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Class created to Insert or Update an Lead and Contacts from an API.
* ================================================================================================================================
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          14/12/2021      Created     Class created to Insert or Update an Lead and Contacts from an API.
**********************************************************************************************************************************/

@RestResource(urlMapping='/lead/*')
global with sharing class LeadAndLeadContactsIntegration{
    
    @HttpPost
    global static String upsertLead(){
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        LeadAndLeadContactsIntegrationVO request = (LeadAndLeadContactsIntegrationVO) System.JSON.deserialize(req.requestBody.toString(), LeadAndLeadContactsIntegrationVO.class);
        
        List<Lead> lead = new List<Lead>();

        List<String> codes = new List<String>();

        Map<String, LeadCommunicationContact__c> leadContacts = new Map<String, LeadCommunicationContact__c>();
       
		      
        if(string.isBlank(request.fullName)){
			res.statusCode = 400;  
            return 'Error: fullName is empty!';            
        }

        if(request.contacts.isEmpty()){
            res.statusCode = 400;  
            return 'Error: The payload has no contacts!'; 
        }
        
        for(LeadAndLeadContactsIntegrationVO.Contact ctt : request.contacts){
            
            if(string.isBlank(ctt.channel)){
                res.statusCode = 400;  
                return 'Error: channel is empty!';
            }	
                       
            if(string.isBlank(ctt.code)){
                res.statusCode = 400;  
                return 'Error: code is empty!';
            }

            if(string.isBlank(ctt.type)){
                res.statusCode = 400;  
                return 'Error: type is empty!';
            }
            
            codes.add(ctt.code);
        }
        

        Id leadId;
        for(LeadCommunicationContact__c theContact : [SELECT    ExternalId__c,
                                                                Channel__c,
                                                                Code__c,
                                                                Type__c,
                                                                Lead__c,
                                                                Lead__r.auxLeadName__c 
													  FROM LeadCommunicationContact__c  
                                                      WHERE Lead__r.auxLeadName__c = :request.fullName AND Code__c IN :codes]){ 
            leadId = theContact.Lead__c;              
            leadContacts.put(theContact.Lead__r.auxLeadName__c+theContact.Code__c, theContact);
        }
                        
        if(leadId != null){

            lead = [SELECT  RecordTypeId, 
                        	FirstName, 
                        	LastName,            
                        	DocumentType__c,
                        	CPF__c, 
                        	Company,
                        	mainDocumentCode__c
                FROM Lead
                WHERE Id =: leadId];
        
            lead[0].DocumentType__c        = request.mainDocument.type;
			lead[0].CPF__c                 = request.mainDocument.code;
            lead[0].Company                = string.isBlank(request.company.businessName) ? '--' : request.company.businessName;
            lead[0].mainDocumentCode__c	   = string.isBlank(request.company.mainDocumentCode) ? '--' : request.company.mainDocumentCode;
            
        }else{
            
            String firstName; 
            String lastName;
            
            try{
                firstName = request.fullName.substring(0, request.fullName.indexOf(' '));
                lastName = request.fullName.substring(request.fullName.indexOf(' ')+1, request.fullName.length());
            } catch(Exception e){
                res.statusCode = 500;
                return 'Error: Incorrect fullName!';
            }
         	
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];

            Lead newLead = new Lead();
            
            newLead.RecordTypeId        = recordTypeLead.Id;
            newLead.FirstName	        = firstName;
            newLead.LastName            = lastName;
            newLead.DocumentType__c     = request.mainDocument.type;
			newLead.CPF__c              = request.mainDocument.code;
            newLead.Company             = string.isBlank(request.company.businessName) ? '--' : request.company.businessName;
            newLead.mainDocumentCode__c	= string.isBlank(request.company.mainDocumentCode) ? '--' : request.company.mainDocumentCode;
            
            lead.add(newLead);                          
        }
	        try {
                upsert lead;

                List<LeadCommunicationContact__c> cttToInsert = new List<LeadCommunicationContact__c>();

                for(LeadAndLeadContactsIntegrationVO.Contact newCtt : request.contacts){

                    LeadCommunicationContact__c theContact = leadContacts.get(request.fullName+newCtt.code);

                    if(theContact == null){
                        theContact = new LeadCommunicationContact__c(Lead__c = lead[0].Id);
                    }                       

                    theContact.ExternalId__c       = newCtt.id;
                    theContact.Channel__c          = newCtt.channel;
                    theContact.Code__c             = newCtt.code;
                    theContact.Type__c             = newCtt.type;
                    cttToInsert.add(theContact);
                }

                if(cttToInsert.size() > 0){
                    upsert cttToInsert;
                } 

                res.statusCode = 200;
                return 'Success: Record created/updated successfully!';

            } catch (Exception e) {
                res.statusCode = 500;
                if(res.statusCode == 500){
                    return 'Error: Failed to complete the request. Please, review the payload.';
                }
                System.debug(e.getMessage());
                return 'Error: Failed to complete the request!';
            }
    }
    
}