creditas-sf/force-app/main/default/objects/Contact/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PERSONAL</fullName>
            </value>
            <value>
                <fullName>COMERCIAL</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do Contato</description>
    <label>CPF do contato</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de Documento do Lead</description>
    <label>Tipo de documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/mainDocumentCode__c.field-meta.xml
<CustomField>
    <fullName>mainDocumentCode__c</fullName>
    <description>Documento Principal da Empresa (CNPJ)</description>
    <label>Documento principal da empresa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <businessProcess>Auto</businessProcess>
    <description>Tipo de Registro do Lead: Auto</description>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/LeadCommunicationContact__c.object-meta.xml
<CustomObject>
    <description>Contatos do Lead (Telefone, WhatsApp, Email, etc.)</description>
    <label>Contato do Lead</label>
    <nameField>
        <displayFormat>LC-{00000000}</displayFormat>
        <label>Número de Contato do Lead</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contatos do Lead</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <description>Canal de Comunicação (Email, Phone, WhatsApp).</description>
    <inlineHelpText>Canal de Comunicação (Email, Phone, WhatsApp).</inlineHelpText>
    <label>Canal</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <description>Descrição do Canal de Comunicação (Email, Número de Telefone, Número de WhatsApp).</description>
    <inlineHelpText>Descrição do Canal de Comunicação (Email, Número de Telefone, Número de WhatsApp).</inlineHelpText>
    <label>Código</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Contato do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que leva até o Lead ao qual pertence o Contato.</description>
    <inlineHelpText>Campo que leva até o Lead ao qual pertence o Contato.</inlineHelpText>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipLabel>Contatos do Lead</relationshipLabel>
    <relationshipName>LeadCommunicationContacts</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/LeadCommunicationContact__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do Canal de Comunicação do Lead (Personal, Comercial).</description>
    <inlineHelpText>Tipo do Canal de Comunicação do Lead (Personal, Comercial).</inlineHelpText>
    <label>Tipo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/LeadFromContactIntegrationTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Test Class to LeadFromContactIntegration Class.
* ================================================================================================================================
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          12/01/2022      Created     Test Class to LeadFromContactIntegration Class.
**********************************************************************************************************************************/

@isTest
public with sharing class LeadFromContactIntegrationTest{

	static testMethod void foundLead() {
    	String json= '  { '+ 
		'   "contact": '+ 
        '   {   '+
        '   "id": "L001", '+
        '   "channel": "Email", '+
        '   "code": "maria.neves@gmail.com", '+
        '   "type": "COMERCIAL" '+
        '   } '+
        '	} ';
        
		Test.startTest();

            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
              
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;
            newLead.ExternalId__c       = 'L001';            
            newLead.FirstName	        = 'Maria';
            newLead.LastName            = 'Das Neves';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678911';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c	= '--';
            insert newLead;
          
            Lead idLead = [SELECT Id FROM Lead];
          
            LeadCommunicationContact__c newContact = new LeadCommunicationContact__c();
          
            newContact.ExternalId__c	= 'L001';
            newContact.Channel__c       = 'Email';
            newContact.Code__c          = 'maria.neves@gmail.com';
            newContact.Type__c          = 'COMERCIAL';
            newContact.Lead__c	        = idLead.Id;
            insert newContact;
        
            LeadFromContactIntegrationVO VO = new LeadFromContactIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
          
            req.requestURI = '/services/leads/search';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            LeadFromContactIntegration.getLead();  
            System.assertequals(200, res.statusCode, 'One or more leadId related to the informed Contact must be returned.');
        
		Test.stopTest();   
	}

	static testMethod void leadNotFound(){
        String json= '  { '+ 
        '   "contact": '+ 
        '   {   '+
        '   "id": "", '+
        '   "channel": "Email", '+
        '   "code": "maria.neves@gmail.com", '+
        '   "type": "COMERCIAL" '+
        '   } '+
        '	} ';
    
		Test.startTest();
        
        	RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];

            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;
            newLead.ExternalId__c       = 'L001';            
            newLead.FirstName	        = 'Maria';
            newLead.LastName            = 'Das Neves';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678911';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c	= '--';
            insert newLead;
      
            Lead idLead = [SELECT Id FROM Lead];
          
            LeadCommunicationContact__c newContact = new LeadCommunicationContact__c();
          
            newContact.ExternalId__c	= 'L001';
            newContact.Channel__c       = 'Email';
            newContact.Code__c          = 'maria.neves@gmail.com';
            newContact.Type__c          = 'COMERCIAL';
            newContact.Lead__c	        = idLead.Id;
            insert newContact;
    
			LeadFromContactIntegrationVO VO = new LeadFromContactIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
                  
            req.requestURI = '/services/leads/search';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
    
            LeadFromContactIntegration.getLead();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as a Lead related to the informed Contact was not found.');

		Test.stopTest();   
	}

   
	static testMethod void contactWithoutChannel(){        
        String json= '  { '+ 
        '   "contact": '+ 
        '   {   '+
        '   "id": "0010", '+
        '   "channel": "", '+
        '   "code": "erika.t@gmail.com", '+
        '   "type": "COMERCIAL" '+
        '   } '+
        '	} ';
        
        Test.startTest();
    
            LeadFromContactIntegrationVO VO = new LeadFromContactIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
                  
            req.requestURI = '/services/leads/search';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
                
            LeadFromContactIntegration.getLead();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the Channel was not informed.');
    
		Test.stopTest();   
	} 
    
    static testMethod void contactWithoutCode(){        
        String json= '  { '+ 
        '   "contact": '+ 
        '   {   '+
        '   "id": "0010", '+
        '   "channel": "Email", '+
        '   "code": "", '+
        '   "type": "COMERCIAL" '+
        '   } '+
        '	} ';
        
        Test.startTest();
    
            LeadFromContactIntegrationVO VO = new LeadFromContactIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
                  
            req.requestURI = '/services/leads/search';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
                
            LeadFromContactIntegration.getLead();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the Code was not informed.');
    
        Test.stopTest();   
	}  

    static testMethod void contactWithoutType(){        
        String json= '  { '+ 
        '   "contact": '+ 
        '   {   '+
        '   "id": "0010", '+
        '   "channel": "Email", '+
        '   "code": "erika.t@gmail.com", '+
        '   "type": "" '+
        '   } '+
        '	} ';
        
        Test.startTest();
    
            LeadFromContactIntegrationVO VO = new LeadFromContactIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();
                  
            req.requestURI = '/services/leads/search';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
                
            LeadFromContactIntegration.getLead();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the Type was not informed.');
    
        Test.stopTest();   
	} 

}