creditas-sf/force-app/main/default/objects/Product2/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Valor do Produto</description>
    <label>Valor do produto</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <description>Marca do Produto (Ex.: Hyundai)</description>
    <label>Marca</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/CurrentKM__c.field-meta.xml
<CustomField>
    <fullName>CurrentKM__c</fullName>
    <description>KM Atual do Produto (Ex.: 100.000)</description>
    <label>KM atual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/LinkToAdmin__c.field-meta.xml
<CustomField>
    <fullName>LinkToAdmin__c</fullName>
    <description>Link para o Veículo / Produto no Sistema Admin (Ex.: https://admin.crmvolanty.com/#/anunciado/detalhes/6451306068705280/informacao)</description>
    <label>Link do admin</label>
    <type>Url</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/LinkToVehicle__c.field-meta.xml
<CustomField>
    <fullName>LinkToVehicle__c</fullName>
    <description>Link para o Veículo / Produto no Portal Creditas Auto (Ex.: https://auto.creditas.com/comprar/hyundai/hb20/6451306068705280/hyundai-hb20-1.0-comfort-plus-12v-flex-4p-manual-39759km)</description>
    <label>Link do carro</label>
    <type>Url</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/Location__c.field-meta.xml
<CustomField>
    <fullName>Location__c</fullName>
    <description>Loja onde o Veículo / Produto está localizado (Ex.: SP - Shopping Jardim Sul)

Observação: No sistema de origem, Loja = Cav</description>
    <label>Loja [estoque]</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/ManufacturingYear__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingYear__c</fullName>
    <description>Ano de Fabricação do Produto (Ex.: 2022)</description>
    <label>Ano de fabricação</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/ModelYear__c.field-meta.xml
<CustomField>
    <fullName>ModelYear__c</fullName>
    <description>Ano do Produto (Ex.: 2022)</description>
    <label>Ano do veículo</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/Plate__c.field-meta.xml
<CustomField>
    <fullName>Plate__c</fullName>
    <description>Placa do Produto (Ex.: LUH5716)</description>
    <label>Placa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto</description>
    <label>Tipo de produto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantidade do Produto</description>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/StockVehicleID__c.field-meta.xml
<CustomField>
    <fullName>StockVehicleID__c</fullName>
    <description>ID do Veículo / Produto no Estoque (Ex.: 6451310000000000)</description>
    <label>ID do veículo no estoque</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/StockVehicleStatus__c.field-meta.xml
<CustomField>
    <fullName>StockVehicleStatus__c</fullName>
    <description>Status do Veículo / Produto no Estoque</description>
    <label>Status do carro no Estoque</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Disponível (carro em estoque)</fullName>
            </value>
            <value>
                <fullName>Pré-venda</fullName>
            </value>
            <value>
                <fullName>Reservado</fullName>
            </value>
            <value>
                <fullName>Intermediação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro do Produto: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/classes/ProductIntegration.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Class created to Insert or Update a Product.
* ================================================================================================================================
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          17/01/2022      Created     Class created to Insert or Update a Product.
**********************************************************************************************************************************/

@RestResource(urlMapping='/product/*')
global with sharing class ProductIntegration{
    
    @HttpPost
    global static String upsertProduct(){
        
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        ProductIntegrationVO request = (ProductIntegrationVO) System.JSON.deserialize(req.requestBody.toString(), ProductIntegrationVO.class);
         
        List<Product2> product = new List<Product2>();
        Decimal currentKMDecimal;
        Decimal valueAmountDecimal;
        Decimal modelYearDecimal;
        Decimal manufacturingYearDecimal;
        Decimal quantityDecimal;
        String stockVehicleStatus;
        
        if(string.isNotBlank(request.currentKM)){
         	String currentKMDot = request.currentKM.replace(',','.');
        	currentKMDecimal = decimal.valueOf(currentKMDot);  
        }
           
        if(string.isNotBlank(request.value.amount)){
         	String valueAmountDot = request.value.amount.replace(',','.');
         	valueAmountDecimal = decimal.valueOf(valueAmountDot);     
        } 
       
        if(string.isBlank(request.modelYear)){
           modelYearDecimal = null;
        }else{
            modelYearDecimal = decimal.valueOf(request.modelYear);
       	}
                
        if(string.isBlank(request.manufacturingYear)){
           manufacturingYearDecimal = null;
        }else{
           manufacturingYearDecimal = decimal.valueOf(request.manufacturingYear);
       	}
        
        if(string.isBlank(request.quantity)){
			quantityDecimal = null;
        }else{
            quantityDecimal = decimal.valueOf(request.quantity);
       	}
        
        if(string.isBlank(request.name)){
			res.statusCode = 400;  
            return 'Error: name is empty!';            
        }
               
        if(string.isBlank(request.ProductId)){
			res.statusCode = 400;  
            return 'Error: productId is empty!';            
        }
        
        if(string.isBlank(request.currencyIsoCode)){
			res.statusCode = 400;  
            return 'Error: currencyIsoCode is empty!';            
        }
                 
       List<CurrencyType> currencyProductOut = [SELECT Id FROM CurrencyType WHERE isoCode =: request.currencyIsoCode];

        if(currencyProductOut.isEmpty()){ 
            res.statusCode = 400;  
            return 'Error: No match found for Currency!';
        }
                   
       	if(string.isBlank(request.value.currencyIsoCode)){
			res.statusCode = 400;  
            return 'Error: currencyIsoCode is empty!';            
        }
          
		List<CurrencyType> currencyProduct = [SELECT Id FROM CurrencyType WHERE isoCode =: request.value.currencyIsoCode];

        if(currencyProduct.isEmpty()){ 
            res.statusCode = 400;  
            return 'Error: No match found for Currency!';
        }
              
        if(string.isNotBlank(request.stockVehicleStatus)){
            
            if(request.stockVehicleStatus == 'Disponível'){
            	stockVehicleStatus = 'Disponível (carro em estoque)';
            }else{
            	stockVehicleStatus = request.stockVehicleStatus;
            }
            
			List<PicklistValueInfo> picklistStockValues= [SELECT Value FROM PicklistValueInfo WHERE EntityParticle.EntityDefinition.QualifiedApiName = 'Product2' AND EntityParticle.DeveloperName = 'StockVehicleStatus' AND Value =: stockVehicleStatus];
        
        	if(picklistStockValues.isEmpty()){ 
            	res.statusCode = 400;  
            	return 'No match found for stockVehicleStatus!';
            }             
        }
        
        product = [SELECT ExternalId,
                   		  Name,
                   		  ManufacturingYear__c,
                   		  CurrencyIsoCode,
                   		  Amount__c,
                   		  Plate__c,
                   		  Brand__c,
                   		  ModelYear__c,
                   		  CurrentKM__c,
                   		  LinkToAdmin__c,
                   		  LinkToVehicle__c,
                   		  StockVehicleID__c,
                   		  StockVehicleStatus__c,
                   		  Location__c,
                   		  Quantity__c,
                   		  ProductType__c,
						  RecordTypeId                   
                   FROM Product2
                   WHERE ExternalId =: request.ProductId];
        
        if(!product.isEmpty()){
			product[0].Name 				 = request.name;
			product[0].ManufacturingYear__c  = manufacturingYearDecimal;
			product[0].CurrencyIsoCode		 = request.value.currencyIsoCode;
            product[0].Amount__c			 = string.isBlank(request.value.amount) ? null : valueAmountDecimal;
           	product[0].Plate__c              = request.plate; 
           	product[0].Brand__c              = request.brand;
           	product[0].ModelYear__c          = modelYearDecimal;
           	product[0].CurrentKM__c          = string.isBlank(request.currentKM) ? null : currentKMDecimal;  
           	product[0].LinkToAdmin__c   	 = request.linkToAdmin;
           	product[0].LinkToVehicle__c  	 = request.linkToVehicle;              
           	product[0].StockVehicleID__c  	 = request.stockVehicleID;             
           	product[0].StockVehicleStatus__c = string.isBlank(request.stockVehicleStatus) ? '' : stockVehicleStatus;                
           	product[0].Location__c 			 = request.location;
            product[0].Quantity__c 			 = quantityDecimal;
            product[0].ProductType__c 		 = request.productType; 
            
            
		}else{
            
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
           
            Product2 newProduct = new Product2();
            
            newProduct.RecordTypeId			 = recordTypeProduct.Id;
            newProduct.ExternalId			 = request.productId;
            newProduct.Name 				 = request.name;
			newProduct.ManufacturingYear__c  = manufacturingYearDecimal;
			newProduct.CurrencyIsoCode		 = request.value.currencyIsoCode;
            newProduct.Amount__c			 = string.isBlank(request.value.amount) ? null : valueAmountDecimal;
           	newProduct.Plate__c              = request.plate; 
           	newProduct.Brand__c              = request.brand;
           	newProduct.ModelYear__c          = modelYearDecimal;  
           	newProduct.CurrentKM__c          = string.isBlank(request.currentKM) ? null : currentKMDecimal;  
           	newProduct.LinkToAdmin__c   	 = request.linkToAdmin;
           	newProduct.LinkToVehicle__c  	 = request.linkToVehicle;              
           	newProduct.StockVehicleID__c  	 = request.stockVehicleID;             
           	newProduct.StockVehicleStatus__c = string.isBlank(request.stockVehicleStatus) ? '' : stockVehicleStatus;               
           	newProduct.Location__c 			 = request.location;
            newProduct.Quantity__c 			 = quantityDecimal;
            newProduct.ProductType__c 		 = request.productType; 

            product.add(newProduct);
        }
        
        try {
        	upsert product; 
            
            res.statusCode = 200;
            return 'Success: Record created/updated successfully!';
         
        }catch (Exception e) {
            System.debug(e.getMessage());
            return 'Error: Failed to complete the request!';
        }       
    }
}