creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ExternalOpportunityTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityTenant__c</fullName>
    <label>ExternalOpportunityTenant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ExternalOpportunityVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityVersion__c</fullName>
    <label>ExternalOpportunityVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/QuoteTriggerController.cls
/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Default handler for the QuoteTrigger
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Nathalia Rosa          17/12/2021      Created     	Default handler for the QuoteTrigger
**********************************************************************************************************************************/
public without sharing class QuoteTriggerController extends TriggerHandler
{
    private List<Quote> lstNewQuotes;
    private List<Quote> lstOldQuotes;
    private Map<Id, Quote> mapNewQuotes;
    private Map<Id, Quote> mapOldQuotes;
    
    public QuoteTriggerController()
    {
        this.lstNewQuotes = (List<Quote>) Trigger.new;
        this.lstOldQuotes = (List<Quote>) Trigger.old;
        this.mapNewQuotes = (Map<Id, Quote>) Trigger.newMap;
        this.mapOldQuotes = (Map<Id, Quote>) Trigger.oldMap;
    }
   
    public override void beforeInsert()
    {
        this.updateOpportunityExternalFields();
    }
    
    public override void afterInsert() 
    {
        
    }
    
    public override void beforeUpdate()
    {
        this.updateMethod();
        this.updateOpportunityExternalFields();
    }
    
    public override void afterUpdate() 

    {
    }

    private void updateMethod()
    {
        Util.updateIsExternallySyncedOpportunity('Quote', lstNewQuotes, mapOldQuotes);
    }

    private void updateOpportunityExternalFields()
    {
        Set<Id> setOpportunityIds = new Set<Id>();
        
        for(Quote varQuotes : lstNewQuotes)
        {
            setOpportunityIds.add(varQuotes.OpportunityId);
        }

        Map<Id, Opportunity> mapOpportunity = new Map<Id, Opportunity>([SELECT Id, Name, ExternalVersion__c, ExternalId__c, ExternalTenant__c FROM Opportunity WHERE Id IN :setOpportunityIds]);

        for(Quote varQuotes : lstNewQuotes)
        {
            varQuotes.ExternalOpportunityId__c = mapOpportunity.get(varQuotes.OpportunityId).ExternalId__c;
            varQuotes.ExternalOpportunityVersion__c = mapOpportunity.get(varQuotes.OpportunityId).ExternalVersion__c;
            varQuotes.ExternalOpportunityTenant__c = mapOpportunity.get(varQuotes.OpportunityId).ExternalTenant__c;
        }        
    }
}