creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ParameterTac__c.field-meta.xml
<CustomField>
    <fullName>ParameterTac__c</fullName>
    <label>Valor TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityService.cls
/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Web Service customizado para criação de Opportunities and seus objetos relacionados 
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Thales Yumiya           16/09/2021      Created     Implementação das requisições REST do web service de Opportunity
**********************************************************************************************************************************/
@RestResource(urlMapping='/IntegrationOpportunity/*')
global without sharing class OpportunityService {
    
	@HttpPost
    global static void postMethod() 
    {
        OpportunityIntegrationModel requestBodyObj = OpportunityIntegrationModel.parse(RestContext.request.requestBody.toString());

        Id opportunityId = upsertOpportunity(requestBodyObj);
        
        upsertQuote(requestBodyObj, opportunityId);
    }
    
    
    private static Id upsertOpportunity(OpportunityIntegrationModel requestBodyObj)
    {            
        Opportunity opportunityToUpsert = new Opportunity();      
        opportunityToUpsert.Id = [SELECT ExternalId__c FROM Opportunity WHERE ExternalId__c = :requestBodyObj.id]?.Id;
        opportunityToUpsert.ExternalVersion__c = Decimal.valueOf(requestBodyObj.version);
        opportunityToUpsert.ExternalTenant__c = requestBodyObj.tenant;
        opportunityToUpsert.ExternalCreationDate__c = DateTime.parse(requestBodyObj.createdAt);
        opportunityToUpsert.ExternalUpdatedDate__c = DateTime.parse(requestBodyObj.updateAt);
                
        upsert opportunityToUpsert;
         
        return opportunityToUpsert.Id;

    }

    
    private static void upsertQuote(OpportunityIntegrationModel requestBodyObj, Id opportunityId)
    {
        Quote quoteToUpsert = new Quote();
        quoteToUpsert.Id = [SELECT Id FROM Quote WHERE OpportunityId = :opportunityId]?.Id;
        quoteToUpsert.ParameterTac__c = requestBodyObj.conditions.parameters.tac.amount;
    }

    /*public static Opportunity getOpportunityById(Id opportunityId) {
        return [SELECT Id, Name 
                FROM Opportunity
                WHERE Id =: opportunityId];
    }*/

    private class Response {
        public String status;
        public String opportunityId;
        public String message;
    }
}