creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/OpportunityProcess__c.object-meta.xml
<CustomObject>
    <label>Processos da Oportunidade</label>
    <nameField>
        <label>Processos da Oportunidade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processos da Oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Processos da Oportunidade</relationshipLabel>
    <relationshipName>Processos_da_Oportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityProcessTriggerService.cls
public with sharing class OpportunityProcessTriggerService {
    
    public static void updateMethod(List<OpportunityProcess__c> newOpportunities, Map<Id, OpportunityProcess__c> oldOpportunitiesById)
    {
        Util.updateIsExternallySyncedOpportunity('OpportunityProcess__c', newOpportunities, oldOpportunitiesById);
    }

    public static void updateOpportunityExternalFields(List<OpportunityProcess__c> newOpportunities)
    {
        Set<Id> opportunityIds = new Set<Id>();
        
        for(OpportunityProcess__c opportunityProcess : newOpportunities)
        {
            opportunityIds.add(opportunityProcess.Opportunity__c);
        }

        Map<Id, Opportunity> opportunities = new Map<Id, Opportunity>([SELECT Id, Name, ExternalVersion__c, ExternalId__c, ExternalTenant__c FROM Opportunity WHERE Id IN :opportunityIds]);

        for(OpportunityProcess__c opportunityProcess : newOpportunities)
        {
            opportunityProcess.ExternalOpportunityId__c = opportunities.get(opportunityProcess.Opportunity__c).ExternalId__c;
            opportunityProcess.ExternalOpportunityVersion__c = opportunities.get(opportunityProcess.Opportunity__c).ExternalVersion__c;
            opportunityProcess.ExternalOpportunityTenant__c = opportunities.get(opportunityProcess.Opportunity__c).ExternalTenant__c;
        }        
    }
}