creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/SynchOpportunityDataController.cls
public with sharing class SynchOpportunityDataController {
    
    @AuraEnabled(cacheable=true)
    public static Opportunity getSyncInfo(Id oppId) {
      Opportunity result = [SELECT IsSynchEnabled__c, IsExternallySynched__c, name FROM Opportunity WHERE Id =:oppId][0];
        return result;       
    }
    
    @AuraEnabled
    public static void updateSynchingFields(Opportunity opp) {
        
        Opportunity oppToUpdate = new Opportunity(
           Id = opp.Id,
           IsSynchEnabled__c = 'SYNCHING',
           IsExternallySynched__c = false
        );
         
        update oppToUpdate;
    }
}