creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>SOLIDARY_DEBTOR</fullName>
            </value>
            <value>
                <fullName>COLLATERAL_GUARANTOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/GarantiasTriggerHandlerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Classe de teste para a classe GarantiasTriggerHandler
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          22/10/2021      Created     Classe de teste para o GarantiasTriggerHandler
**********************************************************************************************************************************/
@isTest
public class GarantiasTriggerHandlerTest {
    
    @TestSetup
    static void makeData()
    {
        Account newAcc = TestSetup.getAccount('Conta', true);
        
        Opportunity newOppty = TestSetup.getOpportunity(newAcc.Id, true);
        
        Opportunity newOppty2 = TestSetup.getOpportunity(newAcc.Id, true);
        
        OpportunityRole__c newOpptyRole = TestSetup.getOppRole(newAcc, newOppty, 'PRINCIPAL', false, true);
        
        OpportunityRole__c newOpptyRole2 = TestSetup.getOppRole(newAcc, newOppty2, 'COLLATERAL_GUARANTOR', false, true);
        
        FinancialResources__c newRecFin = TestSetup.getNewFinRes('Novo Recurso Financeiro', true);	        
    }
    
    @isTest
    static void insertGuaranteeFailed() 
    {
        FinancialResources__c recFinRes = [SELECT Id FROM FinancialResources__c];
        
        Account accRes = [SELECT Id FROM Account];
        
        List<Opportunity> opptyRes = [SELECT Id FROM Opportunity WHERE AccountId =: accRes.Id ];
        
        OpportunityRole__c roleRes = [SELECT Id, Role__c, Opportunity__c
                   					  FROM OpportunityRole__c 
                   					  WHERE Opportunity__c IN :opptyRes AND Role__c = 'PRINCIPAL'];
        

        Garantias__c newGuarantee= new Garantias__c();
        //newGuarantee.Name = 'Nova Garantia';
        newGuarantee.Account__c = accRes.Id;
        newGuarantee.Opportunity__c = roleRes.Opportunity__c;
        newGuarantee.Recurso_Financeiro__c = recFinRes.Id;
        
                    
        Test.startTest();
        try{
			insert newGuarantee; 
        } catch (DMLException e) {
    		System.debug('The following exception has occurred: ' + e.getMessage());
        }       
        Test.stopTest();
        
		List<Garantias__c> res = [SELECT Id FROM Garantias__c];  
        
        System.assertEquals(0, res.Size());
    }
    
    @isTest
    static void insertUpdateGuaranteeSucess() 
    {
        FinancialResources__c recFinRes = [SELECT Id FROM FinancialResources__c];
        
        Account accRes = [SELECT Id FROM Account];
        
        List<Opportunity> opptyRes = [SELECT Id FROM Opportunity WHERE AccountId =: accRes.Id ];
              
        OpportunityRole__c roleRes = [SELECT Id, Role__c, Opportunity__c
                   					  FROM OpportunityRole__c 
                   					  WHERE Opportunity__c IN :opptyRes AND Role__c = 'COLLATERAL_GUARANTOR'];
        
        Garantias__c newGuarantee= new Garantias__c();
        //newGuarantee.Name = 'Nova Garantia';
        newGuarantee.Account__c = accRes.Id;
        newGuarantee.Opportunity__c = roleRes.Opportunity__c;
        newGuarantee.Recurso_Financeiro__c = recFinRes.Id;
        insert newGuarantee;
        
		Garantias__c resInserted = [SELECT Name FROM Garantias__c];  
        
        //newGuarantee.Name = 'Nova Garantia2';
      
        Test.startTest();
        update newGuarantee;   
        Test.stopTest();
        
        Garantias__c resUpdated = [SELECT Name FROM Garantias__c];
            
        //System.assertNotEquals(resInserted, resUpdated);
    }
    
}