creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Quantia referente ao registro que está sendo cadastrado</description>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Cor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalCodeOrigin__c.field-meta.xml
<CustomField>
    <fullName>ExternalCodeOrigin__c</fullName>
    <externalId>true</externalId>
    <label>Código da Tabela FIPE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/LicensingState__c.field-meta.xml
<CustomField>
    <fullName>LicensingState__c</fullName>
    <label>UF de licenciamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ManufacturingYear__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingYear__c</fullName>
    <label>Ano de Fabricação</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ModelYear__c.field-meta.xml
<CustomField>
    <fullName>ModelYear__c</fullName>
    <label>Ano do Modelo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Plate__c.field-meta.xml
<CustomField>
    <fullName>Plate__c</fullName>
    <label>Placa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ResourceKey__c.field-meta.xml
<CustomField>
    <fullName>ResourceKey__c</fullName>
    <label>ResourceKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ResourceKeyType__c.field-meta.xml
<CustomField>
    <fullName>ResourceKeyType__c</fullName>
    <label>Tipo da Chave</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DEED_NUMBER</fullName>
            </value>
            <value>
                <fullName>RENAVAM</fullName>
            </value>
            <value>
                <fullName>CHASSIS</fullName>
            </value>
            <value>
                <fullName>CERTIFICATE_ID</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Origem do valor que está sendo cadastrado</description>
    <label>Origem</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SALES</fullName>
            </value>
            <value>
                <fullName>BUSINESSES</fullName>
            </value>
            <value>
                <fullName>INVESTMENT</fullName>
            </value>
            <value>
                <fullName>COMMISSIONS</fullName>
            </value>
            <value>
                <fullName>DONATIONS</fullName>
            </value>
            <value>
                <fullName>REMITTANCES</fullName>
            </value>
            <value>
                <fullName>RAFFLES</fullName>
            </value>
            <value>
                <fullName>SAVINGS</fullName>
            </value>
            <value>
                <fullName>SAVING_FUNDS</fullName>
            </value>
            <value>
                <fullName>THIRD_PARTY_RESOURCES</fullName>
            </value>
            <value>
                <fullName>SALARIES</fullName>
            </value>
            <value>
                <fullName>INHERITANCE</fullName>
            </value>
            <value>
                <fullName>LOANS</fullName>
            </value>
            <value>
                <fullName>SCHOLARSHIPS</fullName>
            </value>
            <value>
                <fullName>FEES</fullName>
            </value>
            <value>
                <fullName>PENSIONS</fullName>
            </value>
            <value>
                <fullName>RENTS</fullName>
            </value>
            <value>
                <fullName>NO_SOURCES</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Estado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do recurso que está sendo registrado</description>
    <label>Tipo de Recurso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>PRESUMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>CONFIRMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>NET_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>LAND</fullName>
            </value>
            <value>
                <fullName>CONDOMINIUM_HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL_ROOM</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>MOTORCYCLE</fullName>
            </value>
            <value>
                <fullName>QUADRICYCLE</fullName>
            </value>
            <value>
                <fullName>TRUCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Certificado.recordType-meta.xml
<RecordType>
    <fullName>Certificado</fullName>
    <active>true</active>
    <label>Certificado</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Imovel.recordType-meta.xml
<RecordType>
    <fullName>Imovel</fullName>
    <active>true</active>
    <label>Imóvel</label>
</RecordType>

creditas-sf/force-app/main/default/classes/FinancialResourceSetup.cls
@isTest
public with sharing class FinancialResourceSetup {
    
    public static FinancialResources__c createFinancialResource(String recordTypeDevName){
        String finRT = Util.getRecordTypeIdbyName('FinancialResources__c', recordTypeDevName);
        FinancialResources__c finResource = new FinancialResources__c(
            RecordTypeId = finRT,
            Name = 'Test Financial Resource',
            ExternalId__c = 'FIN-RESOURCE-2077',
            ExternalCreationDate__c = Datetime.now().addDays(-5),
            ExternalUpdatedDate__c = Datetime.now(),
            State__c = 'SP',
            Amount__c = 20777702
        );
        if('Auto' == recordTypeDevName){
            finResource.ResourceKeyType__c = 'RENAVAM';
            finResource.ResourceKey__c = '14522325';
            finResource.Plate__c = 'DBZ-2077';
            finResource.ModelYear__c = String.valueOf(Date.today().year());
            finResource.ManufacturingYear__c = String.valueOf(Date.today().year());
            finResource.Brand__c = 'Tesla';
            finResource.Model__c = 'Y';
            finResource.Color__c = 'Frost White';
            finResource.LicensingState__c = 'SP';
            finResource.ExternalCodeOrigin__c = '10771989';
        } else if('Certificado' == recordTypeDevName){
            finResource.Source__c = 'INVESTMENT';
            finResource.Type__c = 'MONTHLY_INCOME';
        } else if('Imovel' == recordTypeDevName){
            finResource.ResourceKeyType__c = 'DEED_NUMBER';
            finResource.ResourceKey__c = '14522325';
            finResource.Type__c = 'APARTMENT';
        } else {
            finResource.Source__c = 'RENTS';
            finResource.Type__c = 'NET_MONTHLY_INCOME';
        }

        return finResource;
    }
}