creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/EmployeeTriggerService.cls
public with sharing class EmployeeTriggerService {
  public static void firePlatformEventSynchEmployee(List<Employee__c> employees) {
    List<SynchEmployee__e> events = new List<SynchEmployee__e>();
    for (Employee__c employee : employees) {
      if (employee.IsSynchEnabled__c == 'ENABLED') {
        SynchEmployee__e synch = new SynchEmployee__e();
        events.add(synch);
      }
    }

    Eventbus.publish(events);
  }

  public static void updateExternallySynced(List<Employee__c> employees) {
    List<String> trackedFields = Util.returnCustomMetadaDataFieldApiName('Employee__c');
    for (Employee__c employee : employees) {
      if (TriggerHelper.changedField(employee, trackedFields)) {
        employee.IsExternallySynched__c = false;
      }
    }
  }
}