creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Valor da margem</description>
    <label>Valor da margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/EmployeeTriggerTest.cls
@isTest
private class EmployeeTriggerTest {
  @IsTest
  private static void testUpdateSingle() {
    Employee__c employee = new Employee__c(
      Name = 'Test',
      IsSynchEnabled__c = 'ENABLED',
      IsExternallySynched__c = true,
      Margin__c = 5000
    );

    insert employee;

    employee.Margin__c = 6000;

    Test.startTest();

    update employee;

    Test.stopTest();

    Boolean isExternallySynched = [SELECT Margin__c, IsExternallySynched__c FROM Employee__c].IsExternallySynched__c;

    Set<String> trackedFieds = new Set<String>(Util.returnCustomMetadaDataFieldApiName('Employee__c'));

    if (trackedFieds.contains('Margin__c')) {
      System.assertEquals(false, isExternallySynched, 'IsExternallySynched field value should be \'false\'');
    } else {
      System.assertEquals(true, isExternallySynched, 'IsExternallySynched field value should be \'true\'');
    }
  }

  @IsTest
  private static void testUpdateBulk() {
    List<Employee__c> employees = new List<Employee__c>();

    for (Integer i = 1; i <= 200; i++) {
      employees.add(
        new Employee__c(Name = 'Test', IsSynchEnabled__c = 'ENABLED', IsExternallySynched__c = true, Margin__c = 5000)
      );
    }

    insert employees;

    for (Employee__c employee : employees) {
      employee.Margin__c = 6000;
    }

    Test.startTest();

    update employees;

    Test.stopTest();

    employees = [SELECT Margin__c, IsExternallySynched__c FROM Employee__c];

    Set<String> trackedFieds = new Set<String>(Util.returnCustomMetadaDataFieldApiName('Employee__c'));

    System.assertEquals(200, employees.size(), 'There should be 200 records');

    for (Employee__c employee : employees) {
      System.assertEquals(6000, employee.Margin__c, 'Margin__c field value should be \'6000\'');

      if (trackedFieds.contains('Margin__c')) {
        System.assertEquals(
          false,
          employee.IsExternallySynched__c,
          'IsExternallySynched__c field value should be \'false\''
        );
      } else {
        System.assertEquals(
          true,
          employee.IsExternallySynched__c,
          'IsExternallySynched__c field value should be \'true\''
        );
      }
    }
  }
}