creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/TaskDetailSettings__c.object-meta.xml
<CustomObject>
    <label>Task Detail Settings</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TaskDetailSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Detail Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/PicklistValues__c.field-meta.xml
<CustomField>
    <fullName>PicklistValues__c</fullName>
    <label>Picklist Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/classes/GetAllObjects.cls
public with sharing class GetAllObjects {
    
    @AuraEnabled(cacheable=true)

    Public static List<String> objects(){
        
        List<string> allObjects = new List<string>();

        for(Schema.SObjectType objTyp : Schema.getGlobalDescribe().Values()){
           String name = objTyp.getDescribe().getName();
        
         if(!name.containsignorecase('history') && !name.containsignorecase('tag')&&
            !name.containsignorecase('share') && !name.containsignorecase('feed')){      
                allObjects.add(name);
              System.debug( 'Name : ' + name);
          }
        
        }
        return allObjects;
    }    
  

    
    @AuraEnabled(cacheable=true)
    Public static List<String> profiles(){
        
        List<String> allProfiles = new List<String>();
        
        for(Profile profile :  [SELECT Name FROM Profile ORDER BY Name ASC]){
            allProfiles.add(profile.name);
        }
        
        //List<Profile> allProfiles = [SELECT Name FROM Profile ORDER BY Name ASC];
          
        return allProfiles;
        
    }

    @AuraEnabled(cacheable=true)
    public static String getPicklistMethod(Id recordId) {
        TaskDetailSettings__c pickListValues = [SELECT PicklistValues__c FROM TaskDetailSettings__c WHERE Id = :recordId];
        return pickListValues.PicklistValues__c; //{English;English123}
}

}