creditas-sf/force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar Negociações (Deals) realizadas com os Contatos (Leads) no processo de Auto.</description>
    <label>Deal</label>
    <nameField>
        <label>Nome do Deal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Deal__c/fields/DealValue__c.field-meta.xml
<CustomField>
    <fullName>DealValue__c</fullName>
    <description>Valor da Negociação</description>
    <label>Valor da negociação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo da Negociação</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead que está fazendo a negociação.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Negociacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/LeadOrigin__c.field-meta.xml
<CustomField>
    <fullName>LeadOrigin__c</fullName>
    <description>Origem do Lead (CREDITAS_AUTO, Webmotors, etc.)</description>
    <label>Origem do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREDITAS_AUTO</fullName>
            </value>
            <value>
                <fullName>Webmotors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade (Preenchido por regra de automação no sistema CRM)</description>
    <label>Prioridade</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <description>UTM Campanha (search-institucional, [creditas-auto][search][institucional][cliques])</description>
    <label>UTM campanha</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_Media__c.field-meta.xml
<CustomField>
    <fullName>UTM_Media__c</fullName>
    <description>UTM Mídia (ex,: cpc)</description>
    <label>UTM mídia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_source__c.field-meta.xml
<CustomField>
    <fullName>UTM_source__c</fullName>
    <description>UTM Fonte (ex.: google)</description>
    <label>UTM fonte</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro da Negociação: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Lead/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <businessProcess>Auto</businessProcess>
    <description>Tipo de Registro do Lead: Auto</description>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto</description>
    <label>Tipo de produto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantidade do Produto</description>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro do Produto: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/ProductOfInterest__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa os Produtos de Interesse relacionados a um Deal.</description>
    <label>Produto de Interesse</label>
    <nameField>
        <label>Nome do Produto de Interesse</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Interesse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal com o qual o Produto de Interesse está relacionado.</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Produtos de Interesse</relationshipLabel>
    <relationshipName>Produtos_de_Interesse</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que vincula o Produto de Interesse ao Produto cadastrado.</description>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos de Interesse</relationshipLabel>
    <relationshipName>ProductOfInterest</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto de Interesse</description>
    <label>Tipo de produto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <description>Quantidade do Produto de Interesse.</description>
    <label>Quantidade</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro do Produto de Interesse: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/classes/DealAndLeadIntegration.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Class created to Insert or Update a Deal and Products of Interest from an API.
* ================================================================================================================================
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          19/01/2022      Created    Class created to Insert or Update a Deal and Products of Interest from an API.
**********************************************************************************************************************************/

@RestResource(urlMapping='/leads/*/deal')
global with sharing class DealAndLeadIntegration {

    @HttpPost
    global static String upsertDeal(){

        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        DealAndLeadIntegrationVO request = (DealAndLeadIntegrationVO) System.JSON.deserialize(req.requestBody.toString(), DealAndLeadIntegrationVO.class);

        List<Deal__c> deal = new List<Deal__c>();

        Map<String, ProductOfInterest__c> mapProdInterest = new Map<String, ProductOfInterest__c>();
        Map<String, Product2> mapProducts = new Map<String, Product2>();

        Set<String> productIdList = new Set<String>(); 

        String uriStringId = req.requestURI.split('/')[2];
        List<Lead> lead = [SELECT Id, FirstName, LastName FROM Lead WHERE ExternalId__c =: uriStringId];
        
        if(lead.isEmpty()){
            res.statusCode = 400;  
            return 'Error: No Lead was found with the External ID informed in the URL!';
        }

        if(string.isBlank(request.dealId)){ 
			res.statusCode = 400;  
            return 'Error: dealId is empty!';            
        }

        if(string.isBlank(request.totalValue.amount)){
            res.statusCode = 400;   
            return 'Error: amount is empty!';
        } 
    
        if(string.isBlank(request.totalValue.currencyIsoCode)){
            res.statusCode = 400;  
            return 'Error: currencyIsoCode is empty!';
        }

        List<CurrencyType> currencyDeal = [SELECT Id FROM CurrencyType WHERE isoCode =: request.totalValue.currencyIsoCode];

        if(currencyDeal.isEmpty()){ 
            res.statusCode = 400;  
            return 'Error: No match found for Currency!';
        }

        if(string.isBlank(request.source)){
            res.statusCode = 400;  
            return 'Error: source is empty!';
        }

       if(string.isBlank(request.UTM_source)){
            res.statusCode = 400;  
            return 'Error: UTM_source is empty!';
        }

        if(string.isBlank(request.UTM_Medium)){
            res.statusCode = 400;  
            return 'Error: UTM_Medium is empty!';
        }

        if(string.isBlank(request.UTM_Campaign)){
            res.statusCode = 400;  
            return 'Error: UTM_Campaign is empty!';
        }

        if(request.productsOfInterest.isEmpty()){
            res.statusCode = 400;  
            return 'Error: It is necessary to inform at least one Product of Interest!'; 
        }

        for(DealAndLeadIntegrationVO.ProdInterest prod : request.productsOfInterest){

            if(string.isBlank(prod.productId)){ 
                res.statusCode = 400;  
                return 'Error: productId is empty!';
            }

            if(prod.quantity == NULL || prod.quantity != 1){ 
                res.statusCode = 400;  
                return 'Error: quantity is incorrect or has value different of 1';
            }
            
            if(string.isBlank(prod.productType)){ 
                res.statusCode = 400;  
                return 'Error: productType is empty!';
            }

            productIdList.add(prod.productId);
        }

        List<Product2> findProducts = [SELECT Id, Name, ExternalId FROM Product2 WHERE ExternalId IN: productIdList]; 

        If(productIdList.size() != findProducts.size()){
            res.statusCode = 400;
            return 'Error: No products found for this productId!';
        }
                              
        String totValueAmountDot = request.totalValue.amount.replace(',','.');
        Decimal totValueAmountDecimal = decimal.valueOf(totValueAmountDot); 

        Group queue = [SELECT Id FROM Group WHERE Name = 'Creditas Auto - Vendas' AND Type = 'Queue'];
        
        deal = [SELECT  Name,
                        DealValue__c, 
                        LeadOrigin__c,
                        UTM_Campaign__c,
                        UTM_source__c,
                        UTM_Media__c,
                        Priority__c,
                        CurrencyIsoCode, 
                        OwnerId,
                        Lead__c,
                        ExternalId__c
                FROM Deal__c
                WHERE ExternalId__c =: request.dealId]; 
            
        if(!deal.isEmpty()){

            for(ProductOfInterest__c productInterest : [SELECT  Quantity__c,
                                                                productType__c,
                                                                Deal__r.ExternalId__c,
                                                                Product__r.ExternalId
                                                        FROM ProductOfInterest__c
                                                        WHERE Deal__c =: deal[0].id ]){
                mapProdInterest.put(productInterest.Deal__r.ExternalId__c+productInterest.Product__r.ExternalId, productInterest);
            } 
            
            deal[0].DealValue__c    = totValueAmountDecimal;
            deal[0].CurrencyIsoCode = request.totalValue.currencyIsoCode.toUpperCase(); 
            deal[0].LeadOrigin__c   = request.source;
            deal[0].UTM_Campaign__c = request.UTM_Campaign;
            deal[0].UTM_source__c   = request.UTM_source;
            deal[0].UTM_Media__c    = request.UTM_Medium;
            deal[0].Priority__c     = request.priority;   

        }else{

            RecordType recordTypeDeal = [SELECT id FROM RecordType WHERE DeveloperName = 'AutoSales' AND SobjectType = 'Deal__c'];
           
            Deal__c newDeal = new Deal__c();

            newDeal.Name            = 'Comprar carro - '+ lead[0].FirstName + ' '+ lead[0].LastName;
            newDeal.RecordType      = recordTypeDeal;
            newDeal.DealValue__c    = totValueAmountDecimal;
            newDeal.CurrencyIsoCode = request.totalValue.currencyIsoCode.toUpperCase(); 
            newDeal.LeadOrigin__c   = request.source;
            newDeal.UTM_Campaign__c = request.UTM_Campaign;
            newDeal.UTM_source__c   = request.UTM_source;
            newDeal.UTM_Media__c    = request.UTM_Medium;
            newDeal.Priority__c     = request.priority;
            newDeal.ExternalId__c   = request.dealId;
            newDeal.OwnerId         = queue.Id;
            newDeal.Lead__c         = lead[0].Id;

            deal.add(newDeal);
        }
            try{
                upsert deal;

                RecordType recordTypeProdInt = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSales' AND SobjectType = 'ProductOfInterest__c'];

                
                for(Product2 product : findProducts){
                    mapProducts.put(product.ExternalId, product);
                }

                List<ProductOfInterest__c> prodIntToInsert = new  List<ProductOfInterest__c> ();

                for(DealAndLeadIntegrationVO.ProdInterest reqProd : request.productsOfInterest){

                    ProductOfInterest__c prodInterest = mapProdInterest.get(request.dealId+reqProd.productId);

                    Product2 prod = mapProducts.get(reqProd.productId);
                
                    if(prodInterest == NULL){
                        prodInterest                    = new ProductOfInterest__c(Deal__c = deal[0].id);
                        prodInterest.Name               = prod.Name;
                        prodInterest.recordtype         = recordTypeProdInt;
                        prodInterest.productType__c     = reqProd.productType; 
                        prodInterest.Product__c         = prod.Id;
                        prodInterest.quantity__c        = reqProd.quantity;

                        prodIntToInsert.add(prodInterest);
                    }
                   
                }
                
                if(prodIntToInsert.size() > 0){
                    upsert prodIntToInsert;
                }

                res.statusCode = 200;
                return 'Success: Record created/updated successfully!';

            }catch (Exception e) {
                System.debug(e.getMessage());
                return 'Error: Failed to complete the request!';
            }     
    }
}