creditas-sf/force-app/main/default/objects/Deal__c/Deal__c.object-meta.xml
<CustomObject>
    <description>Objeto para registrar Negociações (Deals) realizadas com os Contatos (Leads) no processo de Auto.</description>
    <label>Deal</label>
    <nameField>
        <label>Nome do Deal</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Deals</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Deal__c/fields/DealValue__c.field-meta.xml
<CustomField>
    <fullName>DealValue__c</fullName>
    <description>Valor da Negociação</description>
    <label>Valor da negociação</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo da Negociação</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/Lead__c.field-meta.xml
<CustomField>
    <fullName>Lead__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Lead que está fazendo a negociação.</description>
    <label>Lead</label>
    <referenceTo>Lead</referenceTo>
    <relationshipName>Negociacoes</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/LeadOrigin__c.field-meta.xml
<CustomField>
    <fullName>LeadOrigin__c</fullName>
    <description>Origem do Lead (CREDITAS_AUTO, Webmotors, etc.)</description>
    <label>Origem do Lead</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>CREDITAS_AUTO</fullName>
            </value>
            <value>
                <fullName>Webmotors</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/Priority__c.field-meta.xml
<CustomField>
    <fullName>Priority__c</fullName>
    <description>Prioridade (Preenchido por regra de automação no sistema CRM)</description>
    <label>Prioridade</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_Campaign__c.field-meta.xml
<CustomField>
    <fullName>UTM_Campaign__c</fullName>
    <description>UTM Campanha (search-institucional, [creditas-auto][search][institucional][cliques])</description>
    <label>UTM campanha</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_Media__c.field-meta.xml
<CustomField>
    <fullName>UTM_Media__c</fullName>
    <description>UTM Mídia (ex,: cpc)</description>
    <label>UTM mídia</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/fields/UTM_source__c.field-meta.xml
<CustomField>
    <fullName>UTM_source__c</fullName>
    <description>UTM Fonte (ex.: google)</description>
    <label>UTM fonte</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Deal__c/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro da Negociação: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Lead/fields/CPF__c.field-meta.xml
<CustomField>
    <fullName>CPF__c</fullName>
    <description>CPF do Contato</description>
    <label>CPF do contato</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de Documento do Lead</description>
    <label>Tipo de documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>ID Externo do Lead</description>
    <externalId>true</externalId>
    <label>ID Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/fields/mainDocumentCode__c.field-meta.xml
<CustomField>
    <fullName>mainDocumentCode__c</fullName>
    <description>Documento Principal da Empresa (CNPJ)</description>
    <label>Documento principal da empresa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Lead/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <businessProcess>Auto</businessProcess>
    <description>Tipo de Registro do Lead: Auto</description>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Product2/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto</description>
    <label>Tipo de produto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Product2/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro do Produto: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/ProductOfInterest__c.object-meta.xml
<CustomObject>
    <description>Objeto que representa os Produtos de Interesse relacionados a um Deal.</description>
    <label>Produto de Interesse</label>
    <nameField>
        <label>Nome do Produto de Interesse</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Produtos de Interesse</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/Deal__c.field-meta.xml
<CustomField>
    <fullName>Deal__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Deal com o qual o Produto de Interesse está relacionado.</description>
    <label>Deal</label>
    <referenceTo>Deal__c</referenceTo>
    <relationshipLabel>Produtos de Interesse</relationshipLabel>
    <relationshipName>Produtos_de_Interesse</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Campo que vincula o Produto de Interesse ao Produto cadastrado.</description>
    <label>Produto</label>
    <referenceTo>Product2</referenceTo>
    <relationshipLabel>Produtos de Interesse</relationshipLabel>
    <relationshipName>ProductOfInterest</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/productId__c.field-meta.xml
<CustomField>
    <fullName>productId__c</fullName>
    <externalId>true</externalId>
    <inlineHelpText>ID do Produto de Interesse que será enviado pelo Mulesoft.</inlineHelpText>
    <label>ID do Produto</label>
    <length>255</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto de Interesse</description>
    <label>Tipo de produto</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductOfInterest__c/recordTypes/AutoSales.recordType-meta.xml
<RecordType>
    <fullName>AutoSales</fullName>
    <active>true</active>
    <description>Tipo de Registro do Produto de Interesse: Auto - Vendas</description>
    <label>Auto - Vendas</label>
</RecordType>

creditas-sf/force-app/main/default/classes/DealAndLeadIntegrationTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Test Class to DealAndLeadIntegrationClass.
* ================================================================================================================================
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          20/01/2022      Created     Test Class to DealAndLeadIntegrationClass.
**********************************************************************************************************************************/

@istest
public class DealAndLeadIntegrationTest {

    static testMethod void insertDealAndProductOfInterest(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSales' AND SobjectType = 'Product2'];
           
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     			
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                   
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id; 
        	newLead.Status	        	= 'New';
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'cred123';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;
            	
			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/cred123/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(200, res.statusCode, 'A deal and the Products of Interest should be inserted.');    
        Test.stopTest();  
    }

    static testMethod void updatetDealAndInterestProduct(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+     
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;

                 
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

            Lead lead = [SELECT Id, FirstName, LastName FROM Lead WHERE ExternalId__c = 'EID-12345'];
            Group queue = [SELECT Id FROM Group WHERE Name = 'Creditas Auto - Vendas' AND Type = 'Queue'];     
            RecordType recordTypeDeal = [SELECT id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Deal__c'];
           
            Deal__c newDeal = new Deal__c();
            newDeal.Name            = 'Comprar carro - '+ lead.FirstName + ' '+ lead.LastName;
            newDeal.RecordType      = recordTypeDeal;
            newDeal.DealValue__c    =  12345.12;
            newDeal.CurrencyIsoCode = 'BRL'; 
            newDeal.LeadOrigin__c   = 'CREDITAS';
            newDeal.UTM_Campaign__c = '[creditas-auto][search][institucional][cliques]';
            newDeal.UTM_source__c   = 'google';
            newDeal.UTM_Media__c    = 'cpc';
            newDeal.Priority__c     = 2;
            newDeal.ExternalId__c   = 'DE-001';
            newDeal.OwnerId         = queue.Id;
            newDeal.Lead__c         = lead.Id;
            insert newDeal;

            RecordType recordTypeProdInt = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'ProductOfInterest__c'];
            Product2 prodId = [SELECT Id FROM Product2 WHERE ExternalId = 'ID12301239'];
            Deal__c dealId = [SELECT Id FROM  Deal__c WHERE ExternalId__c = 'DE-001'];

            ProductOfInterest__c interestProd = new ProductOfInterest__c();
            interestProd.Deal__c            = dealId.Id;
            interestProd.Name               = 'Chevrolet Onix 2021';
            interestProd.recordtype         = recordTypeProdInt; 
            interestProd.productId__c       = prodId.id;
            interestProd.productType__c     = 'Creditas Auto Buyer'; 
            interestProd.Product__c         = prodId.Id;
            insert interestProd;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(200, res.statusCode, 'A deal should be updated.');    
        Test.stopTest();
    } 
    
    static testMethod void invalidLeadExternalId(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-1234/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the leadId is not correct.');    
        Test.stopTest();  
    }

    static testMethod void withoutDealId(){
        String json= '   { '+
        '   "dealId":"",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the dealId was not informed.');    
        Test.stopTest();  
    }

    static testMethod void withoutAmount(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"",   '+     
        '   "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the amount was not informed.');    
        Test.stopTest();  
    }

    static testMethod void withoutCurrency(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":""   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+ 
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the currency was not informed.');    
        Test.stopTest();  
    }

    static testMethod void incorrectCurrency(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":"BR"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+   
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;
        
			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the currency informed does not exist.');    
        Test.stopTest();  
    }

    static testMethod void withoutSource(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   ';

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the source was not informed.');    
        Test.stopTest();  
    }

    static testMethod void withoutUTMSource(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   ';

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the UTM_Source was not informed.');    
        Test.stopTest();  
    }

    static testMethod void withoutUTMMedium(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+       
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   ';

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the UTM_Medium was not informed.');    
        Test.stopTest();  
    }

    static testMethod void withoutUTMCampaign(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '   "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   ';

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the UTM_Campaign was not informed.');    
        Test.stopTest();  
    }


    static testMethod void withoutProductOfInterest() {
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest":   '+
        '   [   '+ 
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as a Product of Interest was not informed.' );    
        Test.stopTest();  
    }

    static testMethod void productOfInterestwithoutProductId() {
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "",   '+     
        '   "quantity": 1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;
    
			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the productId of the Product of Interest was not informed.');    
        Test.stopTest();  
    }

    static testMethod void productOfInterestwithoutQuantity(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity": null,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;
                  

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the quantity of the Product of Interest was not informed or was incorrect.');    
        Test.stopTest();  
    }

    static testMethod void productOfInterestwithoutProductType(){
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "ID12301239",   '+     
        '   "quantity": 1,   '+     
        '   "productType":""   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should have occurred, as the productType of the Product of Interest was not informed.');    
        Test.stopTest();  
    }

    static testMethod void productIdNotFound() {
        String json= '   { '+
        '   "dealId":"DE-001",  '+    
        '   "totalValue":{   '+     
        '   "amount":"12345,1234",   '+     
        '    "currencyIsoCode":"BRL"   '+    
        '   },   '+     
        '   "source":"CREDITAS_AUTO",   '+     
        '   "UTM_source":"google",   '+     
        '   "UTM_Medium":"cpc",   '+     
        '   "UTM_Campaign":"[creditas-auto][search][institucional][cliques]",   '+ 
        '   "priority":111,   '+     
        '   "productsOfInterest": [  '+  
        '   {   '+     
        '   "ProductId" : "IDABC",   '+     
        '   "quantity":1,   '+     
        '   "productType":"Creditas Auto Buyer"   '+ 
        '   }   '+    
        '   ]   '+     
        '   }   '; 

        Test.startTest();  
        
            RecordType recordTypeProduct = [SELECT Id FROM RecordType WHERE DeveloperName = 'AutoSAles' AND SobjectType = 'Product2'];
            
            Product2 newproduct         = new Product2();
            newproduct.RecordTypeId	    = recordTypeProduct.Id;
            newProduct.ExternalId		= 'ID12301239';
            newProduct.Name 			= 'Chevrolet Onix 2021';
            newProduct.productType__c   = 'Creditas Auto Buyer';
            newProduct.CurrencyIsoCode	= 'BRL';
            insert newproduct;
     
            RecordType recordTypeLead = [SELECT Id FROM RecordType WHERE Name = 'Auto' AND SobjectType = 'Lead'];
                    
            Lead newLead = new Lead();
            newLead.RecordTypeId        = recordTypeLead.Id;            
            newLead.FirstName	        = 'Jane';
            newLead.LastName            = 'Doe';
            newLead.ExternalId__c       = 'EID-12345';
            newLead.DocumentType__c     = 'CPF';
            newLead.CPF__c              = '12345678910';
            newLead.Company             = '--';
            newLead.mainDocumentCode__c = '--';
            insert newLead;

			DealAndLeadIntegrationVO VO = new DealAndLeadIntegrationVO();
            RestRequest req = new RestRequest(); 
            RestResponse res = new RestResponse();

            req.requestURI = '/leads/EID-12345/deal';
            req.httpMethod = 'POST';
            req.requestBody = Blob.valueof(json);
            RestContext.request = req;
            RestContext.response= res;             
        
            DealAndLeadIntegration.upsertDeal();  
            System.assertequals(400, res.statusCode, 'An error should occur, as a Product with the productId informed was not found.');    
        Test.stopTest();  
    }
}