creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalPersonId__c.field-meta.xml
<CustomField>
    <fullName>ExternalPersonId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OpportunityRoles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>SOLIDARY_DEBTOR</fullName>
            </value>
            <value>
                <fullName>COLLATERAL_GUARANTOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/GarantiasTriggerHandler.cls
/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Handler padrão para a trigger do Objeto Garantias (Garantias__c).
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Gabriel Vidal           13/10/2021      Created     Implementação de handler voltado para uso da Trigger do objeto Garantias (Garantias__c)
**********************************************************************************************************************************/
public without sharing class GarantiasTriggerHandler extends TriggerHandler 
{
    private List<Garantias__c> lstNewGarantias;
    private List<Garantias__c> lstOldGarantias;
    private Map<Id, Garantias__c> mapNewGarantias;
    private Map<Id, Garantias__c> mapOldGarantias;
    final String GARANTIAS_ERROR_MESSAGE = System.Label.Garantias_Error_Message;

    public GarantiasTriggerHandler() 
    {
        this.lstNewGarantias = (List<Garantias__c>) Trigger.new;
        this.lstOldGarantias = (List<Garantias__c>) Trigger.old;
        this.mapNewGarantias = (Map<Id, Garantias__c>) Trigger.newMap;
        this.mapOldGarantias = (Map<Id, Garantias__c>) Trigger.oldMap;
    }


    public override void beforeInsert()
    {
        this.verifyOpportunityRole();
    }


    public override void afterInsert() 
    {
    }


    public override void beforeUpdate()
    {
        this.verifyOpportunityRole();
    }


    public override void afterUpdate() 
    {              
    }


    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description somente Recursos Financeiros possuídos por um "COLLATERAL_GUARANTOR" podem ser associados às garantias
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0         Gabriel Vidal           13/10/21
    **********************************************************************************************************************************/
    public void verifyOpportunityRole()
    {
        Set<Id> opportunityIds = new Set<Id>();
        for (Garantias__c garantiaNew : lstNewGarantias) 
        {
            opportunityIds.add(garantiaNew.Opportunity__c);
        }

        Map<Id, String> accountIdToRoleName = new Map<Id, String>();
        for (OpportunityRole__c oppRole : [ SELECT ExternalPersonId__c, Role__c 
                                            FROM OpportunityRole__c 
                                            WHERE Opportunity__c IN :opportunityIds])
        {
            accountIdToRoleName.put(oppRole.ExternalPersonId__c, oppRole.Role__c);
        }

        for (Garantias__c garantiaNew : lstNewGarantias) 
        {
            if (accountIdToRoleName.get(garantiaNew.Account__c) != 'COLLATERAL_GUARANTOR')
            {
                garantiaNew.addError(GARANTIAS_ERROR_MESSAGE);
            }
        }
    }
}