creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/Custom_Field_Tracking_Map__mdt.object-meta.xml
<CustomObject>
    <description>Mapeamento de campos para sincronização personalizada de campos</description>
    <label>Custom Field Tracking Map</label>
    <pluralLabel>Customs Fields Tracking Map</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/CampoRastreado__c.field-meta.xml
<CustomField>
    <fullName>CampoRastreado__c</fullName>
    <label>CampoRastreado</label>
    <metadataRelationshipControllingField>Custom_Field_Tracking_Map__mdt.ObjetoRastreado__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map1</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/ObjetoRastreado__c.field-meta.xml
<CustomField>
    <fullName>ObjetoRastreado__c</fullName>
    <label>ObjetoRastreado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ccbNumber__c.field-meta.xml
<CustomField>
    <fullName>ccbNumber__c</fullName>
    <label>Número da CCB</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/MigrationRecord__c.field-meta.xml
<CustomField>
    <fullName>MigrationRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration Record</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/SynchOpportunity__e/SynchOpportunity__e.object-meta.xml
<CustomObject>
    <description>Platform Event to Update the SynchOpportunityData component</description>
    <label>SynchOpportunity</label>
    <pluralLabel>SynchOpportunities</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/classes/OpportunityTriggerService.cls
public with sharing class OpportunityTriggerService {
  public static void updateIsExternallySynced(
    Map<Id, Opportunity> mapNewOpportunity,
    Map<Id, Opportunity> mapOldOpportunity
  ) {
    String varSObjectApiName = 'Opportunity';
    Map<String, Custom_Field_Tracking_Map__mdt> mapTrackedFields = new Map<String, Custom_Field_Tracking_Map__mdt>();

    for (Custom_Field_Tracking_Map__mdt varCustomTrackedField : [
      SELECT CampoRastreado__r.QualifiedApiName
      FROM Custom_Field_Tracking_Map__mdt
      WHERE ObjetoRastreado__r.QualifiedApiName = :varSObjectApiName
    ]) {
      mapTrackedFields.put(
        varCustomTrackedField.CampoRastreado__r.QualifiedApiName,
        varCustomTrackedField
      );
    }

    for (Opportunity newOpportunity : mapNewOpportunity.values()) {
      Opportunity oldOpportunity = mapOldOpportunity.get(newOpportunity.Id);

      for (String trackedField : mapTrackedFields.keySet()) {
        if (
          newOpportunity.get(trackedField) != oldOpportunity.get(trackedField) &&
          newOpportunity.MigrationRecord__c != true
        ) {
          newOpportunity.IsExternallySynched__c = false;
        }
      }
    }
  }

  public static void firePlatformEventSynchAccount(Map<Id, Opportunity> mapNewOpportunity) {
    for (Opportunity newOpportunity : mapNewOpportunity.values()) {
      if (newOpportunity.IsSynchEnabled__c == 'ENABLED') {
        SynchOpportunity__e synch = new SynchOpportunity__e();
        DataBase.SaveResult sr = EventBus.publish(synch);
        break;
      }
    }
  }

  public static void firePlatformEventAutoFinContractUpdate(Map<Id, Opportunity> mapNewOpportunity) {
    List<AutoFinContractUpdate__e> eventList = new List<AutoFinContractUpdate__e>();
    for (Opportunity newOpportunity : mapNewOpportunity.values()) {
        if (TriggerHelper.changedField(newOpportunity, 'CCBnumber__c')) {
            AutoFinContractUpdate__e event = new AutoFinContractUpdate__e(RecordId__c = newOpportunity.Id);
            eventList.add(event);
        }
    }

    if(eventList.isEmpty()){ return; }
    EventBus.publish(eventList);
  }
}