creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/Custom_Field_Tracking_Map__mdt.object-meta.xml
<CustomObject>
    <description>Mapeamento de campos para sincronização personalizada de campos</description>
    <label>Custom Field Tracking Map</label>
    <pluralLabel>Customs Fields Tracking Map</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/CampoRastreado__c.field-meta.xml
<CustomField>
    <fullName>CampoRastreado__c</fullName>
    <label>CampoRastreado</label>
    <metadataRelationshipControllingField>Custom_Field_Tracking_Map__mdt.ObjetoRastreado__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map1</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/ObjetoRastreado__c.field-meta.xml
<CustomField>
    <fullName>ObjetoRastreado__c</fullName>
    <label>ObjetoRastreado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/MigrationRecord__c.field-meta.xml
<CustomField>
    <fullName>MigrationRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration Record</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/SynchAccount__e/SynchAccount__e.object-meta.xml
<CustomObject>
    <description>Platform Event to Update the SynchAccount component</description>
    <label>SynchAccount</label>
    <pluralLabel>SynchAccounts</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/classes/OpportunityTriggerController.cls
/***********************************************************************************************************************************
 * Copyright © 2021 Creditas
 * ================================================================================================================================
 * @description Default Controller for trigger OpportunityTrigger
 * ================================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Nathalia Rosa           17/12/2021      Created     Default Controller for trigger OpportunityTrigger
 * 1.1       Matheus Fernandes       17/02/2021      Changed     Calling OpportunityEvaluationController on beforeInsert
 **********************************************************************************************************************************/
public without sharing class OpportunityTriggerController extends TriggerHandler {
    private List<Opportunity> lstNewOpportunity;
    private List<Opportunity> lstOldOpportunity;
    private Map<Id, Opportunity> mapNewOpportunity;
    private Map<Id, Opportunity> mapOldOpportunity;
  
    public OpportunityTriggerController() {
      this.lstNewOpportunity = (List<Opportunity>) Trigger.new;
      this.lstOldOpportunity = (List<Opportunity>) Trigger.old;
      this.mapNewOpportunity = (Map<Id, Opportunity>) Trigger.newMap;
      this.mapOldOpportunity = (Map<Id, Opportunity>) Trigger.oldMap;
    }
  
    public override void beforeInsert() {
      //OpportunityEvaluationController.evaluateByOpportunity(lstNewOpportunity);
    }
  
    public override void afterInsert() {
      
    }
  
    public override void beforeUpdate() {
      this.updateIsExternallySynced();
      this.firePlatformEventSynchAccount();
    }
  
    public override void afterUpdate() {
      OpportunityAssignmentController.handleAtWorkOpportunityAssignment(lstNewOpportunity);
    }
  
    public static Id getOpportunityRecordTypeId(String recordTypeName) {
      return Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get(recordTypeName).getRecordTypeId();
    }
  
    private void updateIsExternallySynced() {
      String varSObjectApiName = 'Opportunity';
      Map<String, Custom_Field_Tracking_Map__mdt> mapTrackedFields = new Map<String, Custom_Field_Tracking_Map__mdt>();
  
      for (Custom_Field_Tracking_Map__mdt varCustomTrackedField : [
        SELECT CampoRastreado__r.QualifiedApiName
        FROM Custom_Field_Tracking_Map__mdt
        WHERE ObjetoRastreado__r.QualifiedApiName = :varSObjectApiName
      ]) {
        mapTrackedFields.put(varCustomTrackedField.CampoRastreado__r.QualifiedApiName, varCustomTrackedField);
      }
  
      for (Opportunity newOpportunity : mapNewOpportunity.values()) {
        Opportunity oldOpportunity = mapOldOpportunity.get(newOpportunity.Id);
  
        for (String trackedField : mapTrackedFields.keySet()) {
          if (
            newOpportunity.get(trackedField) != oldOpportunity.get(trackedField) &&
            newOpportunity.MigrationRecord__c != true
          ) {
            newOpportunity.IsExternallySynched__c = false;
          }
        }
      }
    }
  
    private void firePlatformEventSynchAccount() {
      for (Opportunity newOpportunity : mapNewOpportunity.values()) {
        if (newOpportunity.IsSynchEnabled__c == 'ENABLED') {
          SynchAccount__e synch = new SynchAccount__e();
          DataBase.SaveResult sr = EventBus.publish(synch);
        }
      }
    }
  }