creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/API_Transaction_Errors__b.object-meta.xml
<CustomObject>
    <label>API_Transaction_Errors</label>
    <pluralLabel>API_Transaction_Errors</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/CreatedBy__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy__c</fullName>
    <label>CreatedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>API_Transaction_Errors1</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/insertLogUtils.cls
public with sharing class InsertLogUtils {

    public static Boolean insertErrorLog(String endPoint, String requestBody, Integer errorCode, String errorMessage){
        Boolean returnMessage = false;

        API_Transaction_Errors__b ate = new API_Transaction_Errors__b();
        ate.Endpoint__c = endPoint;
        ate.RequestBody__c = requestBody;
        ate.ReturnCode__c = errorCode;
        ate.ErrorMessage__c = errorMessage;
        ate.CreatedDate__c = System.now();
        ate.CreatedBy__c = UserInfo.getUserId();

        if(!Test.isRunningTest()){
            Database.SaveResult sr = database.insertImmediate(ate);
            returnMessage = sr.isSuccess();
        }
        return returnMessage;
    }
}