creditas-sf/force-app/main/default/objects/AddressDataSection__c/AddressDataSection__c.object-meta.xml
<CustomObject>
    <description>Objeto Utilizado apenas para o Squad AtWork</description>
    <label>Seção Dados de Endereço</label>
    <nameField>
        <displayFormat>DE-{00000}</displayFormat>
        <label>Seção Dados de Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Endereço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Endereço</relationshipLabel>
    <relationshipName>AddressDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/ContactDetailsSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Contato</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Seção Dados de Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Contato</relationshipLabel>
    <relationshipName>ContactDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/GeneralSection__c/GeneralSection__c.object-meta.xml
<CustomObject>
    <label>Seção Geral</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Sessão Geral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seções Gerais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/GeneralSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seções Gerais</relationshipLabel>
    <relationshipName>SecoesGerais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OperationSection__c/OperationSection__c.object-meta.xml
<CustomObject>
    <label>Seção Operação</label>
    <nameField>
        <label>Seção Operação Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Operação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/WarrantyDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Garantia</label>
    <nameField>
        <label>Seção Dados de Garantia Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Garantia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/classes/ProposalIntegrationControllerTest.cls
@isTest
public class ProposalIntegrationControllerTest {

    private static final String MOCK_AUTH = '{"access_token":"tOxqtBAtTEMUdeCNOlZdsUnvjO8gGmMFq01AFQeOLAtlOWglcI3lR6aXpKNvYH8i2hXgbKjqDZ6sJs8SmpQZ9g","token_type":"Bearer","expires_in":86400}';
    
    @TestSetup
    static void makeData(){
        Account accCustomer = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opp = OpportunitySetup.createOpportunity(accCustomer.Id, 'AutoFin');
        opp.Description = 'teste';
        insert opp;
        
        PersonalDataSection__c personalSection  = new PersonalDataSection__c();
        personalSection.Opportunity__c = opp.Id;
        personalSection.Name__c = 'Nivaele';
        insert personalSection;

        AddressDataSection__c addressSection   = new AddressDataSection__c();
        addressSection.Opportunity__c = opp.Id;
        insert addressSection;
        
        ContactDetailsSection__c contactSection   = new ContactDetailsSection__c();
        contactSection.Opportunity__c = opp.Id;
        insert contactSection;

        WarrantyDataSection__c warrantySection  = new WarrantyDataSection__c();
        warrantySection.Opportunity__c = opp.Id;
        insert warrantySection;

        IncomeDataSection__c incomeSection    = new IncomeDataSection__c();
        incomeSection.Opportunity__c = opp.Id;
        insert incomeSection;

        OperationSection__c operationSection = new OperationSection__c();
        operationSection.Opportunity__c = opp.Id;
        insert operationSection;

        OthersSection__c othersSection = new OthersSection__c();
        othersSection.Opportunity__c = opp.Id;
        insert othersSection;

        GeneralSection__c generalSection = new GeneralSection__c();
        generalSection.Opportunity__c = opp.Id;
        insert generalSection;
    }

    @isTest
    static void finishAnalysisSuccessTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        String response;
        
        HttpMockFactory mock = createMock(new List<Integer>{200,200},new List<String>{MOCK_AUTH,''});
    
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        response = ProposalIntegrationController.finishAnalysis(opp.Id, 'pendency');
        Test.stopTest();
        System.assertEquals('Success', response, 'Should have received a success message.');
    }
    
    @isTest
    static void finishAnalysisFailTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        String response;
        
        HttpMockFactory mock = createMock(new List<Integer>{200,400},new List<String>{MOCK_AUTH,''});

        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        response = ProposalIntegrationController.finishAnalysis(opp.Id, 'pendency');
        Test.stopTest();
        System.assertEquals('Error', response, 'Should return Error.');
    }
    
    @isTest
    static void finishAnalysisCatchErrorTest(){
        Opportunity opp = new Opportunity(Name = 'teste1', StageName = 'Em Análise de Formalização', CloseDate = Date.today());
        insert opp;
        Exception testException;
    
        Test.startTest();
        Try{
        	ProposalIntegrationController.finishAnalysis(opp.Id, 'pendency');
        }catch(Exception e){
            testException = e;
        }
        
        Test.stopTest();
        System.assertEquals('List has no rows for assignment to SObject', testException.getMessage(), 'Should have sections record');
    }

    @isTest
    static void failedAuthentication(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        String response;
        
        HttpMockFactory mock = createMock(new List<Integer>{400},new List<String>{MOCK_AUTH});
    
        Test.setMock(HttpCalloutMock.class, mock);
        Test.startTest();
        response = ProposalIntegrationController.finishAnalysis(opp.Id, 'pendency');
        Test.stopTest();
        System.assertEquals('Error', response, 'Should have received a error message.');
    }

    private static HttpMockFactory createMock(List<Integer> statusCode, List<String> payloads){
        HttpMockFactory mock = new HttpMockFactory(
            statusCode,
            new List<String>{'OK','OK'},
            payloads,
            new List<Map<String,String>>{new Map<String,String>(), new Map<String,String>()}
        );
        return mock;
    }
}