creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/classes/CustomSetupController.cls
/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Controller class for CustomSetup__c object related functions 
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       17/02/2021      Created     Class creation
 **********************************************************************************************************************/
public with sharing class CustomSetupController {

  public static String getPendencyReturnApiName() {
    return CustomSetupService.PENDENCY_RETURN;
  }

  public static CustomSetup__c getCustomSetupByRecordType(String recordTypeDevName){
    String customSetupRecordTypeId = Util.getRecordTypeIdbyName('CustomSetup__c', recordTypeDevName);
    return CustomSetupService.selectCustomSetups(customSetupRecordTypeId)[0];
  }

  public static List<CustomQueue__c> selectCustomQueues(){
    return CustomSetupService.selectCustomQueues();
  }

  public static List<CustomQueue__c> selectCustomQueues(Set<Id> customQueueIds){
    return CustomSetupService.selectCustomQueues(customQueueIds);
  }
}