creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto para a fila de @work</description>
    <inlineHelpText>O valor escolhido determinará qual a pontuação referente a esse produto.</inlineHelpText>
    <label>Tipo de Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomSetup__c/fields/DateFilter__c.field-meta.xml
<CustomField>
    <fullName>DateFilter__c</fullName>
    <label>Data de Filtro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data de Criação</fullName>
                <default>true</default>
                <label>Data de Criação</label>
            </value>
            <value>
                <fullName>Data de Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <label>AtWork</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <businessProcess>%40Work - Creditas</businessProcess>
    <label>@Work</label>
</RecordType>

creditas-sf/force-app/main/default/objects/ProductAssignedUser__c/ProductAssignedUser__c.object-meta.xml
<CustomObject>
    <label>Usuário por fila</label>
    <nameField>
        <displayFormat>UPF - {0000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProductAssignedUsers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProductAssignedUser__c/fields/CustomSetupUser__c.field-meta.xml
<CustomField>
    <fullName>CustomSetupUser__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>CustomSetupUser</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipName>ProductAssignedUsers</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductAssignedUser__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de Produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ProductAssignedUser__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Usuário</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Juncoes</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/User/fields/UserAvailable__c.field-meta.xml
<CustomField>
    <fullName>UserAvailable__c</fullName>
    <defaultValue>true</defaultValue>
    <label>Usuário Disponível</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/OpportunityAssignment.cls
/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Classe para atribuição de oportunidades de forma automática
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       25/01/2021      Created     Criação da classe
 **********************************************************************************************************************/
public with sharing class OpportunityAssignment {
  private static Id opportunityAtWorkRecordTypeId = Util.getRecordTypeIdbyName('Opportunity', 'AtWork');

  public static void handleAtWorkOpportunityAssignment(List<Opportunity> lstOpportunity) {
    boolean runAssignment = false;

    for (Opportunity opp : lstOpportunity) {
      if (opp.RecordTypeId == opportunityAtWorkRecordTypeId) {
        runAssignment = true;
        break;
      }
    }

    if (runAssignment) {
      runAtWorkOpportunityAssignment();
    }
  }

  private static void runAtWorkOpportunityAssignment() {
    CustomSetup__c cSetup = EvaluationMethods.getAtWorkCustomSetup();

    List<Opportunity> lstAtWorkOpportunities = EvaluationMethods.getAtWorkOpportunitiesSorted(
      cSetup.CustomQueue__r,
      cSetup.DateFilter__c
    );

    if (cSetup.ProductAssignedUsers__r.isEmpty() || lstAtWorkOpportunities.isEmpty()) {
      return;
    }

    Set<Id> setAllUsers = new Set<Id>();
    Set<Id> setUnavailableUsers = new Set<Id>();

    for (ProductAssignedUser__c prodUser : cSetup.ProductAssignedUsers__r) {
      setAllUsers.add(prodUser.User__c);
      if (!prodUser.User__r.UserAvailable__c) {
        setUnavailableUsers.add(prodUser.User__c);
      }
    }

    for (Opportunity op : lstAtWorkOpportunities) {
      if (setAllUsers.contains(op.OwnerId)) {
        setUnavailableUsers.add(op.OwnerId);
      }
    }

    Map<String, List<Id>> mapUsersByProductType = createMapUsersByProductType(cSetup.ProductAssignedUsers__r);
    List<Opportunity> lstOpptyToAssign = new List<Opportunity>();

    for (Opportunity op : lstAtWorkOpportunities) {
      if (mapUsersByProductType.isEmpty()) {
        break;
      }

      List<Id> lstProductTypeUsers = mapUsersByProductType.get(op.ProductType__c);

      if (lstProductTypeUsers == null || lstProductTypeUsers.isEmpty()) {
        mapUsersByProductType.remove(op.ProductType__c);
        continue;
      }

      Id selectedUserId;

      for (Integer i = 0; i < lstProductTypeUsers.size(); i++) {
        Id userId = lstProductTypeUsers.get(i);

        if (setUnavailableUsers.contains(userId)) {
          continue;
        }

        selectedUserId = userId;
        mapUsersByProductType.get(op.ProductType__c).remove(i);
        break;
      }

      if (selectedUserId != null) {
        op.OwnerId = selectedUserId;
        lstOpptyToAssign.add(op);
        setUnavailableUsers.add(selectedUserId);
      }
    }

    if (lstOpptyToAssign.isEmpty()) {
      return;
    }

    update lstOpptyToAssign;
  }

  private static Map<String, List<Id>> createMapUsersByProductType(List<ProductAssignedUser__c> lstProductUser) {
    Map<String, Set<Id>> mapSetUsersByProductType = new Map<String, Set<Id>>();

    for (ProductAssignedUser__c productUser : lstProductUser) {
      if (mapSetUsersByProductType.containsKey(productUser.ProductType__c)) {
        mapSetUsersByProductType.get(productUser.ProductType__c).add(productUser.User__c);
      } else {
        mapSetUsersByProductType.put(productUser.ProductType__c, new Set<Id>{ productUser.User__c });
      }
    }

    Map<String, List<Id>> mapListUsersByProductType = new Map<String, List<Id>>();

    for (String prodType : mapSetUsersByProductType.keySet()) {
      mapListUsersByProductType.put(prodType, new List<Id>(mapSetUsersByProductType.get(prodType)));
    }

    return mapListUsersByProductType;
  }
}