creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Pontuação das filas</description>
    <inlineHelpText>Escolha um valor entre 0 e 999</inlineHelpText>
    <label>Pontuação</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto para a fila de @work</description>
    <inlineHelpText>O valor escolhido determinará qual a pontuação referente a esse produto.</inlineHelpText>
    <label>Tipo de Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomSetup__c/fields/DateFilter__c.field-meta.xml
<CustomField>
    <fullName>DateFilter__c</fullName>
    <label>Data de Filtro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data de Criação</fullName>
                <default>true</default>
                <label>Data de Criação</label>
            </value>
            <value>
                <fullName>Data de Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <label>AtWork</label>
</RecordType>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/CustomSetupTest.cls
/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Test class for CustomSetupController
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       17/02/2021      Created     Class creation
 **********************************************************************************************************************/
@isTest
public class CustomSetupTest {

    @TestSetup
    static void makeData(){
        Id recordTypeId = Util.getRecordTypeIdbyName('CustomSetup__c', 'AtWork');

        CustomSetup__c cSetup = new CustomSetup__c(RecordTypeId=recordTypeId, Name = 'Test', DateFilter__c = 'CreatedDate');
    
        insert cSetup;

        insert new List<CustomQueue__c>{
            new CustomQueue__c(Name = 'DISCHARGE', ProductType__c = 'DISCHARGE', CustomSetup__c = cSetup.Id, Points__c = 10),
            new CustomQueue__c(
              Name = 'REFINANCING',
              ProductType__c = 'REFINANCING',
              CustomSetup__c = cSetup.Id,
              Points__c = 20
            ),
            new CustomQueue__c(Name = 'STORE', ProductType__c = 'STORE', CustomSetup__c = cSetup.Id, Points__c = 30),
            new CustomQueue__c(
              Name = 'PAYROLL_LOAN',
              ProductType__c = 'PAYROLL_LOAN',
              CustomSetup__c = cSetup.Id,
              Points__c = 40
            ),
            new CustomQueue__c(
              Name = 'SALARY_ADVANCE',
              ProductType__c = 'SALARY_ADVANCE',
              CustomSetup__c = cSetup.Id,
              Points__c = 50
            ),
            new CustomQueue__c(
              Name = 'PENDENCY_RETURN',
              ProductType__c = 'PENDENCY_RETURN',
              CustomSetup__c = cSetup.Id,
              Points__c = 100
            )
          };
    }

    @isTest
    private static void testGetPendencyReturnApiName(){

        String pendencyReturnApiName = CustomSetupController.getPendencyReturnApiName();

        System.assert(String.isNotBlank(pendencyReturnApiName), 'Pendency Return ApiName should have a value');
    }

    @isTest
    private static void testGetCustomSetupByRecordType() {
        
        Test.startTest();

        CustomSetup__c customSetup = CustomSetupController.getCustomSetupByRecordType('AtWork');

        Test.stopTest();

        System.assert(customSetup!=null, 'Custom Setup is null.');
        System.assertEquals('Test', customSetup.Name, 'Incorrect Custom Setup Name');
    }

    @IsTest
    private static void testSelectCustomQueues(){

        String pendencyReturnApiName = CustomSetupController.getPendencyReturnApiName();

        List<CustomQueue__c> sampleQueues = [SELECT Id FROM CustomQueue__c WHERE ProductType__c != :pendencyReturnApiName LIMIT 2];
        Set<Id> sampleQueueIds = new Set<Id>{sampleQueues[0].Id, sampleQueues[1].Id};
        
        Test.startTest();
        
        List<CustomQueue__c> allQueues = CustomSetupController.selectCustomQueues();
        List<CustomQueue__c> someQueues = CustomSetupController.selectCustomQueues(sampleQueueIds);

        Test.stopTest();

        System.assertEquals(6, allQueues.size(), 'Expected 6 itens in CustomQueue__c list');

        // PENDENCY_RETURN custom queue will always return
        System.assertEquals(3, someQueues.size(), 'Expected 3 itens in CustomQueue__c list');
    }
}