creditas-sf/force-app/main/default/objects/CustomQueue__c/CustomQueue__c.object-meta.xml
<CustomObject>
    <label>Fila</label>
    <nameField>
        <label>Fila</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Filas</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/CustomSetup__c.field-meta.xml
<CustomField>
    <fullName>CustomSetup__c</fullName>
    <description>Relacionamento com o objeto de Custom Setup para determinar a pontuação de cada fila</description>
    <label>CustomSetup</label>
    <referenceTo>CustomSetup__c</referenceTo>
    <relationshipLabel>Filas</relationshipLabel>
    <relationshipName>CustomQueue</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/Points__c.field-meta.xml
<CustomField>
    <fullName>Points__c</fullName>
    <description>Pontuação das filas</description>
    <inlineHelpText>Escolha um valor entre 0 e 999</inlineHelpText>
    <label>Pontuação</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomQueue__c/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <description>Tipo de Produto para a fila de @work</description>
    <inlineHelpText>O valor escolhido determinará qual a pontuação referente a esse produto.</inlineHelpText>
    <label>Tipo de Produto</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/CustomSetup__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para definir as regras de customização de priorização da fila de @Work</description>
    <label>Parametrização</label>
    <nameField>
        <label>Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Parametrizações</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CustomSetup__c/fields/DateFilter__c.field-meta.xml
<CustomField>
    <fullName>DateFilter__c</fullName>
    <label>Data de Filtro</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Data de Criação</fullName>
                <default>true</default>
                <label>Data de Criação</label>
            </value>
            <value>
                <fullName>Data de Solicitação</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CustomSetup__c/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <label>AtWork</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/PriorityPoints__c.field-meta.xml
<CustomField>
    <fullName>PriorityPoints__c</fullName>
    <label>Priorização</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <businessProcess>%40Work - Creditas</businessProcess>
    <label>@Work</label>
</RecordType>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/EvaluationMethods.cls
/***********************************************************************************************************************
 * Copyright © 2021 Creditas
 * =======================================================================================================================
 * @description Priorização de oportunidades de AtWork
 * 
 =======================================================================================================================
 * History
 * -------
 * VERSION   AUTHOR                  DATE            DETAIL      Description
 * 1.0       Matheus Fernandes       18/01/2021      Created     Criação da classe para priorização de oportunidades de AtWork
 **********************************************************************************************************************/
public with sharing class EvaluationMethods {
  public static void evaluateAtWorkOpportunities(List<Opportunity> lstOpportunity) {
    List<Opportunity> lstOpportunityToUpdate = new List<Opportunity>();

    for (Opportunity opp : lstOpportunity) {
      if (opp.RecordTypeId == opportunityAtWorkRecordTypeId) {
        lstOpportunityToUpdate.add(opp);
      }
    }

    if (!lstOpportunityToUpdate.isEmpty()) {
      setPriorityPoints(lstOpportunityToUpdate);
    }
  }

  public static void evaluateAtWorkOpportunities(List<CustomQueue__c> lstCustomQueue) {
    List<Opportunity> lstOpportunityToUpdate = getAtWorkOpportunities(lstCustomQueue);
    if (!lstOpportunityToUpdate.isEmpty()) {
      updatePriorityPoints(lstOpportunityToUpdate);
    }
  }

  private static Id opportunityAtWorkRecordTypeId = Util.getRecordTypeIdbyName('Opportunity', 'AtWork');

  private static void setPriorityPoints(List<Opportunity> lOpportunity) {
    CustomSetup__c customSetup = getAtWorkCustomSetup();
    Map<String, Double> mapQueuePoints = createQueuePointsMap(customSetup.CustomQueue__r);

    for (Opportunity opp : lOpportunity) {
      opp.PriorityPoints__c = mapQueuePoints.containsKey(opp.ProductType__c)
        ? mapQueuePoints.get(opp.ProductType__c)
        : 0;
    }
  }

  private static void updatePriorityPoints(List<Opportunity> lOpportunity) {
    List<Opportunity> lOppsToUpdate = new List<Opportunity>();

    CustomSetup__c customSetup = getAtWorkCustomSetup();
    Map<String, Double> mapQueuePoints = createQueuePointsMap(customSetup.CustomQueue__r);

    for (Opportunity opp : lOpportunity) {
      opp.PriorityPoints__c = mapQueuePoints.containsKey(opp.ProductType__c)
        ? mapQueuePoints.get(opp.ProductType__c)
        : 0;
      lOppsToUpdate.add(opp);
    }

    update lOppsToUpdate;
  }

  private static Map<String, Double> createQueuePointsMap(List<CustomQueue__c> lCustomQueue) {
    Map<String, Double> mapQueuePoints = new Map<String, Double>();
    for (CustomQueue__c cQueue : lCustomQueue) {
      mapQueuePoints.put(cQueue.ProductType__c, cQueue.Points__c);
    }

    return mapQueuePoints;
  }

  private static List<Opportunity> getAtWorkOpportunities(List<CustomQueue__c> lstCustomQueue) {
    Set<String> setProductType = new Set<String>();
    for (CustomQueue__c cQueue : lstCustomQueue) {
      setProductType.add(cQueue.ProductType__c);
    }

    return [
      SELECT Id, ProductType__c, PriorityPoints__c, RecordTypeId
      FROM Opportunity
      WHERE RecordTypeId = :opportunityAtWorkRecordTypeId AND ProductType__c IN :setProductType
    ];
  }

  private static CustomSetup__c getAtWorkCustomSetup() {
    return [
      SELECT Id, DateFilter__c, (SELECT Id, ProductType__c, Points__c FROM CustomQueue__r)
      FROM CustomSetup__c
      WHERE Name = 'Parametrização de Filas e Usuários'
    ];
  }
}