creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCityStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCityStatus__c</fullName>
    <label>Status da cidade de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCountryStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCountryStatus__c</fullName>
    <label>Status do país de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthDateStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthDateStatus__c</fullName>
    <label>Status da Data de Nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHdispatchDateObservation__c.field-meta.xml
<CustomField>
    <fullName>CNHdispatchDateObservation__c</fullName>
    <label>Observação da data de expedição da CNH</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHdispatchDateStatus__c.field-meta.xml
<CustomField>
    <fullName>CNHdispatchDateStatus__c</fullName>
    <label>Status da data de expedição da CNH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHissuingAgencyStatus__c.field-meta.xml
<CustomField>
    <fullName>CNHissuingAgencyStatus__c</fullName>
    <label>Status do órgão expedidor da CNH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHnumberObservation__c.field-meta.xml
<CustomField>
    <fullName>CNHnumberObservation__c</fullName>
    <label>Observação do número da CNH</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHnumberPendingReason__c.field-meta.xml
<CustomField>
    <fullName>CNHnumberPendingReason__c</fullName>
    <label>Motivo Pendência do Número da CNH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documento ilegível</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHnumberStatus__c.field-meta.xml
<CustomField>
    <fullName>CNHnumberStatus__c</fullName>
    <label>Status do número da CNH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFObservation__c.field-meta.xml
<CustomField>
    <fullName>CPFObservation__c</fullName>
    <label>Observação do CPF</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFPendingReason__c.field-meta.xml
<CustomField>
    <fullName>CPFPendingReason__c</fullName>
    <label>Motivo Pendência CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF Irregular na Receita Federal</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
           
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFRejectReason__c.field-meta.xml
<CustomField>
    <fullName>CPFRejectReason__c</fullName>
    <label>Motivo Rejeição do CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFStatus__c.field-meta.xml
<CustomField>
    <fullName>CPFStatus__c</fullName>
    <label>Status do CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/DispatchDateObservation__c.field-meta.xml
<CustomField>
    <fullName>DispatchDateObservation__c</fullName>
    <label>Observação da data de expedição</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/DispatchDateStatus__c.field-meta.xml
<CustomField>
    <fullName>DispatchDateStatus__c</fullName>
    <label>Status da Data de Expedição</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/FathersNameStatus__c.field-meta.xml
<CustomField>
    <fullName>FathersNameStatus__c</fullName>
    <label>Status do nome do pai</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/IssuingAgencyStatus__c.field-meta.xml
<CustomField>
    <fullName>IssuingAgencyStatus__c</fullName>
    <label>Status do Órgão Expedidor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/MothersNameStatus__c.field-meta.xml
<CustomField>
    <fullName>MothersNameStatus__c</fullName>
    <label>Status do Nome da Mãe</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NameStatus__c.field-meta.xml
<CustomField>
    <fullName>NameStatus__c</fullName>
    <label>Status do Nome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NationalityStatus__c.field-meta.xml
<CustomField>
    <fullName>NationalityStatus__c</fullName>
    <label>Status da nacionalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/PersonExposedRejectReason__c.field-meta.xml
<CustomField>
    <fullName>PersonExposedRejectReason__c</fullName>
    <label>Motivo Rejeição Pessoa Politicamente Exp</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Identificado PEP</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/PoliticallyExposedPersonObservation__c.field-meta.xml
<CustomField>
    <fullName>PoliticallyExposedPersonObservation__c</fullName>
    <label>Observação pessoa politicamente exposta</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/PoliticallyExposedPersonStatus__c.field-meta.xml
<CustomField>
    <fullName>PoliticallyExposedPersonStatus__c</fullName>
    <label>Status da pessoa politicamente exposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/RGobservation__c.field-meta.xml
<CustomField>
    <fullName>RGobservation__c</fullName>
    <label>Observação do RG</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/RGStatus__c.field-meta.xml
<CustomField>
    <fullName>RGStatus__c</fullName>
    <label>Status do RG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/UFIssuingAgencyStatus__c.field-meta.xml
<CustomField>
    <fullName>UFIssuingAgencyStatus__c</fullName>
    <label>Status do UF do Órgão Expedidor</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalPersonalDataService.cls
public with sharing class ProposalPersonalDataService {

    public static Map<String, SObject> getPersonalDataSectionRecord(Id recordId) 
    {
        List<PersonalDataSection__c> personalDataSection = new List<PersonalDataSection__c>();
        Map<String, SObject> result = new Map<String, SObject>();

        personalDataSection = [SELECT   Id, 
                                        Opportunity__c, 
                                        Name, 
                                        NameStatus__c, 
                                        FathersNameStatus__c,
                                        MothersNameStatus__c,
                                        CPFStatus__c, CPFPendingReason__c, CPFRejectReason__c, CPFObservation__c,
                                        BirthCityStatus__c, BirthCountryStatus__c, BirthDateStatus__c,
                                        NationalityStatus__c,
                                        PoliticallyExposedPersonStatus__c, PersonExposedRejectReason__c, PoliticallyExposedPersonObservation__c,
                                        RGStatus__c, RGPendingReason__c, RGobservation__c, RGRejectReason__c,
                                        IssuingAgencyStatus__c,
                                        DispatchDateStatus__c, DispatchDateObservation__c, DateDispatchPendingReason__c,
                                        UFIssuingAgencyStatus__c, 
                                        CNHnumberStatus__c, CNHnumberPendingReason__c, CNHnumberObservation__c,
                                        CNHdispatchDateStatus__c, CNHdispatchDateObservation__c, CNHdispatchDatePendingReason__c,
                                        CNHissuingAgencyStatus__c, CNHissuingAgencyObservation__c, CNHissuingAgencyPendingReason__c
                                        FROM PersonalDataSection__c
                                        WHERE Opportunity__c =: recordId
                                        LIMIT 1];
        
        if(!personalDataSection.isEmpty()) {
            result.put('dadosPessoais', personalDataSection[0]);
        }

        return result;
    }

    public static Map<String, SObject> getDocuments(Id recordId)
    {
        List<Documents__c> documents;
        Map<String, SObject> result = new Map<String, SObject>();
        
        
        documents = [SELECT Id, 
                            Name,
                            Account__c,
                            DocumentNumber__c, 
                            DocumentType__c, 
                            Issuer__c, 
                            IssueDate__c, 
                            IssuerState__c 
                            FROM Documents__c
                            WHERE Account__c = :recordId
                            AND (DocumentType__c = 'RG' OR DocumentType__c = 'CNH')
                            ORDER BY CreatedDate ASC];
                    
        if(!documents.isEmpty()) 
        {
            for(Documents__c document : documents) 
            {
                result.put(document.DocumentType__c, document);
            }
        }

        return result;
    }
}