creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCityStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCityStatus__c</fullName>
    <label>Status da cidade de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCountryStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCountryStatus__c</fullName>
    <label>Status do país de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthDateStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthDateStatus__c</fullName>
    <label>Status da Data de Nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFStatus__c.field-meta.xml
<CustomField>
    <fullName>CPFStatus__c</fullName>
    <label>Status do CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NameStatus__c.field-meta.xml
<CustomField>
    <fullName>NameStatus__c</fullName>
    <label>Status do Nome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NationalityStatus__c.field-meta.xml
<CustomField>
    <fullName>NationalityStatus__c</fullName>
    <label>Status da nacionalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/PoliticallyExposedPersonStatus__c.field-meta.xml
<CustomField>
    <fullName>PoliticallyExposedPersonStatus__c</fullName>
    <label>Status da pessoa politicamente exposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/PersonalDataSectionRepositoryTest.cls
/**
 * @author Otávio Frank - GFT Brasil
 */
@isTest
public class PersonalDataSectionRepositoryTest {

    @TestSetup
    static void makeData(){

        Account account = TestSetup.getAccount('test', true);
        
        Opportunity opportunity = OpportunitySetup.createOpportunity(account.Id,'AutoFin');
        insert opportunity;

        PersonalDataSection__c personalDataRecord = new PersonalDataSection__c();
        personalDataRecord.Opportunity__c = opportunity.Id;
        personalDataRecord.NameStatus__c = 'Aprovar';
        personalDataRecord.CPFStatus__c = 'Rejeitar';
        personalDataRecord.BirthCityStatus__c = 'Aprovar';
        personalDataRecord.BirthCountryStatus__c = 'Aprovar';
        personalDataRecord.BirthDateStatus__c = 'Pendenciar';
        personalDataRecord.NationalityStatus__c = 'Pendenciar';
        personalDataRecord.PoliticallyExposedPersonStatus__c = 'Pendenciar';

        insert personalDataRecord;
    }

    @isTest
    public static void givenOppIdThenFindLastPersonalDataSection() {

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        PersonalDataSectionRepository repo = new PersonalDataSectionRepository();

        test.startTest();

        List<PersonalDataSection__c> lastPersonalDataSection = repo.findLastPersonalDataSectionByOppId( opportunity.Id );

        test.stopTest();

        System.assertEquals(1, lastPersonalDataSection.size() , 'Should have 1 personalDataSection record');
    }
}