creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Task/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/TaskDetails__c/TaskDetails__c.object-meta.xml
<CustomObject>
    <label>Detalhe da Tarefa</label>
    <nameField>
        <label>Detalhe da Tarefa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detalhes da Tarefa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/FieldKey1__c.field-meta.xml
<CustomField>
    <fullName>FieldKey1__c</fullName>
    <label>Field Key 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/FieldName1__c.field-meta.xml
<CustomField>
    <fullName>FieldName1__c</fullName>
    <label>Field Name 1</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/FieldValue1__c.field-meta.xml
<CustomField>
    <fullName>FieldValue1__c</fullName>
    <label>Field Value 1</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOME</fullName>
                <default>true</default>
                <label>HOME</label>
            </value>
            <value>
                <fullName>AUTOFIN</fullName>
            </value>
            <value>
                <fullName>ATWORK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>Task Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/WorkflowKey__c.field-meta.xml
<CustomField>
    <fullName>WorkflowKey__c</fullName>
    <label>Workflow Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/TaskDetailSettings__c.object-meta.xml
<CustomObject>
    <label>Task Detail Settings</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TaskDetailSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Detail Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/CheckboxGroupValues__c.field-meta.xml
<CustomField>
    <fullName>CheckboxGroupValues__c</fullName>
    <label>Checkbox Group Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/DisplaySequence__c.field-meta.xml
<CustomField>
    <fullName>DisplaySequence__c</fullName>
    <label>DisplaySequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldKey__c.field-meta.xml
<CustomField>
    <fullName>FieldKey__c</fullName>
    <label>FieldKey</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldType__c.field-meta.xml
<CustomField>
    <fullName>FieldType__c</fullName>
    <label>FieldType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Multi-picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>CheckboxGroup</fullName>
            </value>
            <value>
                <fullName>RadioGroup</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/MappedField__c.field-meta.xml
<CustomField>
    <fullName>MappedField__c</fullName>
    <label>Mapped Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/PicklistValues__c.field-meta.xml
<CustomField>
    <fullName>PicklistValues__c</fullName>
    <label>Picklist Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOME</fullName>
                <default>true</default>
                <label>HOME</label>
            </value>
            <value>
                <fullName>AUTOFIN</fullName>
            </value>
            <value>
                <fullName>ATWORK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/RadioGroupValues__c.field-meta.xml
<CustomField>
    <fullName>RadioGroupValues__c</fullName>
    <label>Radio Group Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>TaskType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validar Emissão da Minuta</fullName>
            </value>
            <value>
                <fullName>Condicionante de Fechamento para Emissão</fullName>
            </value>
            <value>
                <fullName>Condicionante de Formalização para Emissão</fullName>
            </value>
            <value>
                <fullName>Adiantar Minuta</fullName>
            </value>
            <value>
                <fullName>Confirmar Valores</fullName>
            </value>
            <value>
                <fullName>Atualizar Proposta Final de Crédito</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Fechamento</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Formalização</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão e Operações Cartorárias</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Jurídico</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Crédito</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Risco Imobiliário</fullName>
            </value>
            <value>
                <fullName>Emitir Minuta</fullName>
            </value>
            <value>
                <fullName>Conferir Minuta</fullName>
            </value>
            <value>
                <fullName>Validar Minuta com Credor</fullName>
            </value>
            <value>
                <fullName>Enviar Minuta Rascunho para o Cliente</fullName>
            </value>
            <value>
                <fullName>Ajustar Minuta</fullName>
            </value>
            <value>
                <fullName>Liberar Minuta Final</fullName>
            </value>
            <value>
                <fullName>Formalização - Nova proposta</fullName>
            </value>
            <value>
                <fullName>Formalização - Em análise</fullName>
            </value>
            <value>
                <fullName>Formalização - Pendência</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/WorkflowKey__c.field-meta.xml
<CustomField>
    <fullName>WorkflowKey__c</fullName>
    <label>WorkflowKey</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/TaskDetailsControllerTest.cls
@isTest
public class TaskDetailsControllerTest {
    
    private static final Id RECORDTYPE_TASK_AUTOFIN = Schema.SObjectType.Task.getRecordTypeInfosByDeveloperName().get('AutoFin').getRecordTypeId();
    
    @testSetup
    public static void createData() {
        
        /*Schema.DescribeFieldResult taskTypeDescription = Task.TaskType__c.getDescribe();
		List<Schema.PicklistEntry> taskTypePicklistValuesList = taskTypeDescription.getPicklistValues();*/
        
        List<TaskDetailSettings__c> lLstTaskDetailSettings = new List<TaskDetailSettings__c>();
        
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 1, 'AFcpf', 'Text', '1', 'Formalização - Em análise', '','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 2, 'AFsalario', 'Currency', '2', 'Formalização - Em análise', '','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 3, 'AFampanhacomercial', 'Multi-picklist', '3', 'Formalização - Em análise', 'Sim;Não','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 4, 'AFoperacaoIQ', 'Picklist', '4', 'Formalização - Em análise', 'Sim;Não','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 5, 'AFisActive', 'Checkbox', '5', 'Formalização - Em análise','','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 6, 'AFconta', 'Relationship', '6', 'Formalização - Em análise','','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 7, 'AFtext', 'Header', '7', 'Formalização - Em análise','','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 8, 'AFnumber', 'Number', '8', 'Formalização - Em análise','','',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 9, 'AFconta', 'RadioGroup', '9', 'Formalização - Em análise','','Sim;Não',''));
        lLstTaskDetailSettings.add(createTaskDetailSettings('AUTOFIN', 'Teste', 10, 'AFconta', 'CheckboxGroup', '10', 'Formalização - Em análise','','','Sim;Não'));

        insert lLstTaskDetailSettings;

        TaskDetails__c lTaskDetails = new TaskDetails__c();
		lTaskDetails.FieldName1__c = 'CPF';
		lTaskDetails.FieldKey1__c = 'CPF';
		lTaskDetails.FieldValue1__c = '123.456.789-10';
        insert lTaskDetails;

        Opportunity lOpportunity = TestSetup.getOpportunity(null, false);
        insert lOpportunity;
            
        Task lTask = new Task();
        lTask.TaskDetails__c = lTaskDetails.Id;
        lTask.RecordTypeId = RECORDTYPE_TASK_AUTOFIN;
        lTask.TaskType__c = 'Formalização - Em análise';
        lTask.WhatId = lOpportunity.Id;
        insert lTask;
    }

    @isTest
    public static void getInfoTask(){
        Task lTask = [SELECT Id FROM Task LIMIT 1];
        
        Test.startTest();
        Map<String,Object> lresult = TaskDetailsController.getTaskDetails(lTask.Id);
        Test.stopTest();
        
        System.assert(lresult.get('TaskDetailSettings') != null);
        System.assert(lresult.get('TaskDetails') != null);
    }
    
    @isTest
    public static void updateTaskTest(){
        TaskDetails__c lTaskDetails = [SELECT Id FROM TaskDetails__c LIMIT 1];
        Task lTask = new Task();
        insert lTask;
        
        Test.startTest();
        TaskDetailsController.updateRecordTask(lTask.Id, lTaskDetails.Id);
        Test.stopTest();
        
        Task lTaskResult = [SELECT Id, TaskDetails__c FROM Task WHERE Id =:lTask.Id LIMIT 1];
        System.assertEquals(lTaskDetails.Id, lTaskResult.TaskDetails__c);
    }
    
    @isTest
    public static void getInfoTaskErro(){
        Task lTask = [SELECT Id FROM Task LIMIT 1];
        Boolean exceptionOccurred = false;
        
        Test.startTest();
        try{
        	Map<String,Object> lresult = TaskDetailsController.getTaskDetails('12345');
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals(true, exceptionOccurred);
    }
    
    @isTest
    public static void updateTaskTestErro(){
        Boolean exceptionOccurred = false;
        
        Test.startTest();
        try{
        	TaskDetailsController.updateRecordTask('12345', '1234');
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals(true, exceptionOccurred);
    }
    
    @isTest
    public static void getRecordTaskDetailsErro(){
        Boolean exceptionOccurred = false;
        
        Test.startTest();
        try{
        	TaskDetailsController.getRecordTaskDetails('12345');
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals(true, exceptionOccurred);
    }
    
    @isTest
    public static void getOpportunityTest(){
        Task lTask = [SELECT Id FROM Task LIMIT 1];
        Test.startTest();
        	TaskDetailsController.getOpportunity(lTask.Id);
        Test.stopTest();
    }
    public static TaskDetailSettings__c createTaskDetailSettings(String aProduct, String aWorkflow, Integer aDisplaySequence, String aFieldKey,  String aFieldType,  String aMappedField,  String aTaskType, String aPicklistValues, String aRadioGroupValues, String aCheckboxGroupValues){
        TaskDetailSettings__c lTaskSettings = new TaskDetailSettings__c();
        lTaskSettings.Product__c = aProduct;
        lTaskSettings.WorkflowKey__c = aWorkflow; 
        lTaskSettings.DisplaySequence__c = aDisplaySequence; 
        lTaskSettings.FieldKey__c = aFieldKey; 
        lTaskSettings.FieldType__c = aFieldType; 
        lTaskSettings.FieldName__c = aWorkflow; 
        lTaskSettings.MappedField__c = aMappedField;
        lTaskSettings.TaskType__c = aTaskType;
        lTaskSettings.PicklistValues__c = aPicklistValues;
        lTaskSettings.RadioGroupValues__c = aRadioGroupValues;
        lTaskSettings.CheckboxGroupValues__c = aCheckboxGroupValues;
        
        return lTaskSettings;
    }
}