creditas-sf/force-app/main/default/objects/GeneralSection__c/GeneralSection__c.object-meta.xml
<CustomObject>
    <label>Seção Geral</label>
    <nameField>
        <displayFormat>G-{00000}</displayFormat>
        <label>Sessão Geral Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seções Gerais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/GeneralSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seções Gerais</relationshipLabel>
    <relationshipName>SecoesGerais</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalGeneralSectionSetup.cls
@isTest
public with sharing class ProposalGeneralSectionSetup extends DataBuilder{
    public ProposalGeneralSectionSetup(Opportunity opp, String externalId) {
        this.setRecord(
            new GeneralSection__c(
                Opportunity__c = opp.Id,
                GeneralSectionExternalIdAtWork__c = externalId,
                GeneralDataObservation__c = 'observation'
            )
        );
        this.setIterableFields(new String[]{ 'Name', 'GeneralDataObservation__c' });
    }
    public GeneralSection__c createGeneralSection(Map<String, Object> sObjectOpts, Boolean doInsert){
        return (GeneralSection__c) this.createSObject(sobjectOpts, doInsert);
    }
    public List<GeneralSection__c> createGeneralSections(Map<String, Object> sObjectOpts, Integer qtd, Boolean doInsert){
        return (List<GeneralSection__c>) this.createSObjects(sobjectOpts, qtd, doInsert);
    }
}