creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/Addresses__c.object-meta.xml
<CustomObject>
    <description>Objeto para registros dos endereços do cliente/empresa, independente da localidade (Brasil/México).</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Numeração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Esse campo determina o qual a conta que está relacionada ao endereço cadastrado.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Endere_os</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>CommunicationContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ProfessionalInfo__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalInfo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Emprego</label>
    <referenceTo>ProfessionalInfo__c</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/FichaFormalizacaoControllerTest.cls
@isTest
public class FichaFormalizacaoControllerTest {
    
    @TestSetup
    static void makeData() 
    {
        Account varAccount = TestSetup.getAccount('Francisco', true);

        Documents__c varDocuments = new Documents__c();
        varDocuments.Account__c = varAccount.Id;
        insert varDocuments;

        ProfessionalInfo__c varProfessionalInfo = new ProfessionalInfo__c();
        varProfessionalInfo.Account__c = varAccount.Id;
        insert varProfessionalInfo;

        CommunicationContacts__c varCommunicationContact = new CommunicationContacts__c();
        varCommunicationContact.Account__c = varAccount.Id;
        insert varCommunicationContact;

        Addresses__c varAddress = new Addresses__c();
        varAddress.Account__c = varAccount.Id;
        insert varAddress;

        FinancialResources__c varFinancialResources = new FinancialResources__c();
        insert varFinancialResources;

        AccountFinancialRelationship__c varAccountFinancial = new AccountFinancialRelationship__c();
        varAccountFinancial.Account__c = varAccount.Id;
        varAccountFinancial.Recurso_Financeiro__c = varFinancialResources.Id;
        insert varAccountFinancial;

    }

    @isTest
    static void getData() {

        Id varAccountId = [SELECT Id, Name FROM Account LIMIT 1]?.Id;

        System.debug('TYUMI => varaccountId: ' + varAccountId);

        Test.startTest();
        FichaFormalizacaoController.getRecords(varAccountId);
        Test.stopTest();

    }
}