creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccFinRelationshipTriggerTest.cls
@isTest
private with sharing class AccFinRelationshipTriggerTest {
  @TestSetup
  static void makeData() {
    Account newAcc = TestSetup.getAccount('Conta', true);

    FinancialResources__c newRecFin = TestSetup.getNewFinRes(
      'Novo Recurso Financeiro',
      true
    );

    FinancialResources__c newRecFin2 = TestSetup.getNewFinRes(
      'Novo Recurso Financeiro2',
      true
    );
  }

  @isTest
  static void insertFinancialRelationship() {
    List<FinancialResources__c> recFinRes = [
      SELECT Id
      FROM FinancialResources__c
    ];

    Account accRes = [SELECT Id FROM Account];

    AccountFinancialRelationship__c newFinRel = new AccountFinancialRelationship__c();
    newFinRel.Account__c = accRes.Id;
    newFinRel.Recurso_Financeiro__c = recFinRes[0].Id;

    Test.startTest();
    insert newFinRel;
    Test.stopTest();

    List<AccountFinancialRelationship__c> res = [
      SELECT Id
      FROM AccountFinancialRelationship__c
    ];

    System.assertNotEquals(0, res.Size());
  }

  @isTest
  static void updateFinancialRelationship() {
    List<FinancialResources__c> recFinRes = [
      SELECT Id
      FROM FinancialResources__c
    ];

    Account accRes = [SELECT Id FROM Account];

    AccountFinancialRelationship__c newFinRel = new AccountFinancialRelationship__c();
    newFinRel.Account__c = accRes.Id;
    newFinRel.Recurso_Financeiro__c = recFinRes[0].Id;
    insert newFinRel;

    AccountFinancialRelationship__c resInserted = [
      SELECT Id, Recurso_Financeiro__c
      FROM AccountFinancialRelationship__c
    ];

    newFinRel.Recurso_Financeiro__c = recFinRes[1].Id;

    Test.startTest();
    update newFinRel;
    Test.stopTest();

    AccountFinancialRelationship__c resUpdated = [
      SELECT Id, Recurso_Financeiro__c
      FROM AccountFinancialRelationship__c
    ];

    System.assertNotEquals(resInserted, resUpdated);
  }
}