creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ConfirmedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda confirmada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeObservation__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeObservation__c</fullName>
    <label>Observação da renda mínima</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeRejectReason__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeRejectReason__c</fullName>
    <label>Motivo Rejeição Renda Mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente não atinge a renda mínima</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeStatus__c</fullName>
    <label>Status da renda mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeObservation__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeObservation__c</fullName>
    <label>Observação da renda informada</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeStatus__c</fullName>
    <label>Status da renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/NetWorthStatus__c.field-meta.xml
<CustomField>
    <fullName>NetWorthStatus__c</fullName>
    <label>Status do patrimônio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/PresumedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>PresumedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda considerada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationObservation__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationObservation__c</fullName>
    <label>Observação da situação profissional</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationPendingReason__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationPendingReason__c</fullName>
    <label>Motivo Pendência Situação Profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprovante de renda divergente da ocupação do cliente</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationStatus__c</fullName>
    <label>Status da situação profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionObservation__c.field-meta.xml
<CustomField>
    <fullName>ProfessionObservation__c</fullName>
    <label>Observação da profissão</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionPendingReason__c.field-meta.xml
<CustomField>
    <fullName>ProfessionPendingReason__c</fullName>
    <label>Motivo Pendência Profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprovante de renda divergente da ocupação do cliente</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionStatus__c</fullName>
    <label>Status da profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ReportedIncomePendingReason__c.field-meta.xml
<CustomField>
    <fullName>ReportedIncomePendingReason__c</fullName>
    <label>Motivo Pendência Renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documeneto não aceito/inválido</fullName>
            </value>
            <value>
                <fullName>Documento de renda ilegível 	Documento incompleto</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/IncomeDataSectionRepository.cls
/**
 * @author Otávio Frank - GFT Brasil
 */
public virtual class IncomeDataSectionRepository extends Repository {

    virtual
    public List<IncomeDataSection__c> findLastIncomeDataSectionByOppId( String oppId ) {

        return [ SELECT  Name, CurrencyIsoCode, CreatedDate, ProfessionalSituationStatus__c, 
                         ProfessionalSituationObservation__c, JobTitle__c, 
                         ConfirmedMonthlyIncome__c, ProfessionStatus__c, 
                         ProfessionObservation__c, PresumedMonthlyIncome__c, 
                         MonthlyIncome__c, NetWorthStatus__c, MinimalRequiredIncome__c, 
                         Status__c, MonthlyIncomeStatus__c, MonthlyIncomeObservation__c, 
                         NetWorth__c, MinimalRequiredIncomeStatus__c, MinimalRequiredIncomeObservation__c, 
                         PresumedMonthlyIncomeStatus__c, ConfirmedMonthlyIncomeStatus__c, 
                         MinimalRequiredIncomeRejectReason__c, ProfessionalSituationPendingReason__c, 
                         ProfessionPendingReason__c, ReportedIncomePendingReason__c, Opportunity__c
                FROM IncomeDataSection__c
                WHERE Opportunity__c =: oppId
                ORDER BY CreatedDate DESC limit 1 ];
    }
}