creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ConfirmedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda confirmada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeStatus__c</fullName>
    <label>Status da renda mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeStatus__c</fullName>
    <label>Status da renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/NetWorthStatus__c.field-meta.xml
<CustomField>
    <fullName>NetWorthStatus__c</fullName>
    <label>Status do patrimônio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/PresumedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>PresumedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda considerada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationStatus__c</fullName>
    <label>Status da situação profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionStatus__c</fullName>
    <label>Status da profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/classes/IncomeDataSectionRepositoryTest.cls
/**
 * @author Otávio Frank - GFT Brasil
 */
@isTest
public class IncomeDataSectionRepositoryTest {
    
    @TestSetup
    static void makeData(){

        Account account = TestSetup.getAccount('test', true);
        
        Opportunity opportunity = OpportunitySetup.createOpportunity(account.Id,'AutoFin');
        insert opportunity;
    }

    @isTest
    public static void givenOpportunityIdFindLastIncomeDataSection() {

        IncomeDataSectionRepository repo = new incomeDataSectionRepository();

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Approved';
        incomeDataSection.ProfessionStatus__c               = 'Approved';
        incomeDataSection.NetWorthStatus__c                 = 'Approved';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Approved';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Approved';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Approved';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Approved';

        insert incomeDataSection;

        Test.startTest();

        List<IncomeDataSection__c> lastIncomeDataSection = repo.findLastIncomeDataSectionByOppId(opportunity.Id);
        
        Test.stopTest();

        System.assertEquals( 1 , lastIncomeDataSection.size(), 'Should have 1 incomeDataSection record' );
    }

    @isTest
    public static void givenListOfIncomeDataSectionThenSave() {

        IncomeDataSectionRepository repo = new incomeDataSectionRepository();

        Test.startTest();

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Approved';
        incomeDataSection.ProfessionStatus__c               = 'Approved';
        incomeDataSection.NetWorthStatus__c                 = 'Approved';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Approved';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Approved';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Approved';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Approved';

        List<IncomeDataSection__c> lastIncomeDataSection = (List<IncomeDataSection__c>) repo.save( new List<IncomeDataSection__c>{ incomeDataSection });
        
        Test.stopTest();

        System.assertEquals( true , String.IsNotBlank( lastIncomeDataSection[0].Id ), 'Should have 1 record with Id' );
    }

    @isTest
    public static void givenListOfIncomeDataSectionThenDelete() {

        IncomeDataSectionRepository repo = new incomeDataSectionRepository();

        Test.startTest();

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Approved';
        incomeDataSection.ProfessionStatus__c               = 'Approved';
        incomeDataSection.NetWorthStatus__c                 = 'Approved';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Approved';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Approved';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Approved';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Approved';

        List<IncomeDataSection__c> lastIncomeDataSection = (List<IncomeDataSection__c>) repo.save( new List<IncomeDataSection__c>{ incomeDataSection });
        
        System.assertEquals( true , String.IsNotBlank( lastIncomeDataSection[0].Id ), 'Should have 1 record with Id' );

        repo.remove( lastIncomeDataSection );

        List<IncomeDataSection__c> result = repo.findLastIncomeDataSectionByOppId(opportunity.Id);

        Test.stopTest();

        System.assertEquals( true , result.isEmpty() , 'The list must be empty' );

    }

    @isTest
    public static void givenAnIncomeDataSectionThenSave() {

        IncomeDataSectionRepository repo = new incomeDataSectionRepository();

        Test.startTest();

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Approved';
        incomeDataSection.ProfessionStatus__c               = 'Approved';
        incomeDataSection.NetWorthStatus__c                 = 'Approved';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Approved';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Approved';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Approved';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Approved';

        incomeDataSection = (IncomeDataSection__c) repo.save( incomeDataSection );
        
        Test.stopTest();

        System.assertEquals( true , String.IsNotBlank( incomeDataSection.Id ), 'The record must have an Id' );
    }

    @isTest
    public static void givenAnIncomeDataSectionThenDelete() {

        IncomeDataSectionRepository repo = new incomeDataSectionRepository();

        Test.startTest();

        Opportunity opportunity = [ SELECT ID FROM Opportunity LIMIT 1 ];

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Approved';
        incomeDataSection.ProfessionStatus__c               = 'Approved';
        incomeDataSection.NetWorthStatus__c                 = 'Approved';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Approved';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Approved';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Approved';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Approved';

        incomeDataSection = (IncomeDataSection__c) repo.save( incomeDataSection );

        System.assertEquals( true , String.IsNotBlank( incomeDataSection.Id ), 'The record must have an Id' );

        repo.remove( incomeDataSection );

        List<IncomeDataSection__c> lastIncomeDataSection = repo.findLastIncomeDataSectionByOppId(opportunity.Id);

        Test.stopTest();

        System.assertEquals( true , lastIncomeDataSection.isEmpty() , 'The list must be empty' );

    }

}