creditas-sf/force-app/main/default/objects/Account/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>Número da Conta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <label>Código do Banco</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <formula>TEXT(Account.DocumentType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo do documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/Full_name__c.field-meta.xml
<CustomField>
    <fullName>Full_name__c</fullName>
    <formula>Account.FirstName__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Nome Completo</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AtWork.recordType-meta.xml
<RecordType>
    <fullName>AtWork</fullName>
    <active>true</active>
    <businessProcess>%40Work - Creditas</businessProcess>
    <label>@Work</label>
</RecordType>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/formalizationAnalysisController.cls
public with sharing class formalizationAnalysisController {

    //private static final String OPP_ATWORK_RECORDTYPEID = Util.getRecordTypeIdbyName('Opportunity','AtWork');
    @AuraEnabled
    public static Opportunity getOpportunnityInfo(String aOpportunityId){
        try {
            return [SELECT AccountNumber__c, Amount, BankCode__c, Branch__c, DocumentNumber__c, DocumentType__c, Full_name__c, toLabel(ProductType__c), Account.BirthDate__c FROM Opportunity WHERE Id = :aOpportunityId];
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

}