creditas-sf/force-app/main/default/objects/Account/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>Número da Conta</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/AccountNumber__c.field-meta.xml
<CustomField>
    <fullName>AccountNumber__c</fullName>
    <label>AccountNumber</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/BankAccountType__c.field-meta.xml
<CustomField>
    <fullName>BankAccountType__c</fullName>
    <label>Tipo de Conta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>SAVINGS</fullName>
                <label>Conta Poupança</label>
            </value>
            <value>
                <fullName>CHECKINGS</fullName>
                <label>Conta Corrente</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/BankCode__c.field-meta.xml
<CustomField>
    <fullName>BankCode__c</fullName>
    <label>Código do Banco</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/Branch__c.field-meta.xml
<CustomField>
    <fullName>Branch__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ContractDate__c.field-meta.xml
<CustomField>
    <fullName>ContractDate__c</fullName>
    <formula>TEXT(SyncedQuote.ContractDate__c )</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Data do contrato</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/MonthlyInterest__c.field-meta.xml
<CustomField>
    <fullName>MonthlyInterest__c</fullName>
    <formula>TEXT(SyncedQuote.MonthlyInterest__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Taxa de Juros</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>Tipo de produto</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetName>ProductType</valueSetName>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>TEXT(SyncedQuote.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prazo solicitado</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/RequestedAmount__c.field-meta.xml
<CustomField>
    <fullName>RequestedAmount__c</fullName>
    <formula>TEXT(SyncedQuote.RequestedAmount__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor do crédito solicitado</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/CollateralAmount__c.field-meta.xml
<CustomField>
    <fullName>CollateralAmount__c</fullName>
    <label>CollateralAmount</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ContractDate__c.field-meta.xml
<CustomField>
    <fullName>ContractDate__c</fullName>
    <label>ContractDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/CreditScore__c.field-meta.xml
<CustomField>
    <fullName>CreditScore__c</fullName>
    <label>CreditScore</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/DailyCet__c.field-meta.xml
<CustomField>
    <fullName>DailyCet__c</fullName>
    <label>Taxa Diaria</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/GracePeriod__c.field-meta.xml
<CustomField>
    <fullName>GracePeriod__c</fullName>
    <label>GracePeriod</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/InstallmentType__c.field-meta.xml
<CustomField>
    <fullName>InstallmentType__c</fullName>
    <label>InstallmentType</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>FIXED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/MonthlyCet__c.field-meta.xml
<CustomField>
    <fullName>MonthlyCet__c</fullName>
    <label>MonthlyCet</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/MonthlyInterest__c.field-meta.xml
<CustomField>
    <fullName>MonthlyInterest__c</fullName>
    <label>MonthlyInterest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ParameterAdditionalCosts__c.field-meta.xml
<CustomField>
    <fullName>ParameterAdditionalCosts__c</fullName>
    <label>ParameterAdditionalCosts</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ParameterCalcVersion__c.field-meta.xml
<CustomField>
    <fullName>ParameterCalcVersion__c</fullName>
    <label>ParameterCalcVersion</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ParameterIOF__c.field-meta.xml
<CustomField>
    <fullName>ParameterIOF__c</fullName>
    <label>ParameterIOF</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ParameterTac__c.field-meta.xml
<CustomField>
    <fullName>ParameterTac__c</fullName>
    <label>Valor TC</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ProductType__c.field-meta.xml
<CustomField>
    <fullName>ProductType__c</fullName>
    <label>ProductType</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/RequestedAmount__c.field-meta.xml
<CustomField>
    <fullName>RequestedAmount__c</fullName>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ServiceDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceDate__c</fullName>
    <label>Primeiro Vencimento</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/ServiceLastDate__c.field-meta.xml
<CustomField>
    <fullName>ServiceLastDate__c</fullName>
    <label>Último Vencimento</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/Term__c.field-meta.xml
<CustomField>
    <fullName>Term__c</fullName>
    <label>Term</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/UF__c.field-meta.xml
<CustomField>
    <fullName>UF__c</fullName>
    <label>UF</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/YearlyCet__c.field-meta.xml
<CustomField>
    <fullName>YearlyCet__c</fullName>
    <label>Taxa Anual</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/YearlyInterest__c.field-meta.xml
<CustomField>
    <fullName>YearlyInterest__c</fullName>
    <label>YearlyInterest</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/globalValueSets/ProductType.globalValueSet-meta.xml
<GlobalValueSet>
    <customValue>
        <fullName>SALARY_ADVANCE</fullName>
        <label>Antecipação</label>
    </customValue>
    <customValue>
        <fullName>PAYROLL_LOAN</fullName>
        <label>Payroll</label>
    </customValue>
    <customValue>
        <fullName>STORE</fullName>
        <label>Store</label>
    </customValue>
    <customValue>
        <fullName>REFINANCING</fullName>
        <label>Refinanciamento</label>
    </customValue>
    <customValue>
        <fullName>DISCHARGE</fullName>
        <label>Quitação</label>
    </customValue>
    <customValue>
        <fullName>PENDENCY_RETURN</fullName>
        <label>Retorno de Pendência</label>
    </customValue>
    <masterLabel>Tipo de produto</masterLabel>
</GlobalValueSet>

creditas-sf/force-app/main/default/classes/OpportunityIntegrationService.cls
public with sharing class OpportunityIntegrationService {
    public class OpportunityIntegrationException extends Exception {
    }

    public class Response{
        public Integer statusCode;
        public String opportunityId;
        public String message;
        public Response(Integer statusCode, String oppId, String message){
            this.statusCode = statusCode;
            this.opportunityId = oppId;
            this.message = message;
        }
    }

    public static Map<String, String> getPersonIdAndAccountName(List<OpportunityIntegrationVO.cls_participants> participantsList){
        
        Map<String, String> newMap = new Map<String, String>();
        String personId;
        for(OpportunityIntegrationVO.cls_participants participant : participantsList){
            for(String partRole : participant.roles){
                if(partRole == 'PRINCIPAL'){
                    personId = participant.person.id;
                    newMap.put('personId', personId);
                    break;
                }
            }
        }

        accountName = [SELECT Name FROM Account WHERE ExternalId__c = :personId WITH SECURITY_ENFORCED]?.Name;

        if(accountName != null){
            newMap.put('accountName', accountName);
        }

        return newMap; 
    }

    public static RestResponse setResponse(Response response, Integer errorCode){
        //String errorResponse = String.isBlank(errorMessage) ? 'An error has occurred. Please, contact a Salesforce Administrator.' : errorMessage;
        RestResponse res = RestContext.response != null ?  RestContext.response : new RestResponse();
        res.responseBody = Blob.valueOf(JSON.serialize(response));
        res.statusCode = errorCode;
        return res;
    }

    public static Boolean upsertOpportunity(){   

        Opportunity opportunityToUpsert = new Opportunity();    
        opportunityToUpsert.Id = [SELECT Id, ExternalId__c FROM Opportunity WHERE ExternalId__c = :requestBodyObj.id]?.Id;
        opportunityToUpsert.ExternalId__c = requestBodyObj.id;
        opportunityToUpsert.ExternalVersion__c = Decimal.valueOf(requestBodyObj.version);
        opportunityToUpsert.ExternalTenant__c = requestBodyObj.tenant;
        opportunityToUpsert.Name = accountName.split('_',2)[0];
        opportunityToUpsert.AccountId = accountName.split('_',2)[1];        
        opportunityToUpsert.StageName = 'Formalização';       
        opportunityToUpsert.CloseDate = System.today().addDays(30);                         
        opportunityToUpsert.ExternalCreationDate__c = Date.valueOf(requestBodyObj.createdAt);
        opportunityToUpsert.ExternalUpdatedDate__c = Date.valueOf(requestBodyObj.updateAt);
        opportunityToUpsert.ProductType__c = requestBodyObj.productType;
        opportunityToUpsert.Description = requestBodyObj.purpose;

        opportunityToUpsert.IsExternallySynched__c = true;
        opportunityToUpsert.IsSynchEnabled__c = 'ENABLED';

        if(requestBodyObj.conditions.depositAccount != null){
            opportunityToUpsert.BankCode__c = requestBodyObj.conditions.depositAccount.bankCode;
            opportunityToUpsert.Branch__c = requestBodyObj.conditions.depositAccount.branch;
            opportunityToUpsert.AccountNumber__c = requestBodyObj.conditions.depositAccount.accountNumber;
            opportunityToUpsert.BankAccountType__c = requestBodyObj.conditions.depositAccount.bankAccountType;
        }
              
        try {
            upsert opportunityToUpsert;  
            opportunityId = opportunityToUpsert.Id;  
        } catch (System.DmlException e){
            hasError = true;
            errorMessage = e.getDmlMessage(0);            
            return;
        }      
    }
    public static void upsertQuote(){
        Quote quoteObject = new Quote();
        quoteObject.Id = [SELECT Id FROM Quote WHERE OpportunityId = :opportunityId LIMIT 1]?.Id;

        if(requestBodyObj.conditions.installments != null){
            if(requestBodyObj.conditions.installments.value != null){
                quoteObject.UnitPrice__c = Decimal.valueOf(requestBodyObj.conditions.installments.value.amount);
            }
            quoteObject.InstallmentType__c = requestBodyObj.conditions.installments.type;
            quoteObject.Quantity__c = requestBodyObj.conditions.installments.term;
            quoteObject.ServiceDate__c = Date.valueOf(requestBodyObj.conditions.installments.firstDueDate);
            quoteObject.ServiceLastDate__c = Date.valueOf(requestBodyObj.conditions.installments.lastDueDate);
        }

        if(requestBodyObj.conditions.interest != null){
            quoteObject.MonthlyInterest__c =  Decimal.valueOf(requestBodyObj.conditions.interest.monthly);
            quoteObject.YearlyInterest__c =  Decimal.valueOf(requestBodyObj.conditions.interest.yearly);  
        }

        if(requestBodyObj.conditions.cet != null){
            quoteObject.DailyCet__c = requestBodyObj.conditions.cet.daily;
            quoteObject.MonthlyCet__c = requestBodyObj.conditions.cet.monthly;
            quoteObject.YearlyCet__c = requestBodyObj.conditions.cet.yearly;
        }

        if(requestBodyObj.conditions.parameters != null){
            quoteObject.Term__c = requestBodyObj.conditions.parameters.term;
            quoteObject.UF__c = requestBodyObj.conditions.parameters.uf;
            quoteObject.CreditScore__c = requestBodyObj.conditions.parameters.creditScore;
            quoteObject.GracePeriod__c = requestBodyObj.conditions.parameters.gracePeriod;
            quoteObject.ParameterCalcVersion__c = requestBodyObj.conditions.parameters.calculatorVersion;
            if (requestBodyObj.conditions.parameters.tac != null){
                quoteObject.ParameterTac__c = Decimal.valueOf(requestBodyObj.conditions.parameters.tac.amount);
            } 
            if (requestBodyObj.conditions.parameters.iof != null){
                quoteObject.ParameterIOF__c = Decimal.valueOf(requestBodyObj.conditions.parameters.iof.amount);
            }
            if (requestBodyObj.conditions.parameters.additionalCosts != null){
                quoteObject.ParameterAdditionalCosts__c = Decimal.valueOf(requestBodyObj.conditions.parameters.additionalCosts.amount);
            }
            if(requestBodyObj.conditions.parameters.collateralValue != null){
                quoteObject.CollateralAmount__c = Decimal.valueOf(requestBodyObj.conditions.parameters.collateralValue.amount);
            }
            if(requestBodyObj.conditions.parameters.requestedAmount != null){
                quoteObject.RequestedAmount__c = Decimal.valueOf((requestBodyObj.conditions.parameters.requestedAmount.amount));
            }
        }

        if (requestBodyObj.conditions.parameters.contractDate != null){
            quoteObject.ContractDate__c = Date.valueOf(requestBodyObj.conditions.parameters.contractDate);
        }

        if (requestBodyObj.conditions.limitData != null){
            if (requestBodyObj.conditions.limitData.cetLimit != null){
                quoteObject.LimitCetMinimunc__c = requestBodyObj.conditions.limitData.cetLimit.minimum;
                quoteObject.LimitCetMaximum__c = requestBodyObj.conditions.limitData.cetLimit.maximum;
            }
            if (requestBodyObj.conditions.limitData.interest != null){
                if (requestBodyObj.conditions.limitData.interest.yearlyLimit != null){
                    quoteObject.yearlyLimitMinimunc__c = requestBodyObj.conditions.limitData.interest.yearlyLimit.minimum; 
                    quoteObject.yearlyLimitMaximum__c = requestBodyObj.conditions.limitData.interest.yearlyLimit.maximum;
                }
                if (requestBodyObj.conditions.limitData.interest.monthlyLimit != null){
                    quoteObject.monthlyLimitMinimunc__c = requestBodyObj.conditions.limitData.interest.monthlyLimit.minimum;  
                    quoteObject.monthlyLimitMaximum__c = requestBodyObj.conditions.limitData.interest.monthlyLimit.maximum;
                }
            }      
            if(requestBodyObj.conditions.limitData.total != null){
                quoteObject.LimitTotal__c = requestBodyObj.conditions.limitData.total.amount != null ? Decimal.valueOf(requestBodyObj.conditions.limitData.total.amount) : null;
            }     
            quoteObject.LimitInstallmentType__c = requestBodyObj.conditions.limitData.installmentType;
            quoteObject.LimitDueDate__c = requestBodyObj.conditions.limitData.dueDate != null ? Date.valueOf(requestBodyObj.conditions.limitData.dueDate) : null; 
        } 

        if (requestBodyObj.conditions.monthlyInterestRateComposition != null && !requestBodyObj.conditions.monthlyInterestRateComposition.isEmpty()){
            quoteObject.MonthlyIntRateCompType__c = requestBodyObj.conditions.monthlyInterestRateComposition[0].type;
            quoteObject.MonthlyIntRateCompValue__c = requestBodyObj.conditions.monthlyInterestRateComposition[0].value;
        }

        if (requestBodyObj.conditions.netValues != null){
            quoteObject.NetValue__c = requestBodyObj.conditions.netValues.amount != null ? Decimal.valueOf(requestBodyObj.conditions.netValues.amount) : null;
        }
        quoteObject.OpportunityId = opportunityId; 
        quoteObject.Name = accountName.split('_',2)[0] + ' Quote';
        
    
        try {
            upsert quoteObject;
        } catch (System.DmlException e){
            hasError = true;
            errorMessage = e.getDmlMessage(0);            
            return;
        }        
    }
    
    public static void upsertOpportunityRoles(){
        Set<String> externalPersonIds = new Set<String>();
        for(OpportunityIntegrationVO.cls_participants participant : requestBodyObj.participants)
        {
            externalPersonIds.add(participant.person.id);
        }
        
        Map<String, OpportunityRole__c> externalPersonIdToOpportunityRoleMap = new Map<String, OpportunityRole__c>();
        for (OpportunityRole__c opportunityRole : [SELECT Id, Opportunity__c, ExternalPersonId__c, ExternalPersonId__r.ExternalId__c, Role__c 
                                                   FROM OpportunityRole__c
                                                   WHERE ExternalPersonId__r.ExternalId__c IN :externalPersonIds 
                                                   AND Opportunity__c = :opportunityId])
        {
			externalPersonIdToOpportunityRoleMap.put(opportunityRole.ExternalPersonId__r.ExternalId__c, opportunityRole);                                                  
        }
        
        Map<String, Account> externalPersonIdToAccountMap = new Map<String, Account>();
        for (Account acc : [SELECT Id, ExternalId__c, Name FROM Account WHERE ExternalId__c IN :externalPersonIds])
        {
            externalPersonIdToAccountMap.put(acc.ExternalId__c, acc);
        }

        List<OpportunityRole__c> opportunityRolesToUpsert = new List<OpportunityRole__c>();
        for(OpportunityIntegrationVO.cls_participants participant : requestBodyObj.participants)
        {
            Id oppRoleId = externalPersonIdToOpportunityRoleMap.get(participant.person.id)?.Id;
            Id personId = externalPersonIdToAccountMap.get(participant.person.id)?.Id;
            if (personId == null){
                continue;
            }
            OpportunityRole__c opportunityRoleToUpsert = new OpportunityRole__c
            (         
            	Id = oppRoleId,
            	Role__c = participant.roles[0],                  
            	ExternalPersonId__c = personId,
            	Opportunity__c = opportunityId
            ); 
            
            opportunityRolesToUpsert.add(opportunityRoleToUpsert);
        }

        try {
            upsert opportunityRolesToUpsert;
        } catch (System.DmlException e){
            hasError = true;
            errorMessage = e.getDmlMessage(0);            
            return;
        }      
    }
}