creditas-sf/force-app/main/default/objects/Account/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <label>AdmissionDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/agency__c.field-meta.xml
<CustomField>
    <fullName>agency__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <description>Número da conta do cliente</description>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Nome do banco do cliente.</description>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CivilStatus__c.field-meta.xml
<CustomField>
    <fullName>CivilStatus__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MARRIED</fullName>
                <label>Casado(a)</label>
            </value>
            <value>
                <fullName>SEPARATED</fullName>
                <label>Separado(a)</label>
            </value>
            <value>
                <fullName>SINGLE</fullName>
                <label>Solteiro(a)</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorciado(a)</label>
            </value>
            <value>
                <fullName>WIDOW</fullName>
                <label>Viúvo(a)</label>
            </value>
            <value>
                <fullName>STABLE_UNION</fullName>
                <label>União estável</label>
            </value>
            <value>
                <fullName>NOT_INFORMED</fullName>
                <label>Não informado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CompanyCNPJ__c.field-meta.xml
<CustomField>
    <fullName>CompanyCNPJ__c</fullName>
    <label>CNPJ da empresa</label>
    <length>14</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CompanyName__c.field-meta.xml
<CustomField>
    <fullName>CompanyName__c</fullName>
    <label>Nome da empresa</label>
    <type>TextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CompanyStatus__c.field-meta.xml
<CustomField>
    <fullName>CompanyStatus__c</fullName>
    <description>Status da Empresa</description>
    <label>Status da empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Nome Completo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>FEMALE</fullName>
                <label>Feminino</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <description>Filiação</description>
    <label>Nome da Mãe</label>
    <type>TextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/Addresses__c.object-meta.xml
<CustomObject>
    <description>Objeto para registros dos endereços do cliente/empresa, independente da localidade (Brasil/México).</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Numeração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/AreaLevel1__c.field-meta.xml
<CustomField>
    <fullName>AreaLevel1__c</fullName>
    <description>Esse campo tem contexto diferente de acordo com o país.</description>
    <label>Nível 1</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/AreaLevel2__c.field-meta.xml
<CustomField>
    <fullName>AreaLevel2__c</fullName>
    <description>Esse campo tem contexto diferente de acordo com o país.</description>
    <label>Cidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Complement__c.field-meta.xml
<CustomField>
    <fullName>Complement__c</fullName>
    <label>Complemento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Neighborhood__c.field-meta.xml
<CustomField>
    <fullName>Neighborhood__c</fullName>
    <label>Bairro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Logradouro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Número</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo de endereço a ser inserido</description>
    <inlineHelpText>Insira o tipo do endereço que esse registro se refere</inlineHelpText>
    <label>Tipo de endereço</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>BILLING</fullName>
                <label>Cobrança</label>
            </value>
            <value>
                <fullName>HOME</fullName>
                <label>Residencial</label>
            </value>
            <value>
                <fullName>WORK</fullName>
                <label>Trabalho</label>
            </value>
            <value>
                <fullName>DELIVERY</fullName>
                <label>Correspondência</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outros</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Contato</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Tipo de contato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PERSONAL</fullName>
                <label>Pessoal</label>
            </value>
            <value>
                <fullName>COMERCIAL</fullName>
                <label>Profissional</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Campo usado para registro do numero do documento que está sendo registrado.</description>
    <label>Número do documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de documento que está sendo cadastrado</description>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CURP</fullName>
            </value>
            <value>
                <fullName>PIS</fullName>
            </value>
            <value>
                <fullName>RNE</fullName>
            </value>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>Data de emissão do documento que está sendo registrado</description>
    <label>Data de expedição</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Issuer__c.field-meta.xml
<CustomField>
    <fullName>Issuer__c</fullName>
    <description>Órgão emissor do documento que está sendo registrado</description>
    <label>Órgão Emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/IssuerState__c.field-meta.xml
<CustomField>
    <fullName>IssuerState__c</fullName>
    <description>Estado onde o documento que está sendo cadastrado foi emitido</description>
    <label>Estado emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/CPF.recordType-meta.xml
<RecordType>
    <fullName>CPF</fullName>
    <active>true</active>
    <label>CPF</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/PIS.recordType-meta.xml
<RecordType>
    <fullName>PIS</fullName>
    <active>true</active>
    <label>PIS</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/RG.recordType-meta.xml
<RecordType>
    <fullName>RG</fullName>
    <active>true</active>
    <label>RG</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <formula>TEXT(Account.DocumentType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo do documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/Home.recordType-meta.xml
<RecordType>
    <fullName>Home</fullName>
    <active>true</active>
    <businessProcess>Home - Creditas</businessProcess>
    <label>Home</label>
</RecordType>

creditas-sf/force-app/main/default/classes/formalizationAnalysisService.cls
public with sharing class formalizationAnalysisService {

    public static String  getAccountIdFromOpp(String aOppId){
        return [SELECT AccountId FROM Opportunity WHERE Id = :aOppId]?.AccountId;
    }

    public static Account getAccount(String aAccountId){
        Set<String> lDocumentsRTSet = new Set<String>();
        String lDocumentRGRecordType = Util.getRecordTypeIdbyName('Documents__c', 'RG');
        String lDocumentPISRecordType = Util.getRecordTypeIdbyName('Documents__c', 'PIS');
        String lDocumentCPFRecordType = Util.getRecordTypeIdbyName('Documents__c', 'CPF');
        lDocumentsRTSet.add(lDocumentRGRecordType);
        lDocumentsRTSet.add(lDocumentPISRecordType);
        lDocumentsRTSet.add(lDocumentCPFRecordType);
        Account lAcc = [SELECT FirstName__c, Mother__c, BirthDate__c, Gender__c, DocumentNumber__c, CivilStatus__c, ExternalCreationDate__c, AdmissionDate__c,
                            ExternalUpdatedDate__c, BankName__c, Agency__c, BankAccountNumber__c, CompanyName__c, CompanyCNPJ__c, CompanyStatus__c, Margin__c,
                            (SELECT DocumentNumber__c, Issuer__c, IssuerState__c, IssueDate__c,DocumentType__c FROM Documentos__r WHERE RecordTypeId IN :lDocumentsRTSet),
                            (SELECT PostalCode__c, Street__c, StreetNumber__c,Complement__c,Neighborhood__c, AreaLevel2__c, AreaLevel1__c FROM Enderecos__r WHERE Type__c = 'HOME'),
                            (SELECT Code__c, Channel__c FROM CommunicationContacts__r WHERE Channel__c = 'EMAIL' OR Channel__c = 'SMS')
                            FROM Account 
                            WHERE Id = :aAccountId LIMIT 1];
        return lAcc;
    }

}