creditas-sf/force-app/main/default/objects/Account/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <label>AdmissionDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Juridica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Juridica</fullName>
    <active>true</active>
    <label>Pessoa Jurídica</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <description>Data de admissão do funcionário</description>
    <label>Data de admissão</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta pessoa jurídica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa jurídica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID de identificação interno do colaborador(a)</description>
    <externalId>true</externalId>
    <label>ID do colaborador</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Valor da margem</description>
    <label>Valor da margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/PersonAccount__c.field-meta.xml
<CustomField>
    <fullName>PersonAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta pessoa física</description>
    <label>Conta pessoa física</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa física.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Física</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>PersonAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Valor do salário</description>
    <label>Valor do salário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountEmployeeIntegrationTest.cls
@isTest
private with sharing class AccountEmployeeIntegrationTest {
  private static final String ENDPOINT = '/services/apexrest/Account/Employee/upsertEmployee';

  @isTest
  private static void testCreateEmployee() {
    String json = getJsonPayload();

    Test.startTest();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json);
    RestContext.request = req;
    RestContext.response = res;

    String response = AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    String accountPersonRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
    String accountCompanyRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');

    List<Employee__c> employees = getEmployees();

    System.assertEquals(false, employees.isEmpty(), 'No Employee__c record was created');
    System.assertEquals(1, employees.size(), 'Only 1 Employee__c record should have been created');

    Employee__c employee = employees.get(0);

    System.assertNotEquals(null, employee, 'Employee__c record shouldn\'t be null');
    System.assertEquals(200, res.statusCode, 'Status Code should be 200');
    System.assertEquals('Record created/updated successfully.', response, 'Wrong response');
    System.assertEquals('TEST-EMPLOYEE-001', employee.ExternalId__c, 'Wrong employee External Id');
    System.assertEquals(Date.newInstance(2022, 2, 22), employee.AdmissionDate__c, 'Wrong employee Admission Date');
    System.assertEquals(5555.99, employee.Margin__c, 'Wrong employee Margin');
    System.assertEquals(3333.33, employee.Salary__c, 'Wrong employee Salary');
    System.assertEquals(
      accountPersonRecordTypeId,
      employee.PersonAccount__r.RecordTypeId,
      'Wrong person account Record Type Id'
    );
    System.assertEquals('TEST-PERSON-001', employee.PersonAccount__r.ExternalId__c, 'Wrong person account External Id');
    System.assertEquals(
      accountCompanyRecordTypeId,
      employee.Company__r.RecordTypeId,
      'Wrong company account Record Type Id'
    );
    System.assertEquals('TEST-COMPANY-001', employee.Company__r.ExternalId__c, 'Wrong company account External Id');
  }

  @isTest
  private static void testUpdateEmployee() {
    String accountPersonRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
    String accountCompanyRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');

    insert new List<Account>{
      new Account(Name = 'João da Silva', ExternalId__c = 'TEST-PERSON-001', RecordTypeId = accountPersonRecordTypeId),
      new Account(Name = 'Creditas', ExternalId__c = 'TEST-COMPANY-001', RecordTypeId = accountCompanyRecordTypeId)
    };

    insert new Employee__c(
      Name = 'João da Silva - Creditas',
      ExternalId__c = 'TEST-EMPLOYEE-001',
      PersonAccount__r = new Account(ExternalId__c = 'TEST-PERSON-001'),
      Company__r = new Account(ExternalId__c = 'TEST-COMPANY-001')
    );

    String json = getJsonPayload();

    Test.startTest();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json);
    RestContext.request = req;
    RestContext.response = res;

    String response = AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    List<Employee__c> employees = getEmployees();

    System.assertEquals(false, employees.isEmpty(), 'No Employee__c record was created');
    System.assertEquals(1, employees.size(), 'Only 1 Employee__c record should have been created');

    Employee__c employee = employees.get(0);

    System.assertNotEquals(null, employee, 'Employee__c record shouldn\'t be null');
    System.assertEquals(200, res.statusCode, 'Status Code should be 200');
    System.assertEquals('Record created/updated successfully.', response, 'Wrong response');
    System.assertEquals('João da Silva - Creditas', employee.Name, 'Wrong employee Name');
    System.assertEquals('TEST-EMPLOYEE-001', employee.ExternalId__c, 'Wrong employee External Id');
    System.assertEquals(Date.newInstance(2022, 2, 22), employee.AdmissionDate__c, 'Wrong employee Admission Date');
    System.assertEquals(5555.99, employee.Margin__c, 'Wrong employee Margin');
    System.assertEquals(3333.33, employee.Salary__c, 'Wrong employee Salary');
    System.assertEquals('João da Silva', employee.PersonAccount__r.Name, 'Wrong person account Name');
    System.assertEquals(
      accountPersonRecordTypeId,
      employee.PersonAccount__r.RecordTypeId,
      'Wrong person account Record Type Id'
    );
    System.assertEquals('TEST-PERSON-001', employee.PersonAccount__r.ExternalId__c, 'Wrong person account External Id');
    System.assertEquals('Creditas', employee.Company__r.Name, 'Wrong company account Name');
    System.assertEquals(
      accountCompanyRecordTypeId,
      employee.Company__r.RecordTypeId,
      'Wrong company account Record Type Id'
    );
    System.assertEquals('TEST-COMPANY-001', employee.Company__r.ExternalId__c, 'Wrong company account External Id');
  }

  @isTest
  private static void testExceptions() {
    String json = getJsonPayload();

    Test.startTest();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';

    // test invalid json
    req.requestBody = Blob.valueof(json.replace('"version": 1,', '"version": ,'));
    RestContext.request = req;
    RestContext.response = res;
    String jsonParseError = AccountEmployeeIntegrationController.upsertEmployee();

    // test required fields
    req.requestBody = Blob.valueof(json.replace('"TEST-EMPLOYEE-001"', '" "'));
    RestContext.request = req;
    RestContext.response = res;
    String requiredFieldsError = AccountEmployeeIntegrationController.upsertEmployee();

    // test invalid dateTime
    req.requestBody = Blob.valueof(json.replace('"2022-02-22T09:31:08.615466"', '"-"'));
    RestContext.request = req;
    RestContext.response = res;
    String dateTimeError = AccountEmployeeIntegrationController.upsertEmployee();

    // test invalid date
    req.requestBody = Blob.valueof(json.replace('"2022-02-22"', '"-"'));
    RestContext.request = req;
    RestContext.response = res;
    String dateError = AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    System.assertEquals(400, res.statusCode, 'Status Code should be 400');

    List<Employee__c> employees = getEmployees();

    System.assert(employees.isEmpty(), 'No Employee__c record should exist');
    System.assert(jsonParseError.startsWith('Error: JSON parse failed'), 'Wrong response');
    System.assert(requiredFieldsError.startsWith('Error: required field(s) missing'), 'Wrong response');
    System.assert(dateTimeError.startsWith('Error: couldn\'t parse dateTime string'), 'Wrong response');
    System.assert(dateError.startsWith('Error: couldn\'t parse date string'), 'Wrong response');
  }

  private static List<Employee__c> getEmployees() {
    return [
      SELECT
        Name,
        AdmissionDate__c,
        Margin__c,
        Salary__c,
        ExternalId__c,
        PersonAccount__r.Name,
        PersonAccount__r.RecordTypeId,
        PersonAccount__r.ExternalId__c,
        Company__r.Name,
        Company__r.RecordTypeId,
        Company__r.ExternalId__c
      FROM Employee__c
    ];
  }

  private static String getJsonPayload() {
    return '{' +
      '  "version": 1,' +
      '  "createdAt": "2022-02-22T09:31:08.615466",' +
      '  "updatedAt": "2022-02-22T09:31:08.615466",' +
      '  "employeeCode": "5856",' +
      '  "companyId": "TEST-COMPANY-001",' +
      '  "employeeType": "STANDARD_CONTRACT",' +
      '  "personId": "TEST-PERSON-001",' +
      '  "personVersion": "1",' +
      '  "id": "TEST-EMPLOYEE-001",' +
      '  "mainDocument": {' +
      '    "code": "45106105803",' +
      '    "type": "CPF"' +
      '  },' +
      '  "tenant": "creditasbr",' +
      '  "status": "ACTIVE",' +
      '  "admissionDate": "2022-02-22",' +
      '  "margin": {' +
      '    "amount": 5555.99,' +
      '    "currency": "BRL"' +
      '  },' +
      '  "salary": {' +
      '    "amount": 3333.33,' +
      '    "currency": "BRL"' +
      '  }' +
      '}';
  }
}