creditas-sf/force-app/main/default/objects/Account/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <label>AdmissionDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Juridica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Juridica</fullName>
    <active>true</active>
    <label>Pessoa Jurídica</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <description>Data de admissão do funcionário</description>
    <label>Data de admissão</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta pessoa jurídica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa jurídica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID de identificação interno do colaborador(a)</description>
    <externalId>true</externalId>
    <label>ID do colaborador</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Valor da margem</description>
    <label>Valor da margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/PersonAccount__c.field-meta.xml
<CustomField>
    <fullName>PersonAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta pessoa física</description>
    <label>Conta pessoa física</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa física.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Física</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>PersonAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Valor do salário</description>
    <label>Valor do salário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountEmployeeIntegrationServiceTest.cls
@istest
private class AccountEmployeeIntegrationServiceTest {
  private static final String ENDPOINT = '/services/apexrest/Account/Employee/upsertEmployee';

  @IsTest
  private static void testInsertEmployeeSuccess() {
    String json = getJsonPayload();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json);
    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();

    AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    List<Employee__c> employees = getEmployees();
    Map<Id, Account> accountsById = new Map<Id, Account>(getAccounts());

    System.assertEquals(1, employees.size(), '1 employee record should have been created');
    System.assertEquals(2, accountsById.size(), '2 account records should have been created');
    System.assert(accountsById.containsKey(employees.get(0).PersonAccount__c), 'Person account not created');
    System.assert(accountsById.containsKey(employees.get(0).Company__c), 'Company account not created');
  }

  @IsTest
  private static void testInsertEmployeeFail() {
    String json = getJsonPayload();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json.replace('"2022-02-22"', '"-"'));
    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();

    AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    List<Employee__c> employees = getEmployees();
    List<Account> accounts = getAccounts();

    System.assertEquals(0, employees.size(), 'No employee record should\'ve been created');
    System.assertEquals(0, accounts.size(), 'No account record should\'ve been created');
  }

  @IsTest
  private static void testUpdateEmployeeSuccess() {
    String accountPersonRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
    String accountCompanyRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');

    insert new List<Account>{
      new Account(Name = 'João da Silva', ExternalId__c = 'TEST-PERSON-001', RecordTypeId = accountPersonRecordTypeId),
      new Account(Name = 'Creditas', ExternalId__c = 'TEST-COMPANY-001', RecordTypeId = accountCompanyRecordTypeId)
    };

    insert new Employee__c(
      Name = 'João da Silva - Creditas',
      ExternalId__c = 'TEST-EMPLOYEE-001',
      PersonAccount__r = new Account(ExternalId__c = 'TEST-PERSON-001'),
      Company__r = new Account(ExternalId__c = 'TEST-COMPANY-001')
    );

    String json = getJsonPayload();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json);
    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();

    AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    Employee__c employee = getEmployees().get(0);

    System.assertEquals('João da Silva - Creditas', employee.Name, 'Wrong employee Name');
    System.assertEquals(Date.newInstance(2022, 2, 22), employee.AdmissionDate__c, 'Wrong employee Admission Date');
    System.assertEquals(5555.99, employee.Margin__c, 'Wrong employee Margin');
    System.assertEquals(3333.33, employee.Salary__c, 'Wrong employee Salary');
    System.assertEquals('João da Silva', employee.PersonAccount__r.Name, 'Wrong person account Name');
    System.assertEquals('Creditas', employee.Company__r.Name, 'Wrong company account Name');
  }

  @IsTest
  private static void testUpdateEmployeeFail() {
    String accountPersonRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
    String accountCompanyRecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');

    insert new List<Account>{
      new Account(Name = 'João da Silva', ExternalId__c = 'TEST-PERSON-001', RecordTypeId = accountPersonRecordTypeId),
      new Account(Name = 'Creditas', ExternalId__c = 'TEST-COMPANY-001', RecordTypeId = accountCompanyRecordTypeId)
    };

    insert new Employee__c(
      Name = 'João da Silva - Creditas',
      ExternalId__c = 'TEST-EMPLOYEE-001',
      PersonAccount__r = new Account(ExternalId__c = 'TEST-PERSON-001'),
      Company__r = new Account(ExternalId__c = 'TEST-COMPANY-001')
    );

    String json = getJsonPayload();

    RestRequest req = new RestRequest();
    RestResponse res = new RestResponse();
    req.requestURI = ENDPOINT;
    req.httpMethod = 'POST';
    req.requestBody = Blob.valueof(json.replace('"2022-02-22"', '"-"'));
    RestContext.request = req;
    RestContext.response = res;

    Test.startTest();

    AccountEmployeeIntegrationController.upsertEmployee();

    Test.stopTest();

    Employee__c employee = getEmployees().get(0);

    System.assertNotEquals(
      Date.newInstance(2022, 2, 22),
      employee.AdmissionDate__c,
      'Employee Admission Date shouldn\'t have been updated'
    );
    System.assertNotEquals(5555.99, employee.Margin__c, 'Employee Margin shouldn\'t have been updated');
    System.assertNotEquals(3333.33, employee.Salary__c, 'Employee Salary shouldn\'t have been updated');
  }

  private static List<Employee__c> getEmployees() {
    return [
      SELECT
        Name,
        AdmissionDate__c,
        Margin__c,
        Salary__c,
        ExternalId__c,
        PersonAccount__c,
        PersonAccount__r.Name,
        Company__c,
        Company__r.Name
      FROM Employee__c
    ];
  }

  private static List<Account> getAccounts() {
    return [SELECT Id FROM Account];
  }

  private static String getJsonPayload() {
    return '{' +
      '  "version": 1,' +
      '  "createdAt": "2022-02-22T09:31:08.615466",' +
      '  "updatedAt": "2022-02-22T09:31:08.615466",' +
      '  "employeeCode": "5856",' +
      '  "companyId": "TEST-COMPANY-001",' +
      '  "employeeType": "STANDARD_CONTRACT",' +
      '  "personId": "TEST-PERSON-001",' +
      '  "personVersion": "1",' +
      '  "id": "TEST-EMPLOYEE-001",' +
      '  "mainDocument": {' +
      '    "code": "45106105803",' +
      '    "type": "CPF"' +
      '  },' +
      '  "tenant": "creditasbr",' +
      '  "status": "ACTIVE",' +
      '  "admissionDate": "2022-02-22",' +
      '  "margin": {' +
      '    "amount": 5555.99,' +
      '    "currency": "BRL"' +
      '  },' +
      '  "salary": {' +
      '    "amount": 3333.33,' +
      '    "currency": "BRL"' +
      '  }' +
      '}';
  }
}