creditas-sf/force-app/main/default/objects/Account/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <label>AdmissionDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/EmployeeId__c.field-meta.xml
<CustomField>
    <fullName>EmployeeId__c</fullName>
    <externalId>true</externalId>
    <label>EmployeeId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/EmployeeStatus__c.field-meta.xml
<CustomField>
    <fullName>EmployeeStatus__c</fullName>
    <label>EmployeeStatus</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>ON_LEAVE</fullName>
            </value>
            <value>
                <fullName>FIRED</fullName>
            </value>
            <value>
                <fullName>RETIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/EmployeeType__c.field-meta.xml
<CustomField>
    <fullName>EmployeeType__c</fullName>
    <description>Tipo de contrato de trabalho</description>
    <label>Tipo de contrato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD_CONTRACT</fullName>
            </value>
            <value>
                <fullName>LEGAL_PERSON</fullName>
            </value>
            <value>
                <fullName>FREELANCER</fullName>
            </value>
            <value>
                <fullName>HOURLY_WAGE</fullName>
            </value>
            <value>
                <fullName>INTERN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCompanyId__c.field-meta.xml
<CustomField>
    <fullName>ExternalCompanyId__c</fullName>
    <description>ID de identificação interno da empresa</description>
    <externalId>true</externalId>
    <label>ID da empresa</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalEmployeeVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalEmployeeVersion__c</fullName>
    <label>ExternalEmployeeVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountEmployeeIntegration.cls
@RestResource(urlMapping='/Account/*')
global with sharing class AccountEmployeeIntegration {
    
    @HttpPost
    global static String updateEmployee(){
        RestRequest req = RestContext.request;
        RestResponse res = RestContext.response;
        List<Account> acc = new List<Account>();
        AccountEmployeeIntegrationVO request = (AccountEmployeeIntegrationVO) System.JSON.deserialize(req.requestBody.toString(), AccountEmployeeIntegrationVO.class);
        if(request.personId != ''){
            acc = [SELECT AdmissionDate__c, 
                          EmployeeId__c, 
                          EmployeeStatus__c,
                          EmployeeType__c,
                          ExternalCompanyId__c, 
                          ExternalEmployeeVersion__c, 
                          ExternalId__c, 
                          ExternalTenant__c, 
                          Margin__c, 
                          Salary__c, 
                          Type,
                          ExternalVersion__c 
                    FROM Account 
                    WHERE ExternalId__c =: request.personId];
        } 
        else {
            res.statusCode = 400;
            return 'PersonId invalido.';
        }
        
        if(!acc.isEmpty()){
            String admissionDate = request.admissionDate;

            list<String> lstSplitDate = admissionDate.split('-');
            Date admissionDateFormatted = date.newinstance(Integer.valueOf(lstSplitDate[0]), Integer.valueOf(lstSplitDate[1]), Integer.valueOf(lstSplitDate[2]));
            
            acc[0].AdmissionDate__c           = admissionDateFormatted;
            acc[0].EmployeeId__c              = request.id;
            acc[0].EmployeeStatus__c          = request.status;
            acc[0].EmployeeType__c            = request.employeeType;
            acc[0].ExternalCompanyId__c       = request.companyId;
            acc[0].ExternalEmployeeVersion__c = decimal.valueOf(request.personVersion);
            acc[0].ExternalId__c              = request.personId;
            acc[0].ExternalTenant__c          = request.tenant;
            acc[0].Margin__c                  = request.margin.amount;
            acc[0].Salary__c                  = request.salary.amount;
            acc[0].ExternalVersion__c         = decimal.valueOf(request.version);

            update acc;
        } 
        else {
            res.statusCode = 400;
            return 'Conta com personId ' + request.personId + ' não encontrada.';
        }
        res.statusCode = 200;
        return 'Registro atualizado com sucesso!';
    }
}