creditas-sf/force-app/main/default/objects/Account/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <label>AdmissionDate</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <label>Margin</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <label>Salario</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/AdmissionDate__c.field-meta.xml
<CustomField>
    <fullName>AdmissionDate__c</fullName>
    <description>Data de admissão do funcionário</description>
    <label>Data de admissão</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Company__c.field-meta.xml
<CustomField>
    <fullName>Company__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta pessoa jurídica</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa jurídica.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Jurídica</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>Company</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <caseSensitive>true</caseSensitive>
    <description>ID de identificação interno do colaborador(a)</description>
    <externalId>true</externalId>
    <label>ID do colaborador</label>
    <length>100</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo representa a região da conta (Região de origem do registro - br/mx)</description>
    <label>Tenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Versão do Person ID vinculado</description>
    <label>Versão de person</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Margin__c.field-meta.xml
<CustomField>
    <fullName>Margin__c</fullName>
    <description>Valor da margem</description>
    <label>Valor da margem</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/PersonAccount__c.field-meta.xml
<CustomField>
    <fullName>PersonAccount__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <description>Conta pessoa física</description>
    <label>Conta pessoa física</label>
    <lookupFilter>
        <active>true</active>
        <errorMessage>Preencha a conta pessoa física.</errorMessage>
        <filterItems>
            <field>Account.RecordTypeId</field>
            <operation>equals</operation>
            <value>Pessoa Física</value>
        </filterItems>
        <isOptional>false</isOptional>
    </lookupFilter>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Colaboradores</relationshipLabel>
    <relationshipName>PersonAccount</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Salary__c.field-meta.xml
<CustomField>
    <fullName>Salary__c</fullName>
    <description>Valor do salário</description>
    <label>Valor do salário</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <description>Situação do vinculo empregatício e de importação</description>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PENDING</fullName>
            </value>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>ON_LEAVE</fullName>
            </value>
            <value>
                <fullName>FIRED</fullName>
            </value>
            <value>
                <fullName>RETIRED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo de contrato de trabalho</description>
    <label>Tipo de contrato</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STANDARD_CONTRACT</fullName>
                <default>true</default>
                <label>STANDARD_CONTRACT</label>
            </value>
            <value>
                <fullName>LEGAL_PERSON</fullName>
            </value>
            <value>
                <fullName>FREELANCER</fullName>
            </value>
            <value>
                <fullName>HOURLY_WAGE</fullName>
            </value>
            <value>
                <fullName>INTERN</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountEmployeeIntegrationService.cls
public with sharing class AccountEmployeeIntegrationService {
  public class AccountEmployeeIntegrationException extends Exception {
  }

  public class AccountNotFoundException extends Exception {
  }

  RestRequest request;
  AccountEmployeeIntegrationVO requestBodyObject;
  Integer statusCode;
  String message;

  String companyExternalId {
    get {
      return this.requestBodyObject.companyId;
    }
  }
  String personExternalId {
    get {
      return this.requestBodyObject.personId;
    }
  }
  String employeeExternalId {
    get {
      return this.requestBodyObject.id;
    }
  }

  public AccountEmployeeIntegrationService(RestRequest request) {
    this.request = request;
  }

  public void processRequest() {
    try {
      this.parseBody();
      this.checkRequiredFields();
      this.checkAccounts();
      this.upsertEmployee();
      this.setStatusAndMessage(200, 'Record created/updated successfully.');
    } catch (AccountEmployeeIntegrationException e) {
      this.setStatusAndMessage(400, e.getMessage());
    } catch (AccountNotFoundException e) {
      this.setStatusAndMessage(500, e.getMessage());
    } catch (Exception e) {
      this.setStatusAndMessage(400, 'Error: couldn\'t process request.');
    }
  }

  public Integer getStatusCode() {
    return this.statusCode;
  }

  public String getMessage() {
    return this.message;
  }

  private void setStatusAndMessage(Integer code, String message) {
    this.statusCode = code;
    this.message = message;
  }

  private void parseBody() {
    try {
      this.requestBodyObject = (AccountEmployeeIntegrationVO) System.JSON.deserialize(
        this.request.requestBody.toString(),
        AccountEmployeeIntegrationVO.class
      );
    } catch (Exception e) {
      throw new AccountEmployeeIntegrationException('Error: JSON parse failed.', e);
    }
  }

  private void checkRequiredFields() {
    for (String id : new List<String>{ this.companyExternalId, this.personExternalId, this.employeeExternalId }) {
      if (String.isBlank(id)) {
        throw new AccountEmployeeIntegrationException('Error: required field(s) missing (companyId, personId or id)');
      }
    }
  }

  private void upsertEmployee() {
    String employeeName = getEmployeeNameByExternalId(this.employeeExternalId);
    if (String.isBlank(employeeName)) {
      employeeName = this.employeeExternalId;
    }

    Employee__c employee = new Employee__c(
      Name = employeeName,
      PersonAccount__r = new Account(ExternalId__c = this.personExternalId),
      Company__r = new Account(ExternalId__c = this.companyExternalId),
      Type__c = this.requestBodyObject.employeeType,
      Status__c = this.requestBodyObject.status,
      AdmissionDate__c = this.getParsedDate(this.requestBodyObject.admissionDate),
      Margin__c = this.requestBodyObject.margin.amount,
      Salary__c = this.requestBodyObject.salary.amount,
      ExternalId__c = this.employeeExternalId,
      ExternalVersion__c = Decimal.valueOf(this.requestBodyObject.version),
      ExternalTenant__c = this.requestBodyObject.tenant
    );

    try {
      upsert employee ExternalId__c;
    } catch (Exception e) {
      throw new AccountEmployeeIntegrationException('Error: Employee record creation/update failed.', e);
    }
  }

  private void checkAccounts() {
    Map<String, Boolean> statusByAccountExternalId = new Map<String, Boolean>{
      this.personExternalId => false,
      this.companyExternalId => false
    };

    for (Account account : this.getAccountsByExternalIds(statusByAccountExternalId.keySet())) {
      statusByAccountExternalId.put(account.ExternalId__c, true);
    }

    if (!statusByAccountExternalId.get(this.personExternalId)) {
      throw new AccountNotFoundException('Error: account record not found for the provided personId.');
    }

    if (!statusByAccountExternalId.get(this.companyExternalId)) {
      throw new AccountNotFoundException('Error: account record not found for the provided companyId.');
    }
  }

  private List<Account> getAccountsByExternalIds(Set<String> externalIds) {
    return [SELECT ExternalId__c FROM Account WHERE ExternalId__c IN :externalIds];
  }

  private String getEmployeeNameByExternalId(String externalId) {
    return [SELECT Name FROM Employee__c WHERE ExternalId__c = :externalId]?.Name;
  }

  private Date getParsedDate(String dateString) {
    if (String.isBlank(dateString)) {
      return null;
    }

    try {
      list<String> dateParts = dateString.split('-');

      return date.newinstance(
        Integer.valueOf(dateParts[0]),
        Integer.valueOf(dateParts[1]),
        Integer.valueOf(dateParts[2])
      );
    } catch (Exception e) {
      throw new AccountEmployeeIntegrationException('Error: couldn\'t parse date string: ' + dateString + '.', e);
    }
  }
}