creditas-sf/force-app/main/default/objects/Account/fields/agency__c.field-meta.xml
<CustomField>
    <fullName>agency__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <description>Número da conta do cliente</description>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Nome do banco do cliente.</description>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Birth_City__c</fullName>
    <label>Birth City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <description>Filiação</description>
    <label>Nome do Pai</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <description>Filiação</description>
    <label>Nome da Mãe</label>
    <type>TextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthLowerLimit__c</fullName>
    <label>Patrimônio líquido mínimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthUpperLimit__c</fullName>
    <label>NetWorthUpperLimit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/Addresses__c.object-meta.xml
<CustomObject>
    <description>Objeto para registros dos endereços do cliente/empresa, independente da localidade (Brasil/México).</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Numeração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Esse campo determina o qual a conta que está relacionada ao endereço cadastrado.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/AreaLevel2__c.field-meta.xml
<CustomField>
    <fullName>AreaLevel2__c</fullName>
    <description>Esse campo tem contexto diferente de acordo com o país.</description>
    <label>Cidade</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Country__c.field-meta.xml
<CustomField>
    <fullName>Country__c</fullName>
    <description>País referente ao endereço que está sendo cadastrado</description>
    <inlineHelpText>País referente ao endereço que está sendo cadastrado</inlineHelpText>
    <label>País</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Street__c.field-meta.xml
<CustomField>
    <fullName>Street__c</fullName>
    <label>Logradouro</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/StreetNumber__c.field-meta.xml
<CustomField>
    <fullName>StreetNumber__c</fullName>
    <label>Número</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>CommunicationContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Contato</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Campo usado para registro do numero do documento que está sendo registrado.</description>
    <label>Número do documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Issuer__c.field-meta.xml
<CustomField>
    <fullName>Issuer__c</fullName>
    <description>Órgão emissor do documento que está sendo registrado</description>
    <label>Órgão Emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/IssuerState__c.field-meta.xml
<CustomField>
    <fullName>IssuerState__c</fullName>
    <description>Estado onde o documento que está sendo cadastrado foi emitido</description>
    <label>Estado emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/RG.recordType-meta.xml
<RecordType>
    <fullName>RG</fullName>
    <active>true</active>
    <label>RG</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Outros.recordType-meta.xml
<RecordType>
    <fullName>Outros</fullName>
    <active>true</active>
    <label>Outros</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/MinimalRequiredIncome__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncome__c</fullName>
    <label>Renda Mínima</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalServiceTest.cls
@isTest
public with sharing class ProposalServiceTest {

    @TestSetup
    static void makeData()
    {
        Account accCustomer               = TestSetup.getAccount('Nivaele', false);
        accCustomer.Birth_City__c         = 'Monte Caramelo';
        accCustomer.Mother__c             = 'Juzimara da Silva';
        accCustomer.Father__c             = 'Josialdo Ferreira';
        accCustomer.NetWorthLowerLimit__c = 20000;
        accCustomer.NetWorthUpperLimit__c = 30000;
        accCustomer.DocumentNumber__c     = '51479566039';
        accCustomer.BankName__c           = 'Itausa';
        accCustomer.Agency__c             = '00001'; 
        accCustomer.BankAccountNumber__c  = '01020304';
        accCustomer.RecordTypeId          = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
        insert accCustomer;

        Account accRole              = TestSetup.getAccount('Account_Role', false);
        accRole.DocumentNumber__c    = '12047477000101';
        accRole.BankName__c          = 'test bank collateral guarantor';
        accRole.Agency__c            = '12345'; 
        accRole.BankAccountNumber__c = '0123456'; 
        accRole.RecordTypeId         = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
        insert accRole;

        Documents__c rg = new Documents__c();
        rg.Account__c = accCustomer.Id;
        rg.DocumentNumber__c = '4242344';
        rg.IssuerState__c = 'SP';
        rg.Issuer__c = 'SSP';
        insert rg;

        CommunicationContacts__c email = new CommunicationContacts__c();
        email.Account__c = accCustomer.Id;
        email.Channel__c = 'EMAIL';
        email.Code__c = 'nivaele@ig.com.br';
        insert email;

        Addresses__c address = new Addresses__c();
        address.Account__c = accCustomer.Id;
        address.Street__c = 'Rua Itapetininga';
        address.StreetNumber__c  = '45';
        address.Country__c = 'Brasil';
        address.AreaLevel2__c = 'Sao Jao Del Rei';
        insert address;

        Opportunity opportunity              = new Opportunity();
        opportunity.AccountId                = accCustomer.Id;
        opportunity.MinimalRequiredIncome__c = 3000;
        opportunity.Name                     = 'Formalizacao Autofin';
        opportunity.StageName                = 'Em Análise de Formalização';
        opportunity.CloseDate                = Date.today().addDays(10);
        opportunity.ExternalTenant__c        = 'creditasbr';
        opportunity.ExternalVersion__c       = 1;      
        opportunity.RecordTypeId             = Util.getRecordTypeIdbyName('Opportunity', 'AutoFin');
        insert opportunity;

        ProfessionalInfo__c professionalInfo = new ProfessionalInfo__c();
        professionalInfo.Account__c          = accCustomer.Id;
        professionalInfo.Status__c           = 'CLT';
        professionalInfo.JobTitle__c         = 'Engenheiro';
        insert professionalInfo;

        OpportunityRole__c oppRoleGuarantor = TestSetup.getOppRole(accRole, opportunity, 'COLLATERAL_GUARANTOR', false, true); 
        OpportunityRole__c oppRolePrincipal = TestSetup.getOppRole(accCustomer, opportunity, 'PRINCIPAL', true, true);   

        FinancialResources__c finResource = FinancialResourceSetup.createFinancialResource('Auto');
        finResource.ManufacturingYear__c = '2022';
        finResource.Amount__c = 10000;
        finResource.Type__c = 'CAR';
        insert finResource;

        FinancialResources__c monthlyIncome = new FinancialResources__c();
        monthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        monthlyIncome.Type__c               = 'MONTHLY_INCOME';
        monthlyIncome.Amount__c             = 5000;
        insert monthlyIncome;

        FinancialResources__c confirmedMonthlyIncome = new FinancialResources__c();
        confirmedMonthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        confirmedMonthlyIncome.Type__c               = 'CONFIRMED_MONTHLY_INCOME';
        confirmedMonthlyIncome.Amount__c             = 4500;
        insert confirmedMonthlyIncome;

        FinancialResources__c presumedMonthlyIncome = new FinancialResources__c();
        presumedMonthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        presumedMonthlyIncome.Type__c               = 'PRESUMED_MONTHLY_INCOME';
        presumedMonthlyIncome.Amount__c             = 4800;
        insert presumedMonthlyIncome;

        AccountFinancialRelationship__c accFinRel1 = new AccountFinancialRelationship__c();
        accFinRel1.Account__c                      = accCustomer.Id;
        accFinRel1.Recurso_Financeiro__c           = monthlyIncome.Id;
        insert accFinRel1;

        AccountFinancialRelationship__c accFinRel2 = new AccountFinancialRelationship__c();
        accFinRel2.Account__c                      = accCustomer.Id;
        accFinRel2.Recurso_Financeiro__c           = presumedMonthlyIncome.Id;
        insert accFinRel2;

        AccountFinancialRelationship__c accFinRel3 = new AccountFinancialRelationship__c();
        accFinRel3.Account__c                      = accCustomer.Id;
        accFinRel3.Recurso_Financeiro__c           = confirmedMonthlyIncome.Id;
        insert accFinRel3;

        Garantias__c guarantee = new Garantias__c(Account__c = accRole.Id, Opportunity__c = opportunity.Id, Recurso_Financeiro__c = finResource.Id);
        insert guarantee;

        Quote quote         = new Quote();
        quote.Name          = 'Teste';
        quote.OpportunityId = opportunity.Id;
        quote.UnitPrice__c  = 100;
        quote.Quantity__c   = 20;
        insert quote;

        List<SObject> sectionsObjects = new List<SObject>();

        PersonalDataSection__c personalDataSection  = new PersonalDataSection__c(Opportunity__c = opportunity.Id);
        ContactDetailsSection__c contactDataSection = new ContactDetailsSection__c(Opportunity__c = opportunity.Id);
        AddressDataSection__c addressDataSection    = new AddressDataSection__c(Opportunity__c = opportunity.Id);
        WarrantyDataSection__c warrantyDataSection  = new WarrantyDataSection__c(Opportunity__c = opportunity.Id);
        IncomeDataSection__c incomeDataSection      = new IncomeDataSection__c(Opportunity__c = opportunity.Id);
        OperationSection__c operationDataSection    = new OperationSection__c(Opportunity__c = opportunity.Id);

        sectionsObjects.add(personalDataSection);
        sectionsObjects.add(contactDataSection);
        sectionsObjects.add(addressDataSection);
        sectionsObjects.add(warrantyDataSection);
        sectionsObjects.add(incomeDataSection);
        sectionsObjects.add(operationDataSection);

        insert sectionsObjects;
    }

    @isTest
    public static void copyInfoSuccess()
    {
        Account acc                           = [SELECT Id, Name, BirthCity__c, Mother__c, Father__c FROM Account WHERE Name = 'Nivaele' LIMIT 1];
        Opportunity opp                       = [SELECT Id FROM Opportunity WHERE AccountId = :acc.Id LIMIT 1];
        Quote quote                           = [SELECT Id, Quantity__c FROM Quote LIMIT 1];
        Documents__c rg                       = [SELECT Id, DocumentNumber__c, IssuerState__c, Issuer__c FROM Documents__c];
        CommunicationContacts__c email        = [SELECT Id, Code__c FROM CommunicationContacts__c LIMIT 1];
        Addresses__c address                  = [SELECT Id, Street__c, StreetNumber__c, Country__c, AreaLevel2__c FROM Addresses__c LIMIT 1];
        FinancialResources__c monthlyIncome   = [SELECT Id, Type__c, Amount__c FROM FinancialResources__c WHERE Type__c = 'MONTHLY_INCOME' LIMIT 1];
        FinancialResources__c presumedIncome  = [SELECT Id, Type__c, Amount__c FROM FinancialResources__c WHERE Type__c = 'PRESUMED_MONTHLY_INCOME' LIMIT 1];
        FinancialResources__c confirmedIncome = [SELECT Id, Type__c, Amount__c FROM FinancialResources__c WHERE Type__c = 'CONFIRMED_MONTHLY_INCOME' LIMIT 1];
        ProfessionalInfo__c professionalInfo  = [SELECT Id, Status__c, JobTitle__c FROM ProfessionalInfo__c LIMIT 1];
        
        Test.startTest();
        ProposalService.start(acc.Id, opp.Id);
        Test.stopTest();
        
        PersonalDataSection__c personalDataSection  = [SELECT Id, Name__c, BirthCity__c,Mother__c, Father__c, RG__c, Issuer__c, IssuerState__c FROM  PersonalDataSection__c LIMIT 1];
        ContactDetailsSection__c contactDataSection = [SELECT Id, Email__c FROM ContactDetailsSection__c];
        AddressDataSection__c addressDataSection    = [SELECT Id, StreetNumber__c, Country__c, AreaLevel2__c, Street__c  FROM AddressDataSection__c];
        WarrantyDataSection__c warrantyDataSection  = [SELECT Id FROM WarrantyDataSection__c];
        IncomeDataSection__c incomeDataSection      = [SELECT Id, JobTitle__c, Status__c, MonthlyIncome__c, PresumedMonthlyIncome__c, ConfirmedMonthlyIncome__c  FROM IncomeDataSection__c LIMIT 1];
        OperationSection__c operationDataSection    = [SELECT Id, Quantity__c  FROM OperationSection__c];

        System.assertEquals(acc.Name, personalDataSection.Name__c,'Field value should have been the same');
        System.assertEquals(acc.Father__c, personalDataSection.Father__c,'Field value should have been the same');
        System.assertEquals(acc.Mother__c, personalDataSection.Mother__c,'Field value should have been the same');
        System.assertEquals(acc.BirthCity__c, personalDataSection.BirthCity__c,'Field value should have been the same');
        
        System.assertEquals(email.Code__c, contactDataSection.Email__c, 'Field value should have been the same');
        
        System.assertEquals(address.StreetNumber__c, addressDataSection.StreetNumber__c, 'Field value should have been the same');
        System.assertEquals(address.Country__c, addressDataSection.Country__c, 'Field value should have been the same');
        System.assertEquals(address.AreaLevel2__c, addressDataSection.AreaLevel2__c, 'Field value should have been the same');
        System.assertEquals(address.Street__c, addressDataSection.Street__c, 'Field value should have been the same');
        
        System.assertEquals(professionalInfo.JobTitle__c, incomeDataSection.JobTitle__c, 'Field value should have been the same');
        System.assertEquals(professionalInfo.Status__c, incomeDataSection.Status__c, 'Field value should have been the same');
        System.assertEquals(monthlyIncome.Amount__c, incomeDataSection.MonthlyIncome__c, 'Field value should have been the same');
        System.assertEquals(presumedIncome.Amount__c, incomeDataSection.PresumedMonthlyIncome__c, 'Field value should have been the same');
        System.assertEquals(confirmedIncome.Amount__c, incomeDataSection.ConfirmedMonthlyIncome__c, 'Field value should have been the same');
        
        System.assertEquals(quote.Quantity__c, operationDataSection.Quantity__c, 'Field value should have been the same');
    }

    @isTest
    public static void createSectionsSuccess() 
    {
        Account acc       = [SELECT Id, Name, BirthCity__c, Mother__c, Father__c FROM Account WHERE Name = 'Nivaele' LIMIT 1];
        Opportunity opp   = [SELECT Id FROM Opportunity WHERE AccountId = :acc.Id LIMIT 1];

        List<SObject> sections = new List<SObject>();

        PersonalDataSection__c personalDataSection  = new PersonalDataSection__c(Opportunity__c = opp.Id);
        ContactDetailsSection__c contactDataSection = new ContactDetailsSection__c(Opportunity__c = opp.Id);
        AddressDataSection__c addressDataSection    = new AddressDataSection__c(Opportunity__c = opp.Id);
        WarrantyDataSection__c warrantyDataSection  = new WarrantyDataSection__c(Opportunity__c = opp.Id);
        IncomeDataSection__c incomeDataSection      = new IncomeDataSection__c(Opportunity__c = opp.Id);
        OperationSection__c operationDataSection    = new OperationSection__c(Opportunity__c = opp.Id);

        sections.add(personalDataSection);
        sections.add(contactDataSection);
        sections.add(addressDataSection);
        sections.add(warrantyDataSection);
        sections.add(incomeDataSection);
        sections.add(operationDataSection);
        
        insert sections;

        Test.startTest();
        ProposalService.start(acc.Id, opp.Id);
        Test.stopTest();
        
        List<PersonalDataSection__c> updatedPersonalDataSection  = [SELECT Id, Name__c, BirthCity__c,Mother__c, Father__c, RG__c, Issuer__c, IssuerState__c FROM  PersonalDataSection__c];
        List<ContactDetailsSection__c> updatedContactDataSection = [SELECT Id, Email__c FROM ContactDetailsSection__c];
        List<AddressDataSection__c> updatedAddressDataSection    = [SELECT Id, StreetNumber__c, Country__c, AreaLevel2__c, Street__c  FROM AddressDataSection__c];
        List<WarrantyDataSection__c> updatedWarrantyDataSection  = [SELECT Id FROM WarrantyDataSection__c];
        List<IncomeDataSection__c> updatedIncomeDataSection      = [SELECT Id, JobTitle__c, Status__c, MonthlyIncome__c, PresumedMonthlyIncome__c, ConfirmedMonthlyIncome__c  FROM IncomeDataSection__c];
        List<OperationSection__c> updatedOperationDataSection    = [SELECT Id, Quantity__c  FROM OperationSection__c];

        System.assertEquals(2, updatedPersonalDataSection.size(), 'Expected twice the records of sections.');
        System.assertEquals(2, updatedContactDataSection.size(), 'Expected twice the records of sections.');
        System.assertEquals(2, updatedAddressDataSection.size(), 'Expected twice the records of sections.');
        System.assertEquals(2, updatedWarrantyDataSection.size(), 'Expected twice the records of sections.');
        System.assertEquals(2, updatedIncomeDataSection.size(), 'Expected twice the records of sections.');
        System.assertEquals(2, updatedOperationDataSection.size(), 'Expected twice the records of sections.');
    }

    @isTest
    public static void cloneFail()
    {
        Exception testException;
        Account acc       = [SELECT Id, Name, BirthCity__c, Mother__c, Father__c FROM Account WHERE Name = 'Account_Role' LIMIT 1];
        Opportunity opp   = [SELECT Id FROM Opportunity LIMIT 1];
        
        Test.startTest();
        try {
            ProposalService.start(opp.Id, acc.Id);
        } catch(Exception e) {
            testException = e;
        }
        Test.stopTest();

        System.assertEquals('List has no rows for assignment to SObject', testException.getMessage(), 'Should not return results in the list.');
    }

    @isTest
    public static void cloneStageSuccess()
    {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];

        Test.startTest();
        ProposalService.changeStageName(opp.Id);
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Id, StageName FROM Opportunity LIMIT 1];

        System.assertEquals('Em Análise de Formalização', updatedOpp.StageName, 'Incorrect value for Stage Name.');
    }

    @isTest
    public static void cloneStageFail()
    {
        Exception testException;
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Test.startTest();
        try {
            ProposalService.changeStageName(acc.Id);
        } catch (Exception e) {
            testException = e;
        }
        Test.stopTest();

        Opportunity updatedOpp = [SELECT Id, StageName FROM Opportunity LIMIT 1];

        System.assertEquals('Em Análise de Formalização', updatedOpp.StageName, 'Incorrect value for Stage Name.');
    }
}