creditas-sf/force-app/main/default/objects/Account/fields/agency__c.field-meta.xml
<CustomField>
    <fullName>agency__c</fullName>
    <label>Agência</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <description>Número da conta do cliente</description>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Nome do banco do cliente.</description>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Quantia referente ao registro que está sendo cadastrado</description>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ManufacturingYear__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingYear__c</fullName>
    <label>Ano de Fabricação</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do recurso que está sendo registrado</description>
    <label>Tipo de Recurso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>PRESUMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>CONFIRMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>NET_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>LAND</fullName>
            </value>
            <value>
                <fullName>CONDOMINIUM_HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL_ROOM</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>MOTORCYCLE</fullName>
            </value>
            <value>
                <fullName>QUADRICYCLE</fullName>
            </value>
            <value>
                <fullName>TRUCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OperationSection__c/OperationSection__c.object-meta.xml
<CustomObject>
    <label>Seção Operação</label>
    <nameField>
        <label>Seção Operação Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Operação</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OperationSection__c/fields/BranchStatus__c.field-meta.xml
<CustomField>
    <fullName>BranchStatus__c</fullName>
    <label>Status da agência</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <formula>TEXT(SyncedQuote.Quantity__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Prazo solicitado</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/Quantity__c.field-meta.xml
<CustomField>
    <fullName>Quantity__c</fullName>
    <label>Quantity</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Quote/fields/UnitPrice__c.field-meta.xml
<CustomField>
    <fullName>UnitPrice__c</fullName>
    <label>UnitPrice</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalOperationServiceTest.cls
@isTest
public class ProposalOperationServiceTest {
    @TestSetup
    static void makeData(){
        String accPessoaFisica = [SELECT ID FROM RECORDTYPE WHERE DeveloperName = 'Pessoa_Fisica' AND SobjectType = 'Account']?.Id;
		List<Account> accounts = new List<Account>();
        Account accCustomer = TestSetup.getAccount('Nivaele', false);
        accCustomer.DocumentNumber__c = '51479566039';
        accCustomer.BankName__c = 'test bank principal';
        accCustomer.Agency__c = '00001'; 
        accCustomer.BankAccountNumber__c = '01020304';
        accCustomer.RecordTypeId = accPessoaFisica;
        accounts.add(accCustomer);
        
        Account accRole = TestSetup.getAccount('Account_Role', false);
        accRole.DocumentNumber__c = '12047477000101';
        accRole.BankName__c = 'test bank collateral guarantor';
        accRole.Agency__c = '12345'; 
        accRole.BankAccountNumber__c = '0123456'; 
        accRole.RecordTypeId = accPessoaFisica;
        accounts.add(accRole);
        
        insert accounts;
        
        Opportunity opp = TestSetup.getOpportunity(accCustomer.Id, false);
        opp.Description = 'Test Description Opportunity';
        insert opp;

        OpportunityRole__c oppRoleGuarantor = TestSetup.getOppRole(accRole, opp, 'COLLATERAL_GUARANTOR', false, true); 
        OpportunityRole__c oppRolePrincipal = TestSetup.getOppRole(accCustomer, opp, 'PRINCIPAL', true, true);   

        FinancialResources__c finResource = FinancialResourceSetup.createFinancialResource('Auto');
        finResource.ManufacturingYear__c = '2022';
        finResource.Amount__c = 10000;
        finResource.Type__c = 'CAR';
        insert finResource;
        
        Garantias__c guarantee = new Garantias__c(
            Account__c = accRole.Id,
            Opportunity__c = opp.Id,
            Recurso_Financeiro__c = finResource.Id
        );
        insert guarantee;

        OperationSection__c operation = new OperationSection__c();
        operation.Opportunity__c = opp.Id;
        operation.BranchStatus__c = 'Aprovar';
        insert operation;
        
        Quote quote = new Quote();
        quote.Name = 'Teste';
        quote.OpportunityId = opp.Id;
        quote.UnitPrice__c = 100;
        quote.Quantity__c = 20;
        insert quote;
    }
    
    @isTest
    static void getOperationSectionSuccessTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        OperationSection__c result = new OperationSection__c();

        Test.startTest();
        result = ProposalOperationService.getOperationSectionFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals('Aprovar', result.BranchStatus__c ,'Incorrect OperationSection value');
    }
    
    @isTest
    static void getOperationSectionEmptyTest(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);
        
        OperationSection__c result = new OperationSection__c();

        Test.startTest();
        result = ProposalOperationService.getOperationSectionFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new OperationSection__c(), result ,'Should return empty OperationSection');
    }

    @isTest
    static void getQuoteFromOppSuccessTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Quote result = new Quote();

        Test.startTest();
        result = ProposalOperationService.getQuoteFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(100, result.UnitPrice__c ,'Incorrect Quote value');
    }

    @isTest
    static void getQuoteFromOppEmptyTest(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);
        
        Quote result = new Quote();

        Test.startTest();
        result = ProposalOperationService.getQuoteFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new Quote(), result ,'Should return empty Quote');
    }

    @isTest
    static void getPrincipalProponentFromOppTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Account result = new Account();

        Test.startTest();
        result = ProposalOperationService.getProponentFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals('00001', result.Agency__c ,'Incorrect Proponente value');
    }
    
    @isTest
    static void getProponentFromOppEmptyTest(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);
        
        Account result = new Account();

        Test.startTest();
        result = ProposalOperationService.getProponentFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new Account(), result ,'Should return empty Proponente');
    }

    @isTest
    static void getFinancialFromOppTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        FinancialResources__c result = new FinancialResources__c();

        Test.startTest();
        result = ProposalOperationService.getFinancialFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(10000, result.Amount__c ,'Incorrect Financial Resources value');
    }

    @isTest
    static void getFinancialFromOppEmptyTest(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);
        
        FinancialResources__c result = new FinancialResources__c();

        Test.startTest();
        result = ProposalOperationService.getFinancialFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new FinancialResources__c(), result ,'Should return empty FinancialResources');
    }

    @isTest
    static void getOpportunityInfoTest(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
		Opportunity result = new Opportunity();
        
        Test.startTest();
        result = ProposalOperationService.getOpportunityInfo(opp.Id);
        Test.stopTest();
        
        System.assertEquals('Test Description Opportunity', result.Description ,'Incorrect Opportunity value');
    }

    @isTest
    static void getOpportunityInfoTestFail(){
        Exception testException;
        Account acc = [SELECT Id FROM Account LIMIT 1];
        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);
        Opportunity result = new Opportunity();
        Test.startTest();
        try{
        	result = ProposalOperationService.getOpportunityInfo(acc.Id);
        }catch(Exception e){
            testException = e;
        }
        Test.stopTest();
        
        System.assertEquals('List has no rows for assignment to SObject', testException.getMessage() ,'Incorrect Exception message');
    }
}