creditas-sf/force-app/main/default/objects/Account/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Nome do banco do cliente.</description>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountRelationships__c/AccountRelationships__c.object-meta.xml
<CustomObject>
    <label>Conta Relacionada</label>
    <nameField>
        <displayFormat>AccRel-{00000000}</displayFormat>
        <label>Código da Conta Relacionada</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Contas Relacionadas</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountRelationships__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountRelationships__c/fields/PrimaryRelationship__c.field-meta.xml
<CustomField>
    <fullName>PrimaryRelationship__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Conta Principal</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contas Relacionadas</relationshipLabel>
    <relationshipName>Contas_Relacionadas</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/Addresses__c.object-meta.xml
<CustomObject>
    <description>Objeto para registros dos endereços do cliente/empresa, independente da localidade (Brasil/México).</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Numeração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Esse campo determina o qual a conta que está relacionada ao endereço cadastrado.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Complement__c.field-meta.xml
<CustomField>
    <fullName>Complement__c</fullName>
    <label>Complemento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Endere_os</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>CommunicationContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Contato</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Code</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Campo usado para registro do numero do documento que está sendo registrado.</description>
    <label>Número do documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountIntegrationServiceTest.cls
@IsTest
public class AccountIntegrationServiceTest {
  @TestSetup
  static void makeData() {
    List<Account> relationshipAccounts = new List<Account>{
      AccountSetup.createAccount('test-001-account-002', 'Pessoa_Fisica'),
      AccountSetup.createAccount('test-001-account-003', 'Pessoa_Fisica'),
      AccountSetup.createAccount('test-002-account-002', 'Pessoa_Fisica'),
      AccountSetup.createAccount('test-002-account-003', 'Pessoa_Fisica')
    };
    relationshipAccounts[0].ExternalId__c = 'test-001-account-002';
    relationshipAccounts[1].ExternalId__c = 'test-001-account-003';
    relationshipAccounts[2].ExternalId__c = 'test-002-account-002';
    relationshipAccounts[3].ExternalId__c = 'test-002-account-003';

    insert relationshipAccounts;

    String json = AccountIntegrationMock.getUpdateMock();
    runUpsert(json);
  }

  @IsTest
  static void testInsertSuccess() {
    String json = AccountIntegrationMock.getPayloadMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);
    List<Account> accounts = [SELECT Id FROM Account];

    assertResponseSuccess(statusCode, response);
    System.assertEquals(6, accounts.size(), 'Number of existing accounts is incorrect');
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(
      3,
      account.CommunicationContacts__r.size(),
      '3 contacts should\'ve been created'
    );
    System.assertEquals(2, account.Enderecos__r.size(), '2 addresses should\'ve been created');
    System.assertEquals(
      2,
      account.Contas_Relacionadas__r.size(),
      '2 relationships should\'ve been created'
    );
    System.assertEquals(2, account.Documentos__r.size(), '2 documents should\'ve been created');
    System.assertEquals(
      4,
      account.AccountFinancialRelationships__r.size(),
      '2 financial relationships should\'ve been created'
    );
    System.assertEquals(
      2,
      account.ProfessionalInfos__r.size(),
      '2 professional infos should\'ve been created'
    );
    System.assertEquals(2, account.Filiation__r.size(), '2 filiations should\'ve been created');
  }

  @IsTest
  static void testUpdateSuccess() {
    String json = AccountIntegrationMock.getChangedDataMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);
    List<Account> accounts = [SELECT Id FROM Account];

    assertResponseSuccess(statusCode, response);
    System.assertEquals(5, accounts.size(), 'Number of existing accounts is incorrect');
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals('Itaú', account.BankName__c, 'Bank name not updated');
    System.assertEquals(
      '11999998883',
      account.CommunicationContacts__r[0].Code__c,
      'Contact code not updated'
    );
    System.assertEquals(
      'apto 33',
      account.Enderecos__r[0].Complement__c,
      'Address complement not updated'
    );
    System.assertEquals(
      '12345',
      account.Documentos__r[1].DocumentNumber__c,
      'Document number not updated'
    );
    System.assertEquals(
      'Lily Aldrin Ericksen',
      account.Filiation__r[0].Name__c,
      'Filiation name not updated'
    );
  }

  @IsTest
  static void testDeleteContactSuccess() {
    String json = AccountIntegrationMock.getDeleteContactMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(
      2,
      account.CommunicationContacts__r.size(),
      'Number of communication contacts is incorrect'
    );
  }

  @IsTest
  static void testDeleteAddressSuccess() {
    String json = AccountIntegrationMock.getDeleteAddressMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(1, account.Enderecos__r.size(), 'Number of addresses is incorrect');
  }

  @IsTest
  static void testDeleteRelationshipSuccess() {
    String json = AccountIntegrationMock.getDeleteRelationshipMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(
      1,
      account.Contas_Relacionadas__r.size(),
      'Number of relationships is incorrect'
    );
  }

  @IsTest
  static void testDeleteDocumentSuccess() {
    String json = AccountIntegrationMock.getDeleteDocumentMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(1, account.Documentos__r.size(), 'Number of documents is incorrect');
  }

  @IsTest
  static void testDeleteProfessionalInfoSuccess() {
    String json = AccountIntegrationMock.getDeleteProfessionalInfoMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(
      1,
      account.ProfessionalInfos__r.size(),
      'Number of professional infos is incorrect'
    );
    System.assertEquals(
      3,
      account.AccountFinancialRelationships__r.size(),
      'Number of financial relationships infos is incorrect'
    );
  }

  @IsTest
  static void testDeleteIncomeSuccess() {
    String json = AccountIntegrationMock.getDeleteIncomeMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(
      3,
      account.AccountFinancialRelationships__r.size(),
      'Number of financial relationships is incorrect'
    );
  }

  @IsTest
  static void testDeleteFiliationSuccess() {
    String json = AccountIntegrationMock.getDeleteFiliationMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    Integer statusCode = integration.getStatusCode();
    AccountIntegrationResponseVO response = integration.getResponse();
    Account account = selectAccount(response.accountId);

    assertResponseSuccess(statusCode, response);
    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    System.assertEquals(1, account.Filiation__r.size(), 'Number of filiations is incorrect');
  }

  @IsTest
  static void testInvalidJson() {
    String json = '(this is not json)';

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    AccountIntegrationResponseVO response = integration.getResponse();

    System.assertNotEquals(null, response, 'Response body shouldn\'t be null');
    assertResponseError(response, 500, 'Invalid JSON format.');
  }

  @IsTest
  static void testProfessionalIncomeException() {
    String json = AccountIntegrationMock.getProfessionalIncomeExceptionMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    AccountIntegrationResponseVO response = integration.getResponse();

    System.assertNotEquals(null, response, 'Response body shouldn\'t be null');
    assertResponseError(
      response,
      500,
      'Each Professional Info must have only one professional income.'
    );
  }

  @IsTest
  static void testMainDocumentNullException() {
    String json = AccountIntegrationMock.getMainDocumentNullExceptionMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    AccountIntegrationResponseVO response = integration.getResponse();

    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    assertResponseError(response, 500, 'Main Document can\'t be null.');
  }

  @IsTest
  static void testInvalidCurrencyCodeException() {
    String json = AccountIntegrationMock.getInvalidCurrencyCodeExceptionMock();

    Test.startTest();
    AccountIntegrationService integration = runUpsert(json);
    Test.stopTest();

    Blob responseBlob = integration.getResponseAsBlob();
    AccountIntegrationResponseVO response = integration.getResponse();

    System.assertNotEquals(null, responseBlob, 'Response body shouldn\'t be null');
    assertResponseError(response, 500, 'Invalid currency code');
  }

  static AccountIntegrationService runUpsert(String json) {
    AccountIntegrationService integration = new AccountIntegrationService();
    integration.setRequestBody(json);
    integration.upsertData();
    return integration;
  }

  static Account selectAccount(String accountId) {
    List<Account> accounts = [
      SELECT
        Id,
        BankName__c,
        (SELECT Id, Code__c FROM CommunicationContacts__r),
        (SELECT Id, Complement__c FROM Enderecos__r),
        (SELECT Id FROM Contas_Relacionadas__r),
        (SELECT Id, DocumentNumber__c FROM Documentos__r),
        (
          SELECT
            Id,
            Recurso_Financeiro__c,
            Recurso_Financeiro__r.ExternalId__c,
            Recurso_Financeiro__r.ProfessionalInfo__c
          FROM AccountFinancialRelationships__r
        ),
        (SELECT Id FROM ProfessionalInfos__r),
        (SELECT Id, Name__c FROM Filiation__r)
      FROM Account
      WHERE Id = :accountId
    ];

    return accounts.isEmpty() ? null : accounts[0];
  }

  static void assertResponseSuccess(Integer statusCode, AccountIntegrationResponseVO response){
    System.assertEquals(200, statusCode, 'Status code is incorrect');
    System.assertEquals(statusCode, response.status, 'Response status is incorrect');
    System.assertNotEquals(null, response.accountId, 'Response accountId is incorrect');
    System.assertEquals('Account upserted.', response.message, 'Response message is incorrect');
  }

  static void assertResponseError(
    AccountIntegrationResponseVO response,
    Integer status,
    String message
  ) {
    System.assertEquals(
      null,
      response.accountId,
      'Response body field \'accountId\' should be null'
    );
    System.assertEquals(
      status,
      response.status,
      'Response body field \'status\' should be \'' +
      status +
      '\''
    );
    System.assertEquals(
      true,
      response.message.startsWith(message),
      'Response body field \'message\' should start with \'' +
      message +
      '\''
    );
  }
}