creditas-sf/force-app/main/default/objects/Account/fields/BankAccountNumber__c.field-meta.xml
<CustomField>
    <fullName>BankAccountNumber__c</fullName>
    <description>Número da conta do cliente</description>
    <label>Bank Account Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BankName__c.field-meta.xml
<CustomField>
    <fullName>BankName__c</fullName>
    <description>Nome do banco do cliente.</description>
    <label>Banco</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Birth_City__c</fullName>
    <label>Birth City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Birth_Country__c.field-meta.xml
<CustomField>
    <fullName>Birth_Country__c</fullName>
    <label>País de Nascimento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CivilStatus__c.field-meta.xml
<CustomField>
    <fullName>CivilStatus__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MARRIED</fullName>
                <label>Casado(a)</label>
            </value>
            <value>
                <fullName>SEPARATED</fullName>
                <label>Separado(a)</label>
            </value>
            <value>
                <fullName>SINGLE</fullName>
                <label>Solteiro(a)</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorciado(a)</label>
            </value>
            <value>
                <fullName>WIDOW</fullName>
                <label>Viúvo(a)</label>
            </value>
            <value>
                <fullName>STABLE_UNION</fullName>
                <label>União estável</label>
            </value>
            <value>
                <fullName>NOT_INFORMED</fullName>
                <label>Não informado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Clabe__c.field-meta.xml
<CustomField>
    <fullName>Clabe__c</fullName>
    <description>Campo para identificar número de conta bancária do cliente. (creditas-mx)</description>
    <label>Clabe</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Curp__c.field-meta.xml
<CustomField>
    <fullName>Curp__c</fullName>
    <description>Campo.utilizado para identificação do cidadão mexicano. (Creditas-mx)</description>
    <label>Curp</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Education__c.field-meta.xml
<CustomField>
    <fullName>Education__c</fullName>
    <label>Education</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ILLITERATE</fullName>
            </value>
            <value>
                <fullName>PRIMARY_SCHOOL_INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>PRIMARY_SCHOOL_COMPLETED</fullName>
            </value>
            <value>
                <fullName>FOURTH_YEAR_PRIMARY_SCHOOL_INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>FOURTH_YEAR_PRIMARY_SCHOOL_COMPLETED</fullName>
            </value>
            <value>
                <fullName>HIGH_SCHOOL_INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>HIGH_SCHOOL_COMPLETED</fullName>
            </value>
            <value>
                <fullName>COLLEGE_DEGREE_INCOMPLETE</fullName>
            </value>
            <value>
                <fullName>COLLEGE_DEGREE_COMPLETED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalModifiedBy__c.field-meta.xml
<CustomField>
    <fullName>ExternalModifiedBy__c</fullName>
    <label>ExternalModifiedBy</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/FirstName__c.field-meta.xml
<CustomField>
    <fullName>FirstName__c</fullName>
    <label>Nome Completo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>FEMALE</fullName>
                <label>Feminino</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IneNumber__c.field-meta.xml
<CustomField>
    <fullName>IneNumber__c</fullName>
    <label>Ine Number</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/LastName__c.field-meta.xml
<CustomField>
    <fullName>LastName__c</fullName>
    <label>Ultimo nome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nacionalidade</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthLowerLimit__c</fullName>
    <label>Patrimônio líquido mínimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthUpperLimit__c</fullName>
    <label>NetWorthUpperLimit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/PoliticallyExposed__c.field-meta.xml
<CustomField>
    <fullName>PoliticallyExposed__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Pessoa Politicamente Exposta</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/SecondLastName__c.field-meta.xml
<CustomField>
    <fullName>SecondLastName__c</fullName>
    <label>Outro nome/sobrenome</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/SecondName__c.field-meta.xml
<CustomField>
    <fullName>SecondName__c</fullName>
    <label>Second Name</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/API_Transaction_Errors__b.object-meta.xml
<CustomObject>
    <label>API_Transaction_Errors</label>
    <pluralLabel>API_Transaction_Errors</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/CreatedBy__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy__c</fullName>
    <label>CreatedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>API_Transaction_Errors1</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccountIntegrationService.cls
public with sharing class AccountIntegrationService {
  class AccountIntegrationServiceException extends Exception {
    String detailedMessage;

    public String getDetailedMessage() {
      return this.detailedMessage;
    }

    public void setDetailedMessage(String message) {
      this.detailedMessage = message;
    }
  }

  class TestException extends Exception {
  }

  @TestVisible
  static Boolean isExceptionTest = false;

  static AccountIntegrationServiceException createAISException(
    String message,
    String detailedMessage
  ) {
    AccountIntegrationServiceException aisException = new AccountIntegrationServiceException(
      message
    );
    aisException.setDetailedMessage(detailedMessage);
    return aisException;
  }

  static AccountIntegrationServiceException createAISException(String message) {
    return createAISException(message, message);
  }

  String requestBodyString;
  String upsertedAccountId;
  AccountIntegrationRequestVO requestBodyObject;
  AccountIntegrationResponseVO responseBodyObject;

  public Blob getResponseBodyAsBlob() {
    return Blob.valueOf(JSON.serialize(this.responseBodyObject));
  }

  public void setRequestBody(String json) {
    this.requestBodyString = json;
  }

  public void upsertData() {
    this.upsertedAccountId = null;
    try {
      if (isExceptionTest) {
        throw new TestException('This is a test exception.');
      }
      this.parseRequestBody();
      this.validateData();
      this.upsertRecords();
      this.setResponse(200, 'Account upserted.');
    } catch (AccountIntegrationServiceException aisException) {
      this.handleAISException(aisException);
    } catch (Exception e) {
      this.handleException(e);
    }
  }

  void parseRequestBody() {
    this.requestBodyObject = AccountIntegrationRequestVO.parse(this.requestBodyString);
    if (this.requestBodyObject.hasError) {
      throw createAISException('Invalid JSON format.', this.requestBodyObject.errorMessage);
    }
  }

  void validateData() {
    if (this.requestBodyObject.professionalInfo != null) {
      for (
        AccountIntegrationRequestVO.ProfessionalInfo professionalInfo : this.requestBodyObject.professionalInfo
      ) {
        if (
          professionalInfo.professionalIncome != null &&
          professionalInfo.professionalIncome.size() > 1
        ) {
          throw createAISException(
            'Each Professional Info must have only one professional income.'
          );
        }
      }
    }

    if (
      this.requestBodyObject.mainDocument == null ||
      String.isBlank(this.requestBodyObject.mainDocument.code)
    ) {
      throw createAISException('Main Document can\'t be null.');
    }
  }

  void upsertRecords() {
    this.upsertedAccountId = this.upsertAccount();
  }

  Id upsertAccount() {
    Account account = this.getAccount();
    try {
      // upsert account ExternalId__c;
      upsert account;
      return account.Id;
    } catch (Exception e) {
      throw createAISException('An error has occurred upserting Account object.', e.getMessage());
    }
  }

  Account getAccount() {
    Account account = new Account();
    account.ExternalId__c = this.requestBodyObject.id;
    account.Name = this.requestBodyObject.fullName;
    account.Gender__c = this.requestBodyObject.gender;
    account.ExternalTenant__c = this.requestBodyObject.tenant;
    account.ExternalModifiedBy__c = this.requestBodyObject.modifiedBy;
    account.CivilStatus__c = this.requestBodyObject.civilStatus;
    account.Birth_City__c = this.requestBodyObject.cityOfBirth;
    account.Birth_Country__c = this.requestBodyObject.countryOfBirth;
    account.Nationality__c = this.requestBodyObject.nationality;

    if (String.isNotBlank(this.requestBodyObject.birthDate)) {
      account.BirthDate__c = Date.valueOf(this.requestBodyObject.birthDate);
    }

    if (String.isNotBlank(this.requestBodyObject.createdAt)) {
      account.ExternalCreationDate__c = Date.valueOf(this.requestBodyObject.createdAt);
    }

    if (String.isNotBlank(this.requestBodyObject.updatedAt)) {
      account.ExternalUpdatedDate__c = Date.valueOf(this.requestBodyObject.updatedAt);
    }

    account.ExternalVersion__c = this.requestBodyObject.version;
    account.DocumentType__c = this.requestBodyObject.mainDocument.type;
    account.DocumentNumber__c = this.requestBodyObject.mainDocument.code;

    if (this.requestBodyObject.additionalProperties != null) {
      account.FirstName__c = this.requestBodyObject.additionalProperties.firstName;
      account.SecondName__c = this.requestBodyObject.additionalProperties.secondName;
      account.LastName__c = this.requestBodyObject.additionalProperties.lastName;
      account.SecondLastName__c = this.requestBodyObject.additionalProperties.secondLastName;
      account.Curp__c = this.requestBodyObject.additionalProperties.curp;
      account.IneNumber__c = this.requestBodyObject.additionalProperties.ineNumber;
      account.BankName__c = this.requestBodyObject.additionalProperties.bankName;
      account.BankAccountNumber__c = this.requestBodyObject.additionalProperties.accountNumber;
      account.Clabe__c = this.requestBodyObject.additionalProperties.clabe;

      account.PoliticallyExposed__c = this.requestBodyObject.additionalProperties.politicallyExposed ==
        null
        ? false
        : this.requestBodyObject.additionalProperties.politicallyExposed;
    }

    if (this.requestBodyObject.education != null) {
      account.Education__c = this.requestBodyObject.education.degree;
    }

    if (this.requestBodyObject.wealth != null) {
      if (String.isNotBlank(this.requestBodyObject.wealth.networthLowerLimit)) {
        account.NetWorthLowerLimit__c = decimal.valueof(
          this.requestBodyObject.wealth.networthLowerLimit
        );
      }

      if (String.isNotBlank(this.requestBodyObject.wealth.networthUpperLimit)) {
        account.NetWorthUpperLimit__c = decimal.valueof(
          this.requestBodyObject.wealth.networthUpperLimit
        );
      }

      if (String.isNotBlank(this.requestBodyObject.wealth.currencyCode)) {
        account.CurrencyIsoCode = this.requestBodyObject.wealth.currencyCode;
      }
    }

    account.Id = this.getAccountId();
    account.IsExternallySynched__c = true;
    account.IsSynchEnabled__c = 'ENABLED';
    return account;
  }

  Id getAccountId() {
    String externalId = this.requestBodyObject.id;
    Id accountId = [
      SELECT Id
      FROM Account
      WHERE ExternalId__c = :externalId AND ExternalId__c != NULL
      LIMIT 1
    ]
    ?.Id;

    if (accountId == null) {
      String docNumber = this.requestBodyObject.mainDocument.type == 'CPF'
        ? Util.getMaskedCPF(this.requestBodyObject.mainDocument.code)
        : this.requestBodyObject.mainDocument.code;

      accountId = [SELECT Id FROM Account WHERE DocumentNumber__c = :docNumber LIMIT 1]?.Id;
    }

    return accountId;
  }

  // void upsertContacts() {
  // }

  // void upsertAddresses() {
  // }

  // void upsertRelationships() {
  // }

  // void upsertDocuments() {
  // }

  // void upsertIncome() {
  // }

  // void upsertProfessionalInfo() {
  // }

  // void upsertFiliation() {
  // }

  void handleAISException(AccountIntegrationServiceException aisException) {
    this.setResponse(500, aisException.getMessage());
    this.insertErrorLog(500, aisException.getDetailedMessage());
  }

  void handleException(Exception e) {
    this.setResponse(
      500,
      'An unexpected error has occurred. Please, contact a Salesforce administrator.'
    );
    this.insertErrorLog(500, e.getMessage());
  }

  void insertErrorLog(Integer statusCode, String message) {
    API_Transaction_Errors__b ate = new API_Transaction_Errors__b();
    ate.Endpoint__c = '/services/apexrest/IntegrationAccountIN';
    ate.RequestBody__c = this.requestBodyString;
    ate.ReturnCode__c = statusCode;
    ate.ErrorMessage__c = message;
    ate.CreatedDate__c = System.now();
    ate.CreatedBy__c = UserInfo.getUserId();
    if (!Test.isRunningTest()) {
      database.insertImmediate(ate);
    }
  }

  void setResponse(Integer statusCode, String message) {
    this.responseBodyObject = new AccountIntegrationResponseVO();
    this.responseBodyObject.accountId = this.upsertedAccountId;
    this.responseBodyObject.message = message;
    this.responseBodyObject.status = statusCode;
  }
}