creditas-sf/force-app/main/default/objects/Account/fields/Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Birth_City__c</fullName>
    <label>Birth City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Birth_Country__c.field-meta.xml
<CustomField>
    <fullName>Birth_Country__c</fullName>
    <label>País de Nascimento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CivilStatus__c.field-meta.xml
<CustomField>
    <fullName>CivilStatus__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MARRIED</fullName>
                <label>Casado(a)</label>
            </value>
            <value>
                <fullName>SEPARATED</fullName>
                <label>Separado(a)</label>
            </value>
            <value>
                <fullName>SINGLE</fullName>
                <label>Solteiro(a)</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorciado(a)</label>
            </value>
            <value>
                <fullName>WIDOW</fullName>
                <label>Viúvo(a)</label>
            </value>
            <value>
                <fullName>STABLE_UNION</fullName>
                <label>União estável</label>
            </value>
            <value>
                <fullName>NOT_INFORMED</fullName>
                <label>Não informado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalModifiedBy__c.field-meta.xml
<CustomField>
    <fullName>ExternalModifiedBy__c</fullName>
    <label>ExternalModifiedBy</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>FEMALE</fullName>
                <label>Feminino</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/MigrationRecord__c.field-meta.xml
<CustomField>
    <fullName>MigrationRecord__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Migration Record</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nacionalidade</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Juridica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Juridica</fullName>
    <active>true</active>
    <label>Pessoa Jurídica</label>
</RecordType>

creditas-sf/force-app/main/default/classes/AccountTriggerHandlerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Classe de teste para a classe AccountTriggerHandler
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Thales Yumiya           11/08/2021      Created     Classe de teste para o AccountTriggerHandlerTest
**********************************************************************************************************************************/
@isTest
public class AccountTriggerHandlerTest {
    
    private static final Id RECORDTYPE_CONTA_FISICA = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Pessoa_Fisica').getRecordTypeId();
    private static final Id RECORDTYPE_CONTA_JURIDICA = Schema.SObjectType.Account.getRecordTypeInfosByDeveloperName().get('Pessoa_Juridica').getRecordTypeId();
    
    @TestSetup
    static void makeData()
    {
        Profile userProfile = [SELECT Id FROM Profile LIMIT 1];
        User userTest = new User();
        userTest.LastName = 'Test';
        userTest.Alias = 'Test';
        userTest.Email = 'usertest@Creditas.com.dev';
        userTest.Username = 'usertest@Creditas.com.dev';
        usertest.EmployeeNumber = '01984';
        userTest.CommunityNickname = 'UserTest';
        userTest.ProfileId = userProfile.Id;
        userTest.LocaleSidKey = 'pt_BR';
        userTest.LanguageLocaleKey = 'pt_BR';
        userTest.EmailEncodingKey = 'UTF-8';
        userTest.TimeZoneSidKey = 'America/Sao_Paulo';
        insert userTest;
        
        List<Account> lstTestAccounts = new List<Account>();

        Account testAccount = new Account(Name = 'TestAccount1', MigrationRecord__c = false, IsExternallySynched__c = true);
        Integer aux = integer.valueof(crypto.getRandomLong());
        testAccount.RecordTypeId = RECORDTYPE_CONTA_FISICA;
        testAccount.DocumentNumber__c = '66239925020';
        testAccount.ExternalTenant__c = 'creditasbr';

        lstTestAccounts.add(testAccount);

        testAccount = new Account(Name = 'TestAccount2', MigrationRecord__c = false, IsExternallySynched__c = true);
        aux = integer.valueof(crypto.getRandomLong());
        testAccount.RecordTypeId = RECORDTYPE_CONTA_JURIDICA;
        testAccount.DocumentNumber__c = '73155938000154';
        testAccount.ExternalTenant__c = 'creditasbr';

        lstTestAccounts.add(testAccount);

        insert lstTestAccounts;
        
    }

    @isTest
    static void updateIsExternallySync() 
    {
        Account varAccount = [SELECT Id, ExternalId__c, isExternallySynched__c, ExternalVersion__c, ExternalCreationDate__c, ExternalUpdatedDate__c,
                              ExternalTenant__c, ExternalModifiedBy__c, DocumentType__c, DocumentNumber__c, Name, Gender__c, BirthDate__c,
                              CivilStatus__c, Birth_City__c, Birth_Country__c, Nationality__c, IsSynchEnabled__c
                              FROM Account LIMIT 1];
   
        varAccount.ExternalId__c = '3213213231';
        varAccount.IsSynchEnabled__c = 'ENABLED';

        Test.startTest();
        update varAccount;

        varAccount = [SELECT Id, ExternalId__c, isExternallySynched__c, ExternalVersion__c, ExternalCreationDate__c, ExternalUpdatedDate__c,
        ExternalTenant__c, ExternalModifiedBy__c, DocumentType__c, DocumentNumber__c, Name, Gender__c, BirthDate__c,
        CivilStatus__c, Birth_City__c, Birth_Country__c, Nationality__c, IsSynchEnabled__c
        FROM Account LIMIT 1];

        Test.stopTest();

        System.assertEquals(false, varAccount.IsExternallySynched__c, 'O campo isExternallySync deveria ter mudado para false');
        System.assertEquals('ENABLED', varAccount.IsSynchEnabled__c, 'O campo isSynchEnabled não foi mudado para Enabled');
    }
}