creditas-sf/force-app/main/default/objects/Account/fields/Birth_Country__c.field-meta.xml
<CustomField>
    <fullName>Birth_Country__c</fullName>
    <label>País de Nascimento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthCity__c.field-meta.xml
<CustomField>
    <fullName>BirthCity__c</fullName>
    <label>Cidade de Nascimento</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/BirthDate__c.field-meta.xml
<CustomField>
    <fullName>BirthDate__c</fullName>
    <label>Birth Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/CivilStatus__c.field-meta.xml
<CustomField>
    <fullName>CivilStatus__c</fullName>
    <label>Estado Civil</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MARRIED</fullName>
                <label>Casado(a)</label>
            </value>
            <value>
                <fullName>SEPARATED</fullName>
                <label>Separado(a)</label>
            </value>
            <value>
                <fullName>SINGLE</fullName>
                <label>Solteiro(a)</label>
            </value>
            <value>
                <fullName>DIVORCED</fullName>
                <label>Divorciado(a)</label>
            </value>
            <value>
                <fullName>WIDOW</fullName>
                <label>Viúvo(a)</label>
            </value>
            <value>
                <fullName>STABLE_UNION</fullName>
                <label>União estável</label>
            </value>
            <value>
                <fullName>NOT_INFORMED</fullName>
                <label>Não informado</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/EconomicActivity__c.field-meta.xml
<CustomField>
    <fullName>EconomicActivity__c</fullName>
    <label>Atividade econômica profissional:</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Agricultura [AGRICULTURE]</fullName>
            </value>
            <value>
                <fullName>Mineração [MINING]</fullName>
            </value>
            <value>
                <fullName>Óleo [OIL]</fullName>
            </value>
            <value>
                <fullName>Fabricação de alimentos [FOOD_MANUFACTURING]</fullName>
            </value>
            <value>
                <fullName>Pecuária [CATTLE_RAISING]</fullName>
            </value>
            <value>
                <fullName>Têxtil [TEXTILE]</fullName>
            </value>
            <value>
                <fullName>Madeira [WOOD]</fullName>
            </value>
            <value>
                <fullName>Papel [PAPER]</fullName>
            </value>
            <value>
                <fullName>Editorial [EDITORIAL]</fullName>
            </value>
            <value>
                <fullName>Química [CHEMISTRY]</fullName>
            </value>
            <value>
                <fullName>Floresta [FOREST]</fullName>
            </value>
            <value>
                <fullName>Petroquímicos [PETROCHEMICALS]</fullName>
            </value>
            <value>
                <fullName>Minerais não metálicos [NON_METALLIC_MINERALS]</fullName>
            </value>
            <value>
                <fullName>Metalurgia [METALLURGY]</fullName>
            </value>
            <value>
                <fullName>Maquinaria [MACHINERY]</fullName>
            </value>
            <value>
                <fullName>Fabricação [MANUFACTURE]</fullName>
            </value>
            <value>
                <fullName>Acabamento [FINISHING]</fullName>
            </value>
            <value>
                <fullName>Construção [CONSTRUCTION]</fullName>
            </value>
            <value>
                <fullName>Energia elétrica [ELECTRIC_POWER]</fullName>
            </value>
            <value>
                <fullName>Comida pronta [PREPARED_FOOD]</fullName>
            </value>
            <value>
                <fullName>Roupas [CLOTHES]</fullName>
            </value>
            <value>
                <fullName>Lojas [STORES]</fullName>
            </value>
            <value>
                <fullName>Comércio [COMMERCE]</fullName>
            </value>
            <value>
                <fullName>Veículos [VEHICLES]</fullName>
            </value>
            <value>
                <fullName>Armas de fogo [FIREARMS]</fullName>
            </value>
            <value>
                <fullName>Serviços financeiros [FINANCIAL_SERVICES]</fullName>
            </value>
            <value>
                <fullName>Imóveis [REAL_STATE]</fullName>
            </value>
            <value>
                <fullName>Jogos de sorte/ apostas [RAFFLES_SEEPSTAKES]</fullName>
            </value>
            <value>
                <fullName>Transporte terrestre [GROUND_TRANSPORTATION]</fullName>
            </value>
            <value>
                <fullName>Transporte aéreo [AIR_TRANSPORTATION]</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalModifiedBy__c.field-meta.xml
<CustomField>
    <fullName>ExternalModifiedBy__c</fullName>
    <label>ExternalModifiedBy</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>FEMALE</fullName>
                <label>Feminino</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Nationality__c.field-meta.xml
<CustomField>
    <fullName>Nationality__c</fullName>
    <label>Nacionalidade</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/EconomicActivity__c.field-meta.xml
<CustomField>
    <fullName>EconomicActivity__c</fullName>
    <label>EconomicActivity</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AGRICULTURE</fullName>
            </value>
            <value>
                <fullName>MINING</fullName>
            </value>
            <value>
                <fullName>OIL</fullName>
            </value>
            <value>
                <fullName>FOOD_MANUFACTURING</fullName>
            </value>
            <value>
                <fullName>CATTLE_RAISING</fullName>
            </value>
            <value>
                <fullName>TEXTILE</fullName>
            </value>
            <value>
                <fullName>WOOD</fullName>
            </value>
            <value>
                <fullName>PAPER</fullName>
            </value>
            <value>
                <fullName>EDITORIAL</fullName>
            </value>
            <value>
                <fullName>CHEMISTRY</fullName>
            </value>
            <value>
                <fullName>FOREST</fullName>
            </value>
            <value>
                <fullName>PETROCHEMICALS</fullName>
            </value>
            <value>
                <fullName>NON_METALLIC_MINERALS</fullName>
            </value>
            <value>
                <fullName>METALLURGY</fullName>
            </value>
            <value>
                <fullName>MACHINERY</fullName>
            </value>
            <value>
                <fullName>MANUFACTURE</fullName>
            </value>
            <value>
                <fullName>FINISHING</fullName>
            </value>
            <value>
                <fullName>CONSTRUCTION</fullName>
            </value>
            <value>
                <fullName>ELECTRIC_POWER</fullName>
            </value>
            <value>
                <fullName>PREPARED_FOOD</fullName>
            </value>
            <value>
                <fullName>CLOTHES</fullName>
            </value>
            <value>
                <fullName>STORES</fullName>
            </value>
            <value>
                <fullName>COMMERCE</fullName>
            </value>
            <value>
                <fullName>VEHICLES</fullName>
            </value>
            <value>
                <fullName>FIREARMS</fullName>
            </value>
            <value>
                <fullName>FINANCIAL_SERVICES</fullName>
            </value>
            <value>
                <fullName>REAL_STATE</fullName>
            </value>
            <value>
                <fullName>RAFFLES_SEEPSTAKES</fullName>
            </value>
            <value>
                <fullName>GROUND_TRANSPORTATION</fullName>
            </value>
            <value>
                <fullName>AIR_TRANSPORTATION</fullName>
            </value>
            <value>
                <fullName>MEDICINE</fullName>
            </value>
            <value>
                <fullName>RELIGION</fullName>
            </value>
            <value>
                <fullName>OTHERS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <label>JobTitle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/StartDate__c.field-meta.xml
<CustomField>
    <fullName>StartDate__c</fullName>
    <label>Start Date</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProfessionalInfoTriggerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Classe de teste para a classe ProfessionalInfoTriggerHandler
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Thales Yumiya           11/08/2021      Created     Classe de teste para o ProfessionalInfoTriggerHandlerTest
**********************************************************************************************************************************/
@isTest
public class ProfessionalInfoTriggerTest {
    
    @TestSetup
    static void makeData()
    {        
        Account varAccount = TestSetup.getAccount('Francisco', true);
        varAccount.IsExternallySynched__c = true;
        
        ProfessionalInfo__c varProfessionalInfo = new ProfessionalInfo__c();
        varProfessionalInfo.Account__c = varAccount.Id;
        varProfessionalInfo.JobTitle__c = 'Engenheiro';
        varProfessionalInfo.StartDate__c = Date.today();
        varProfessionalInfo.EconomicActivity__c = 'OTHERS';
        
        insert varProfessionalInfo;
    }

    @isTest
    static void updateIsExternallySync() 
    {
        ProfessionalInfo__c varProfessionalInfo = [SELECT Id, Name, Account__c, JobTitle__c, StartDate__c, EconomicActivity__c
                                                   FROM ProfessionalInfo__c LIMIT 1]; 

        varProfessionalInfo.JobTitle__c = 'Padre';
        varProfessionalInfo.StartDate__c = Date.today().addYears(5);
        varProfessionalInfo.EconomicActivity__c = 'RELIGION';
    
        Test.startTest();
        update varProfessionalInfo;
        Test.stopTest();

        Account varAccount = [SELECT Id, ExternalId__c, isExternallySynched__C, ExternalVersion__c, ExternalCreationDate__c, ExternalUpdatedDate__c,
                              ExternalTenant__c, ExternalModifiedBy__c, DocumentType__c, DocumentNumber__c, Name, Gender__c, BirthDate__c,
                              CivilStatus__c, BirthCity__c, Birth_Country__c, Nationality__c, IsSynchEnabled__c
                              FROM Account
                              WHERE Id =: varProfessionalInfo.Account__c
                              LIMIT 1];

        System.assertEquals(false, varAccount.IsExternallySynched__c, 'O campo isExternallySync deveria ter mudado para false');
    }

    @isTest
    static void updateMultiple()
    {
        Account varAccount = [SELECT Id, Name, isExternallySynched__c FROM Account LIMIT 1];
        List<ProfessionalInfo__c> listProfessionalInfoInsert = new List<ProfessionalInfo__c>();
        List<ProfessionalInfo__c> listProfessionalInfoUpdate = new List<ProfessionalInfo__c>();

        for (Integer i = 0; i < 10; i++) 
        {
            ProfessionalInfo__c varProfessionalInfo = new ProfessionalInfo__c();
            varProfessionalInfo.Account__c = varAccount.Id;

            listProfessionalInfoInsert.add(varProfessionalInfo);    
        }

        insert listProfessionalInfoInsert;

        for(ProfessionalInfo__c varProfessionalInfo : listProfessionalInfoInsert)
        {
            varProfessionalInfo.JobTitle__c = 'Médico';
            varProfessionalInfo.EconomicActivity__c = 'MEDICINE';
            listProfessionalInfoUpdate.add(varProfessionalInfo);
        }
        
        update listProfessionalInfoUpdate;
    }
}