creditas-sf/force-app/main/default/objects/Account/fields/Birth_City__c.field-meta.xml
<CustomField>
    <fullName>Birth_City__c</fullName>
    <label>Birth City</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Father__c.field-meta.xml
<CustomField>
    <fullName>Father__c</fullName>
    <description>Filiação</description>
    <label>Nome do Pai</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/Mother__c.field-meta.xml
<CustomField>
    <fullName>Mother__c</fullName>
    <description>Filiação</description>
    <label>Nome da Mãe</label>
    <type>TextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CNHnumberPendingReason__c.field-meta.xml
<CustomField>
    <fullName>CNHnumberPendingReason__c</fullName>
    <label>Motivo Pendência do Número da CNH</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documento ilegível</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalControllerTest.cls
@isTest
public class ProposalControllerTest {

    @TestSetup
    static void makeData() 
    {
        Account accCustomer               = TestSetup.getAccount('Nivaele', false);
        accCustomer.RecordTypeId          = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
        accCustomer.Birth_City__c         = 'Monte Caramelo';
        accCustomer.Mother__c             = 'Juzimara da Silva';
        accCustomer.Father__c             = 'Josialdo Ferreira';
        insert accCustomer;

        Opportunity opportunity              = new Opportunity();
        opportunity.AccountId                = accCustomer.Id;
        opportunity.Name                     = 'Formalizacao Autofin';
        opportunity.StageName                = 'Em Análise de Formalização';
        opportunity.CloseDate                = Date.today().addDays(10);
        opportunity.ExternalTenant__c        = 'creditasbr';
        opportunity.ExternalVersion__c       = 1;      
        opportunity.RecordTypeId             = Util.getRecordTypeIdbyName('Opportunity', 'AutoFin');
        insert opportunity;
    }

    @isTest
    private static void getReasonTest(){
        String returnReason;
        Test.startTest();
            returnReason = ProposalController.getReason('PersonalDataSection__c','CNHnumberPendingReason__c');
        Test.stopTest();

        System.assertNotEquals('[]', returnReason, 'Should have returned String');
    }

    @isTest
    private static void getReasonWithParamsBlank(){
        String returnReason;
        Test.startTest();
            returnReason = ProposalController.getReason('', '');
        Test.stopTest();
        System.assertEquals('[]', returnReason, 'Should have returned empty list');
    }
    
    @isTest
    private static void getReasonObjectError(){
        String returnReason;
        Test.startTest();
            returnReason = ProposalController.getReason('abc','def');   
        Test.stopTest();
        System.assertEquals('[]', returnReason, 'Should have returned empty list');
    }
    
    @isTest
    private static void getReasonFieldError(){
        String returnReason;
        Test.startTest();
            returnReason = ProposalController.getReason('PersonalDataSection__c','def');   
        Test.stopTest();
        System.assertEquals('[]', returnReason, 'Should have returned empty list');
    }

    @isTest
    private static void startCopySuccess()
    {
        Account acc = [SELECT Id, Name, Birth_City__c, Mother__c, Father__c FROM Account LIMIT 1];
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1]; 

        Test.startTest();
            ProposalController.createNewInstance(acc.Id, opp.Id);   
        Test.stopTest();

        PersonalDataSection__c personalSection = [SELECT Id, Name__c FROM PersonalDataSection__c LIMIT 1];

        System.assertEquals(acc.Name, personalSection.Name__c, 'Field value should be the same');
    }

    @isTest
    public static void startCopyFail()
    {
        Exception testException;
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Contact newContact = new Contact();
        newContact.LastName = 'TesteContato';
        newContact.AccountId = acc.Id;
        insert newContact;
        
        Test.startTest();
        try {
            ProposalController.createNewInstance(acc.Id, newContact.Id);
        } catch(Exception e) {
            testException = e;
        }
        Test.stopTest();

        System.assertEquals('List has no rows for assignment to SObject', testException.getMessage(), 'Wrong exception Thrown.');
    }

    
}