creditas-sf/force-app/main/default/objects/Account/fields/CompanyStatus__c.field-meta.xml
<CustomField>
    <fullName>CompanyStatus__c</fullName>
    <description>Status da Empresa</description>
    <label>Status da empresa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ACTIVE</fullName>
            </value>
            <value>
                <fullName>INACTIVE</fullName>
            </value>
            <value>
                <fullName>PENDING</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/enabledProducts__c.field-meta.xml
<CustomField>
    <fullName>enabledProducts__c</fullName>
    <description>Produtos habilitados para a Empresa</description>
    <label>Produtos habilitados</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>STORE</fullName>
            </value>
            <value>
                <fullName>PAYROLL</fullName>
            </value>
            <value>
                <fullName>SALARY_ADVANCE</fullName>
            </value>
            <value>
                <fullName>CREDIT_CARD</fullName>
            </value>
            <value>
                <fullName>BENEFITS_CARD</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/LegalName__c.field-meta.xml
<CustomField>
    <fullName>LegalName__c</fullName>
    <label>LegalName</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Juridica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Juridica</fullName>
    <active>true</active>
    <label>Pessoa Jurídica</label>
</RecordType>

creditas-sf/force-app/main/default/classes/AccountCompanyIntegrationService.cls
public with sharing class AccountCompanyIntegrationService {

    public static Database.UpsertResult upsertCompany(AccountCompanyIntegrationVO request){

        Datetime createdAtDateTime = formatDatetime(request.createdAt);
        Datetime updatedAtDateTime = formatDatetime(request.updatedAt);           
        String recordTypeAcc = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');
        String products;
        if(request?.enabledProducts != null && !request.enabledProducts.isEmpty() && request.enabledProducts.size() > 1){
            products = String.join(request.enabledProducts,';');
        } else if (!request.enabledProducts.isEmpty()){
            products = request?.enabledProducts[0];
        }      

        Account newAcc = new Account(
            ExternalId__c           = request.Id,
            ExternalVersion__c		= decimal.valueOf(request.version),
            CompanyStatus__c		= request.status,
            ExternalCreationDate__c	= createdAtDateTime,
            ExternalUpdatedDate__c	= updatedAtDateTime,
            DocumentNumber__c		= request.mainDocument.code,
            DocumentType__c			= request.mainDocument.type,
            Name					= request.businessName,
            LegalName__c			= request.legalName,
            enabledProducts__c		= products,
            RecordTypeId            = recordTypeAcc
        );

        Schema.SObjectField externalField = Account.Fields.ExternalId__c;

        Database.upsertResult upsertResult = Database.upsert(newAcc, externalField, false);
        return upsertResult;
    }

    @TestVisible
    private static Datetime formatDatetime(String aDatetime){

        if(String.isBlank(aDatetime)){
            return Datetime.now();
        }
        List<String> dateParts = aDatetime.split('T');
        String part1 = dateParts[0];
        String part2 = dateParts[1].split('\\.')[0];
        String formatedDatetime = part1 + ' ' + part2;        

        return Datetime.valueOf(formatedDatetime);
    }
}