creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthLowerLimit__c</fullName>
    <label>Patrimônio líquido mínimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthUpperLimit__c</fullName>
    <label>NetWorthUpperLimit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Recurso_Financeiro__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Quantia referente ao registro que está sendo cadastrado</description>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditas-mx</fullName>
            </value>
            <value>
                <fullName>creditas-br</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ProfessionalInfo__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalInfo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Emprego</label>
    <referenceTo>ProfessionalInfo__c</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do recurso que está sendo registrado</description>
    <label>Tipo de Recurso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>PRESUMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>CONFIRMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>NET_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>LAND</fullName>
            </value>
            <value>
                <fullName>CONDOMINIUM_HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL_ROOM</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>MOTORCYCLE</fullName>
            </value>
            <value>
                <fullName>QUADRICYCLE</fullName>
            </value>
            <value>
                <fullName>TRUCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Outros.recordType-meta.xml
<RecordType>
    <fullName>Outros</fullName>
    <active>true</active>
    <label>Outros</label>
</RecordType>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ConfirmedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda confirmada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeStatus__c</fullName>
    <label>Status da renda mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeStatus__c</fullName>
    <label>Status da renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/NetWorthStatus__c.field-meta.xml
<CustomField>
    <fullName>NetWorthStatus__c</fullName>
    <label>Status do patrimônio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/PresumedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>PresumedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda considerada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationStatus__c</fullName>
    <label>Status da situação profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionStatus__c</fullName>
    <label>Status da profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/MinimalRequiredIncome__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncome__c</fullName>
    <label>Renda Mínima</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <label>JobTitle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>FREELANCER</fullName>
            </value>
            <value>
                <fullName>CIVIL_SERVANT</fullName>
            </value>
            <value>
                <fullName>RETIRED</fullName>
            </value>
            <value>
                <fullName>BUSINESSMAN</fullName>
            </value>
            <value>
                <fullName>SELF_EMPLOYED</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalIncomeDataControllerTest.cls
@isTest
public with sharing class ProposalIncomeDataControllerTest 
{
    @TestSetup
    static void makeData() { 
        Account varAccount = TestSetup.getAccount('Nivaele', false);
        varAccount.NetWorthLowerLimit__c = 20000;
        varAccount.NetWorthUpperLimit__c = 30000;
        insert varAccount;

        Opportunity opportunity              = new Opportunity();
        opportunity.AccountId                = varAccount.Id;
        opportunity.MinimalRequiredIncome__c = 3000;
        opportunity.Name                     = 'Formalizacao Autofin';
        opportunity.StageName                = 'Novo';
        opportunity.CloseDate                = Date.today().addDays(10);
        opportunity.ExternalTenant__c        = 'creditasbr';
        opportunity.ExternalVersion__c       = 1;      
        opportunity.RecordTypeId             = Util.getRecordTypeIdbyName('Opportunity', 'AutoFin');
        insert opportunity;
        
        ProfessionalInfo__c professionalInfo = new ProfessionalInfo__c();
        professionalInfo.Account__c          = varAccount.Id;
        professionalInfo.Status__c           = 'CLT';
        professionalInfo.JobTitle__c         = 'Engenheiro';
        insert professionalInfo;

        FinancialResources__c monthlyIncome = new FinancialResources__c();
        monthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        monthlyIncome.Type__c               = 'MONTHLY_INCOME';
        monthlyIncome.Amount__c             = 5000;
        insert monthlyIncome;

        FinancialResources__c confirmedMonthlyIncome = new FinancialResources__c();
        confirmedMonthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        confirmedMonthlyIncome.Type__c               = 'CONFIRMED_MONTHLY_INCOME';
        confirmedMonthlyIncome.Amount__c             = 4500;
        insert confirmedMonthlyIncome;

        FinancialResources__c presumedMonthlyIncome = new FinancialResources__c();
        presumedMonthlyIncome.RecordTypeId          = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        presumedMonthlyIncome.Type__c               = 'PRESUMED_MONTHLY_INCOME';
        presumedMonthlyIncome.Amount__c             = 4800;
        insert presumedMonthlyIncome;

        AccountFinancialRelationship__c accFinRel1 = new AccountFinancialRelationship__c();
        accFinRel1.Account__c                      = varAccount.Id;
        accFinRel1.Recurso_Financeiro__c           = monthlyIncome.Id;
        insert accFinRel1;

        AccountFinancialRelationship__c accFinRel2 = new AccountFinancialRelationship__c();
        accFinRel2.Account__c                      = varAccount.Id;
        accFinRel2.Recurso_Financeiro__c           = presumedMonthlyIncome.Id;
        insert accFinRel2;

        AccountFinancialRelationship__c accFinRel3 = new AccountFinancialRelationship__c();
        accFinRel3.Account__c                      = varAccount.Id;
        accFinRel3.Recurso_Financeiro__c           = confirmedMonthlyIncome.Id;
        insert accFinRel3;

        IncomeDataSection__c incomeDataSection              = new IncomeDataSection__c();
        incomeDataSection.Opportunity__c                    = opportunity.Id;
        incomeDataSection.ProfessionalSituationStatus__c    = 'Aprovar';
        incomeDataSection.ProfessionStatus__c               = 'Aprovar';
        incomeDataSection.NetWorthStatus__c                 = 'Aprovar';
        incomeDataSection.MonthlyIncomeStatus__c            = 'Aprovar';
        incomeDataSection.MinimalRequiredIncomeStatus__c    = 'Aprovar';
        incomeDataSection.PresumedMonthlyIncomeStatus__c    = 'Aprovar';
        incomeDataSection.ConfirmedMonthlyIncomeStatus__c   = 'Aprovar';
        insert incomeDataSection;
    }

    @isTest
    static void getIncomeDetailsTest() 
    {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Account acc = [SELECT Id FROM Account LIMIT 1];

        Map<String, SObject> result = new Map<String, SObject>();

        Test.startTest();
        result = ProposalIncomeDataController.getIncomeDetails(acc.Id, opp.Id);
        Test.stopTest();

        IncomeDataSection__c   incomeSection    = (IncomeDataSection__c)    result.get('INCOME_SECTION');
        ProfessionalInfo__c    professionalInfo = (ProfessionalInfo__c)     result.get('PROFESSIONAL_SECTION');
        Opportunity            minimalIncome    = (Opportunity)             result.get('MINIMAL_INCOME'); 
        Account                networth         = (Account)                 result.get('NETWORTH_INCOME');
        FinancialResources__c  monthlyIncome    = (FinancialResources__c)   result.get('MONTHLY_INCOME');
        FinancialResources__c  presumedIncome   = (FinancialResources__c)   result.get('PRESUMED_MONTHLY_INCOME');
        FinancialResources__c  confirmedIncome  = (FinancialResources__c)   result.get('CONFIRMED_MONTHLY_INCOME');

        System.assertEquals('Aprovar', incomeSection.ProfessionalSituationStatus__c, 'Incorrect IncomeDataSection value');
        System.assertEquals('Engenheiro', professionalInfo.JobTitle__c, 'Incorrect Job title value');
        System.assertEquals(3000, minimalIncome.MinimalRequiredIncome__c, 'Incorrect minimal income value');
        System.assertEquals(20000, networth.NetWorthLowerLimit__c, 'Incorrect networth lower limit value');
        System.assertEquals(30000, networth.NetWorthUpperLimit__c, 'Incorrect networth upper limit value');
        System.assertEquals(5000, monthlyIncome.Amount__c, 'Incorrect monthly income value');
        System.assertEquals(4800, presumedIncome.Amount__c, 'Incorrect presumed income value');
        System.assertEquals(4500, confirmedIncome.Amount__c, 'Incorrect confirmed income value');
    }

    @isTest
    static void getIncomeDetailsEmptyTest() 
    {
        Account acc = TestSetup.getAccount('Lenilson', false);
        acc.DocumentNumber__c = '34763590006';
        insert acc;

        Opportunity opp = TestSetup.getOpportunity(acc.Id, true);

        Map<String, SObject> result = new Map<String, SObject>();

        Test.startTest();
        result = ProposalIncomeDataController.getIncomeDetails(acc.Id, opp.Id);
        Test.stopTest();

        IncomeDataSection__c   incomeSection    = (IncomeDataSection__c)    result.get('INCOME_SECTION');
        ProfessionalInfo__c    professionalInfo = (ProfessionalInfo__c)     result.get('PROFESSIONAL_SECTION');
        Opportunity            minimalIncome    = (Opportunity)             result.get('MINIMAL_INCOME'); 
        Account                networth         = (Account)                 result.get('NETWORTH_INCOME');
        FinancialResources__c  monthlyIncome    = (FinancialResources__c)   result.get('MONTHLY_INCOME');
        FinancialResources__c  presumedIncome   = (FinancialResources__c)   result.get('PRESUMED_MONTHLY_INCOME');
        FinancialResources__c  confirmedIncome  = (FinancialResources__c)   result.get('CONFIRMED_MONTHLY_INCOME');

        System.assertEquals(new IncomeDataSection__c(), incomeSection, 'Should have returned an empty Income Section');
        System.assertEquals(new ProfessionalInfo__c(), professionalInfo, 'Should have returned an empty professional info');
        System.assertEquals(null, monthlyIncome, 'Should have returned an empty monthly income');
        System.assertEquals(null, presumedIncome, 'Should have returned an empty presumed income');
        System.assertEquals(null, confirmedIncome, 'Should have returned an empty confirmed income');
    }

    @isTest
    static void saveIncomeSectionSuccess() 
    {   
        Exception testException;
        IncomeDataSection__c incomeSection = [SELECT Id, ProfessionStatus__c FROM IncomeDataSection__c LIMIT 1];
        ProfessionalInfo__c professionalInfo = [SELECT Id FROM ProfessionalInfo__c LIMIT 1];
        FinancialResources__c monthlyIncome = [SELECT Id, Type__c FROM FinancialResources__c WHERE Type__c = 'MONTHLY_INCOME' LIMIT 1];
        FinancialResources__c presumedIncome = [SELECT Id, Type__c FROM FinancialResources__c WHERE Type__c = 'PRESUMED_MONTHLY_INCOME' LIMIT 1];
        FinancialResources__c confirmedIncome = [SELECT Id, Type__c FROM FinancialResources__c WHERE Type__c = 'CONFIRMED_MONTHLY_INCOME' LIMIT 1];
        Account networth = [SELECT Id, NetWorthLowerLimit__c, NetWorthUpperLimit__c FROM Account LIMIT 1];
        Opportunity minimalIncome = [SELECT Id, MinimalRequiredIncome__c FROM Opportunity WHERE Name = 'Formalizacao Autofin' LIMIT 1];
        
        Map<String, SObject> payload = new Map<String, SObject>();

        payload.put('IncomeSection', incomeSection);
        payload.put('ProfessionalInfo', professionalInfo);
        payload.put('MonthlyIncomeInfo', monthlyIncome);
        payload.put('PresumedMonthlyIncomeInfo', presumedIncome);
        payload.put('ConfirmedMonthlyIncomeInfo', confirmedIncome);
        payload.put('NetworthIncomeInfo', networth);
        payload.put('MinimalRequiredIncome', minimalIncome);

        Test.startTest();
        try {
            ProposalIncomeDataController.saveIncomeDataSection(payload);
        } catch(Exception e) {
            testException = e;
        }
        Test.stopTest();

        System.assertEquals(null, testException, 'It was not supposed to return an exception.');
    }

    
    @isTest
    static void saveIncomeSectionFail() 
    {
        Exception testException;

        IncomeDataSection__c incomeSection = [SELECT Id, ProfessionStatus__c FROM IncomeDataSection__c LIMIT 1];
        incomeSection.ProfessionStatus__c = 'Rejeitar';

        FinancialResources__c monthlyIncome = new FinancialResources__c();
        Account networth = new Account();
        Opportunity minimalIncome = new Opportunity();

        Map<String, SObject> payload = new Map<String, SObject>();

        payload.put('IncomeSection', incomeSection);
        payload.put('MonthlyIncomeInfo', monthlyIncome);
        payload.put('NetworthIncomeInfo', networth);
        payload.put('MinimalRequiredIncome', minimalIncome);

        Test.startTest();
        try {
            ProposalIncomeDataController.saveIncomeDataSection(payload);
        } catch(Exception e) {
            testException = e;
        }
        Test.stopTest();

        IncomeDataSection__c incomeUpdated  = [SELECT Id, ProfessionStatus__c FROM IncomeDataSection__c LIMIT 1];

        System.assertEquals('Attempted to upsert a null list', testException.getMessage(), 'The payload should not be null.');
        System.assertEquals('Aprovar', incomeUpdated.ProfessionStatus__c, 'Returned a wrong value for professional status');
    }
}