creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <formula>TEXT(Account.DocumentType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo do documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/TaskDetails__c.object-meta.xml
<CustomObject>
    <label>Detalhe da Tarefa</label>
    <nameField>
        <label>Detalhe da Tarefa</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Detalhes da Tarefa</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOME</fullName>
                <default>true</default>
                <label>HOME</label>
            </value>
            <value>
                <fullName>AUTOFIN</fullName>
            </value>
            <value>
                <fullName>ATWORK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>Task Type</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetails__c/fields/WorkflowKey__c.field-meta.xml
<CustomField>
    <fullName>WorkflowKey__c</fullName>
    <label>Workflow Key</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/TaskDetailSettings__c.object-meta.xml
<CustomObject>
    <label>Task Detail Settings</label>
    <nameField>
        <displayFormat>TD-{00000}</displayFormat>
        <label>TaskDetailSettings Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Task Detail Settings</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/CheckboxGroupValues__c.field-meta.xml
<CustomField>
    <fullName>CheckboxGroupValues__c</fullName>
    <label>Checkbox Group Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/DisplaySequence__c.field-meta.xml
<CustomField>
    <fullName>DisplaySequence__c</fullName>
    <label>DisplaySequence</label>
    <precision>18</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldKey__c.field-meta.xml
<CustomField>
    <fullName>FieldKey__c</fullName>
    <label>FieldKey</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldMask__c.field-meta.xml
<CustomField>
    <fullName>FieldMask__c</fullName>
    <label>FieldMask</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldName__c.field-meta.xml
<CustomField>
    <fullName>FieldName__c</fullName>
    <label>FieldName</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/FieldType__c.field-meta.xml
<CustomField>
    <fullName>FieldType__c</fullName>
    <label>FieldType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Checkbox</fullName>
            </value>
            <value>
                <fullName>Currency</fullName>
            </value>
            <value>
                <fullName>Date</fullName>
            </value>
            <value>
                <fullName>Multi-picklist</fullName>
            </value>
            <value>
                <fullName>Number</fullName>
            </value>
            <value>
                <fullName>Picklist</fullName>
            </value>
            <value>
                <fullName>Relationship</fullName>
            </value>
            <value>
                <fullName>Text</fullName>
            </value>
            <value>
                <fullName>Header</fullName>
            </value>
            <value>
                <fullName>CheckboxGroup</fullName>
            </value>
            <value>
                <fullName>RadioGroup</fullName>
            </value>
            <value>
                <fullName>Datetime</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/MappedField__c.field-meta.xml
<CustomField>
    <fullName>MappedField__c</fullName>
    <label>Mapped Field</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/NumberPrecision__c.field-meta.xml
<CustomField>
    <fullName>NumberPrecision__c</fullName>
    <label>Number Precision</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/PicklistValues__c.field-meta.xml
<CustomField>
    <fullName>PicklistValues__c</fullName>
    <label>Picklist Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/Product__c.field-meta.xml
<CustomField>
    <fullName>Product__c</fullName>
    <label>Product</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>HOME</fullName>
                <default>true</default>
                <label>HOME</label>
            </value>
            <value>
                <fullName>AUTOFIN</fullName>
            </value>
            <value>
                <fullName>ATWORK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/RadioGroupValues__c.field-meta.xml
<CustomField>
    <fullName>RadioGroupValues__c</fullName>
    <label>Radio Group Values</label>
    <length>1000</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/ReadOnlyForProfiles__c.field-meta.xml
<CustomField>
    <fullName>ReadOnlyForProfiles__c</fullName>
    <label>Read Only For Profiles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[HOME] Analista de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Analista de GCA</fullName>
            </value>
            <value>
                <fullName>[HOME] Consultor(a) de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Coordenação de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de contratos e assinaturas</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Gerente de contrato e assinatura</fullName>
            </value>
            <value>
                <fullName>[HOME] Líder de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Líder de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Lider de GCA</fullName>
            </value>
            <value>
                <fullName>[AUTOFIN] Admin</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/RelatedObject__c.field-meta.xml
<CustomField>
    <fullName>RelatedObject__c</fullName>
    <label>Related Object</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/RequiredForProfiles__c.field-meta.xml
<CustomField>
    <fullName>RequiredForProfiles__c</fullName>
    <label>Required For Profiles</label>
    <type>MultiselectPicklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>[HOME] Analista de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Analista de GCA</fullName>
            </value>
            <value>
                <fullName>[HOME] Consultor(a) de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Coordenação de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de contratos e assinaturas</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Especialista de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Gerente de contrato e assinatura</fullName>
            </value>
            <value>
                <fullName>[HOME] Líder de Fechamento</fullName>
            </value>
            <value>
                <fullName>[HOME] Líder de formalização</fullName>
            </value>
            <value>
                <fullName>[HOME] Lider de GCA</fullName>
            </value>
            <value>
                <fullName>System Administrator</fullName>
            </value>
            <value>
                <fullName>[AUTOFIN] Admin</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/TaskType__c.field-meta.xml
<CustomField>
    <fullName>TaskType__c</fullName>
    <label>TaskType</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Validar Emissão da Minuta</fullName>
            </value>
            <value>
                <fullName>Condicionante de Fechamento para Emissão</fullName>
            </value>
            <value>
                <fullName>Condicionante de Formalização para Emissão</fullName>
            </value>
            <value>
                <fullName>Adiantar Minuta</fullName>
            </value>
            <value>
                <fullName>Confirmar Valores</fullName>
            </value>
            <value>
                <fullName>Atualizar Proposta Final de Crédito</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Fechamento</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Formalização</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão e Operações Cartorárias</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Jurídico</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Crédito</fullName>
            </value>
            <value>
                <fullName>Pendência de Emissão de Risco Imobiliário</fullName>
            </value>
            <value>
                <fullName>Emitir Minuta</fullName>
            </value>
            <value>
                <fullName>Conferir Minuta</fullName>
            </value>
            <value>
                <fullName>Validar Minuta com Credor</fullName>
            </value>
            <value>
                <fullName>Enviar Minuta Rascunho para o Cliente</fullName>
            </value>
            <value>
                <fullName>Ajustar Minuta</fullName>
            </value>
            <value>
                <fullName>Liberar Minuta Final</fullName>
            </value>
            <value>
                <fullName>Formalização - Nova proposta</fullName>
            </value>
            <value>
                <fullName>Formalização - Em análise</fullName>
            </value>
            <value>
                <fullName>Formalização - Pendência</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/TaskDetailSettings__c/fields/WorkflowKey__c.field-meta.xml
<CustomField>
    <fullName>WorkflowKey__c</fullName>
    <label>WorkflowKey</label>
    <length>100</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/TaskDetailsController.cls
/*********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Controller para o componente da página customizada de Tasks
* ================================================================================================================================
* History
* -------
* Test Class: TaskDetailsControllerTest
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       ?                       16/12/2021      Created     Inclui os métodos responsáveis por atualizar a página de Tasks com os campos
**********************************************************************************************************************************/
public with sharing class TaskDetailsController {
    
    @AuraEnabled(cacheable=false)
    public static String getRecordType(String taskId) {
        try{
            Id taskValidId = taskId;
            return [SELECT Id, Recordtype.DeveloperName FROM Task WHERE Id =: taskId LIMIT 1]?.RecordType.DeveloperName;
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }

    }

    @AuraEnabled(cacheable=false)
    public static Map<String,Object> getTaskDetails(String taskId) {
        try {
            Map<String, Object> mapResult = new Map<String, object>();
            Task task = [SELECT Id, TaskType__c, TaskDetails__c, Recordtype.DeveloperName FROM Task WHERE id = :taskId LIMIT 1];
            
            mapResult.put('Product',task.Recordtype.DeveloperName); 
            mapResult.put('TaskType',task.TaskType__c); 
    
            if(task != null && task.Recordtype.DeveloperName != null){
                List<TaskDetailsVO> lstTaskDetailSettingVO = getTaskDetailSettings(task.TaskType__c, task.Recordtype.DeveloperName.toUppercase());
                mapResult.put('TaskDetailSettings', lstTaskDetailSettingVO);
                
                if(task.TaskDetails__c != null){
                    List<SObject> recordTaskDetail = getRecordTaskDetails(task.TaskDetails__c);
                    mapResult.put('TaskDetails', recordTaskDetail);
                }
            }
            return mapResult;
            
        }catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static void updateRecordTask(String taskId, String taskDetailsId) {
        try {
            Id validTaskId = taskId;
            Id validTaskDetailsId = taskDetailsId;
            if(validTaskId != null && validTaskDetailsId != null){
                Task updateTask = new Task(Id = validTaskId);
                updateTask.TaskDetails__c = validTaskDetailsId;

                update updateTask;
            }
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=true)
    public static Opportunity getOpportunity(String Id) {

        Task varTask = [SELECT Id, TaskDetails__c, WhatId, AccountId FROM Task WHERE Id =: Id];

        Opportunity varOpportunity;
        String varObjectName;
        Id recordId;
        
        if(String.isNotBlank(varTask.whatId))
        {
            recordId = (Id) varTask.whatId;
            varObjectName = Util.getSObjectNameById(recordId);
    
            if(varObjectName.equals('Opportunity'))
            {
                varOpportunity = [SELECT Id, Name, Account.name, Account.DocumentType__c, Account.DocumentNumber__c, CreatedDate 
                                    FROM Opportunity
                                    WHERE Id = :varTask.WhatId];
            }
        } 

        return varOpportunity;
    }

    @AuraEnabled(cacheable=false)
    public static List<TaskDetailsVO> getTaskDetailSettings(String taskType, String recordTypeTask) {

        List<TaskDetailsVO> resultTaskDetailsVO = new List<TaskDetailsVO>();
        
        List<TaskDetailSettings__c> lstTaskSettings = [
            SELECT Id, Name, CurrencyIsoCode, Product__c, WorkflowKey__c, FieldKey__c, 
                FieldName__c, FieldType__c, RequiredForProfiles__c, ReadOnlyForProfiles__c, 
                RelatedObject__c, NumberPrecision__c, PicklistValues__c, MappedField__c, TaskType__c,
                DisplaySequence__c, FieldMask__c, CheckboxGroupValues__c, RadioGroupValues__c
            FROM TaskDetailSettings__c 
            WHERE TaskType__c = :taskType
            AND Product__c = :recordTypeTask
            ORDER BY DisplaySequence__c
        ];
            
        for(TaskDetailSettings__c currentFieldSettings : lstTaskSettings){

            TaskDetailsVO mappedFieldVO = new TaskDetailsVO();
            
            mappedFieldVO.fieldKey       = currentFieldSettings.FieldKey__c;
            mappedFieldVO.fieldName      = currentFieldSettings.FieldName__c;
            mappedFieldVO.fieldType      = currentFieldSettings.FieldType__c;
            mappedFieldVO.Id             = currentFieldSettings.id;
            mappedFieldVO.fieldMappedKey = currentFieldSettings.MappedField__c;
            mappedFieldVO.fieldMask      = (currentFieldSettings.FieldMask__c != null) ? currentFieldSettings.FieldMask__c : '';
            
            
            mappedFieldVO.isReadOnly = actionByProfile(currentFieldSettings.ReadOnlyForProfiles__c);
            mappedFieldVO.isRequired = actionByProfile(currentFieldSettings.RequiredForProfiles__c);

            if(currentFieldSettings.FieldType__c == 'Currency'){
                mappedFieldVO.isCurrency = true;
                mappedFieldVO.numberPrecision = (currentFieldSettings.NumberPrecision__c != null) ? currentFieldSettings.NumberPrecision__c : '0.01';
            } 
            else if(currentFieldSettings.FieldType__c == 'Multi-picklist'){
                mappedFieldVO.isMultiPicklist = true;
                mappedFieldVO.picklistValues = currentFieldSettings.PicklistValues__c != null ? currentFieldSettings.PicklistValues__c : '';
            } 
            else if(currentFieldSettings.FieldType__c == 'Picklist'){
                mappedFieldVO.isPicklist = true;
                mappedFieldVO.picklistValues = currentFieldSettings.PicklistValues__c != null ? currentFieldSettings.PicklistValues__c : '';
            } 
            else if(currentFieldSettings.FieldType__c == 'Checkbox'){
                mappedFieldVO.isCheckbox = true;
            }
            else if(currentFieldSettings.FieldType__c == 'Relationship'){
                mappedFieldVO.isRelationship = true;
                mappedFieldVO.relatedObject = currentFieldSettings.RelatedObject__c;
            }
            else if(currentFieldSettings.FieldType__c == 'Header'){
                mappedFieldVO.isHeader = true;
            }            
            else if(currentFieldSettings.FieldType__c == 'Number'){
                mappedFieldVO.isNumber = true;
                mappedFieldVO.numberPrecision = (currentFieldSettings.NumberPrecision__c != null) ? currentFieldSettings.NumberPrecision__c : '0';
            }           
            else if(currentFieldSettings.FieldType__c == 'CheckboxGroup'){
                mappedFieldVO.isCheckboxGroup = true;
                mappedFieldVO.checkboxGroupValues = currentFieldSettings.CheckboxGroupValues__c != null ? currentFieldSettings.CheckboxGroupValues__c : '';
            }
            else if(currentFieldSettings.FieldType__c == 'RadioGroup'){
                mappedFieldVO.isRadioGroup = true;
                mappedFieldVO.radioGroupValues = currentFieldSettings.RadioGroupValues__c != null ? currentFieldSettings.RadioGroupValues__c : '';
            }
            else {
                mappedFieldVO.isDefault = true;         
            }

            resultTaskDetailsVO.add(mappedFieldVO);
        }
        return resultTaskDetailsVO;
    }

    @AuraEnabled(cacheable=false)
    public static List<SObject> getRecordTaskDetails(String taskDetails){
        try {
            List<SObject> recordTaskDetail = new List<SObject>();
            DescribeSObjectResult describeResult = TaskDetails__c.getSObjectType().getDescribe();
            List<String> fieldNames = new List<String>( describeResult.fields.getMap().keySet() );
            Id taskDetailsId = taskDetails;
            String query =
            ' SELECT ' +
            String.join( fieldNames, ',' ) +
            ' FROM ' +
            describeResult.getName() +
            ' WHERE Id = :taskDetailsId';
            query = query + ' limit 1';

            recordTaskDetail = Database.query( query );
            return recordTaskDetail;
        } catch (Exception e) {
            throw new AuraHandledException(e.getMessage());
        }
    }

    @AuraEnabled(cacheable=false)
    public static Boolean actionByProfile(String profiles){
        if(String.isBlank(profiles)){
            return false;
        }
        
        List<String> lstProfiles = profiles.split(';');
        
        Id currentProfileId = userinfo.getProfileId();
        String currentProfileName = [SELECT Id, Name FROM Profile WHERE Id =: currentProfileId]?.Name;
        
        return lstProfiles.contains(currentProfileName);
    }    
}