creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Campo usado para registro do numero do documento que está sendo registrado.</description>
    <label>Número do documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de documento que está sendo cadastrado</description>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CURP</fullName>
            </value>
            <value>
                <fullName>PIS</fullName>
            </value>
            <value>
                <fullName>RNE</fullName>
            </value>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/CNH.recordType-meta.xml
<RecordType>
    <fullName>CNH</fullName>
    <active>true</active>
    <label>CNH</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/RG.recordType-meta.xml
<RecordType>
    <fullName>RG</fullName>
    <active>true</active>
    <label>RG</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <formula>TEXT(Account.DocumentType__c)</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Tipo do documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFStatus__c.field-meta.xml
<CustomField>
    <fullName>CPFStatus__c</fullName>
    <label>Status do CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/SObjectUtilsTest.cls
@isTest
public with sharing class SObjectUtilsTest {
    
    @TestSetup
    static void makeData(){
        Account varAccount = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opportunity        = new Opportunity();
        opportunity.AccountId          = varAccount.Id;
        opportunity.Name               = 'Teste';
        opportunity.StageName          = 'Novo';
        opportunity.CloseDate          = Date.today().addDays(10);
        opportunity.ExternalTenant__c  = 'creditasbr';
        opportunity.ExternalVersion__c = 1;      
        insert opportunity;
        
        Documents__c rgDocument      = new Documents__c();
        rgDocument.Account__c        = varAccount.Id;
        rgDocument.DocumentType__c   = 'RG';
        rgDocument.DocumentNumber__c = '43325578';
        rgDocument.RecordTypeId      = Util.getRecordTypeIdbyName('Documents__c', 'RG');
        insert rgDocument;

        Documents__c cnhDocument      = new Documents__c();
        cnhDocument.Account__c        = varAccount.Id;
        cnhDocument.DocumentType__c   = 'CNH';
        cnhDocument.DocumentNumber__c = '1123432432565';
        cnhDocument.RecordTypeId      = Util.getRecordTypeIdbyName('Documents__c', 'CNH');
        insert cnhDocument;
        
    }

    @isTest
    static void upsertRecordsSuccess() {
        List<Documents__c> documents = [SELECT Id, Name, DocumentType__c, DocumentNumber__c FROM Documents__c];
        Documents__c rg = new Documents__c();
        Documents__c cnh = new Documents__c();

        for(Documents__c document : documents) 
        {
            if(document.DocumentType__c.equals('RG')) 
            {
                rg = document;
                rg.DocumentNumber__c = '33222445';
            } else {
                cnh = document;
                cnh.DocumentNumber__c = '99984432';
            }
        }

        Test.startTest();
        SObjectUtils.upsertRecords(documents);
        Test.stopTest();

        System.assertEquals(rg.DocumentNumber__c, '33222445', 'RG number not successfully updated.');
    }

    @isTest
    static void upsertRecordSuccess() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        PersonalDataSection__c personalDataSection = new PersonalDataSection__c();
        personalDataSection.CPFStatus__c = 'Approved';
        personalDataSection.Opportunity__c = opp.Id;

        Test.startTest();
        SObjectUtils.upsertRecord(personalDataSection);
        Test.stopTest();

        System.assertEquals(personalDataSection.CPFStatus__c, 'Approved', 'CPFStatus with wrong value.');
    }

    @isTest
    static void upsertRecordsFail() {
        Account account = [SELECT Id FROM Account];
        List<Documents__c> documents = [SELECT Id, Account__c, DocumentType__c, Name FROM Documents__c WHERE DocumentType__c = 'RG'];

        String exceptionMessage = '';
        
        Test.startTest();
            try {
                documents[0].Account__c = '123456778';
                SObjectUtils.upsertRecords(documents);
            } catch (Exception e) {
                exceptionMessage = e.getMessage();
            }
        Test.stopTest();

        System.assertEquals('Invalid id: 123456778', exceptionMessage, 'Incorrect exception message.');
    }

    @isTest
    static void upsertRecordFail() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        PersonalDataSection__c personalDataSection = new PersonalDataSection__c();
        personalDataSection.CPFStatus__c = 'Aprovado';
        personalDataSection.Opportunity__c = opp.Id;

        String exceptionMessage = '';

        Test.startTest();
        try {
            SObjectUtils.upsertRecord(personalDataSection);
        } catch (Exception e) {
            exceptionMessage = e.getMessage();
        }
        Test.stopTest();

        System.assert( exceptionMessage != null);
    }
}