creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Documents__c/Documents__c.object-meta.xml
<CustomObject>
    <description>Objeto utilizado para registros das informações de documentos. Não usado para upload de arquivos.</description>
    <label>Documento</label>
    <nameField>
        <displayFormat>D-{00000000}</displayFormat>
        <label>Código do Documento</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Documentos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Documentos</relationshipLabel>
    <relationshipName>Documentos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <description>Campo usado para registro do numero do documento que está sendo registrado.</description>
    <label>Número do documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <description>Tipo de documento que está sendo cadastrado</description>
    <label>Tipo de Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CNH</fullName>
            </value>
            <value>
                <fullName>CURP</fullName>
            </value>
            <value>
                <fullName>PIS</fullName>
            </value>
            <value>
                <fullName>RNE</fullName>
            </value>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RG</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/IssueDate__c.field-meta.xml
<CustomField>
    <fullName>IssueDate__c</fullName>
    <description>Data de emissão do documento que está sendo registrado</description>
    <label>Data de expedição</label>
    <type>Date</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/Issuer__c.field-meta.xml
<CustomField>
    <fullName>Issuer__c</fullName>
    <description>Órgão emissor do documento que está sendo registrado</description>
    <label>Órgão Emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/fields/IssuerState__c.field-meta.xml
<CustomField>
    <fullName>IssuerState__c</fullName>
    <description>Estado onde o documento que está sendo cadastrado foi emitido</description>
    <label>Estado emissor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/CPF.recordType-meta.xml
<RecordType>
    <fullName>CPF</fullName>
    <active>true</active>
    <label>CPF</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Documents__c/recordTypes/RG.recordType-meta.xml
<RecordType>
    <fullName>RG</fullName>
    <active>true</active>
    <label>RG</label>
</RecordType>

creditas-sf/force-app/main/default/classes/DocumentsTriggerTest.cls
@isTest
private with sharing class DocumentsTriggerTest {

    @TestSetup
    static void makeData()
    {    
        Account account = AccountSetup.createAccount('Franscisco', 'Pessoa_Fisica');
        account.IsExternallySynched__c = true;
        insert account;
        
        Documents__c varDocument = DocumentSetup.generateDocment(account.Id,'CPF');
        insert varDocument;
    }

    @isTest
    static void updateIsExternallySync() 
    {
        Documents__c varDocument = [SELECT Account__c FROM Documents__c WHERE DocumentType__c = 'CPF' LIMIT 1]; 

        varDocument.IssueDate__c = Date.today().addDays(6);
        varDocument.IssuerState__c = 'MG';
        varDocument.DocumentNumber__c = DocumentGenerator.generateCPF();
        varDocument.Issuer__c = 'SSP';
    
        Test.startTest();
        update varDocument;
        Test.stopTest();

        Account varAccount = [SELECT isExternallySynched__C
                              FROM Account
                              WHERE Id =: varDocument.Account__c
                              LIMIT 1];

        System.assertEquals(false, varAccount.IsExternallySynched__c, 'O campo isExternallySync deveria ter mudado para false');
    }

    @isTest
    static void updateMultipleDocumentsSameAccount()
    {
        List<Documents__c> documentList = new List<Documents__c>();
        Documents__c documentCPF = [SELECT Account__c FROM Documents__c WHERE IssueDate__c = :Date.today() LIMIT 1];
        documentList.add(documentCPF);
        Documents__c documentRG = DocumentSetup.generateDocment(documentCPF.Account__c,'RG');
        insert documentRG;
        documentList.add(documentRG);

        for(Documents__c iDocument : documentList){
            iDocument.IssuerState__c = 'BA';
            iDocument.DocumentNumber__c = DocumentGenerator.generateCPF();
        }
        Test.startTest();
            update documentList;
        Test.stopTest();

        Account varAccount = [SELECT isExternallySynched__C
                              FROM Account
                              WHERE Id =: documentCPF.Account__c
                              LIMIT 1];

        System.assertEquals(false, varAccount.IsExternallySynched__c, 'O campo isExternallySync deveria ter mudado para false');

    }

        

}