creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/Custom_Field_Tracking_Map__mdt.object-meta.xml
<CustomObject>
    <description>Mapeamento de campos para sincronização personalizada de campos</description>
    <label>Custom Field Tracking Map</label>
    <pluralLabel>Customs Fields Tracking Map</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/CampoRastreado__c.field-meta.xml
<CustomField>
    <fullName>CampoRastreado__c</fullName>
    <label>CampoRastreado</label>
    <metadataRelationshipControllingField>Custom_Field_Tracking_Map__mdt.ObjetoRastreado__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map1</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/ObjetoRastreado__c.field-meta.xml
<CustomField>
    <fullName>ObjetoRastreado__c</fullName>
    <label>ObjetoRastreado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/Home.recordType-meta.xml
<RecordType>
    <fullName>Home</fullName>
    <active>true</active>
    <businessProcess>Home - Creditas</businessProcess>
    <label>Home</label>
</RecordType>

creditas-sf/force-app/main/default/classes/OpportunityTriggerControllerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Testing Class for the OpportunityTriggerController
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Nathalia Rosa           23/12/2021      Created     Testing Class for the OpportunityTriggerController
**********************************************************************************************************************************/
@isTest
public class OpportunityTriggerControllerTest {  
    
    private static final Id RECORDTYPE_HOME = Schema.SObjectType.Opportunity.getRecordTypeInfosByDeveloperName().get('Home').getRecordTypeId();

    @TestSetup
    static void makeData()
    {   //Account and Opportunity to create a role setting     
        Account varAccount = TestSetup.getAccount('Joao', false);
        varAccount.DocumentNumber__c = '276.050.350-04';       
        insert varAccount; 
        
        Opportunity varOpportunity1 = TestSetup.getOpportunity(varAccount.Id, true);
        varOpportunity1.Name = 'Joao'; 
        varOpportunity1.RecordTypeId = RECORDTYPE_HOME;
        update varOpportunity1; 
    }

    @isTest
    static void updateIsExternallySync() 
        
    {   //Create a setting of Account/Opportunity to update IsExternallySync field       
        String varSObjectApiName = 'Opportunity';
     
        Account varAccount = [SELECT Id, Name FROM Account LIMIT 1]; 
     
        Opportunity varOpportunity = [SELECT Id, ExternalId__c, isExternallySynched__C, ExternalVersion__c, ExternalTenant__c, Name, IsSynchEnabled__c, RecordTypeId
                                      FROM Opportunity 
                                      WHERE AccountId =: varAccount.id LIMIT 1];
        
        varOpportunity.ExternalId__c = '3213213231';
        varOpportunity.IsSynchEnabled__c = 'ENABLED';
        varOpportunity.RecordTypeId = RECORDTYPE_HOME; 
        varOpportunity.ExternalTenant__c = 'creditasbr';
     
     	Custom_Field_Tracking_Map__mdt newCustomMdt = new Custom_Field_Tracking_Map__mdt();
        newCustomMdt.CampoRastreado__c = 'IsSynchEnabled__c';
        newCustomMdt.ObjetoRastreado__c = 'IsSynchEnabled__c';
     
        Test.startTest();
        //Testing Update field
        try{ 
            varOpportunity.ExternalTenant__c = 'creditasmx';
            update varOpportunity;
        } catch (DMLException e) {
            System.debug('The following exception has occurred: ' + e.getMessage());
        } 
        
        Test.stopTest();
		//Assert for the field IsExternallySynched__c need to be false
        System.assertEquals(false, varOpportunity.IsExternallySynched__c, 'O campo isExternallySync deveria ter mudado para false');
        //Assert for the field IsSynchEnabled__c need to be ENABLED
        System.assertEquals('ENABLED', varOpportunity.IsSynchEnabled__c, 'O campo isSynchEnabled não foi mudado para Enabled');
    }  
}