creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/classes/SynchAccountDataControllerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Classe de teste para a classe SynchAccountDataController
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          28/10/2021      Created     Classe de teste para SynchAccountDataController
**********************************************************************************************************************************/
@isTest
public class SynchAccountDataControllerTest {
    
    @TestSetup
    static void makeData()
    {
        Account newAccount = new Account();
        newAccount.Name = 'New Account';
        newAccount.DocumentNumber__c = '58131786277';
        newAccount.IsExternallySynched__c = true;
        newAccount.RecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
        newAccount.IsSynchEnabled__c= '	ENABLED';
        insert(newAccount);
    }
    
    @isTest
   	static void getAccountSucess() 
    {             
        Account accId = [SELECT Id FROM Account];
        
        Test.startTest();
        Account responseAccount = SynchAccountDataController.getAccountData(accId.Id);
        Test.stopTest();
                
       	System.assertEquals(accId.Id, responseAccount.Id,'Same account should have returned');
    }

    @isTest
   	static void getAccountInvalidId() 
    {             
               
        Test.startTest();
        try{
            Account responseAccount = SynchAccountDataController.getAccountData('invalidId');
        }
        catch(Exception e){
            System.assertEquals(null, SynchAccountDataController.getAccountData('invalidId'),'null should have been returned');
        }
        Test.stopTest();
                
    }
    
    @isTest
    static void updateAccount() 
    {
        Account acc = [SELECT Id, IsSynchEnabled__c FROM Account];
        String beforeUpdate = acc.IsSynchEnabled__c;
       
        Test.startTest();
        SynchAccountDataController.checkSynchingField(acc);
        Test.stopTest();
    
        Account accUpdated = [SELECT Id, IsSynchEnabled__c FROM Account];
        System.assertNotEquals(beforeUpdate, accUpdated.IsSynchEnabled__c, 'Field IsSynchEnabled__c should have changed');
    }
}