creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditas-mx</fullName>
            </value>
            <value>
                <fullName>creditas-br</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/ExternalOpportunityTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityTenant__c</fullName>
    <label>ExternalOpportunityTenant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/ExternalOpportunityVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityVersion__c</fullName>
    <label>ExternalOpportunityVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityTenant__c</fullName>
    <label>ExternalOpportunityTenant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityVersion__c</fullName>
    <label>ExternalOpportunityVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>SOLIDARY_DEBTOR</fullName>
            </value>
            <value>
                <fullName>COLLATERAL_GUARANTOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/GarantiasTriggerTest.cls
/**********************************************************************************************************************************
* Copyright © 2022 Creditas
* ================================================================================================================================
* Purpose: Testing Class for the GarantiasTriggerController
(Covers the classes: GarantiasTriggerController and GarantiasTriggerService)
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Nathalia Rosa          14/02/2022      Created     Testing Class for the GarantiasTriggerController
**********************************************************************************************************************************/
@isTest
public class GarantiasTriggerTest {
    
    @TestSetup
    static void makeData()
    {   //Accounts to create a PRINCIPAL or CollateralGuarantor opportunity role setting       
        Account accountPrincipal = TestSetup.getAccount('Jose', true); 
        accountPrincipal.DocumentNumber__c = '079.485.450-85';
        accountPrincipal.isExternallySynched__C = true;
        update accountPrincipal;
            
        Account accountCollateralGuarantor = TestSetup.getAccount('Joao', true);        
        accountCollateralGuarantor.DocumentNumber__c = '891.582.300-17';
        accountCollateralGuarantor.isExternallySynched__C = true;
        update accountCollateralGuarantor;
        
        Account accountCollateralGuarantorToFailed = TestSetup.getAccount('Josimar', true);                     
       	accountCollateralGuarantorToFailed.DocumentNumber__c = '745.277.860-08';
       	accountCollateralGuarantorToFailed.isExternallySynched__C = true;
        update accountCollateralGuarantorToFailed;
        
       	//Opportunities to create a PRINCIPAL or CollateralGuarantor opportunity role setting
        Opportunity opportunityPrincipal = TestSetup.getOpportunity(accountPrincipal.Id, true);
        opportunityPrincipal.Name = 'Jose Principal';
        update opportunityPrincipal;
        
        Opportunity opportunityCollateralGuarantor = TestSetup.getOpportunity(accountCollateralGuarantor.Id, true);
        opportunityCollateralGuarantor.Name = 'Joao Collateral Guarantor';
        update opportunityCollateralGuarantor;
        
        Opportunity oppCollateralGuarantorToFailed = TestSetup.getOpportunity(accountCollateralGuarantorToFailed.Id, true);
        oppCollateralGuarantorToFailed.Name = 'Josimar';
        
        //Opportunity Roles to create a PRINCIPAL or CollateralGuarantor opportunity role setting
        OpportunityRole__c oppRolePrincipal = TestSetup.getOppRole(accountPrincipal, opportunityPrincipal, 'PRINCIPAL', false, true);
        
        OpportunityRole__c oppRoleCollateralGuarantor = TestSetup.getOppRole(accountCollateralGuarantor, opportunityCollateralGuarantor, 'COLLATERAL_GUARANTOR', false, true);
        
        OpportunityRole__c oppRoleCollateralGuarantorToFailed = TestSetup.getOppRole(accountCollateralGuarantorToFailed, oppCollateralGuarantorToFailed, 'PRINCIPAL', false, true);
        
        //Financial Resources to create a PRINCIPAL or CollateralGuarantor opportunity role setting    
        FinancialResources__c financialResourcesPrincipal = TestSetup.getNewFinRes('Recurso Financeiro', true);          
        upsert financialResourcesPrincipal;
        
        FinancialResources__c finResourcesCollateralGuarantor = TestSetup.getNewFinRes('Recurso Collateral Guarantor', true);
        upsert finResourcesCollateralGuarantor;
        
        FinancialResources__c finResourcesToFailed = TestSetup.getNewFinRes('Recurso Financeiro To Failed', true); 
        upsert finResourcesToFailed;
        
        //Create Garantias to test updateIsExternallySync method
        Garantias__c guaranteesCollateralGuarantor = TestSetup.getGuarantees(accountCollateralGuarantor, opportunityCollateralGuarantor, finResourcesCollateralGuarantor, true);
  
    }
    
    @isTest
    static void insertGuaranteeFailed() 
    {   //Create a setting of Account/Opportunity and Opportunity Role with Role__c = Principal 
        Account accountToFailed = [SELECT Id FROM Account WHERE Name ='Josimar'];        

        List<Opportunity> opptyRes = [SELECT Id FROM Opportunity WHERE AccountId =: accountToFailed.Id ];
        
        OpportunityRole__c oppRoleToFailed = [SELECT Id, Role__c, Opportunity__c
                   					  FROM OpportunityRole__c 
                   					  WHERE Opportunity__c IN :opptyRes AND Role__c = 'PRINCIPAL'];
        
        //Create a new Guarantee with Principal Rolle__c 
        Garantias__c newGuarantee= new Garantias__c();      
        newGuarantee.Account__c = accountToFailed.Id;
        newGuarantee.Opportunity__c = oppRoleToFailed.Opportunity__c;
           
        Test.startTest();
        //Try insert a new Guarantee, the expected is Failed, because only FinancialResources owned by a Guarantee Guarantor can be added to guarantees
        try{
			insert newGuarantee; 
         } catch (DMLException e) {
    		System.debug('The following exception has occurred: ' + e.getMessage());
        }       
        Test.stopTest();
        
        //Assert need to be 0, because a insertion of a new Guarantee with Rolle__c = PRINCIPAL not be permited by Trigger
		List<Garantias__c> listGuarantee = [SELECT Id FROM Garantias__c WHERE Account__c =: accountToFailed.Id LIMIT 1];  
        System.assertEquals(0, listGuarantee.Size(),'The guarantee was created, when it shouldnt, because only FinancialResources owned by a Collateral Guarantor can be added');
    }
    
    @isTest
    static void insertUpdateGuaranteeSucess() 
    {	//Create a setting of Account/Opportunity and Opportunity Role with Role__c = COLLATERAL_GUARANTOR 
        Account accountSuccess = [SELECT Id FROM Account WHERE Name ='Joao'];
        FinancialResources__c financialResourcesSuccess = [SELECT Id FROM FinancialResources__c LIMIT 1];       

        List<Opportunity> opportunitySuccess = [SELECT Id FROM Opportunity WHERE AccountId =: accountSuccess.Id];
        OpportunityRole__c oppRoleCollateralGuarantor = [SELECT Id, Role__c, Opportunity__c
                                                          FROM OpportunityRole__c 
                                                          WHERE Opportunity__c IN :opportunitySuccess AND Role__c = 'COLLATERAL_GUARANTOR'];
        //Create a new Guarantee with Role__c = COLLATERAL_GUARANTOR
        Garantias__c newGuarantee = new Garantias__c();
        newGuarantee.Account__c = accountSuccess.Id;
        newGuarantee.Opportunity__c = oppRoleCollateralGuarantor.Opportunity__c;
        newGuarantee.Recurso_Financeiro__c = financialResourcesSuccess.Id; 
               
        Test.startTest();
        //Try insert a new Guarantee, the expected is Success
        try{
            insert newGuarantee; 
            system.debug('newGuarantee: ' + newGuarantee);
        } catch (DMLException e) {
    		System.debug('The following exception has occurred: ' + e.getMessage());
        }  
        
        Test.stopTest();
        
        //Assert need to be 1, because a insertion of a new Guarantee with Rolle__c = PRINCIPAL not be permited by Trigger
        List<Garantias__c> listGuarantee = [SELECT Id FROM Garantias__c WHERE Account__c =: accountSuccess.Id];         
        System.assertNotEquals(1,listGuarantee.size(),'Only financial resources owned by a Guarantee Guarantor can be added to guarantees');
    }
    
    @isTest
    static void updateIsExternallySync() 
    {  //Test when to update a Guarantees if the field IsExternallySynched__c will change to false
        Garantias__c guaranteesSuccess = [SELECT Id, Name, Opportunity__c, ExternalOpportunityTenant__c FROM Garantias__c LIMIT 1]; 
        guaranteesSuccess.ExternalOpportunityTenant__c = 'creditasbr';
        
        Test.startTest();
        guaranteesSuccess.ExternalOpportunityTenant__c = 'creditasmx';
        update guaranteesSuccess;
        Test.stopTest();
        
        //Assert for the field IsExternallySynched__c need to be false
        Opportunity opportunitySuccess = [SELECT Id, ExternalId__c, isExternallySynched__C, ExternalVersion__c, ExternalTenant__c, IsSynchEnabled__c
                              			  FROM Opportunity WHERE Id =: guaranteesSuccess.Opportunity__c LIMIT 1];
        System.assertEquals(false, opportunitySuccess.IsExternallySynched__c, 'The isExternallySync field should have changed to false');
    }

    @isTest
    static void updateMultipleOpportunityRole()
    {   //Test when to update a multiple Guarantees if the field IsExternallySynched__c will change to false
        Account accountSuccess = [SELECT Id, Name FROM Account WHERE Name ='Joao'];
       
        Opportunity opportunitySuccess = [SELECT Id, Name, isExternallySynched__c, ExternalId__c, ExternalTenant__c, ExternalVersion__c   
                                          FROM Opportunity 
                                          WHERE AccountId =: accountSuccess.Id 
                                          LIMIT 1];
        
        FinancialResources__c financialResourcesSuccess = [SELECT Id, Name FROM FinancialResources__c LIMIT 1];
        
        //Create a Lists to test update and Insert        
        List<Garantias__c> listGuaranteesInsert = new List<Garantias__c>();
        List<Garantias__c> listGuaranteesUpdate = new List<Garantias__c>();

        //Insert Guarantees and populate the list
        for (Integer i = 0; i < 10; i++) 
        {
            Garantias__c varGuarantees = new Garantias__c();
            varGuarantees.Account__c = accountSuccess.Id;
            varGuarantees.Opportunity__c = opportunitySuccess.Id;
            varGuarantees.Recurso_Financeiro__c = financialResourcesSuccess.Id;
            varGuarantees.ExternalOpportunityId__c = opportunitySuccess.ExternalId__c;
            varGuarantees.ExternalOpportunityTenant__c = opportunitySuccess.ExternalTenant__c;
            varGuarantees.ExternalOpportunityVersion__c = opportunitySuccess.ExternalVersion__c;  

            listGuaranteesInsert.add(varGuarantees);    
        }

        insert listGuaranteesInsert;		
         
        for(Garantias__c varGuarantees : listGuaranteesInsert)
        {
            listGuaranteesUpdate.add(varGuarantees);
        }
        
        Test.startTest();
        //Testing Update Multiple Guarantees
        update listGuaranteesUpdate;
        Test.stopTest();
		
        //Assert for the field IsExternallySynched__c need to be false
        Opportunity opportunityUpdate = [SELECT Id, Name, IsExternallySynched__c FROM Opportunity WHERE AccountId =: accountSuccess.Id LIMIT 1];
        System.assertEquals(false, opportunityUpdate.IsExternallySynched__c,'The isExternallySync field should have changed to false');
    }    
}