creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/SynchOpportunityDataControllerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Classe de teste para a classe SynchOpportunityDataController
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Erika Togniolo          17/12/2021      Created     Classe de teste para SynchOpportunityDataController
**********************************************************************************************************************************/
@isTest
public class SynchOpportunityDataControllerTest {
    
    @TestSetup
    static void makeData()
    {

        Account newAccount = new Account();
        newAccount.Name = 'New Account';
        newAccount.DocumentNumber__c = '58131786277';
        newAccount.IsExternallySynched__c = true;
        newAccount.RecordTypeId = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
        newAccount.IsSynchEnabled__c= '	ENABLED';
        insert(newAccount);
               
        Opportunity newOpp = new Opportunity();
        newOpp.AccountId = newAccount.Id;
        newOpp.Name = 'New Opp Synch';
        newOpp.IsExternallySynched__c = true;
        newOpp.IsSynchEnabled__c= '	ENABLED';
        newOpp.StageName = 'Novo';
        newOpp.CloseDate = Date.today().addDays(10);
        
        insert(newOpp);
    }

    @isTest
   	static void getOppData() 
    {
      	             
        Opportunity opp = [SELECT Id FROM Opportunity];
        
        Test.startTest();
        Opportunity res = SynchOpportunityDataController.getSyncInfo(opp.Id);
        Test.stopTest();
                
       	System.assertNotEquals(Null, res);
    }
    
    @isTest
    static void updateOpp() 
    {
        Opportunity opp = [SELECT Id, IsSynchEnabled__c, IsExternallySynched__c FROM Opportunity];
       
        Test.startTest();
        SynchOpportunityDataController.updateSynchingFields(opp);
        Test.stopTest();
    
        Opportunity oppUpdated = [SELECT Id, IsSynchEnabled__c, IsExternallySynched__c FROM Opportunity];
        System.assertNotEquals(opp, oppUpdated);
    }
}