creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/DocumentType__c.field-meta.xml
<CustomField>
    <fullName>DocumentType__c</fullName>
    <label>Tipo do Documento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF</fullName>
            </value>
            <value>
                <fullName>RFC</fullName>
            </value>
            <value>
                <fullName>CNPJ</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Juridica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Juridica</fullName>
    <active>true</active>
    <label>Pessoa Jurídica</label>
</RecordType>

creditas-sf/force-app/main/default/objects/SynchAccount__e/SynchAccount__e.object-meta.xml
<CustomObject>
    <description>Platform Event to Update the SynchAccount component</description>
    <label>SynchAccount</label>
    <pluralLabel>SynchAccounts</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/classes/AccountTriggerService.cls
public with sharing class AccountTriggerService {
    private static final string PF_ACCOUNT_RT = Util.getRecordTypeIdbyName('Account', 'Pessoa_Fisica');
    private static final string PJ_ACCOUNT_RT = Util.getRecordTypeIdbyName('Account', 'Pessoa_Juridica');
    private static final string CPF_ERROR_MESSAGE = 'O CPF não é válido.';
    private static final string CNPJ_ERROR_MESSAGE = 'O CNPJ não é válido.';

    public static void verifyValidDocument(List<Account> lstNewAccount)
    {
        for(Account varAccount : lstNewAccount)
        {
            if(String.isBlank(varAccount.DocumentNumber__c)) { continue; }

            verifyDocument(varAccount);
            if(PF_ACCOUNT_RT.equals(varAccount.RecordTypeId))
            {
                varAccount.DocumentNumber__c = Util.getMaskedCPF(varAccount.DocumentNumber__c);
                
            } else if(PJ_ACCOUNT_RT.equals(varaccount.RecordTypeId))
            {
                varAccount.DocumentNumber__c = Util.getMaskedCNPJ(varAccount.DocumentNumber__c);
            }
            
        }
    }

    private static void verifyDocument(Account varAccount)
    {
        if(!Util.isValidDocumentNumber(varAccount.DocumentNumber__c) && varAccount.DocumentType__c.equals('CPF'))
        {
            varAccount.DocumentNumber__c.addError(CPF_ERROR_MESSAGE);
        } else if(!Util.isValidDocumentNumber(varAccount.DocumentNumber__c) && varAccount.DocumentType__c.equals('CNPJ'))
        {
            varAccount.DocumentNumber__c.addError(CNPJ_ERROR_MESSAGE);
        }
    }

    public static void updateExternallySynced(List<Account> lstNewAccount){
        List<String> trackedFields = Util.returnCustomMetadaDataFieldApiName('Account');
        for(Account iAccount : lstNewAccount){
            if(TriggerHelper.changedField(iAccount, trackedFields)){
                iAccount.IsExternallySynched__c = false;
            }
        }
    }

    public static void firePlatformEventSynchAccount(List<Account> lstNewAccount){
        for(Account iAccount : lstNewAccount){
            if (iAccount.IsSynchEnabled__c == 'ENABLED') {               
                SynchAccount__e synch = new SynchAccount__e(); 
                EventBus.publish(synch);
            }
        }
    }
}