creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <formula>Account.DocumentNumber__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Número do Documento</label>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Oportunidade.</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
                <default>true</default>
                <label>DISABLED</label>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/OpportunityProcess__c.object-meta.xml
<CustomObject>
    <label>Processos da Oportunidade</label>
    <nameField>
        <label>Processos da Oportunidade Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Processos da Oportunidade</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityProcess__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Processos da Oportunidade</relationshipLabel>
    <relationshipName>Processos_da_Oportunidade</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityProcessTriggerControllerTest.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Testing Class for the OpportunityProcessTriggerController
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Nathalia Rosa           27/12/2021      Created     Testing Class for the OpportunityProcessTriggerController
**********************************************************************************************************************************/
@isTest
public class OpportunityProcessTriggerControllerTest {    
    
    @TestSetup
    static void makeData()
    {   
        //Accounts to create a setting to Update a OpportunityProcess      
        Account accountJose = TestSetup.getAccount('Jose', true); 
        accountJose.DocumentNumber__c = '276.050.350-04';
        accountJose.IsExternallySynched__c = true;
        update accountJose;
            
        Account accountJoao = TestSetup.getAccount('Joao', true);        
        accountJoao.DocumentNumber__c = '891.582.300-17';
        accountJoao.IsExternallySynched__c = true;
        update accountJoao;
        
        Account accountJosimar = TestSetup.getAccount('Josimar', true);                     
        accountJosimar.DocumentNumber__c = '745.277.860-08';
        accountJosimar.IsExternallySynched__c = true;
        update accountJosimar;
        
        //Opportunities to create a setting to updateIsExternallySync and updateMultipleOpportunityProcess
        Opportunity opportunityJose = TestSetup.getOpportunity(accountJose.Id, true);
        opportunityJose.Name = 'Joao';
        update opportunityJose;
        
        Opportunity opportunityJoao = TestSetup.getOpportunity(accountJoao.Id, true);
        opportunityJoao.Name = 'Jose';
        update opportunityJose;
        
        Opportunity opportunityJosimar = TestSetup.getOpportunity(accountJosimar.Id, true);
        opportunityJosimar.Name = 'Josimar';
        update opportunityJosimar;
		
        //Quotes to create a setting to updateIsExternallySync and updateMultipleOpportunityProcess
        OpportunityProcess__c opportunityProcess = new OpportunityProcess__c();         
        opportunityProcess.Opportunity__c = opportunityJose.Id; 
        opportunityProcess.ExternalOpportunityId__c = opportunityJose.ExternalId__c;
        opportunityProcess.ExternalOpportunityTenant__c = opportunityJose.ExternalTenant__c;
        opportunityProcess.ExternalOpportunityVersion__c = opportunityJose.ExternalVersion__c;
        insert opportunityProcess;

    }

    @isTest
    static void updateIsExternallySync() 
    {
        OpportunityProcess__c varGuarantees = [SELECT Id, Name, Opportunity__c FROM OpportunityProcess__c LIMIT 1]; 

        Test.startTest();
        update varGuarantees;
        Test.stopTest();
        
        Opportunity varOpportunity = [SELECT Id, ExternalId__c, isExternallySynched__C, ExternalVersion__c,
                                      ExternalTenant__c, IsSynchEnabled__c
                                      FROM Opportunity
                                      WHERE Id =: varGuarantees.Opportunity__c 
                                      LIMIT 1];
        System.assertEquals(false, varOpportunity.IsExternallySynched__c, 'The isExternallySync field should have changed to false');
    }

    @isTest
    static void updateMultipleOpportunityProcess()
    {	
        Account accountJose = [SELECT Id, Name FROM Account WHERE Name = 'Jose'];        
        Opportunity opportunityJose = [SELECT Id, Name, isExternallySynched__c, ExternalId__c, ExternalTenant__c, ExternalVersion__c   
                                      FROM Opportunity 
                                      WHERE AccountId =: accountJose.Id]; 
        
        Account accountJoao = [SELECT Id, Name FROM Account WHERE Name = 'Joao'];        
        Opportunity opportunityJoao = [SELECT Id, Name, isExternallySynched__c, ExternalId__c, ExternalTenant__c, ExternalVersion__c   
                                      FROM Opportunity 
                                      WHERE AccountId =: accountJoao.Id]; 
        
        Account accountJosimar = [SELECT Id, Name FROM Account WHERE Name = 'Josimar'];        
        Opportunity opportunityJosimar = [SELECT Id, Name, isExternallySynched__c, ExternalId__c, ExternalTenant__c, ExternalVersion__c   
                                      FROM Opportunity 
                                      WHERE AccountId =: accountJosimar.Id];
        
        
        List<OpportunityProcess__c> listOppProcessInsert = new List<OpportunityProcess__c>();
        List<OpportunityProcess__c> listOppProcessUpdate = new List<OpportunityProcess__c>();

        for (Integer i = 0; i < 10; i++) 
        {
            OpportunityProcess__c oppProcessJoao = new OpportunityProcess__c();            
            oppProcessJoao.Opportunity__c = opportunityJoao.Id;  
            oppProcessJoao.ExternalOpportunityId__c = opportunityJoao.ExternalId__c;
            oppProcessJoao.ExternalOpportunityTenant__c = opportunityJoao.ExternalTenant__c;
            oppProcessJoao.ExternalOpportunityVersion__c = opportunityJoao.ExternalVersion__c;         
            listOppProcessInsert.add(oppProcessJoao); 
            
            OpportunityProcess__c oppProcessJose = new OpportunityProcess__c();            
            oppProcessJose.Opportunity__c = opportunityJose.Id;  
            oppProcessJose.ExternalOpportunityId__c = opportunityJose.ExternalId__c;
            oppProcessJose.ExternalOpportunityTenant__c = opportunityJose.ExternalTenant__c;
            oppProcessJose.ExternalOpportunityVersion__c = opportunityJose.ExternalVersion__c;         
            listOppProcessInsert.add(oppProcessJose); 
            
            OpportunityProcess__c oppProcessJosimar = new OpportunityProcess__c();            
            oppProcessJosimar.Opportunity__c = opportunityJosimar.Id;  
            oppProcessJosimar.ExternalOpportunityId__c = opportunityJosimar.ExternalId__c;
            oppProcessJosimar.ExternalOpportunityTenant__c = opportunityJosimar.ExternalTenant__c;
            oppProcessJosimar.ExternalOpportunityVersion__c = opportunityJosimar.ExternalVersion__c;         
            listOppProcessInsert.add(oppProcessJosimar); 
        }

        insert listOppProcessInsert;

        for(OpportunityProcess__c varOppProcess : listOppProcessInsert)
        {
            listOppProcessUpdate.add(varOppProcess);
        }
        
        Test.startTest();
        update listOppProcessUpdate;
        Test.stopTest();
		
        Opportunity joaoUpdate = [SELECT Id, Name, IsExternallySynched__c FROM Opportunity WHERE AccountId =: accountJoao.Id];
        Opportunity joseUpdate = [SELECT Id, Name, IsExternallySynched__c FROM Opportunity WHERE AccountId =: accountJose.Id];
        Opportunity josimarUpdate = [SELECT Id, Name, IsExternallySynched__c FROM Opportunity WHERE AccountId =: accountJosimar.Id];

        System.assertEquals(false, joaoUpdate.IsExternallySynched__c, 'The isExternallySync field should have changed to false');
        System.assertEquals(false, joseUpdate.IsExternallySynched__c, 'The isExternallySync field should have changed to false');
        System.assertEquals(false, josimarUpdate.IsExternallySynched__c, 'The isExternallySync field should have changed to false');
    }   
}