creditas-sf/force-app/main/default/objects/Account/fields/DocumentNumber__c.field-meta.xml
<CustomField>
    <fullName>DocumentNumber__c</fullName>
    <label>Número do Documento</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/classes/AccountSetup.cls
/*******************************************************************************************************************************
 * Copyright © 2021 Creditas
 * =============================================================================================================================
 * Purpose: Classe para criação de Account para classe de teste
 * =============================================================================================================================
 * History
 * -------
 * VERSION  AUTHOR                          DATE        DETAIL      Description
 * 1.0      Guilherme Sampaio               19/01/2022  Created     Classe para criação de Account para classe de teste
********************************************************************************************************************************/
@isTest
public with sharing class AccountSetup {

    public static Account createAccount(String aName, String aRecordTypeDevName){
        String lAccRT = Util.getRecordTypeIdbyName('Account', aRecordTypeDevName);
        String lDocumentNumber;
        if(aRecordTypeDevName == 'Pessoa_Fisica'){
            lDocumentNumber = DocumentGenerator.generateCPF();
        }else {
            lDocumentNumber = DocumentGenerator.generateCNPJ();
        }
        return new Account(
            Name = aName,
            RecordTypeId = lAccRT,
            DocumentNumber__c = lDocumentNumber,
            IsExternallySynched__c = true
        );
    }

}