creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Brand__c.field-meta.xml
<CustomField>
    <fullName>Brand__c</fullName>
    <label>Marca</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Color__c.field-meta.xml
<CustomField>
    <fullName>Color__c</fullName>
    <label>Cor</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalCodeOrigin__c.field-meta.xml
<CustomField>
    <fullName>ExternalCodeOrigin__c</fullName>
    <externalId>true</externalId>
    <label>Código da Tabela FIPE</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditas-mx</fullName>
            </value>
            <value>
                <fullName>creditas-br</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/LicensingState__c.field-meta.xml
<CustomField>
    <fullName>LicensingState__c</fullName>
    <label>UF de licenciamento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>AC</fullName>
            </value>
            <value>
                <fullName>AL</fullName>
            </value>
            <value>
                <fullName>AM</fullName>
            </value>
            <value>
                <fullName>AP</fullName>
            </value>
            <value>
                <fullName>BA</fullName>
            </value>
            <value>
                <fullName>CE</fullName>
            </value>
            <value>
                <fullName>DF</fullName>
            </value>
            <value>
                <fullName>ES</fullName>
            </value>
            <value>
                <fullName>GO</fullName>
            </value>
            <value>
                <fullName>MA</fullName>
            </value>
            <value>
                <fullName>MT</fullName>
            </value>
            <value>
                <fullName>MS</fullName>
            </value>
            <value>
                <fullName>MG</fullName>
            </value>
            <value>
                <fullName>PA</fullName>
            </value>
            <value>
                <fullName>PB</fullName>
            </value>
            <value>
                <fullName>PR</fullName>
            </value>
            <value>
                <fullName>PE</fullName>
            </value>
            <value>
                <fullName>PI</fullName>
            </value>
            <value>
                <fullName>RJ</fullName>
            </value>
            <value>
                <fullName>RN</fullName>
            </value>
            <value>
                <fullName>RS</fullName>
            </value>
            <value>
                <fullName>RO</fullName>
            </value>
            <value>
                <fullName>RR</fullName>
            </value>
            <value>
                <fullName>SC</fullName>
            </value>
            <value>
                <fullName>SP</fullName>
            </value>
            <value>
                <fullName>SE</fullName>
            </value>
            <value>
                <fullName>TO</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ManufacturingYear__c.field-meta.xml
<CustomField>
    <fullName>ManufacturingYear__c</fullName>
    <label>Ano de Fabricação</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Model__c.field-meta.xml
<CustomField>
    <fullName>Model__c</fullName>
    <label>Modelo</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ModelYear__c.field-meta.xml
<CustomField>
    <fullName>ModelYear__c</fullName>
    <label>Ano do Modelo</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Plate__c.field-meta.xml
<CustomField>
    <fullName>Plate__c</fullName>
    <label>Placa</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ResourceKey__c.field-meta.xml
<CustomField>
    <fullName>ResourceKey__c</fullName>
    <label>ResourceKey</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Estado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantias</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/AutoFin.recordType-meta.xml
<RecordType>
    <fullName>AutoFin</fullName>
    <active>true</active>
    <businessProcess>AutoFin - Creditas</businessProcess>
    <label>AutoFin</label>
</RecordType>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalPersonId__c.field-meta.xml
<CustomField>
    <fullName>ExternalPersonId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OpportunityRoles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ReportedIncome__c.field-meta.xml
<CustomField>
    <fullName>ReportedIncome__c</fullName>
    <label>Renda informada</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Role__c.field-meta.xml
<CustomField>
    <fullName>Role__c</fullName>
    <label>Role</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>PRINCIPAL</fullName>
            </value>
            <value>
                <fullName>SOLIDARY_DEBTOR</fullName>
            </value>
            <value>
                <fullName>COLLATERAL_GUARANTOR</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/WarrantyDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Garantia</label>
    <nameField>
        <label>Seção Dados de Garantia Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Garantia</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/fields/PlateStatus__c.field-meta.xml
<CustomField>
    <fullName>PlateStatus__c</fullName>
    <label>Status da placa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/fields/RenavamStatus__c.field-meta.xml
<CustomField>
    <fullName>RenavamStatus__c</fullName>
    <label>Status do Renavam</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/WarrantyDataSection__c/fields/UFplateStatus__c.field-meta.xml
<CustomField>
    <fullName>UFplateStatus__c</fullName>
    <label>Status da UF da placa</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalWarrantyTest.cls
@isTest
private with sharing class ProposalWarrantyTest {

    @TestSetup
    static void makeData(){
        List<Account> accList = new List<Account>();
        Account acc = AccountSetup.createAccount('Jorge da Capacidoca', 'Pessoa_Fisica');
        acc.ExternalId__c = 'ID-JORGE-CAPACIDOCA';
        accList.add(acc);

        Account accRole = AccountSetup.createAccount('Fiador do Jorge', 'Pessoa_Fisica');
        accRole.ExternalId__c = 'ID-DO-FIADOR';
        accList.add(accRole);
        insert accList;
        List<Opportunity> oppList = new List<Opportunity>();
        Opportunity oppWithFinResource = OpportunitySetup.createOpportunity(acc.Id, 'AutoFin');
        oppWithFinResource.ExternalId__c = 'OPP-JORGE-CAPACIDOCA';
        oppList.add(oppWithFinResource);
        Opportunity oppWithoutFinResource = OpportunitySetup.createOpportunity(acc.Id, 'AutoFin');
        oppWithoutFinResource.ExternalId__c = 'OPP-JORGE-CAPACIDOCA-NO-RESOURCE';
        oppList.add(oppWithoutFinResource);
        insert oppList;
        FinancialResources__c finResource = FinancialResourceSetup.createFinancialResource('Auto');
        insert finResource;
        OpportunityRole__c oppRole = new OpportunityRole__c(
            Opportunity__c = oppWithFinResource.Id,
            Role__c = 'COLLATERAL_GUARANTOR',
            ExternalPersonId__c = accRole.Id,
            ExternalOpportunityId__c = 'OPP-JORGE-CAPACIDOCA',
            ReportedIncome__c = 666
        );
        insert oppRole;

        Garantias__c guarantee = new Garantias__c(
            Account__c = accRole.Id,
            Opportunity__c = oppWithFinResource.Id,
            Recurso_Financeiro__c = finResource.Id
        );
        insert guarantee;

        WarrantyDataSection__c dataSection = new WarrantyDataSection__c(
            UFplateStatus__c = 'Aprovado',
            RenavamStatus__c = 'Aprovado',
            PlateStatus__c = 'Aprovado',
            Opportunity__c = oppWithFinResource.Id
        );
        insert dataSection;

    }

    @isTest
    private static void testgetFinancialResourceSucess(){
        String oppId = [SELECT Id FROM Opportunity WHERE ExternalId__c = 'OPP-JORGE-CAPACIDOCA']?.Id;
        FinancialResources__c finBase = [SELECT ResourceKey__c,Plate__c,ModelYear__c,ManufacturingYear__c,Brand__c,Model__c,Color__c,LicensingState__c,State__c,ExternalCodeOrigin__c FROM FinancialResources__c];

        Test.startTest();
            FinancialResources__c getFin = ProposalWarrantyController.getFinancialResource(oppId);
        Test.stopTest();

        System.assertEquals(finBase.Plate__c, getFin.Plate__c, 'Wrong financial Resources queried');
        System.assertEquals(finBase.Brand__c, getFin.Brand__c, 'Wrong financial Resources queried');
        System.assertEquals(finBase.ResourceKey__c, getFin.ResourceKey__c, 'Wrong financial Resources queried');
    }

    @isTest
    private static void testgetFinancialResourceException(){
        String oppId = 'FAKE_OPP_ID';
        Exception testException;
        Test.startTest();
            try{
                FinancialResources__c getFin = ProposalWarrantyController.getFinancialResource(oppId);
            }catch(Exception e){
                testException = e;
            }
        Test.stopTest();
        System.assertEquals('Invalid id: FAKE_OPP_ID', testException.getMessage(), 'Wrong exception Thrown');
    }

    @isTest
    private static void testgetFinancialResourceEmptyId(){
        String oppId = [SELECT Id FROM Opportunity WHERE ExternalId__c = 'OPP-JORGE-CAPACIDOCA-NO-RESOURCE']?.Id;
        Test.startTest();
            
            FinancialResources__c getFin = ProposalWarrantyController.getFinancialResource(oppId);
            
        Test.stopTest();
        System.assertEquals(new FinancialResources__c(), getFin, 'should return empty FinancialResources__c');
    }

    @isTest
    private static void testSaveFinancialResourceSucess(){
        FinancialResources__c financialResource = FinancialResourceSetup.createFinancialResource('Auto');
        Test.startTest();
            Boolean operationSucess = ProposalWarrantyController.saveFinancialResource(financialResource);
        Test.stopTest();
        System.assert(operationSucess, 'Should be true');
        System.assertEquals(2, [SELECT Count() FROM FinancialResources__c], '2 Record should exist');
    }

    @isTest
    private static void testSaveFinancialResourceFail(){
        String autoRTId = Util.getRecordTypeIdbyName('FinancialResources__c', 'Auto');
        FinancialResources__c financialResource = new FinancialResources__c(Plate__c = 'DBZ-2077', RecordTypeId = autoRTId, ExternalTenant__c = 'blabla');
        Test.startTest();
            Boolean operationSucess = ProposalWarrantyController.saveFinancialResource(financialResource);
        Test.stopTest();
        System.debug(operationSucess);
        System.assert(!operationSucess, 'Should be false');
        System.assertEquals(1, [SELECT Count() FROM FinancialResources__c], '2 Record should exist');
    }

    @isTest
    private static void testgetWarrantyDataSectionSuccess(){
        String oppId = [SELECT Id FROM Opportunity WHERE ExternalId__c = 'OPP-JORGE-CAPACIDOCA']?.Id;
        WarrantyDataSection__c warrantyData = [SELECT UFplateStatus__c, RenavamStatus__c, PlateStatus__c FROM WarrantyDataSection__c WHERE Opportunity__c = :oppId];

        Test.startTest();
        WarrantyDataSection__c getWarrantyData = ProposalWarrantyController.getWarrantyDataSection(oppId);
        Test.stopTest();

        System.assertEquals(warrantyData.UFplateStatus__c, getWarrantyData.UFplateStatus__c, 'Wrong warranty data queried');
        System.assertEquals(warrantyData.RenavamStatus__c, getWarrantyData.RenavamStatus__c, 'Wrong warranty data queried');
        System.assertEquals(warrantyData.PlateStatus__c, getWarrantyData.PlateStatus__c, 'Wrong warranty data queried');
    }

    @isTest
    private static void testgetWarrantyDataSectionEmptyId(){
        String oppId = [SELECT Id FROM Opportunity WHERE ExternalId__c = 'OPP-JORGE-CAPACIDOCA-NO-RESOURCE']?.Id;

        Test.startTest();  
            WarrantyDataSection__c getWarrantyData = ProposalWarrantyController.getWarrantyDataSection(oppId);
        Test.stopTest();

        System.assertEquals(new WarrantyDataSection__c(), getWarrantyData, 'should return empty WarrantyDataSection__c');
    }

    @isTest
    private static void testgetWarrantyDataException(){
        String oppId = 'FAKE_WARRANTY_DATA_ID';
        Exception testException;
        Test.startTest();
            try{
                WarrantyDataSection__c getWarrantyData = ProposalWarrantyController.getWarrantyDataSection(oppId);
            }catch(Exception e){
                testException = e;
            }
        Test.stopTest();
        System.assertEquals('Invalid id: FAKE_WARRANTY_DATA_ID', testException.getMessage(), 'Wrong exception Thrown');
    }

    @isTest
    private static void testSaveWarrantyDataSucess(){
        String oppId = [SELECT Id FROM Opportunity WHERE ExternalId__c = 'OPP-JORGE-CAPACIDOCA-NO-RESOURCE']?.Id;
        WarrantyDataSection__c warrantyData = new WarrantyDataSection__c(UFplateStatus__c = 'Aprovado', Opportunity__c = oppId);
        Test.startTest();
            Boolean operationSucess = ProposalWarrantyController.saveWarrantyDataSection(warrantyData);
        Test.stopTest();
        System.assert(operationSucess, 'Should be true');
        System.assertEquals(2, [SELECT Count() FROM WarrantyDataSection__c], '2 Record should exist');
    }

    @isTest
    private static void testSaveWarrantyDataFail(){
        WarrantyDataSection__c warrantyData = new WarrantyDataSection__c(UFplateStatus__c = 'Aprovado');
        Test.startTest();
            Boolean operationSucess = ProposalWarrantyController.saveWarrantyDataSection(warrantyData);
        Test.stopTest();
        System.assert(!operationSucess, 'Should be false');
        System.assertEquals(1, [SELECT Count() FROM WarrantyDataSection__c], 'only 1 Record should exist');
    }
    
}