creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Recurso_Financeiro__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Quantia referente ao registro que está sendo cadastrado</description>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/AppraisalDate__c.field-meta.xml
<CustomField>
    <fullName>AppraisalDate__c</fullName>
    <description>Data de quando o bem foi avaliado.</description>
    <label>AppraisalDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/External_Version__c.field-meta.xml
<CustomField>
    <fullName>External_Version__c</fullName>
    <label>External Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/FinancialInstitution__c.field-meta.xml
<CustomField>
    <fullName>FinancialInstitution__c</fullName>
    <label>Instituição Financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Estado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Certificado.recordType-meta.xml
<RecordType>
    <fullName>Certificado</fullName>
    <active>true</active>
    <label>Certificado</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Imovel.recordType-meta.xml
<RecordType>
    <fullName>Imovel</fullName>
    <active>true</active>
    <label>Imóvel</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Outros.recordType-meta.xml
<RecordType>
    <fullName>Outros</fullName>
    <active>true</active>
    <label>Outros</label>
</RecordType>

creditas-sf/force-app/main/default/classes/IntegrationAsset.cls
@RestResource(urlMapping='/IntegrationAsset/*')
global without sharing class IntegrationAsset 
{
    public static final String VEHICLE_RECORD_TYPE_NAME = 'Auto';
    public static final String REAL_ESTATE_RECORD_TYPE_NAME = 'Imovel';
    public static final String CERTIFICATE_RECORD_TYPE_NAME = 'Certificado';
    public static final String OTHERS_RECORD_TYPE_NAME = 'Outros';

    @HttpPut
    global static void putMethod()
    {
        AssetIntegrationModel typedRequestBody = AssetIntegrationModel.parse(RestContext.request.requestBody.toString());

        Set<String> ownerExternalIds = new Set<String>();
        for (AssetIntegrationModel.OwnersModel owner : typedRequestBody.owners)
        {
            ownerExternalIds.add(owner.person.id);
        }

        Map<String, Account> accountExternalIdToAccountMap = new Map<String, Account>();
        for (Account acc : [SELECT Id, ExternalId__c FROM Account WHERE ExternalId__c IN :ownerExternalIds])
        {
            accountExternalIdToAccountMap.put(acc.ExternalId__c, acc);
        }
        if (accountExternalIdToAccountMap.isEmpty())
        {
            AssetResponseData ard = new AssetResponseData();
            ard.assetId = null;
            ard.message = 'The owner(s) was not found on Salesforce.';
    
            RestResponse res = RestContext.response;
            res.responseBody = Blob.valueOf(JSON.serialize(ard));
            res.statusCode = 400;

            return;
        }
        
        String recordTypeDeveloperName = '';
        if (typedRequestBody.type == 'VEHICLE') 
        {
            recordTypeDeveloperName = VEHICLE_RECORD_TYPE_NAME;
        } else if (typedRequestBody.type == 'REAL_ESTATE') 
        {
            recordTypeDeveloperName = REAL_ESTATE_RECORD_TYPE_NAME;
        } else if (typedRequestBody.type == 'CERTIFICATE') 
        {
            recordTypeDeveloperName = CERTIFICATE_RECORD_TYPE_NAME;
        } else 
        {
            recordTypeDeveloperName = OTHERS_RECORD_TYPE_NAME;
        }
        Id recordTypeId = Util.getRecordTypeIdbyName('FinancialResources__c', recordTypeDeveloperName);
        
        FinancialResources__c asset = upsertAsset(typedRequestBody, recordTypeId);

        upsertAccountFinancialRelationship(asset, typedRequestBody, accountExternalIdToAccountMap);

        AssetResponseData ard = new AssetResponseData();
        ard.assetId = asset.Id;
        ard.message = 'Asset upserted';

        RestResponse res = RestContext.response;
        res.responseBody = Blob.valueOf(JSON.serialize(ard));
        res.statusCode = 200;
    }

    private static FinancialResources__c upsertAsset(AssetIntegrationModel requestBody, Id recordTypeId)
    {
        FinancialResources__c assetToUpsert = new FinancialResources__c();
        if (recordTypeId != null)
        {
            assetToUpsert.recordTypeId = recordTypeId;
        }
        assetToUpsert.Id = [SELECT Id FROM FinancialResources__c WHERE ExternalId__c = :requestBody.id LIMIT 1]?.Id;
        assetToUpsert.ExternalId__c = requestBody.id;
        assetToUpsert.External_Version__c = requestBody.version;
        assetToUpsert.CurrencyIsoCode = requestBody.value.amount.currencyCode;
        assetToUpsert.Amount__c  = Decimal.valueOf(requestBody.value.amount.amount);
        assetToUpsert.AppraisalDate__c = Date.valueOf(requestBody.value.appraisalDate);
        assetToUpsert.FinancialInstitution__c = requestBody.alienation.financialInstitution;
        assetToUpsert.State__c = requestBody.assetDetail.state;
        assetToUpsert.ExternalCreationDate__c = Date.valueOf(requestBody.createdAt);
        assetToUpsert.ExternalUpdatedDate__c = Date.valueOf(requestBody.updatedAt);

        upsert assetToUpsert;

        return assetToUpsert;
    }

    private static void upsertAccountFinancialRelationship(FinancialResources__c asset, AssetIntegrationModel requestBody, Map<String, Account> accountExternalIdToAccountMap)
    {
        Map<String, AccountFinancialRelationship__c> externalOwnerIdToAssetRelationshipMap = new Map<String, AccountFinancialRelationship__c>();
        for(AccountFinancialRelationship__c accountRelation : [SELECT Id, Account__r.ExternalId__c, Recurso_Financeiro__c 
                                                                            FROM AccountFinancialRelationship__c 
                                                                            WHERE Recurso_Financeiro__c = :asset.Id])
        {
            externalOwnerIdToAssetRelationshipMap.put(accountRelation.Account__r.ExternalId__c, accountRelation);
        }

        List<AccountFinancialRelationship__c> ownerRelationshipsToUpsert = new List<AccountFinancialRelationship__c>();
        for (AssetIntegrationModel.OwnersModel owner : requestBody.owners)
        {
            if (!accountExternalIdToAccountMap.containsKey(owner.person.id))
            {
                continue;
            }
            AccountFinancialRelationship__c assetOwnerRelationship = new AccountFinancialRelationship__c();
            assetOwnerRelationship.Id = externalOwnerIdToAssetRelationshipMap.get(owner.person.id)?.Id;
            assetOwnerRelationship.Account__c = accountExternalIdToAccountMap.get(owner.person.id).Id;
            assetOwnerRelationship.Recurso_Financeiro__c = asset.Id;

            ownerRelationshipsToUpsert.add(assetOwnerRelationship);
        }

        upsert ownerRelationshipsToUpsert;
                                                   
    }

    public class AssetResponseData
    {
        public String assetId;
        public String message;
    }
}