creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>CommunicationContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Channel__c.field-meta.xml
<CustomField>
    <fullName>Channel__c</fullName>
    <label>Channel</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>WHATSAPP</fullName>
            </value>
            <value>
                <fullName>PHONE</fullName>
            </value>
            <value>
                <fullName>EMAIL</fullName>
            </value>
            <value>
                <fullName>SMS</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Code__c.field-meta.xml
<CustomField>
    <fullName>Code__c</fullName>
    <label>Contato</label>
    <length>150</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/ContactDetailsSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Contato</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Seção Dados de Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/MobileStatus__c.field-meta.xml
<CustomField>
    <fullName>MobileStatus__c</fullName>
    <label>Status do Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Contato</relationshipLabel>
    <relationshipName>ContactDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalContactDataControllerTest.cls
@isTest
public class ProposalContactDataControllerTest {
    @TestSetup
    static void makeData(){
        Account varAccount = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = varAccount.Id;
        opportunity.Name = 'Teste';
        opportunity.StageName = 'Novo';
        opportunity.CloseDate = Date.today().addDays(10);
        opportunity.ExternalTenant__c = 'creditasbr';
        opportunity.ExternalVersion__c = 1;      
        insert opportunity;
        
        CommunicationContacts__c communicationSMS = new CommunicationContacts__c(Account__c = varAccount.Id, Channel__c = 'SMS', Code__c = '11 911223344');
        CommunicationContacts__c communicationEMAIL = new CommunicationContacts__c(Account__c = varAccount.Id, Channel__c = 'EMAIL', Code__c = 'test@test.com');
        List<CommunicationContacts__c> communications = new List<CommunicationContacts__c>();
        communications.add(communicationSMS);
        communications.add(communicationEMAIL);
        insert communications;
        
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opportunity.Id, MobileStatus__c = 'Aprovar');
        insert contactDetail;
    }
    
    @isTest
    static void getCommunicationContactSuccess(){
        Account acc = [SELECT Id FROM Account LIMIT 1];
  		Map<String,CommunicationContacts__c> mapResultCommunications = new Map<String,CommunicationContacts__c>();
        
        Test.startTest();
        mapResultCommunications = ProposalContactDataController.getCommunicationContact(acc.Id);
        Test.stopTest();
        
        System.assertEquals('test@test.com', mapResultCommunications.get('EMAIL').Code__c ,'Incorrect email value');
        
    }
    
    @isTest
    static void getCommunicationContactFail(){
        String exceptionMessage = '';
        Map<String,CommunicationContacts__c> mapResultCommunications = new Map<String,CommunicationContacts__c>();
        
        Test.startTest();
        try{
            mapResultCommunications = ProposalContactDataController.getCommunicationContact('123456778');
        }catch(Exception e){
            exceptionMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals('Invalid id: 123456778', exceptionMessage, 'Incorrect exception message.');
    }
 
    @isTest
    static void getContactDetailsSuccess(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        Boolean exceptionOccurred = false;
        ContactDetailsSection__c mapResultCommunications = new ContactDetailsSection__c();
        
        Test.startTest();
        try{
            mapResultCommunications = ProposalContactDataController.getContactDetails(opp.Id);
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals('Aprovar', mapResultCommunications.MobileStatus__c,'Incorrect MobileStatus value'); 
    }
    
    @isTest
    static void getContactDetailsFail(){
        String exceptionMessage = '';
        ContactDetailsSection__c mapResultCommunications = new ContactDetailsSection__c();
        
        Test.startTest();
        try{
            mapResultCommunications = ProposalContactDataController.getContactDetails('123456778');
        }catch(Exception e){
            exceptionMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals('Invalid id: 123456778', exceptionMessage, 'Incorrect exception message.'); 
    }

    
    @isTest
    static void saveCommunicationContactsSuccess(){
        Boolean exceptionOccurred = false;
        Account acc = [SELECT Id FROM Account LIMIT 1];
        CommunicationContacts__c communicationSMS = new CommunicationContacts__c(Account__c = acc.Id, Channel__c = 'SMS', Code__c = '11 911223344');
        CommunicationContacts__c communicationEMAIL = new CommunicationContacts__c(Account__c = acc.Id, Channel__c = 'EMAIL', Code__c = 'test@test.com');
        List<CommunicationContacts__c> communications = new List<CommunicationContacts__c>();
        communications.add(communicationSMS);
        communications.add(communicationEMAIL);
        Test.startTest();
        try{
            ProposalContactDataController.saveCommunicationContacts(communications);
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals(false, exceptionOccurred,'Exception should not occur');
    }
    
    @isTest
    static void saveCommunicationContactsFail() {
        String exceptionMessage = '';
        Account acc = [SELECT Id FROM Account LIMIT 1];
        List<Account> accounts = new List<Account>();
		accounts.add(acc);
        
        Test.startTest();
        try{
            ProposalContactDataController.saveCommunicationContacts(accounts);
            
        }catch(Exception e) {
            exceptionMessage = e.getMessage();
        }

        Test.stopTest();
        
        System.assertEquals('Invalid conversion from runtime type List<Account> to List<CommunicationContacts__c>', exceptionMessage, 'Incorrect exception message.');
    }
    
    @isTest
    static void saveContactDetailsSectionSuccess(){
        Boolean exceptionOccurred = false;
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opp.Id, MobileStatus__c = 'Aprovar');
        
        Test.startTest();
        try{
            ProposalContactDataController.saveContactDetailsSection(contactDetail);
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        System.assertEquals(false, exceptionOccurred,'Exception should not occur');
    }
    
    @isTest
    static void saveContactDetailsSectionFail(){
        Boolean exceptionOccurred = false;
        String exceptionMessage = '';
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        Test.startTest();
        try{
            ProposalContactDataController.saveContactDetailsSection(acc);
        }catch(Exception e){
            exceptionOccurred = true;
            exceptionMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals('Invalid conversion from runtime type Account to ContactDetailsSection__c', exceptionMessage,'Expected a ContactDetailsSection__c record');
    }
}