creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/CommunicationContacts__c.object-meta.xml
<CustomObject>
    <label>CommunicationContact</label>
    <nameField>
        <label>Communication Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>CommunicationContacts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Contatos</relationshipLabel>
    <relationshipName>CommunicationContacts</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/CommunicationContacts__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/CommunicationContactTriggerService.cls
public with sharing class CommunicationContactTriggerService {
    
    public static void updateIsExternallySynced(List<CommunicationContacts__c> lstNewCommunicationContact, Map<Id, CommunicationContacts__c> mapOldCommunicationContact)
    {
        Util.updateIsExternallySynced('CommunicationContacts__c', lstNewCommunicationContact, mapOldCommunicationContact);
    }
    
    public static void updateAccountExternalFields(List<CommunicationContacts__c> lstNewCommunicationContact)
    {
        Set<Id> setAccountIds = new Set<Id>();
        
        for(CommunicationContacts__c varComunicationContacts : lstNewCommunicationContact)
        {
             setAccountIds.add(varComunicationContacts.Account__c);
        }

        Map<Id, Account> mapAccounts = new Map<Id, Account>([SELECT Id, Name, ExternalVersion__c, ExternalId__c, ExternalTenant__c FROM Account WHERE Id IN :setAccountIds]);

        for(CommunicationContacts__c varComunicationContacts : lstNewCommunicationContact)
        {
            varComunicationContacts.ExternalAccountId__c = mapAccounts.get(varComunicationContacts.Account__c).ExternalId__c;
            varComunicationContacts.ExternalAccountVersion__c = mapAccounts.get(varComunicationContacts.Account__c).ExternalVersion__c;
            varComunicationContacts.ExternalAccountTenant__c = mapAccounts.get(varComunicationContacts.Account__c).ExternalTenant__c;
        }        
    }
}