creditas-sf/force-app/main/default/objects/Account/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <description>Data de criação do registro</description>
    <label>Data de criação</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <description>Data da última modificação do registro</description>
    <label>Data de atualização</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Recurso_Financeiro__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/API_Transaction_Errors__b.object-meta.xml
<CustomObject>
    <label>API_Transaction_Errors</label>
    <pluralLabel>API_Transaction_Errors</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/CreatedBy__c.field-meta.xml
<CustomField>
    <fullName>CreatedBy__c</fullName>
    <label>CreatedBy</label>
    <referenceTo>User</referenceTo>
    <relationshipName>API_Transaction_Errors1</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/EndPoint__c.field-meta.xml
<CustomField>
    <fullName>EndPoint__c</fullName>
    <label>EndPoint</label>
    <length>80</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <label>ErrorMessage</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/RequestBody__c.field-meta.xml
<CustomField>
    <fullName>RequestBody__c</fullName>
    <label>RequestBody</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/API_Transaction_Errors__b/fields/ReturnCode__c.field-meta.xml
<CustomField>
    <fullName>ReturnCode__c</fullName>
    <label>ReturnCode</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Contact/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Id referente ao sistema de origem da informação</description>
    <externalId>true</externalId>
    <label>Id Externo</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <description>Quantia referente ao registro que está sendo cadastrado</description>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/AppraisalDate__c.field-meta.xml
<CustomField>
    <fullName>AppraisalDate__c</fullName>
    <description>Data de quando o bem foi avaliado.</description>
    <label>AppraisalDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/External_Version__c.field-meta.xml
<CustomField>
    <fullName>External_Version__c</fullName>
    <label>External Version</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalCreationDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalCreationDate__c</fullName>
    <label>ExternalCreationDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ExternalUpdatedDate__c.field-meta.xml
<CustomField>
    <fullName>ExternalUpdatedDate__c</fullName>
    <label>ExternalUpdatedDate</label>
    <type>DateTime</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/FinancialInstitution__c.field-meta.xml
<CustomField>
    <fullName>FinancialInstitution__c</fullName>
    <label>Instituição Financeira</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/State__c.field-meta.xml
<CustomField>
    <fullName>State__c</fullName>
    <label>Estado</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Auto.recordType-meta.xml
<RecordType>
    <fullName>Auto</fullName>
    <active>true</active>
    <label>Auto</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Certificado.recordType-meta.xml
<RecordType>
    <fullName>Certificado</fullName>
    <active>true</active>
    <label>Certificado</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Imovel.recordType-meta.xml
<RecordType>
    <fullName>Imovel</fullName>
    <active>true</active>
    <label>Imóvel</label>
</RecordType>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Outros.recordType-meta.xml
<RecordType>
    <fullName>Outros</fullName>
    <active>true</active>
    <label>Outros</label>
</RecordType>

creditas-sf/force-app/main/default/classes/IntegrationAssetService.cls
/**********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* Purpose: Class Refactor for IntegrationAsset
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
*  1.0      Gabriel Vidal           03/03/2022      Created     Class Refactor for IntegrationAsset
**********************************************************************************************************************************/
public with sharing class IntegrationAssetService 
{
    public static final String VEHICLE_RECORD_TYPE_NAME = 'Auto';
    public static final String REAL_ESTATE_RECORD_TYPE_NAME = 'Imovel';
    public static final String CERTIFICATE_RECORD_TYPE_NAME = 'Certificado';
    public static final String OTHERS_RECORD_TYPE_NAME = 'Outros';

    public void upsertAsset()
    {        
        String requestBody = RestContext.request.requestBody.toString();           
        try 
        {
            IntegrationAssetVO requestBodyObj = IntegrationAssetVO.parse(requestBody);

            if (requestBodyObj.hasError)
            {
                setErrorResponse(500, 'Invalid JSON format.');
                insertErrorLog(500, requestBody, requestBodyObj.errorMessage);
                return;
            } 

            Map<String, Account> accountExternalIdToAccountMap = getOwners(requestBodyObj);

            Id recordTypeId = getRecordTypeId(requestBodyObj);

            Boolean hasError = commitTransactions(accountExternalIdToAccountMap, requestBodyObj, requestBody, recordTypeId);
            if(hasError)
            {
                setErrorResponse(500, requestBodyObj.errorMessage);
                insertErrorLog(500, requestBody, requestBodyObj.errorMessage);
            }
        } catch (Exception e) 
        {
            setErrorResponse(500, '');
            insertErrorLog(500, requestBody, e.getMessage());
        }
    }

    public static Map<String, Account> getOwners(IntegrationAssetVO requestBodyObj)
    {
        if (requestBodyObj.owners == null || requestBodyObj.owners.isEmpty())
        {
            return new Map<String, Account>();
        }
        Set<String> ownerExternalIds = new Set<String>();
        for (IntegrationAssetVO.OwnersModel owner : requestBodyObj.owners)
        {
            if(String.isNotBlank(owner.person.id))
            {
                ownerExternalIds.add(owner.person.id);           
            }
        }
        Map<String, Account> accountExternalIdToAccountMap = new Map<String, Account>();
        for (Account acc : [SELECT Id, ExternalId__c FROM Account WHERE ExternalId__c IN :ownerExternalIds])
        {
            accountExternalIdToAccountMap.put(acc.ExternalId__c, acc);
        }
        return accountExternalIdToAccountMap;
    }


    public static Id getRecordTypeId(IntegrationAssetVO requestBodyObj)
    {
        String recordTypeDeveloperName = '';
        if (requestBodyObj.type == 'VEHICLE') 
        {
            recordTypeDeveloperName = VEHICLE_RECORD_TYPE_NAME;
        } else if (requestBodyObj.type == 'REAL_ESTATE') 
        {
            recordTypeDeveloperName = REAL_ESTATE_RECORD_TYPE_NAME;
        } else if (requestBodyObj.type == 'CERTIFICATE') 
        {
            recordTypeDeveloperName = CERTIFICATE_RECORD_TYPE_NAME;
        } else 
        {
            recordTypeDeveloperName = OTHERS_RECORD_TYPE_NAME;
        }
        return Util.getRecordTypeIdbyName('FinancialResources__c', recordTypeDeveloperName);
    }


    private static Id upsertAsset(IntegrationAssetVO requestBodyObj, Id recordTypeId)
    {
        FinancialResources__c assetObject = new FinancialResources__c();
        if (recordTypeId != null)
        {
            assetObject.recordTypeId = recordTypeId;
        }
        assetObject.Id = [SELECT Id FROM FinancialResources__c WHERE ExternalId__c = :requestBodyObj.id LIMIT 1]?.Id;
        assetObject.ExternalId__c = requestBodyObj.id;
        assetObject.External_Version__c = requestBodyObj.version;
        if (requestBodyObj.value != null)
        {
            if (requestBodyObj.value.amount != null)
            {
                assetObject.CurrencyIsoCode = requestBodyObj.value.amount.currencyCode;
                assetObject.Amount__c  = Decimal.valueOf(requestBodyObj.value.amount.amount);
            }
            assetObject.AppraisalDate__c = Date.valueOf(requestBodyObj.value.appraisalDate);
        }
        if (requestBodyObj.alienation != null){
            assetObject.FinancialInstitution__c = requestBodyObj.alienation.financialInstitution;
        }
        if (requestBodyObj.assetDetail != null){
            assetObject.State__c = requestBodyObj.assetDetail.state;
        }
        assetObject.ExternalCreationDate__c = Date.valueOf(requestBodyObj.createdAt);
        assetObject.ExternalUpdatedDate__c = Date.valueOf(requestBodyObj.updatedAt);

        try {
            upsert assetObject;  
            return assetObject.Id;
        } catch (System.DmlException e){
            requestBodyObj.hasError = true;
            requestBodyObj.errorMessage = e.getDmlMessage(0);
            return null;
        }  
    }


    private static void upsertAccountFinancialRelationship(Map<String, Account> accountExternalIdToAccountMap, IntegrationAssetVO requestBodyObj, Id assetId)
    {
        Map<String, AccountFinancialRelationship__c> externalOwnerIdToAssetRelationshipMap = new Map<String, AccountFinancialRelationship__c>();
        for(AccountFinancialRelationship__c accountRelation : [SELECT Id, Account__r.ExternalId__c, Recurso_Financeiro__c 
                                                                            FROM AccountFinancialRelationship__c 
                                                                            WHERE Recurso_Financeiro__c = :assetId
                                                                            AND Account__c IN :accountExternalIdToAccountMap.keySet()])
        {
            externalOwnerIdToAssetRelationshipMap.put(accountRelation.Account__r.ExternalId__c, accountRelation);
        }

        List<AccountFinancialRelationship__c> ownerRelationshipsToUpsert = new List<AccountFinancialRelationship__c>();
        for (IntegrationAssetVO.OwnersModel owner : requestBodyObj.owners)
        {
            if (!accountExternalIdToAccountMap.containsKey(owner.person.id))
            {
                continue;
            }
            AccountFinancialRelationship__c assetOwnerRelationship = new AccountFinancialRelationship__c();
            assetOwnerRelationship.Id = externalOwnerIdToAssetRelationshipMap.get(owner.person.id)?.Id;
            assetOwnerRelationship.Account__c = accountExternalIdToAccountMap.get(owner.person.id).Id;
            assetOwnerRelationship.Recurso_Financeiro__c = assetId;

            ownerRelationshipsToUpsert.add(assetOwnerRelationship);
        }

        List<AccountFinancialRelationship__c> accountRelationshipsToDelete = new List<AccountFinancialRelationship__c>();
        for (AccountFinancialRelationship__c afr : [SELECT Id
                                                    FROM AccountFinancialRelationship__c
                                                    WHERE Recurso_Financeiro__c = :assetId
                                                    AND Account__c NOT IN :accountExternalIdToAccountMap.keySet()])
        {
            accountRelationshipsToDelete.add(afr);                                            
        }

        delete accountRelationshipsToDelete;
        upsert ownerRelationshipsToUpsert;                                               
    }


    public static Boolean commitTransactions(Map<String, Account> accountExternalIdToAccountMap, IntegrationAssetVO requestBodyObj, String requestBody, Id recordTypeId)
    {
        Boolean varSuccess = false, hasError = false;
        Id assetId;

        Savepoint sp = Database.setSavepoint();
        if (!hasError)
        {
            try
            {
                assetId = upsertAsset(requestBodyObj, recordTypeId);
                hasError = requestBodyObj.hasError;
                if(!hasError)
                {
					varSuccess = true;                     
                } else 
                {
                	Database.rollback(sp);    
                }
            } catch(Exception e)
            {
                hasError = true;
                requestBodyObj.errorMessage =  e.getMessage();
                Database.rollback(sp); 
            }
            if(varSuccess)
            {
                try
                {
                    if(!accountExternalIdToAccountMap.isEmpty())
                    {
                        upsertAccountFinancialRelationship(accountExternalIdToAccountMap, requestBodyObj, assetId);
                    }
                    successReturn(assetId);
                } catch(Exception e)
                {
                    hasError = true;
                    requestBodyObj.errorMessage = e.getMessage();
                    Database.rollback(sp); 
                }
            }
        } 
        return hasError;
    }


    public static void insertErrorLog(Integer errorCode, String requestBody, String errorMessage)
    {
        System.debug('Error: '+errorMessage);
        API_Transaction_Errors__b ate = new API_Transaction_Errors__b();
        ate.Endpoint__c = '/services/apexrest/IntegrationAsset';
        ate.RequestBody__c = requestBody;
        ate.ReturnCode__c = errorCode;
        ate.ErrorMessage__c = errorMessage;
        ate.CreatedDate__c = System.now();
        ate.CreatedBy__c = UserInfo.getUserId();

        try 
        {
            if (!Test.isRunningTest())
            {
  				database.insertImmediate(ate);              
            }
        } catch (Exception e) 
        {
            setErrorResponse(500, 'Error inserting error log.');
        }
    }


    public static void setErrorResponse(Integer errorCode, String errorMessage)
    {
        AssetResponseData resp = new AssetResponseData();
        resp.assetId = null;
        resp.message = String.isNotBlank(errorMessage) ? errorMessage : 'An error has occurred. Please, contact a Salesforce Administrator.';
        resp.status = errorCode;

        RestResponse res = RestContext.response != null ? RestContext.response : new RestResponse();
        res.responseBody = Blob.valueOf(JSON.serialize(resp));
        res.statusCode = errorCode;
    }


    public static void successReturn(Id assetId)
    {
        AssetResponseData assetResponse = new AssetResponseData();
        assetResponse.assetId = assetId;
        assetResponse.message = 'Asset upserted';
        assetResponse.status = 200;

        RestResponse res = RestContext.response != null ? RestContext.response : new RestResponse();
        res.responseBody = Blob.valueOf(JSON.serialize(assetResponse));
        res.statusCode = 200;
    }
    
    public class AssetResponseData
    {
        public String assetId;
        public String message;
        public Integer status;
    }
}