creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/AddressDataSection__c.object-meta.xml
<CustomObject>
    <description>Objeto Utilizado apenas para o Squad AtWork</description>
    <label>Seção Dados de Endereço</label>
    <nameField>
        <displayFormat>DE-{00000}</displayFormat>
        <label>Seção Dados de Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Endereço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/CEPStatus__c.field-meta.xml
<CustomField>
    <fullName>CEPStatus__c</fullName>
    <label>Status do CEP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Endereço</relationshipLabel>
    <relationshipName>AddressDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/Addresses__c.object-meta.xml
<CustomObject>
    <description>Objeto para registros dos endereços do cliente/empresa, independente da localidade (Brasil/México).</description>
    <label>Endereço</label>
    <nameField>
        <displayFormat>A-{00000000}</displayFormat>
        <label>Numeração</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Endereços</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <description>Esse campo determina o qual a conta que está relacionada ao endereço cadastrado.</description>
    <label>Conta</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Endereços</relationshipLabel>
    <relationshipName>Enderecos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Addresses__c/fields/PostalCode__c.field-meta.xml
<CustomField>
    <fullName>PostalCode__c</fullName>
    <label>CEP</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalAddressesServiceTest.cls
@isTest
public with sharing class ProposalAddressesServiceTest {
    
    @TestSetup
    static void makeData() {
        Account varAccount = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = varAccount.Id;
        opportunity.Name = 'Teste';
        opportunity.StageName = 'Novo';
        opportunity.CloseDate = Date.today().addDays(10);
        opportunity.ExternalTenant__c = 'creditasbr';
        opportunity.ExternalVersion__c = 1;
        insert opportunity;
    }

    @isTest
    static void resultAddressBlank() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        List<Addresses__c> resultAddress = new List<Addresses__c>();
            
        Test.startTest();
        resultAddress = ProposalAddressesService.getAddress(acc.Id);
        Test.stopTest();
        
        System.assertEquals(true, resultAddress.isEmpty(),'List result should be blank');    
    }
    
    @isTest
    static void resultAddressNotBlank() {
        Account acc = [SELECT Id FROM Account LIMIT 1];
        
        List<Addresses__c> resultAddress = new List<Addresses__c>();
        
        Addresses__c address = new Addresses__c();
        address.Account__c    = acc.Id;
        address.PostalCode__c = '0132234';
        insert address;

        Test.startTest();
        resultAddress = ProposalAddressesService.getAddress(acc.Id);
        Test.stopTest();
        
        System.assertEquals(address.PostalCode__c, resultAddress[0].PostalCode__c,'Incorrect returned CEP value');
    }
    
    @isTest
    static void resultAddressSectionBlank(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        AddressDataSection__c resultAddressSection = new AddressDataSection__c();
            
        Test.startTest();
        resultAddressSection = ProposalAddressesService.getAddressDataSection(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new AddressDataSection__c(), resultAddressSection,'Result should be new AddressDataSection__c');
    }
    
    @isTest
    static void resultAddressesSectionNotBlank(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        AddressDataSection__c resultAddressSection = new AddressDataSection__c();
        
        AddressDataSection__c addressSection = new AddressDataSection__c();
        addressSection.Opportunity__c = opp.Id;
        addressSection.CEPStatus__c = 'Aprovar';
        insert addressSection;
        
        Test.startTest();
        resultAddressSection = ProposalAddressesService.getAddressDataSection(opp.Id);
        Test.stopTest();
        
        System.assertEquals(addressSection.Id, resultAddressSection.Id, 'Incorrect returned Id');
    }
}