creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/ContactDetailsSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Contato</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Seção Dados de Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/MobileStatus__c.field-meta.xml
<CustomField>
    <fullName>MobileStatus__c</fullName>
    <label>Status do Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Contato</relationshipLabel>
    <relationshipName>ContactDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalContactDataServiceTest.cls
@isTest
public class ProposalContactDataServiceTest {
    
    @TestSetup
    static void makeData(){
        Account varAccount = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = varAccount.Id;
        opportunity.Name = 'Teste';
        opportunity.StageName = 'Novo';
        opportunity.CloseDate = Date.today().addDays(10);
        opportunity.ExternalTenant__c = 'creditasbr';
        opportunity.ExternalVersion__c = 1;      
        insert opportunity;
    }
    
  @isTest
    static void getContactDetailsSucess(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
  		ContactDetailsSection__c communications = new ContactDetailsSection__c( Email__c = 'test@test123.com', Mobile__c = '11 911223344', Opportunity__c = opp.id );
        insert communications;
        
        Test.startTest();
        ProposalContactDataController.getContactDetails(opp.Id);
        Test.stopTest();
        
        List<ContactDetailsSection__c> contactDetailSec = [SELECT Email__c, Mobile__c, Opportunity__c FROM ContactDetailsSection__c WHERE Opportunity__r.Name = 'Teste'];
       System.assert(!contactDetailSec.isEmpty(), 'ContactDetailsSection not found');
        
       System.assertEquals(contactDetailSec[0].Email__c,'test@test123.com', 'Incorrect Email value');
       System.assertEquals(contactDetailSec[0].Mobile__c, '11 911223344', 'Incorrect Email value');      
    }
    
    @isTest
    static void resultContactDetailsSectionBlank(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c resultDetailsSection = new ContactDetailsSection__c();
            
        Test.startTest();
        resultDetailsSection = ProposalContactDataService.getContactDetailsSectionFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(new ContactDetailsSection__c(), resultDetailsSection,'Result should be new ContactDetailsSection__c');
    }
    
    @isTest
    static void resultContactDetailsSectionNotBlank(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c resultContactDetails = new ContactDetailsSection__c();
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opp.Id, MobileStatus__c = 'Aprovar');
        insert contactDetail;
        
        Test.startTest();
        resultContactDetails = ProposalContactDataService.getContactDetailsSectionFromOpp(opp.Id);
        Test.stopTest();
        
        System.assertEquals(contactDetail.Id, resultContactDetails.Id,'Incorrect returned Id');
    }
    
    
    @isTest
    static void insertCommunicationContacts(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opp.Id, MobileStatus__c = 'Aprovar');
        Test.startTest();
        ProposalContactDataService.upsertContactDetailsSection(contactDetail);
        Test.stopTest();
        ContactDetailsSection__c updatedContactDetailsSection = [SELECT Id, MobileStatus__c FROM ContactDetailsSection__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        System.assertEquals('Aprovar', updatedContactDetailsSection.MobileStatus__c, '');
    }
    
    @isTest
    static void updateCommunicationContacts(){
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opp.Id, MobileStatus__c = 'Aprovar');
        insert contactDetail;
        contactDetail.MobileStatus__c = 'Pendenciar';
        
        Test.startTest();
        ProposalContactDataService.upsertContactDetailsSection(contactDetail);
        Test.stopTest();
        ContactDetailsSection__c updatedContactDetailsSection = [SELECT Id, MobileStatus__c FROM ContactDetailsSection__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        System.assertEquals('Pendenciar', updatedContactDetailsSection.MobileStatus__c, '');
    }
    
    @isTest
    static void updateCommunicationContactsFail(){
        Boolean exceptionOccurred = false;
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        ContactDetailsSection__c contactDetail = new ContactDetailsSection__c(Opportunity__c = opp.Id, MobileStatus__c = 'Aprovar');
        insert contactDetail;
        contactDetail.MobileStatus__c = 'Aguardando';
        
        Test.startTest();
        try{
            ProposalContactDataService.upsertContactDetailsSection(contactDetail);
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
        
        ContactDetailsSection__c updatedContactDetailsSection = [SELECT Id, MobileStatus__c FROM ContactDetailsSection__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        System.assertEquals(true, exceptionOccurred, 'An exception should occur');
    }    
}