creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/AddressDataSection__c.object-meta.xml
<CustomObject>
    <description>Objeto Utilizado apenas para o Squad AtWork</description>
    <label>Seção Dados de Endereço</label>
    <nameField>
        <displayFormat>DE-{00000}</displayFormat>
        <label>Seção Dados de Endereço</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Endereço</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/AddOnStatus__c.field-meta.xml
<CustomField>
    <fullName>AddOnStatus__c</fullName>
    <label>Status do Complemento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/AddressNumberStatus__c.field-meta.xml
<CustomField>
    <fullName>AddressNumberStatus__c</fullName>
    <label>Status do Número</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/CEPStatus__c.field-meta.xml
<CustomField>
    <fullName>CEPStatus__c</fullName>
    <label>Status do CEP</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/CountryStatus__c.field-meta.xml
<CustomField>
    <fullName>CountryStatus__c</fullName>
    <label>Status do país</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/NeighborhoodStatus__c.field-meta.xml
<CustomField>
    <fullName>NeighborhoodStatus__c</fullName>
    <label>Status do Bairro</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Endereço</relationshipLabel>
    <relationshipName>AddressDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/StateStatus__c.field-meta.xml
<CustomField>
    <fullName>StateStatus__c</fullName>
    <label>Status do Estado</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/AddressDataSection__c/fields/StreetAddressStatus__c.field-meta.xml
<CustomField>
    <fullName>StreetAddressStatus__c</fullName>
    <label>Status da Rua</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalAddressesControllerTest.cls
@isTest
public class ProposalAddressesControllerTest {
    
    @TestSetup
    static void makeData(){
        
        Account varAccount = TestSetup.getAccount('Nivaele', true);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = varAccount.Id;
        opportunity.Name = 'Teste';
        opportunity.StageName = 'Novo';
        opportunity.CloseDate = Date.today().addDays(10);
        opportunity.ExternalTenant__c = 'creditasbr';
        opportunity.ExternalVersion__c = 1;      
        insert opportunity;

        AddressDataSection__c addressSection  = new AddressDataSection__c();
        addressSection.Opportunity__c         = opportunity.Id;
        addressSection.CEPStatus__c           = 'APPROVED';
        addressSection.NeighborhoodStatus__c  = 'APPROVED';
        addressSection.StreetAddressStatus__c = 'APPROVED';
        addressSection.AddressNumberStatus__c = 'APPROVED';
        addressSection.StateStatus__c         = 'APPROVED';
        addressSection.CountryStatus__c       = 'APPROVED';
        addressSection.AddOnStatus__c         = 'APPROVED';
        addressSection.PostalCode__c   = '01392003';
        addressSection.Neighborhood__c = 'Boa Vista';
        addressSection.StreetNumber__c = '45';
        addressSection.Street__c       = 'Rua da Glória';
        addressSection.AreaLevel2__c   = 'São Paulo';
        addressSection.AreaLevel1__c   = 'SP';
        addressSection.Country__c      = 'BR';
        addressSection.Complement__c   = 'Perto do Hotel Capunzeira';
        insert addressSection;
    }
    
    @isTest
    static void getAddressesDetailsSuccess(){
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        AddressDataSection__c resultAddress = new AddressDataSection__c();
        
        Test.startTest();
        resultAddress = ProposalAddressesController.getAddressSectiontDetails(opp.Id); 
        Test.stopTest();
        
        System.assertEquals('APPROVED', resultAddress.CEPStatus__c,'Incorrect CEPStatus value');
        System.assertEquals('01392003', resultAddress.PostalCode__c, 'Incorrect PostalCode value');
    }
    
    @isTest
    static void getAddressDetailsFail() {
        
        String exceptionMessage = '';
        AddressDataSection__c resultAddress = new AddressDataSection__c();
        
        Test.startTest();
        try{
            resultAddress = ProposalAddressesController.getAddressSectiontDetails('123456778');
        }catch(Exception e){
            exceptionMessage = e.getMessage();
        }
        Test.stopTest();
        
        System.assertEquals('Invalid id: 123456778', exceptionMessage, 'Incorrect exception message.'); 
    }

 
    @isTest
    static void insertAddressesSectionSuccess() {
        
        Account acc = [SELECT Id, Name FROM Account LIMIT 1];
        Opportunity opp = new Opportunity();
        opp.AccountId = acc.Id;
        opp.Name = 'Teste';
        opp.StageName = 'Novo';
        opp.CloseDate = Date.today().addDays(16);
        insert opp;

        AddressDataSection__c addressSection  = new AddressDataSection__c();
        addressSection.Opportunity__c         =  opp.Id;
        addressSection.CEPStatus__c           = 'PENDING';
        
        Test.startTest();
        ProposalAddressesController.saveAddressSection(addressSection);
        Test.stopTest();
        
        AddressDataSection__c addressSectionResult = [SELECT Id, Name, CEPStatus__c FROM AddressDataSection__c WHERE Opportunity__c =: opp.Id LIMIT 1];

        System.assertEquals(addressSectionResult.CEPStatus__c, 'PENDING', 'AddressDataSection for this opportunity does not exist.');
    }

    @isTest
    static void insertAddressSection() {
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        AddressDataSection__c addressSection = new AddressDataSection__c();
        addressSection.Opportunity__c = opp.Id;
        addressSection.CEPStatus__c = 'APPROVED';

        Test.startTest();
        ProposalAddressesController.saveAddressSection(addressSection);
        Test.stopTest();

        AddressDataSection__c updatedAddressSection = [SELECT Id, CEPStatus__c FROM AddressDataSection__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        System.assertEquals('APPROVED', updatedAddressSection.CEPStatus__c, 'Field status is different from what is expected');
    }

    @isTest
    static void updateAddressSection(){
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        AddressDataSection__c addressSection = [SELECT Id, Name, CEPStatus__c FROM AddressDataSection__c LIMIT 1];
        
        addressSection.CEPStatus__c = 'PENDING';
        
        Test.startTest();
        	ProposalAddressesController.saveAddressSection(addressSection);
        Test.stopTest();
        
        AddressDataSection__c updatedaddressSectionsSection = [SELECT Id, CEPStatus__c FROM AddressDataSection__c WHERE Opportunity__c = :opp.Id LIMIT 1];
        
        System.assertEquals('PENDING', updatedaddressSectionsSection.CEPStatus__c, 'Field status is different from what is expected');
    }

    @isTest
    static void updateAddressSectionFail() {
        
        Boolean exceptionOccurred = false;
        
        Opportunity opp = [SELECT Id FROM Opportunity LIMIT 1];
        
        AddressDataSection__c addressSection = [SELECT Id, Name, CEPStatus__c FROM AddressDataSection__c LIMIT 1];
        
        addressSection.CEPStatus__c = 'Aguardando';
        
        Test.startTest();
        try{
            ProposalAddressesController.saveAddressSection(addressSection);
        }catch(Exception e){
            exceptionOccurred = true;
        }
        Test.stopTest();
         
        System.assertEquals(true, exceptionOccurred, 'An exception should occur');
    }   
}