creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCityStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCityStatus__c</fullName>
    <label>Status da cidade de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthCountryStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthCountryStatus__c</fullName>
    <label>Status do país de nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/BirthDateStatus__c.field-meta.xml
<CustomField>
    <fullName>BirthDateStatus__c</fullName>
    <label>Status da Data de Nascimento</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFPendingReason__c.field-meta.xml
<CustomField>
    <fullName>CPFPendingReason__c</fullName>
    <label>Motivo Pendência CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CPF Irregular na Receita Federal</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
           
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/CPFStatus__c.field-meta.xml
<CustomField>
    <fullName>CPFStatus__c</fullName>
    <label>Status do CPF</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NameStatus__c.field-meta.xml
<CustomField>
    <fullName>NameStatus__c</fullName>
    <label>Status do Nome</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/NationalityStatus__c.field-meta.xml
<CustomField>
    <fullName>NationalityStatus__c</fullName>
    <label>Status da nacionalidade</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção de Dados Pessoais</relationshipLabel>
    <relationshipName>PersonalDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/PoliticallyExposedPersonStatus__c.field-meta.xml
<CustomField>
    <fullName>PoliticallyExposedPersonStatus__c</fullName>
    <label>Status da pessoa politicamente exposta</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/RGobservation__c.field-meta.xml
<CustomField>
    <fullName>RGobservation__c</fullName>
    <label>Observação do RG</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/fields/RGStatus__c.field-meta.xml
<CustomField>
    <fullName>RGStatus__c</fullName>
    <label>Status do RG</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalPersonalDataControllerTest.cls
/**
 * @author Otávio Frank - GFT Brasil
 */
@isTest
public class ProposalPersonalDataControllerTest {

    @isTest
    public static void givenOppIdThenFindLastPersonalDataSection() {

        ProposalPersonalDataController.setPersonalDataSectionRepository( new PersonalDataSectionRepositoryMock() );

        test.startTest();

        PersonalDataSection__c personalDataSection = ProposalPersonalDataController.getLastPersonalDataSectionInstance('oppId');

        test.stopTest();

        System.assertEquals('Approved', personalDataSection.RGStatus__c, 'Should have a status');
    }

    @isTest
    public static void givenSerializedPersonalDataSectionThenSave() {

        Account account = TestSetup.getAccount('test', true);
        
        Opportunity opportunity = new Opportunity();
        opportunity.AccountId = account.Id;
        opportunity.Name = 'Teste';
        opportunity.StageName = 'Novo';
        opportunity.CloseDate = Date.today().addDays(5);
        opportunity.ExternalTenant__c = 'creditasbr';
        opportunity.ExternalVersion__c = 1;
        insert opportunity;

        PersonalDataSection__c personalDataRecord = new PersonalDataSection__c();
        personalDataRecord.Opportunity__c = opportunity.Id;
        personalDataRecord.NameStatus__c = 'Approved';
        personalDataRecord.CPFStatus__c = 'Rejected';
        personalDataRecord.BirthCityStatus__c = 'Approved';
        personalDataRecord.BirthCountryStatus__c = 'Approved';
        personalDataRecord.BirthDateStatus__c = 'Pending';
        personalDataRecord.NationalityStatus__c = 'Pending';
        personalDataRecord.PoliticallyExposedPersonStatus__c = 'Pending';

        insert personalDataRecord;

        test.startTest();

        PersonalDataSection__c personalDataSection = ProposalPersonalDataController.saveInstance( JSON.serialize(personalDataRecord));

        test.stopTest();

        System.assertEquals( true , String.isNotBlank(personalDataSection.Id), 'Should have an Id');
    }

    public class PersonalDataSectionRepositoryMock extends PersonalDataSectionRepository {

        private PersonalDataSection__c personalDataSection;

        public PersonalDataSectionRepositoryMock( ) {

            String payload = '{"attributes":{"type":"PersonalDataSection__c","url":"/services/data/v51.0/sobjects/PersonalDataSection__c/a0K03000001GCQ7EAO"},"Id":"a0K03000001GCQ7EAO","RGobservation__c":null,"RGPendingReason__c":null,"RGRejectReason__c":null,"Opportunity__c":"00603000007pZh6AAE","RGStatus__c":"Approved","CPFStatus__c":"Approved","CPFPendingReason__c":null}';
            this.personalDataSection = ( PersonalDataSection__c ) JSON.deserialize( payload, PersonalDataSection__c.class );

        }

        override
        public List<PersonalDataSection__c> findLastPersonalDataSectionByOppId (String oppId ) {
            return new List<PersonalDataSection__c> { this.personalDataSection };
        }
    }

}