creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/AccountOwner__c.field-meta.xml
<CustomField>
    <fullName>AccountOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titular da Conta</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityTenant__c</fullName>
    <label>ExternalOpportunityTenant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityVersion__c</fullName>
    <label>ExternalOpportunityVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalPersonId__c.field-meta.xml
<CustomField>
    <fullName>ExternalPersonId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OpportunityRoles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityRoleTriggerService.cls
public with sharing class OpportunityRoleTriggerService {
  public static void updateOpportunityIsExternallySynced(
    List<OpportunityRole__c> newOpportunityRoles,
    Map<Id, OpportunityRole__c> oldOpportunityRolesById
  ) {
    Util.updateIsExternallySyncedOpportunity('OpportunityRole__c', newOpportunityRoles, oldOpportunityRolesById);
  }

  public static void updateExternalFields(List<OpportunityRole__c> newOpportunityRoles) {
    Set<Id> opportunityIds = getOpportunityIds(newOpportunityRoles);
    Map<Id, Opportunity> opportunitiesById = new Map<Id, Opportunity>(getOpportunities(opportunityIds));

    for (OpportunityRole__c opportunityRole : newOpportunityRoles) {
      Opportunity opportunity = opportunitiesById.get(opportunityRole.Opportunity__c);

      if (opportunity == null) {
        continue;
      }

      opportunityRole.ExternalOpportunityId__c = opportunity.ExternalId__c;
      opportunityRole.ExternalOpportunityVersion__c = opportunity.ExternalVersion__c;
      opportunityRole.ExternalOpportunityTenant__c = opportunity.ExternalTenant__c;
    }
  }

  public static void validateOpportunityRoles(List<OpportunityRole__c> newOpportunityRoles) {
    Set<Id> opportunityIds = getOpportunityIds(newOpportunityRoles);

    if (hasAccountOwner(newOpportunityRoles)) {
      List<OpportunityRole__c> opportunityRoles = getAccountOwnerOpportunityRoles(opportunityIds);
      Map<Id, List<OpportunityRole__c>> opportunityRolesByOpportunityId = getOpportunityRolesByOpportunityId(
        opportunityRoles
      );

      for (OpportunityRole__c opportunityRole : newOpportunityRoles) {
        List<OpportunityRole__c> accountOwnerOpportunityRoles = opportunityRolesByOpportunityId.get(
          opportunityRole.Opportunity__c
        );

        if (accountOwnerOpportunityRoles == null) {
          continue;
        }

        if (
          opportunityRole.AccountOwner__c &&
          (accountOwnerOpportunityRoles.size() > 1 || (accountOwnerOpportunityRoles.size() == 1 && Trigger.isInsert))
        ) {
          opportunityRole.addError(
            'Não foi possível criar/atualizar o registro pois já existe um titular da conta bancária. Caso necessário, desabilite o titular atual.'
          );
        }
      }
    }
  }

  private static Set<Id> getOpportunityIds(List<OpportunityRole__c> opportunityRoles) {
    Set<Id> opportunityIds = new Set<Id>();

    for (OpportunityRole__c opportunityRole : opportunityRoles) {
      opportunityIds.add(opportunityRole.Opportunity__c);
    }

    return opportunityIds;
  }

  private static Boolean hasAccountOwner(List<OpportunityRole__c> opportunityRoles) {
    for (OpportunityRole__c opportunityRole : opportunityRoles) {
      if (opportunityRole.AccountOwner__c) {
        return true;
      }
    }

    return false;
  }

  private static Map<Id, List<OpportunityRole__c>> getOpportunityRolesByOpportunityId(
    List<OpportunityRole__c> opportunityRoles
  ) {
    Map<Id, List<OpportunityRole__c>> opportunityRolesByOpportunityId = new Map<Id, List<OpportunityRole__c>>();

    for (OpportunityRole__c opportunityRole : opportunityRoles) {
      Id opportunityId = opportunityRole.Opportunity__c;

      if (!opportunityRolesByOpportunityId.containsKey(opportunityId)) {
        opportunityRolesByOpportunityId.put(opportunityId, new List<OpportunityRole__c>());
      }

      opportunityRolesByOpportunityId.get(opportunityId).add(opportunityRole);
    }

    return opportunityRolesByOpportunityId;
  }

  private static List<Opportunity> getOpportunities(Set<Id> opportunityIds) {
    return [
      SELECT Id, Name, ExternalVersion__c, ExternalId__c, ExternalTenant__c
      FROM Opportunity
      WHERE Id IN :opportunityIds
    ];
  }

  private static List<OpportunityRole__c> getAccountOwnerOpportunityRoles(Set<Id> opportunityIds) {
    return [
      SELECT Opportunity__c
      FROM OpportunityRole__c
      WHERE
        Opportunity__c IN :opportunityIds
        AND AccountOwner__c = TRUE
        AND ExternalPersonId__r.RecordType.DeveloperName = 'Pessoa_Fisica'
    ];
  }
}