creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/Garantias__c.object-meta.xml
<CustomObject>
    <label>Garantias</label>
    <nameField>
        <label>Garantias Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Garantias</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Garantias__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Garantias</relationshipLabel>
    <relationshipName>Garantia</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityRepository.cls
public virtual class OpportunityRepository extends Repository {

    virtual
    public Opportunity findById( String oppId ) {

        return [ SELECT Id, RecordType.DeveloperName, ExternalId__c, StageName, CrivoQuery__c,
                        ( Select Recurso_Financeiro__r.ExternalId__c from Garantia__r),
                        Account.ExternalId__c
                 FROM Opportunity
                 WHERE Id =: oppId];
    }

    virtual
    public Opportunity getOpportunityWithChildren(String opportunityId, List<String> objNameList, String numberOfRecords, String order){
        String childrenQuery = '';
        for(String objName : objNameList){
            childrenQuery += buildChildObjectQuery(objName, numberOfRecords, order) + ', ';
        }
        childrenQuery = childrenQuery.removeEnd(', ');

        List<String> sObjectFields = Util.selectAllFields('Opportunity');

        String query = 'SELECT ' +  String.join(sObjectFields, ', ') + ', RecordType.DeveloperName, ' + childrenQuery +
                       ' FROM Opportunity WHERE Id = :opportunityId';

        return Database.query(query.escapeUnicode());
    }

    private static String buildChildObjectQuery(String objName, String numberOfRecords, String order){
        List<String> sObjectFields = Util.selectAllFields(objName+'__c');
        String queryLimit = numberOfRecords == null ? '' : 'LIMIT ' + numberOfRecords;
        return '(SELECT ' + String.join(sObjectFields, ', ') + ' FROM ' + objName + '__r ORDER BY CreatedDate ' + order + ' ' + queryLimit + ' )';
    }
}