creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Recurso_Financeiro__c.field-meta.xml
<CustomField>
    <fullName>Recurso_Financeiro__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Recurso Financeiro</label>
    <referenceTo>FinancialResources__c</referenceTo>
    <relationshipLabel>Proprietários</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/FinancialResourcesTriggerService.cls
public with sharing class FinancialResourcesTriggerService {

    public static void updateIsExternallySynced(List<FinancialResources__c> lstNewFinancialResources){
        List<String> trackedFields = Util.returnCustomMetadaDataFieldApiName('FinancialResources__c');
        Set<Id> changedFinancialResourceIdSet = new Set<Id>();
        for(FinancialResources__c iFinancialResource : lstNewFinancialResources){
            if(TriggerHelper.changedField(iFinancialResource, trackedFields)){
                changedFinancialResourceIdSet.add(iFinancialResource.Id);
            }
        }

        if(changedFinancialResourceIdSet.isEmpty()) { return; }

        List<Account> accountToUpdateList = new List<Account>();
        Set<Id> accIdSet = new Set<Id>();

        for(AccountFinancialRelationship__c accountFinancialRelationship : [SELECT Account__c,Account__r.IsExternallySynched__c,Account__r.ExternalId__c FROM AccountFinancialRelationship__c WHERE Recurso_Financeiro__c IN : changedFinancialResourceIdSet]){
            String accId = accountFinancialRelationship?.Account__c;
            if(String.isNotBlank(accId) && !accIdSet.contains(accId)){
                accIdSet.add(accId);
                Account accountToUpdate = new Account(
                    Id = accId,
                    IsExternallySynched__c = false
                );
                accountToUpdateList.add(accountToUpdate);
            }
        }

        if(accountToUpdateList.isEmpty()) { return; }
        
        TriggerHandler.bypass('AccountTriggerController');
        upsert accountToUpdateList;
        TriggerHandler.clearBypass('AccountTriggerController');
        
    }
}