creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/recordTypes/Pessoa_Fisica.recordType-meta.xml
<RecordType>
    <fullName>Pessoa_Fisica</fullName>
    <active>true</active>
    <label>Pessoa Física</label>
</RecordType>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Opportunity/recordTypes/Home.recordType-meta.xml
<RecordType>
    <fullName>Home</fullName>
    <active>true</active>
    <businessProcess>Home - Creditas</businessProcess>
    <label>Home</label>
</RecordType>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/OpportunityRole__c.object-meta.xml
<CustomObject>
    <label>OpportunityRole</label>
    <nameField>
        <displayFormat>OppRole-{00000000}</displayFormat>
        <label>OpportunityRole Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>OpportunityRoles</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/AccountOwner__c.field-meta.xml
<CustomField>
    <fullName>AccountOwner__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Titular da Conta</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityId__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityId__c</fullName>
    <label>ExternalOpportunityId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityTenant__c</fullName>
    <label>ExternalOpportunityTenant</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalOpportunityVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalOpportunityVersion__c</fullName>
    <label>ExternalOpportunityVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/ExternalPersonId__c.field-meta.xml
<CustomField>
    <fullName>ExternalPersonId__c</fullName>
    <deleteConstraint>Restrict</deleteConstraint>
    <label>Conta Relacionada</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>OpportunityRoles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <required>true</required>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/OpportunityRole__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Opportunity</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Opportunity Roles</relationshipLabel>
    <relationshipName>OpportunityRoles</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/OpportunityRoleTriggerTest.cls
@isTest
public class OpportunityRoleTriggerTest {
  @TestSetup
  static void makeData() {

    Account account = AccountSetup.createAccount('New Account', 'Pessoa_Fisica');

    insert account;

    Opportunity opportunity = OpportunitySetup.createOpportunity(account.Id, 'Home');
    opportunity.ExternalId__c = 'Test001';
    opportunity.ExternalTenant__c = 'creditasbr';
    opportunity.ExternalVersion__c = 1;
    opportunity.IsExternallySynched__c = true;

    insert opportunity;

    List<OpportunityRole__c> roles = new List<OpportunityRole__c>{
      new OpportunityRole__c(
        Opportunity__c = opportunity.Id,
        ExternalPersonId__c = opportunity.AccountId,
        AccountOwner__c = true
      ),
      new OpportunityRole__c(Opportunity__c = opportunity.Id, ExternalPersonId__c = opportunity.AccountId)
    };

    insert roles;
  }

  @IsTest
  static void testInsertOpportunityRoleSuccess() {
    Opportunity opportunity = [SELECT Id, AccountId FROM Opportunity];

    OpportunityRole__c opportunityRole = new OpportunityRole__c(
      Opportunity__c = opportunity.Id,
      ExternalPersonId__c = opportunity.AccountId
    );

    Test.startTest();

    insert opportunityRole;

    Test.stopTest();

    List<OpportunityRole__c> opportunityRoles = [
      SELECT
        ExternalOpportunityId__c,
        ExternalOpportunityTenant__c,
        ExternalOpportunityVersion__c,
        Opportunity__r.IsExternallySynched__c
      FROM OpportunityRole__c
    ];

    System.assertEquals(3, opportunityRoles.size(), 'Incorrect number of Opportunity Roles');

    for (OpportunityRole__c role : opportunityRoles) {
      System.assertEquals(
        'Test001',
        role.ExternalOpportunityId__c,
        'Incorrect value for Opportunity Role ExternalOpportunityId__c'
      );
      System.assertEquals(
        'creditasbr',
        role.ExternalOpportunityTenant__c,
        'Incorrect value for Opportunity Role ExternalOpportunityTenant__c'
      );
      System.assertEquals(
        1,
        role.ExternalOpportunityVersion__c,
        'Incorrect value for Opportunity Role ExternalOpportunityVersion__c'
      );
    }
  }

  @IsTest
  static void testUpdateOpportunityRoleSuccess() {
    OpportunityRole__c opportunityRole = [SELECT AccountOwner__c FROM OpportunityRole__c WHERE AccountOwner__c = TRUE];

    opportunityRole.AccountOwner__c = false;

    Test.startTest();

    update opportunityRole;

    Test.stopTest();

    List<OpportunityRole__c> opportunityRoles = [
      SELECT
        AccountOwner__c,
        ExternalOpportunityId__c,
        ExternalOpportunityTenant__c,
        ExternalOpportunityVersion__c,
        Opportunity__r.IsExternallySynched__c
      FROM OpportunityRole__c
    ];

    System.assertEquals(2, opportunityRoles.size(), 'Incorrect number of Opportunity Roles');

    for (OpportunityRole__c role : opportunityRoles) {
      System.assertEquals(false, role.AccountOwner__c, 'Incorret value for Opportunity Role AccountOwner__c');
    }
  }

  @IsTest
  static void testInsertOpportunityRoleFail() {
    Opportunity opportunity = [SELECT Id, AccountId FROM Opportunity];

    OpportunityRole__c opportunityRole = new OpportunityRole__c(
      Opportunity__c = opportunity.Id,
      ExternalPersonId__c = opportunity.AccountId,
      AccountOwner__c = true
    );

    Exception testException;

    try {
      Test.startTest();
      insert opportunityRole;
      Test.stopTest();
    } catch (Exception e) {
      testException = e;
    }

    List<OpportunityRole__c> opportunityRoles = [
      SELECT ExternalOpportunityId__c, ExternalOpportunityTenant__c, ExternalOpportunityVersion__c
      FROM OpportunityRole__c
    ];

    System.assertEquals(2, opportunityRoles.size(), 'Incorrect number of Opportunity Roles');
    System.assertNotEquals(null, testException, 'Variable testException shouldn\'t be null');
    System.assert(
      testException.getMessage()
        .contains(
          'Não foi possível criar/atualizar o registro pois já existe um titular da conta bancária. Caso necessário, desabilite o titular atual.'
        ),
      'Incorrect exception message'
    );
  }

  @IsTest
  static void testUpdateOpportunityRoleFail() {
    OpportunityRole__c opportunityRole = [SELECT AccountOwner__c FROM OpportunityRole__c WHERE AccountOwner__c = FALSE];

    opportunityRole.AccountOwner__c = true;

    Exception testException;

    try {
      Test.startTest();
      update opportunityRole;
      Test.stopTest();
    } catch (Exception e) {
      testException = e;
    }

    List<OpportunityRole__c> opportunityRoles = [
      SELECT ExternalOpportunityId__c, ExternalOpportunityTenant__c, ExternalOpportunityVersion__c
      FROM OpportunityRole__c
    ];

    System.assertEquals(2, opportunityRoles.size(), 'Incorrect number of Opportunity Roles');
    System.assertNotEquals(null, testException, 'Variable testException shouldn\'t be null');
    System.assert(
      testException.getMessage()
        .contains(
          'Não foi possível criar/atualizar o registro pois já existe um titular da conta bancária. Caso necessário, desabilite o titular atual.'
        ),
      'Incorrect exception message'
    );
  }
}