creditas-sf/force-app/main/default/objects/Account/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <description>Campo utilizado pelo Mulesoft como chave para fazer atualização dos registros.</description>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalTenant__c.field-meta.xml
<CustomField>
    <fullName>ExternalTenant__c</fullName>
    <description>Esse campo é a região da conta (br/mx)</description>
    <label>ExternalTenant</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>creditasmx</fullName>
            </value>
            <value>
                <fullName>creditasbr</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/ExternalVersion__c.field-meta.xml
<CustomField>
    <fullName>ExternalVersion__c</fullName>
    <description>Campo para o mulesoft popular com a versão do registro no sistema externo</description>
    <label>ExternalVersion</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/ExternalAccountId__c.field-meta.xml
<CustomField>
    <fullName>ExternalAccountId__c</fullName>
    <label>ExternalAccountId</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/ExternalId__c.field-meta.xml
<CustomField>
    <fullName>ExternalId__c</fullName>
    <externalId>true</externalId>
    <label>ExternalId</label>
    <length>20</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProfessionalInfoTriggerService.cls
public with sharing class ProfessionalInfoTriggerService {
    
    public static void updateIsExternallySynced(List<ProfessionalInfo__c> newProfessionalInfos, Map<Id, ProfessionalInfo__c> oldProfessionalInfosById)
    {
        Util.updateIsExternallySynced('ProfessionalInfo__c', newProfessionalInfos, oldProfessionalInfosById);
    }

    public static void updateAccountExternalFields(List<ProfessionalInfo__c> newProfessionalInfos)
    {
        Set<Id> accountIds = new Set<Id>();
        
        for(ProfessionalInfo__c professionalInfo : newProfessionalInfos)
        {
             accountIds.add(professionalInfo.Account__c);
        }

        Map<Id, Account> accounts = new Map<Id, Account>([SELECT Id, Name, ExternalVersion__c, ExternalId__c, ExternalTenant__c FROM Account WHERE Id IN :accountIds]);

        for(ProfessionalInfo__c professionalInfo : newProfessionalInfos)
        {
            professionalInfo.ExternalAccountId__c = accounts.get(professionalInfo.Account__c).ExternalId__c;
            professionalInfo.ExternalAccountVersion__c = accounts.get(professionalInfo.Account__c).ExternalVersion__c;
            professionalInfo.ExternalAccountTenant__c = accounts.get(professionalInfo.Account__c).ExternalTenant__c;
        }        
    }
}