creditas-sf/force-app/main/default/objects/Account/fields/Gender__c.field-meta.xml
<CustomField>
    <fullName>Gender__c</fullName>
    <label>Gênero</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MALE</fullName>
                <label>Masculino</label>
            </value>
            <value>
                <fullName>FEMALE</fullName>
                <label>Feminino</label>
            </value>
            <value>
                <fullName>OTHER</fullName>
                <label>Outro</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/PersonalDataSection__c/PersonalDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção de Dados Pessoais</label>
    <nameField>
        <label>Nome do Cliente</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção de Dados Pessoais</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/classes/PicklistUtilsTest.cls
@isTest
private with sharing class PicklistUtilsTest {

    @isTest
    private static void getReasonTest(){
        List<PicklistUtils.PicklistWrapper> returnReason = new List<PicklistUtils.PicklistWrapper>();
        Test.startTest();
            returnReason = PicklistUtils.getPickListValuesWrapped('Account', 'Gender__c');
        Test.stopTest();

        System.assertEquals(false, returnReason.isEmpty(), 'List should not be empty');
    }

    @isTest
    private static void getReasonWithParamsBlank(){
		List<PicklistUtils.PicklistWrapper> returnReason = new List<PicklistUtils.PicklistWrapper>();
        Test.startTest();
            returnReason = PicklistUtils.getPickListValuesWrapped('', '');
        Test.stopTest();
        System.assertEquals(true, returnReason.isEmpty(), 'List should be empty');
    }
    
    @isTest
    private static void getReasonObjectError(){
		List<PicklistUtils.PicklistWrapper> returnReason = new List<PicklistUtils.PicklistWrapper>();
        Test.startTest();
        	returnReason = PicklistUtils.getPickListValuesWrapped('abc','def');   
        Test.stopTest();
        System.assertEquals(true, returnReason.isEmpty(), 'List should be empty');
    }
    
    @isTest
    private static void getReasonFieldError(){
		List<PicklistUtils.PicklistWrapper> returnReason = new List<PicklistUtils.PicklistWrapper>();
        Test.startTest();
        	returnReason = PicklistUtils.getPickListValuesWrapped('PersonalDataSection__c','def');   
        Test.stopTest();
        System.assertEquals(true, returnReason.isEmpty(), 'List should not be empty');
    }
    
}