creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/Employee__c.object-meta.xml
<CustomObject>
    <description>Objeto criado para atender a estrutura de employee</description>
    <label>Colaborador</label>
    <nameField>
        <label>Nome do Colaborador</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Colaboradores</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Employee__c/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/SynchEmployeeDataServiceTest.cls
@isTest
private class SynchEmployeeDataServiceTest {
  @TestSetup
  static void makeData() {
    insert new Employee__c(Name = 'Test');
    insert new Account(Name = 'Test');
  }

  @IsTest
  private static void testUpdateSynchingFieldsSuccess() {
    Id employeeId = [SELECT Id FROM Employee__c].Id;

    Test.startTest();

    SynchEmployeeDataService.updateSynchingFields(employeeId);

    Test.stopTest();

    Employee__c employee = [SELECT IsSynchEnabled__c, IsExternallySynched__c FROM Employee__c];

    System.assertEquals('SYNCHING', employee.IsSynchEnabled__c, 'Incorrect field value');
    System.assertEquals(false, employee.IsExternallySynched__c, 'Incorrect field value');
  }

  @IsTest
  private static void testUpdateSynchingFieldsFail() {
    Id employeeId = [SELECT Id FROM Account].Id;
    Exception testException;

    try {
      Test.startTest();

      SynchEmployeeDataService.updateSynchingFields(employeeId);

      Test.stopTest();
    } catch (TypeException e) {
      testException = e;
    }

    System.assertNotEquals(null, testException, 'A TypeException should\'ve been thrown');
  }
}