creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccFinRelationshipTriggerService.cls
public with sharing class AccFinRelationshipTriggerService {
    public static void updateIsExternallySynced(List<AccountFinancialRelationship__c> lstNewAccountFinancialRelationship) {
        List<Account> accountsToUpdate = new List<Account>();
        Set<Id> accountsToUpdateIds = new Set<Id>();

        for (AccountFinancialRelationship__c accFinancialRelationship : lstNewAccountFinancialRelationship) {
            String accountId = accFinancialRelationship?.Account__c;
            if (String.isNotBlank(accountId) && !accountsToUpdateIds.contains(accountId))
            {
                accountsToUpdateIds.add(accountId);
                
                accountsToUpdate.add(new Account(
                    Id = accountId,
                    IsExternallySynched__c = false
                ));
            }
        }
        TriggerHandler.bypass('AccountTriggerController');
        update accountsToUpdate;
        TriggerHandler.clearBypass('AccountTriggerController');
    }
}