creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/IsSynchEnabled__c.field-meta.xml
<CustomField>
    <fullName>IsSynchEnabled__c</fullName>
    <description>O objetivo desse campo é informar ao Mulesoft, se ele tem permissão para iniciar a sincronização da Conta</description>
    <label>IsSynchEnabled</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>DISABLED</fullName>
            </value>
            <value>
                <fullName>SYNCHING</fullName>
            </value>
            <value>
                <fullName>ENABLED</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/Custom_Field_Tracking_Map__mdt.object-meta.xml
<CustomObject>
    <description>Mapeamento de campos para sincronização personalizada de campos</description>
    <label>Custom Field Tracking Map</label>
    <pluralLabel>Customs Fields Tracking Map</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/CampoRastreado__c.field-meta.xml
<CustomField>
    <fullName>CampoRastreado__c</fullName>
    <label>CampoRastreado</label>
    <metadataRelationshipControllingField>Custom_Field_Tracking_Map__mdt.ObjetoRastreado__c</metadataRelationshipControllingField>
    <referenceTo>FieldDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map1</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map1</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Custom_Field_Tracking_Map__mdt/fields/ObjetoRastreado__c.field-meta.xml
<CustomField>
    <fullName>ObjetoRastreado__c</fullName>
    <label>ObjetoRastreado</label>
    <referenceTo>EntityDefinition</referenceTo>
    <relationshipLabel>Customs_Fields_Sync_Map</relationshipLabel>
    <relationshipName>Customs_Fields_Sync_Map</relationshipName>
    <type>MetadataRelationship</type>
</CustomField>

creditas-sf/force-app/main/default/objects/SynchAccount__e/SynchAccount__e.object-meta.xml
<CustomObject>
    <description>Platform Event to Update the SynchAccount component</description>
    <label>SynchAccount</label>
    <pluralLabel>SynchAccounts</pluralLabel>
</CustomObject>

creditas-sf/force-app/main/default/classes/AccountTriggerHandler.cls
/***********************************************************************************************************************************
* Copyright © 2021 Creditas
* ================================================================================================================================
* @description Handler padrão para a trigger do Objeto Conta (Account).
* ================================================================================================================================
* History
* -------
* VERSION   AUTHOR                  DATE            DETAIL      Description
* 1.0       Thales Yumiya           10/08/2021      Created     Implementação de handler voltado para uso da Trigger do objeto Conta (Account)
**********************************************************************************************************************************/
public without sharing class AccountTriggerHandler extends TriggerHandler
{
    private List<Account> lstNewAccount;
    private List<Account> lstOldAccount;
    private Map<Id, Account> mapNewAccount;
    private Map<Id, Account> mapOldAccount;
    private final Id RECORDTYPE_CONTA_PESSOA_FISICA;
    private final Id RECORDTYPE_CONTA_PESSOA_JURIDICA;
    
    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description Construtor
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0                    
    **********************************************************************************************************************************/
    public AccountTriggerHandler()
    {
        this.lstNewAccount = (List<Account>) Trigger.new;
        this.lstOldAccount = (List<Account>) Trigger.old;
        this.mapNewAccount = (Map<Id, Account>) Trigger.newMap;
        this.mapOldAccount = (Map<Id, Account>) Trigger.oldMap;
        this.RECORDTYPE_CONTA_PESSOA_FISICA = getAccountRecordTypeId('Pessoa Física');
        this.RECORDTYPE_CONTA_PESSOA_JURIDICA = getAccountRecordTypeId('Pessoa Jurídica');
    }
    
    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description Método contextualizado before insert
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0                    
    **********************************************************************************************************************************/
    public override void beforeInsert()
    {
    }
    
    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description Método contextualizado after insert
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0                    
    **********************************************************************************************************************************/
    public override void afterInsert() 
    {
    }
    
    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description Método contextualizado before update
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0                    
    **********************************************************************************************************************************/
    public override void beforeUpdate()
    {
        this.updateIsExternallySynced();
        this.firePlatformEventSynchAccount();
    }
    
    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description Método contextualizado after update
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0                    
    **********************************************************************************************************************************/
    public override void afterUpdate() 
    {
        
    }

    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description pegar id do tipo de registro
    * @return id do tipo de registro
    * @param nome do tipo de registro
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0         
    **********************************************************************************************************************************/
    private static Id getAccountRecordTypeId(String recordTypeName)
    {
        return Schema.SObjectType.Account.getRecordTypeInfosByName().get(recordTypeName).getRecordTypeId();
    }

    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description verificar se os campos rastreados mudaram de valor
    * @return boolean
    * @param Account
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0         Thales Yumiya           11/08/21
    **********************************************************************************************************************************/
    private void updateIsExternallySynced()
    {
        String varSObjectApiName = 'Account';
        
        //String trackedField = '';
        Map<String, Custom_Field_Tracking_Map__mdt> mapTrackedFields = new Map<String, Custom_Field_Tracking_Map__mdt>();

        for(Custom_Field_Tracking_Map__mdt varCustomTrackedField : [SELECT CampoRastreado__r.QualifiedApiName 
                                                                    FROM Custom_Field_Tracking_Map__mdt
                                                                    WHERE ObjetoRastreado__r.QualifiedApiName =: varSObjectApiName])
        {
            mapTrackedFields.put(varCustomTrackedField.CampoRastreado__r.QualifiedApiName, varCustomTrackedField);
        }
        
        for(Account newAccount : mapNewAccount.values())
        {
            Account oldAccount = mapOldAccount.get(newAccount.Id);

            for(String trackedField : mapTrackedFields.keySet())
            {
                System.debug('tracked field: ' + trackedField);

                if(newAccount.get(trackedField) != oldAccount.get(trackedField))
                {
                    newAccount.IsExternallySynched__c = false;
                 
                    System.debug('limit: ' + Limits.getCpuTime());
                    System.debug('campo rastreado >>> ' + trackedField + ' <<< teve seu valor alterado');
                    System.debug('TYUMI => ' + newAccount.IsExternallySynched__c);
                }
            }
        }
    }
    

    /**********************************************************************************************************************************
    * ================================================================================================================================
    * @description disparar o evento de plataforma quando a conta for sincronizada
    * ================================================================================================================================
    * History
    * -------
    * VERSION     AUTHOR                  DATE            DETAIL      Description
    * 1.0         Gabriel Vidal           13/08/2021
    **********************************************************************************************************************************/
    private void firePlatformEventSynchAccount()
    {
        for(Account newAccount : mapNewAccount.values())
        {
            if (newAccount.IsSynchEnabled__c == 'ENABLED')
            {               
                SynchAccount__e synch = new SynchAccount__e(); 
                DataBase.SaveResult sr = EventBus.publish(synch);
            }
        }
    }
}