creditas-sf/force-app/main/default/objects/Account/fields/IsExternallySynched__c.field-meta.xml
<CustomField>
    <fullName>IsExternallySynched__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Esse campo determina se houve alteração dos registros no Salesforce, para que o Mulesoft identifique quando propagar alterações.</description>
    <label>IsExternallySynched</label>
    <type>Checkbox</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/classes/AccFinancialRelationshipTriggerHandler.cls
public without sharing class AccFinancialRelationshipTriggerHandler extends TriggerHandler
{
    private List<AccountFinancialRelationship__c> lstNewAccountFinancialRelationship;
    private List<AccountFinancialRelationship__c> lstOldAccountFinancialRelationship;
    private Map<Id, AccountFinancialRelationship__c> mapNewAccountFinancialRelationship;
    private Map<Id, AccountFinancialRelationship__c> mapOldAccountFinancialRelationship;

    public AccFinancialRelationshipTriggerHandler() 
    {
        this.lstNewAccountFinancialRelationship = (List<AccountFinancialRelationship__c>) Trigger.new;
        this.lstOldAccountFinancialRelationship = (List<AccountFinancialRelationship__c>) Trigger.old;
        this.mapNewAccountFinancialRelationship = (Map<Id, AccountFinancialRelationship__c>) Trigger.newMap;
        this.mapOldAccountFinancialRelationship = (Map<Id, AccountFinancialRelationship__c>) Trigger.oldMap;
    }


    public override void beforeInsert()
    {
    }


    public override void afterInsert() 
    {
        this.updateIsExternallySynced();
    }


    public override void beforeUpdate()
    {
    }


    public override void afterUpdate() 
    {       
        this.updateIsExternallySynced();
    }

    private void updateIsExternallySynced()
    {
        List<Account> accountsToUpdate = new List<Account>();
        Set<Id> accountsToUpdateIds = new Set<Id>();

        for (AccountFinancialRelationship__c accFinancialRelationship : lstNewAccountFinancialRelationship)
        {
            String accountId = accFinancialRelationship?.Account__c;
            if (String.isNotBlank(accountId) && !accountsToUpdateIds.contains(accountId))
            {
                accountsToUpdateIds.add(accountId);
                
                accountsToUpdate.add(new Account(
                    Id = accountId,
                    IsExternallySynched__c = false
                ));
            }
        }
        TriggerHandler.bypass('AccountTriggerController');
        update accountsToUpdate;
        TriggerHandler.clearBypass('AccountTriggerController');
    }


}