creditas-sf/force-app/main/default/objects/Account/fields/NetWorthLowerLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthLowerLimit__c</fullName>
    <label>Patrimônio líquido mínimo</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/Account/fields/NetWorthUpperLimit__c.field-meta.xml
<CustomField>
    <fullName>NetWorthUpperLimit__c</fullName>
    <label>NetWorthUpperLimit</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/AccountFinancialRelationship__c.object-meta.xml
<CustomObject>
    <label>Relações Financeiras</label>
    <nameField>
        <displayFormat>A-{00000}</displayFormat>
        <label>Relações Financeiras</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AccountFinancialRelationships</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>AccountFinancialRelationships</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/AccountFinancialRelationship__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <formula>Recurso_Financeiro__r.Amount__c</formula>
    <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
    <label>Valor</label>
    <precision>18</precision>
    <scale>2</scale>
    <type>Number</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/FinancialResources__c.object-meta.xml
<CustomObject>
    <description>Objeto responsável por armazenar as informações de renda e fonte de renda ara pagamento da divida.</description>
    <label>Recurso Financeiro</label>
    <nameField>
        <label>Nome de Recurso Financeiro</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Recursos Financeiros</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/ProfessionalInfo__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalInfo__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Emprego</label>
    <referenceTo>ProfessionalInfo__c</referenceTo>
    <relationshipLabel>Recursos Financeiros</relationshipLabel>
    <relationshipName>Recursos_Financeiros</relationshipName>
    <type>Lookup</type>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Tipo do recurso que está sendo registrado</description>
    <label>Tipo de Recurso</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>PRESUMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>CONFIRMED_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>NET_MONTHLY_INCOME</fullName>
            </value>
            <value>
                <fullName>HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL</fullName>
            </value>
            <value>
                <fullName>APARTMENT</fullName>
            </value>
            <value>
                <fullName>LAND</fullName>
            </value>
            <value>
                <fullName>CONDOMINIUM_HOUSE</fullName>
            </value>
            <value>
                <fullName>COMMERCIAL_ROOM</fullName>
            </value>
            <value>
                <fullName>CAR</fullName>
            </value>
            <value>
                <fullName>MOTORCYCLE</fullName>
            </value>
            <value>
                <fullName>QUADRICYCLE</fullName>
            </value>
            <value>
                <fullName>TRUCK</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/FinancialResources__c/recordTypes/Outros.recordType-meta.xml
<RecordType>
    <fullName>Outros</fullName>
    <active>true</active>
    <label>Outros</label>
</RecordType>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/IncomeDataSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Renda</label>
    <nameField>
        <label>Seção Dados de Renda Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Seção Dados de Renda</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ConfirmedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>ConfirmedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda confirmada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeObservation__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeObservation__c</fullName>
    <label>Observação da renda mínima</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeRejectReason__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeRejectReason__c</fullName>
    <label>Motivo Rejeição Renda Mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Cliente não atinge a renda mínima</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MinimalRequiredIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MinimalRequiredIncomeStatus__c</fullName>
    <label>Status da renda mínima</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeObservation__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeObservation__c</fullName>
    <label>Observação da renda informada</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/MonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>MonthlyIncomeStatus__c</fullName>
    <label>Status da renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/NetWorthStatus__c.field-meta.xml
<CustomField>
    <fullName>NetWorthStatus__c</fullName>
    <label>Status do patrimônio</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/PresumedMonthlyIncomeStatus__c.field-meta.xml
<CustomField>
    <fullName>PresumedMonthlyIncomeStatus__c</fullName>
    <label>Status da renda considerada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationObservation__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationObservation__c</fullName>
    <label>Observação da situação profissional</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationPendingReason__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationPendingReason__c</fullName>
    <label>Motivo Pendência Situação Profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprovante de renda divergente da ocupação do cliente</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionalSituationStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionalSituationStatus__c</fullName>
    <label>Status da situação profissional</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionObservation__c.field-meta.xml
<CustomField>
    <fullName>ProfessionObservation__c</fullName>
    <label>Observação da profissão</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionPendingReason__c.field-meta.xml
<CustomField>
    <fullName>ProfessionPendingReason__c</fullName>
    <label>Motivo Pendência Profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Comprovante de renda divergente da ocupação do cliente</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ProfessionStatus__c.field-meta.xml
<CustomField>
    <fullName>ProfessionStatus__c</fullName>
    <label>Status da profissão</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovado</fullName>
            </value>
            <value>
                <fullName>Pendenciado</fullName>
            </value>
            <value>
                <fullName>Rejeitado</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/IncomeDataSection__c/fields/ReportedIncomePendingReason__c.field-meta.xml
<CustomField>
    <fullName>ReportedIncomePendingReason__c</fullName>
    <label>Motivo Pendência Renda informada</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Documeneto não aceito/inválido</fullName>
            </value>
            <value>
                <fullName>Documento de renda ilegível 	Documento incompleto</fullName>
            </value>
            <value>
                <fullName>Outros</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/ProfessionalInfo__c.object-meta.xml
<CustomObject>
    <label>Emprego</label>
    <nameField>
        <displayFormat>ProfInfo-{00000000}</displayFormat>
        <label>ProfessionalInfo Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>ProfessionalInfos</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Empregos</relationshipLabel>
    <relationshipName>ProfessionalInfos</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/JobTitle__c.field-meta.xml
<CustomField>
    <fullName>JobTitle__c</fullName>
    <label>JobTitle</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ProfessionalInfo__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>CLT</fullName>
            </value>
            <value>
                <fullName>FREELANCER</fullName>
            </value>
            <value>
                <fullName>CIVIL_SERVANT</fullName>
            </value>
            <value>
                <fullName>RETIRED</fullName>
            </value>
            <value>
                <fullName>BUSINESSMAN</fullName>
            </value>
            <value>
                <fullName>SELF_EMPLOYED</fullName>
            </value>
            <value>
                <fullName>OTHER</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalIncomeDataService.cls
public with sharing class ProposalIncomeDataService {
    
    @AuraEnabled
    public static IncomeDataSection__c getIncomeDataSection(Id opportunityId)
    {
        List<IncomeDataSection__c> recordsIncomeDataSection = new List<IncomeDataSection__c>();
        recordsIncomeDataSection =    [ SELECT Id, 
                                        ProfessionalSituationStatus__c,
                                        ProfessionalSituationPendingReason__c,
                                        ProfessionalSituationObservation__c,
                                        ProfessionStatus__c,
                                        ProfessionPendingReason__c,
                                        ProfessionObservation__c,
                                        NetWorthStatus__c,
                                        MonthlyIncomeStatus__c,
                                        ReportedIncomePendingReason__c,
                                        MonthlyIncomeObservation__c,
                                        MinimalRequiredIncomeStatus__c,
                                        MinimalRequiredIncomeRejectReason__c,
                                        MinimalRequiredIncomeObservation__c,
                                        PresumedMonthlyIncomeStatus__c,
                                        ConfirmedMonthlyIncomeStatus__c
                                        FROM IncomeDataSection__c
                                        WHERE Opportunity__c =: opportunityId
                                        LIMIT 1];
        
        return recordsIncomeDataSection.isEmpty() ? new IncomeDataSection__c() : recordsIncomeDataSection[0];
    }

    @AuraEnabled
    public static ProfessionalInfo__c getProfession(String accountId)
    {
        List<ProfessionalInfo__c> professionalInfo = new List<ProfessionalInfo__c>();
        professionalInfo = [SELECT Id, Status__c, JobTitle__c FROM ProfessionalInfo__c WHERE Account__c = :accountId LIMIT 1];

        return professionalInfo.isEmpty() ? new ProfessionalInfo__c() : professionalInfo[0];
    }

    @AuraEnabled
    public static Account getAccount(String accountId)
    {           
        return [SELECT Id, NetWorthLowerLimit__c, NetWorthUpperLimit__c FROM Account WHERE Id = :accountId LIMIT 1];
    }

    @AuraEnabled
    public static Map<String, FinancialResources__c> getFinancialResource(String accountId)
    {
        Set<Id> financialResourceIdSet = getFinancialResourcesId(accountId);

        if(financialResourceIdSet.isEmpty()) {
            return new Map<String, FinancialResources__c>();
        } else {
            List<FinancialResources__c> resourceList = [SELECT Id, Type__c, Amount__c FROM FinancialResources__c WHERE Id IN :financialResourceIdSet ORDER BY ExternalUpdatedDate__c DESC];
            Map<String, FinancialResources__c> financialResourcesByType = new Map<String, FinancialResources__c>();

            for(FinancialResources__c financialResource : resourceList)
            {   
                if(String.isNotBlank(financialResource?.Type__c))
                {
                    if(financialResource.Type__c.equals('MONTHLY_INCOME')) {
                        financialResourcesByType.put(financialResource.Type__c, financialResource);
                    } else if(financialResource.Type__c.equals('PRESUMED_MONTHLY_INCOME')) { 
                        financialResourcesByType.put(financialResource.Type__c, financialResource);
                    } else if(financialResource.Type__c.equals('CONFIRMED_MONTHLY_INCOME')) { 
                        financialResourcesByType.put(financialResource.Type__c, financialResource);
                    } 
                }
            }

            return financialResourcesByType;
        }
    }

    @AuraEnabled
    public static Opportunity getOpportunity(String opportunityId)
    {
        return [SELECT Id, MinimalRequiredIncome__c FROM Opportunity WHERE Id = :opportunityId LIMIT 1];
    }

    private static Set<Id> getFinancialResourcesId(String accountId) 
    {    
        Set<Id> financialResourceIdSet = new Set<Id>();

        String financialResourceOthersId = Util.getRecordTypeIdbyName('FinancialResources__c', 'Outros');
        
        for(AccountFinancialRelationship__c accFinancialRel : [SELECT Recurso_Financeiro__c, Recurso_Financeiro__r.RecordTypeId FROM AccountFinancialRelationship__c WHERE Account__c = :accountId])
        {
            if(financialResourceOthersId == accFinancialRel.Recurso_Financeiro__r.RecordTypeId)
            {
                financialResourceIdSet.add(accFinancialRel.Recurso_Financeiro__c);
            }
        }

        return financialResourceIdSet;
    }

    public static void saveIncomeSection(Map<String, SObject> records) 
    {
        ProfessionalInfo__c   professionalInfo        = (ProfessionalInfo__c)   records.get('ProfessionalInfo');
        IncomeDataSection__c  validation              = (IncomeDataSection__c)  records.get('IncomeSection');
        Opportunity           minimalRequiredIncome   = (Opportunity)           records.get('MinimalRequiredIncome');
        FinancialResources__c monthlyIncomeInfo       = (FinancialResources__c) records.get('MonthlyIncomeInfo');
        FinancialResources__c presumedMonthlyIncome   = (FinancialResources__c) records.get('PresumedMonthlyIncomeInfo');
        FinancialResources__c confirmedMonthlyIncome  = (FinancialResources__c) records.get('ConfirmedMonthlyIncomeInfo');
        Account               networth                = (Account)               records.get('NetworthIncomeInfo');

        SObjectUtils.upsertRecord(professionalInfo);
        SObjectUtils.upsertRecord(validation);
        SObjectUtils.upsertRecord(minimalRequiredIncome);
        SObjectUtils.upsertRecord(monthlyIncomeInfo);
        SObjectUtils.upsertRecord(presumedMonthlyIncome);
        SObjectUtils.upsertRecord(confirmedMonthlyIncome);
        SObjectUtils.upsertRecord(networth);
    }
}