creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/ContactDetailsSection__c.object-meta.xml
<CustomObject>
    <label>Seção Dados de Contato</label>
    <nameField>
        <displayFormat>DC-{00000}</displayFormat>
        <label>Seção Dados de Contato</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seção Dados de Contato</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/EmailObservation__c.field-meta.xml
<CustomField>
    <fullName>EmailObservation__c</fullName>
    <label>Observação do e-mail</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/EmailStatus__c.field-meta.xml
<CustomField>
    <fullName>EmailStatus__c</fullName>
    <label>Status do E-mail</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/MobileObservation__c.field-meta.xml
<CustomField>
    <fullName>MobileObservation__c</fullName>
    <label>Observação do celular</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/MobileStatus__c.field-meta.xml
<CustomField>
    <fullName>MobileStatus__c</fullName>
    <label>Status do Celular</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Aprovar</fullName>
            </value>
            <value>
                <fullName>Rejeitar</fullName>
            </value>
            <value>
                <fullName>Pendenciar</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

creditas-sf/force-app/main/default/objects/ContactDetailsSection__c/fields/Opportunity__c.field-meta.xml
<CustomField>
    <fullName>Opportunity__c</fullName>
    <label>Oportunidade</label>
    <referenceTo>Opportunity</referenceTo>
    <relationshipLabel>Seção Dados de Contato</relationshipLabel>
    <relationshipName>ContactDataSection</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

creditas-sf/force-app/main/default/classes/ProposalContactDataService.cls
public with sharing class ProposalContactDataService {
    @AuraEnabled
    public static ContactDetailsSection__c getContactDetailsSectionFromOpp(Id opportunityId){
        
        List<ContactDetailsSection__c> recordsContactDetailsSection = new List<ContactDetailsSection__c>();
        recordsContactDetailsSection = [SELECT Id,
                                        Email__c,
                                        Mobile__c,
                                        MobileStatus__c,
                                        MobileRejectReason__c,
                                        MobileObservation__c,
                                        EmailStatus__c,
                                        EmailRejectReason__c,                                       
                                        EmailObservation__c
                                        FROM ContactDetailsSection__c
                                        WHERE Opportunity__c =: opportunityId
                                        ORDER BY CreatedDate  DESC
                                        LIMIT 1];
        
        return recordsContactDetailsSection.isEmpty() ? new ContactDetailsSection__c() : recordsContactDetailsSection[0];
        
    }

    @AuraEnabled
    public static void upsertContactDetailsSection(ContactDetailsSection__c record){
        SObjectUtils.upsertRecord(record);
    }
}